stellar/go

services/federation/README.md
Noticed a bunch of small and potentially confusing errors in the configuration examples for federation server. Also add a short note about dropping the `reverse-federation` field if reverse lookup isn't possible (per conversation w/ @nullstyle).
=> Fix up federation server config examples

support/config/main.go, support/config/main_test.go
This PR allows our config structures to use the tags `valid:"stellar_accountid"` and  `valid:"stellar_seed"` for validation.
=> support/config: Add stellar_seed and stellar_accountid validators

clients/stellartoml/client.go, clients/stellartoml/client_test.go, clients/stellartoml/main.go, clients/stellartoml/main_test.go
This package was imported and refactored from the bridge-server project.
=> Adds client/stellartoml package, for resolving stellar.toml files

clients/federation/client_test.go, clients/stellartoml/client.go, clients/stellartoml/client_test.go, clients/stellartoml/mocks.go, glide.lock, glide.yaml, support/http/httptest/client.go, support/http/httptest/client_expectation.go, support/http/httptest/main.go
This PR adds a number of improvements to mocking, while fixing some small errors.
The `httptest` package gained the `Client` type that allows for mocked http clients in tests, and the `clients/stellartoml` package got a `MockClient` that consumers of the package can use in their tests.
=> Mocking improvements

clients/horizon/client.go, clients/horizon/error.go, clients/horizon/internal.go, clients/horizon/main.go, clients/horizon/main_test.go, clients/horizon/mocks.go, clients/horizon/responses.go, clients/stellartoml/main.go, glide.lock, glide.yaml
This PR brings in some of the added features (such as streaming payments) from the bridge-server horizon client.  In addition:
- I've improved some of the error handling using our support package
- Changed member names to be the same as our other clients
- Fixed some random re-creations of http clients
- Removing logging statements that are better surfaced elsewhere
- Updated the tests to use our http client mocking system
- Added a mock client for use in other packages' tests
=> Horizon client updates

clients/horizon/error.go, clients/horizon/error_test.go, clients/horizon/main.go, clients/horizon/responses.go
This PR adds some helper methods to get details about a `*horizon.Error` that was returned in response to a transaction posted to horizon.
=> clients/horizon: Add `Envelope()` and `ResultCodes()` to `Error`

support/config/broken_test.go, support/db/repo.go, support/db/repo_test.go
- Adds expectedly broken test illustrating upstream govalidator bug.
- Add `Dialect()` helper method to db.Repo
=> Minor updates

handlers/federation/handler_test.go, support/db/dbtest/db.go, support/db/dbtest/main.go, support/db/dbtest/mysql.go, support/db/dbtest/mysql_test.go, support/db/dbtest/postgres.go, support/db/dbtest/postgres_test.go, support/db/dbtest/sqlite.go, support/db/dbtest/sqlite_test.go, support/db/repo_test.go
This PR updates the dbtest library to use test assertions instead of panics for handling errors when creating test databases.  This standardizes the package with way we handle test setup errors and simplifies the code.
=> support/db/dbtest: integrate test assertions

CHANGELOG.md, build/account_merge.go, build/allow_trust.go, build/change_trust.go, build/create_account.go, build/inflation.go, build/main.go, build/main_test.go, build/manage_data.go, build/manage_offer.go, build/payment.go, build/set_options.go, build/transaction.go, build/transaction_envelope.go, build/transaction_envelope_test.go, build/util.go, network/main.go, network/main_test.go
This PR removes the behavior where the build package defaults to signing transactions for the test network.  Unless a developer explicitly sets `DefaultNetwork.Passphrase`, an error will now be returned when building transactions.
Additionally, I took the opportunity to make 30 minutes of progress on unifying our error handling with the `stellar/go/support/errors` package.
=> Remove default network, plus some refactoring

clients/federation/client.go, clients/federation/client_test.go, clients/federation/main.go, clients/stellartoml/client.go, clients/stellartoml/client_test.go, clients/stellartoml/main.go
Stellar.toml and Federation clients connect to untrusted servers. Responses from these servers can be a valid large toml/json that would need to be placed in memory. This can lead to out-of-memory errors and can ultimately crash the app using stellar/go.
This commit is using io.LimitReader to read no more than defined max size of stellar.toml and federation response.
=> Limit bytes read from stellar.toml and federation responses

services/federation/main.go, support/config/main.go, support/config/main_test.go
This PR contains two commits:
1. 4491b16 fixing federation server config file. Some fields didn't have `valid:"optional"` tag but govalidator requires all fields to have `valid` tags.
2. b45f11d close https://github.com/stellar/go/issues/36.
=> Fix config

clients/federation/client.go, clients/federation/client_test.go, handlers/federation/handler.go, handlers/federation/handler_test.go, protocols/federation/main.go, protocols/federation/main_test.go
Unmarshalling integer values (`"memo": 123`) was returning an error:
```
json: cannot unmarshal number into Go struct field NameResponse.memo of type string
```
=> Support integer memo

glide.lock, glide.yaml, handlers/federation/main.go, support/db/delete_builder.go, support/db/delete_builder_test.go, support/db/errors.go, support/db/get_builder.go, support/db/get_builder_test.go, support/db/insert_builder.go, support/db/insert_builder_test.go, support/db/internal.go, support/db/internal_test.go, support/db/main.go, support/db/main_test.go, support/db/select_builder.go, support/db/select_builder_test.go, support/db/session.go, support/db/session_test.go, support/db/table.go, support/db/update_builder.go
This PR adds initial support for programmatically building sql queries.  Big changes include:
- Renamed `Repo` to `Session`
- Added the `Table` struct
- Added query builders for `Select`, `Get`, `Delete`, and `Insert`
TODO:
=> Initial support for query building

clients/horizon/client.go, clients/horizon/main.go, clients/horizon/main_test.go, clients/horizon/mocks.go, clients/horizon/responses.go
Added three requested methods:
```go
LoadAccountOffers(accountID string, params ...interface{}) (offers OffersPage, err error)
LoadOrderBook(selling Asset, buying Asset) (orderBook OrderBookSummary, err error)
StreamLedgers(cursor *Cursor, handler LedgerHandler) error
```
Additionally created `ClientInterface` to ensure both `Client` and `MockClient` implement the same methods.
Close #44 
Close #45 
Close #46
=> New horizon.Client methods

clients/horizon/client.go, clients/horizon/main.go, clients/horizon/main_test.go, clients/horizon/mocks.go
All streaming methods have been updated to restart in case of
recoverable errors or when horizon disconnects. They now also accept
context.Context as a first argument to allow cancelling streaming.
Close https://github.com/stellar/go/issues/43
Example:
```go
package main
import (
"context"
"fmt"
"time"
"github.com/stellar/go/clients/horizon"
)
func main() {
client := horizon.DefaultPublicNetClient
cursor := horizon.Cursor("now")
ctx, cancel := context.WithCancel(context.Background())
defer cancel()
go func() {
time.Sleep(60 * time.Second)
cancel()
}()
err := client.StreamLedgers(ctx, &cursor, func(l horizon.Ledger) {
fmt.Println(l.Sequence)
})
if err != nil {
fmt.Println(err)
}
}
```
=> Restart and cancel streaming

protocols/compliance/main.go, protocols/compliance/route.go, protocols/compliance/route_test.go
Go's encoding/json Decoder returns error when trying to unmarshal number
into Go value of type string. This commit is introducing Route type
implementing Unmarshaler interface, that allows decoding both integer
and string values.
=> Change Route field in compliance to Route type

build/asset.go, build/asset_test.go, build/change_trust.go, build/main.go, build/manage_offer.go, build/payment.go
This PR adds the `Asset#MustXDR()` helper, making this struct more useful for constructing xdr data in programs that are fine with panicking, such as test functions.  `Asset#ToXdrObject()` is renamed to `Asset#ToXDR()` for consistency's sake. Also some tests were written.
=> Improve `build.Asset` ergonomics

.travis.yml, support/scripts/build_release_artifacts/main.go
This PR introduces nightly builds for our monorepo.  The release script has been upgraded to watch for the environment variables that travis sets when being run as a cron job.  When triggered, the script will now build and package all of the different binaries in the repo.  This extends the build time significantly, unfortunately.
Note:  actually deploying the nightly build packages is out of scope for this PR.  I want to ensure that the builds are properly triggering first and I can only test that from master.  A future PR will introduce a non-stubbed deploy step.
=> Nightly builds phase 1

tools/stellar-sign/main.go
This PR adds a simple `infile` flag to support reading a transaction envelope from a file, as well as adding "triple backticks" to the output formatting to allow for better paste integration with slack.
=> tools/stellar-sign:  add infile support, better slack integration

handlers/federation/handler.go, handlers/federation/main.go
Currently when `FederationDriver` methods return error
`federation.Handler` always sends "An internal error occurred" error
message. It is impossible to send another response, for example:
containing information about why request was invalid.
To solve this we make `ErrorResponse` implement error interface. By
doing this `FederationDriver` implementations can return `ErrorResponse`
as an error that will be passed to end user.
=> Pass ErrorResponse errors from FederationDriver to end user

build/main_test.go, clients/horizon/main_test.go, clients/stellartoml/main_test.go, xdr/main_test.go
Example functions in tests do not follow naming conventions of testing
package: https://golang.org/pkg/testing/#hdr-Examples Because of this
examples were not rendered in go docs.
=> Fix Example functions in tests

services/horizon/resource/operations/main.go
no more planned changes, this closes https://github.com/stellar/horizon/issues/404
before the change:
after the change (notice that offer_id field is no longer there, before the amount field):
=> wrap offerId around CreatePassiveOffer to make a ManageOffer

services/horizon/internal/actions_order_book.go
*_issuer -> *_asset_issuer
While using the endpoint, I found that the detailed message had incorrectly specified the params
=> Fix incorrect detail message in /order_book

.travis.yml
Continued work on automated nightly builds.  If this doesn't work I'll need to automate updating a `nightly` tag to build and release from.
=> Add overwrite: true to nightly deploy spec

handlers/federation/handler_test.go, protocols/federation/main.go, protocols/federation/main_test.go
Not sure why `Memo.MarshalJSON()` is returning integer for integer values since https://github.com/stellar/go/pull/40. We agreed that `Memo.MarshalJSON()` should always return strings and `Memo.UnmarshalJSON()` allows both integers in strings for integer values because we can parse both values correctly in Go (Slack: [[1]](https://stellarfoundation.slack.com/archives/C02B04RMK/p1488913219000732) [[2]](https://stellarfoundation.slack.com/archives/C02B04RMK/p1488923785000757)).
=> Marshalling Memo type should always result in string

support/time/main.go, support/time/main_test.go
@tomerweller looks like we were both wrong when it comes to `time.Unix()` in https://github.com/stellar/go/pull/144#discussion_r151078044. You were close (`%100` instead of `%1000`) and I completely misunderstood how `time.Unix()` works, apologies!
=> Fix support/time.Milis.ToTime

services/horizon/internal/db2/history/trade.go, services/horizon/internal/ingest/ingestion_test.go, services/horizon/internal/ingest/session.go, services/horizon/internal/test/trades/main.go, support/time/main.go
Modify trade ingestion to use `Millis` instead of `int64`.
Fixes a bug where trade ingestion treated the ledger close time as millis since epoch, when it was in fact seconds since epoch. 
Added a test.
=> Trade ingestion timestamp fix

services/horizon/internal/db2/core/main.go, services/horizon/internal/db2/core/main_test.go
This PR fixes a misconception that horizon was making about the behavior of the SQL database managed by stellar-core.  Prior to this PR, horizon behaved as though stellar-core would not create gaps in the `ledgerheaders` table when `CATCHUP_RECENT` was configured, which is not how stellar-core actually behaves.  Instead, multiple gaps can be created regardless of the catchup config.
This PR amends the notion of the "Elder" ledger that horizon tracks.  It is now defined as the oldest ledger in the youngest contiguous range of ledgers whose headers are found in the core sql db.
=> Fixes `ElderLedger` query

services/horizon/internal/actions_trade_test.go, services/horizon/internal/db2/history/trade_aggregation.go, services/horizon/internal/test/trades/main.go
Reinstate the asset filters that were accidentally ignored after the query refactoring. 
Modify tests to spot filtering issues.
=> fix trade aggregation asset filters

clients/stellarcore/client.go, clients/stellarcore/info_response.go, clients/stellarcore/info_response_test.go, clients/stellarcore/main.go, clients/stellarcore/main_test.go, services/horizon/internal/app.go, services/horizon/internal/app_test.go, services/horizon/internal/db2/core/main.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/session.go, services/horizon/internal/ingest/system.go, services/horizon/internal/ingest/system_test.go, services/horizon/internal/init_ingester.go, services/horizon/internal/init_metrics.go, services/horizon/internal/ledger/main.go, services/horizon/internal/resource/main.go, services/horizon/internal/resource/root.go, services/horizon/internal/test/t.go
This PR removes the notion of the "Core Elder Ledger" from the API and from the history ingestion system.  Unfortunately the query is too slow for a large horizon database.
- Test "reingestion re-establishment"  on testnet
- Clear testnet and start from scratch
- Pubnet has _not_ had maintenance run on it, so we are going to be re-ingesting a lot of old data.  Someone should start a screen session on one of those boxes and run a full reingestion using `horizon db reingest outdated` after deploying this code.
=> Fix ingestion issues

services/horizon/internal/actions_trade.go, services/horizon/internal/actions_trade_test.go, services/horizon/internal/db2/history/trade.go, services/horizon/internal/ingest/system.go, services/horizon/internal/init_web.go, services/horizon/internal/main_generated.go, services/horizon/internal/resource/main.go, services/horizon/internal/resource/trade.go, services/horizon/internal/resource/trade_aggregation.go, services/horizon/internal/resource/trade_effect.go, support/scripts/run_tests
- Adds the `/accounts/:id/trades` endpoint
- Adds the `/offers/:id/trades` endpoint
- Split test run up, running one invocation of `go test` per subtree of the monorepo
- Remove `order_book/trades` endpoint
=> Re-enable account trades and offer trades endpoints

clients/stellarcore/client.go, services/horizon/internal/actions_payment_test.go, services/horizon/internal/app.go, services/horizon/internal/db2/page_query.go, services/horizon/internal/db2/page_query_test.go, services/horizon/internal/init_web.go
This PR includes a grab bag of simple fixes for horizon:
- prevent panics when clients pass invalid paging info
- add a info message at horizon startup to display ingestion config
- fix bug preventing connection to stellar core when the config value contains a trailing slash
=> Stellar core Info and cursor fixes

services/horizon/db.go, services/horizon/internal/ingest/system.go
This PR adds an administrative command to horizon allowing an operator to clear the horizon database and re-establish the ledger from which history ingestion will begin.
=> Add `horizon db rebase` subcommand

services/horizon/internal/db2/core/transaction.go, services/horizon/internal/db2/core/transaction_test.go, services/horizon/internal/txsub/internal.go, services/horizon/internal/txsub/main.go, services/horizon/internal/txsub/open_submission_list.go, services/horizon/internal/txsub/results/db/main.go, services/horizon/internal/txsub/submitter.go, services/horizon/internal/txsub/system.go, services/horizon/internal/txsub/test_helpers.go
This PR modifies how horizon queries the stellar core database for transaction results to reduce complexity.  By filtering the `txhistory` table by `ledgerseq` we reduce the search space for a result significantly.
=> Improve performance of transaction result lookup

services/horizon/internal/action.go, services/horizon/internal/actions_assets.go, services/horizon/internal/actions_assets_test.go, services/horizon/internal/actions_effects.go, services/horizon/internal/actions_ledger.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_operation.go, services/horizon/internal/actions_payment.go, services/horizon/internal/actions_trade.go, services/horizon/internal/actions_transaction.go, services/horizon/internal/assertions_test.go, services/horizon/internal/render/hal/page.go, support/url/main.go, support/url/main_test.go
apply query filters on paging links. closes #148 
also:
- modifies the Page struct to include a full url, rather than separate base url, path and query params. 
- introduces a support/url package and a URL struct for convenient url modifications.
=> fix paging

glide.lock, glide.yaml
This PR fixes the breakage caused by a disappearing go-debug package and also updates our glide.lock file with the new versions of other deps.
=> Remove disappearing dependency

clients/horizon/responses.go, services/horizon/CHANGELOG.md, services/horizon/internal/docs/reference/endpoints/ledgers-all.md, services/horizon/internal/docs/reference/endpoints/ledgers-single.md, services/horizon/internal/docs/reference/resources/ledger.md, services/horizon/internal/docs/reference/responses.md, services/horizon/internal/resource/ledger.go, services/horizon/internal/resource/main.go
This PR updates our representation of "base fee" and "base reserve" in horizon.  In renames attributes to make it clearer what the number represents.
=> Update base fee and reserve attributes on ledger resource

support/time/main.go, support/time/main_test.go
When trying to round up with 0 the original time should be returned.
Fixes https://github.com/stellar/go/issues/284
=> Fix time rounding

services/horizon/internal/docs/reference/endpoints/trade_aggregations.md
When testing the /trade_aggregations endpoint in laboratory, I couldn't get the example to work.
A couple frustrating minutes later, I realized the public key of the counter asset issuer was incorrect;  I noticed the curl example and the doc arg examples did not match. 
This PR will save other devs those few frustrating minutes 😅
=> Docs example /trade_aggregations correction

clients/federation/client.go, clients/federation/client_test.go, clients/federation/main.go
Add support to `forward` federation requests as described in [SEP-0002](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0002.md).
Required to close https://github.com/stellar/bridge-server/issues/92.
=> Add forward requests to federation.Client

examples/build_transaction/main.go
Hey there,
The transaction build example is missing network phrase, so the `Sign` method returns an error. I just added the test network phrase to the parameters. 
Cheers
=> Add network passphrase to the transaction parameters

services/horizon/internal/docs/reference/resources/account.md
Account Data link doesn't work, gives 404.
The rest of links work due to redirect (cloudflare?)
=> Fix links in doc

tools/stellar-archivist/README.md, tools/stellar-archivist/internal/archive.go, tools/stellar-archivist/internal/archive_test.go, tools/stellar-archivist/internal/fs_archive.go, tools/stellar-archivist/internal/http_archive.go, tools/stellar-archivist/internal/mock_archive.go, tools/stellar-archivist/internal/s3_archive.go, tools/stellar-archivist/main.go
This PR adds custom S3 endpoint support to `stellar-archivist` tool, so that it can be used with any S3-compatible storage (like [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/)).
=> tools/stellar-archivist: support custom S3 endpoints

services/horizon/internal/db2/history/account.go, services/horizon/internal/ingest/asset_stat.go, services/horizon/internal/ingest/batch_insert_builder.go, services/horizon/internal/ingest/effect_ingestion.go, services/horizon/internal/ingest/ingestion.go, services/horizon/internal/ingest/ingestion_test.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/session.go
For a discussion please check: https://github.com/stellar/go/pull/316 Unfortunately I closed it by accident by force-pushing a `master` branch to it. Cannot recover from this on GitHub.
---
Ingestion code is making too many DB requests:
* It inserts each effect, operation, etc. in a separate query.
* It `GetCreateAccountID` is executed multiple times when checking row ID for a given `AccountID`.
Because of so many requests, ingesting a single transaction with 100 payment operations takes 200-500 ms. It can grow to 20 seconds per ledger causing delays in ingestion.
This PR introduces the following changes:
* It batches `INSERT`s to the database.
* It gets all the accounts participating in the ledger and then batch gets / creates them.
After implementing this changes ledger with 50 txs / …
=> Ingestion performance fixes

build/create_account.go, build/main_test.go, build/payment.go
Addresses #336.
This is just a doc and test change. Includes working examples for funding a new account, and making a payment (the latter was just a copy of the `Transaction` example.)
(First PR: I signed the contributor license agreement.)
=> doc: Add examples for `build.Payment` and `build.CreateAccount`

services/horizon/internal/ingest/asset_stat.go, services/horizon/internal/ingest/cursor.go, services/horizon/internal/ingest/cursor_test.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/system.go
Most importantly, this revs the ingester version so we can get a clean up to date reingestion happening on testnet.  Additionally, I've renamed `DB` to `CoreDB` in the ingestion cursor:  this change is preparing for a reingestion mode that loads a `LedgerBundle` from the history database instead of core, allowing us to reingest the history database even if stellar-core has purged its old records.
Finally, this commit removes the trimming of abandoned ledgers from reingestion... IMO it's dangerous to delete rows when it isn't expected.
=> More fixes for reingestion

tools/stellar-hd-wallet/commands/io.go
This is a fix for issue #334.
This fixes the incorrect trimming of newlines on windows machines and now allows functionality of the "accounts" command. Attached is a screenshot of it properly handling individual inputs and giving appropriate error messages for invalid entries. I have now been able to go through the full process and generate the keys.
=> Fix trimming of newlines on windows

services/horizon/main.go
Fixes an issue where command line flags cannot be used when  running migrations.
=> horizon:  Make cli flags "persistent"

services/horizon/internal/docs/reference/endpoints/transactions-all.md
=> Removed duplicate text for 'Endpoints -> All Transactions' API reference

build/main.go, build/transaction.go, build/transaction_test.go
This PR solves the following issue: https://github.com/stellar/go/issues/350
Basically, passing a lower and upper timebounds on a Transaction in `build` package.
=> Timebounds On Transactions

services/horizon/CHANGELOG.md, services/horizon/internal/actions_root.go, services/horizon/internal/actions_root_test.go
Also bumps the changelog to v0.12.3
=> Remove in-request call to stellar-core in the root resource; Fixes a stall (of up to 5 seconds).

services/horizon/internal/ingest/system.go, support/errors/main.go
We would like to vendor in the `strkey` package. And are mostly fine with its transitive dependencies with the exception of `getsentry/raven-go`, which we would rather not vendor into our repo.
This PR removes `support/errors.ReportToSentry` which as far as I can tell is not called in this repo. There is still `services/horizon/internal/errors.ReportToSentry` which is what horizon calls.
=> Remove ReportToSentry from support/errors

README.md
For gophers who are not used to Glide, it's unclear what we should do
with the repos once fetched and all dependencies has been installed.
Make it clear that it still can be used in a classic go workspace and
users do not have to use Glide in their own projects.
=> doc: setup instruction about Glide

services/horizon/CHANGELOG.md, services/horizon/internal/actions/base.go, services/horizon/internal/actions_operation_test.go, services/horizon/internal/render/sse/main.go, services/horizon/internal/render/sse/main_test.go, services/horizon/internal/render/sse/stream.go, services/horizon/internal/render/sse/stream_test.go
Closes #376 by adding a 5 second heartbeat to SSE connections.
=> Add streaming heartbeat support to Horizon

clients/horizon/responses.go
These fields are present in the horizon json responses I've seen from `/accounts/*/payments`, but are missing from the go client deserialization. [Example](https://horizon.stellar.org/accounts/GAGBVEFBASR54F5UJKAWKT3ST4GBWHTJQPQXQKDDTJIWXPQT7SBSVQYH/payments)
The fields can be found [here](https://github.com/stellar/go/blob/3a84b177d74e14c7c5e0736013bfd299414d0692/services/horizon/internal/resource/operations/main.go#L115) in the horizon service source.
=> Add fields to payment endpoint

services/horizon/internal/actions/base.go, services/horizon/internal/actions/helpers.go, services/horizon/internal/actions_payment.go
For https://github.com/stellar/go/issues/193, if we pass in negative cursor to account payment API, the endpoint would fail will HTTP 400. However, there's NO detailed message explaining why the API request failed. 
This PR adds that error message. 
For testing, I ran **stellar-core** on http://localhost:11626/ and **Horizon** on http://localhost:8000/
Now, access this endpoint: 
http://localhost:8000/accounts/GBTYBQW5GLRSYMT4OJQGVAIH5KBIE5ITEWIVDZHVHIZT7XSKU6DLB6QI/payments?cursor=-1&order=asc&limit=6
Before code change
```
{
"type": "https://stellar.org/horizon-errors/bad_request",
"title": "Bad Request",
"status": 400,
"detail": "The request you sent was invalid in some way"
}
```
After code change:
```
{
"type": "https://stellar.org/horizon-errors/invalid_parameters",
"title": …
```
=> Add HTTP 400 message in case of negative cursors

services/horizon/internal/docs/reference/admin.md
I was doing a fresh setup of Horizon on my home laptop. I found out that 'git clone' doesn't always guarantee putting the code in the correct directory. 
Instead, I use 'go get' and made it work. 
Additionally, we should mention $GOPATH in the documentation, indicating where the stellar/go directory should reside.
=> [Documentation] Update horizon guide, use 'go get' instead of 'git clone'

services/friendbot/init_friendbot.go, services/friendbot/internal/friendbot.go, services/friendbot/internal/friendbot_test.go
We should really be testing the `Pay` function so I changed to use that so we can take advantage of the locking (which will prevent race conditions).
Test works now when run in with the `race` flag enabled.
=> fixed race condition in friendbot test

services/horizon/CHANGELOG.md, services/horizon/internal/actions/base.go, services/horizon/internal/render/sse/stream.go
Initial errors in streaming endpoints (ex. streaming payments for non-existent account) are now sent before sending SSE preamble with `200 OK` status code what made clients to reconnect to the stream over and over again.
Preamble is sent just before the first message or comment.
Partial fix for https://github.com/stellar/go/issues/445 to allow us to start testing a new code in `master` in testnet.
=> Send initial errors while streaming

support/http/mux.go
Previous version was using `*` value for `AllowedMethods` on github.com/rs/cors package. However, this property does not allow wildcard values. This commit changes the values passed to `AllowedMethods` to `GET`, `POST` and `HEAD`.
---
Before, `friendbot` service (`Access-Control-Allow-Origin` header not present):
```
curl -H "Origin: https://www.stellar.org/laboratory" -v localhost:8000
* Rebuilt URL to: localhost:8000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> Origin: https://www.stellar.org/laboratory
> 
< HTTP/1.1 400 Bad Request
< Content-Type: application/problem+json; charset=utf-8
< Vary: Origin
< Date: Wed, 23 May 2018 13:42:01 GMT
< Content-Length: 281
``` …
=> Fix sending CORS headers in support/http

services/horizon/internal/init_web.go, services/horizon/internal/middleware_cache_headers.go
In JS SDK we're adding random values to URL because of an older Chrome versions issue: https://github.com/stellar/js-stellar-sdk/issues/15. With correct `Cache-Control` headers it's not needed anymore.
This is a fix for browser based requests. In a future caching strategy should be more sophisticated so that Horizon responses can be cached at the proxy level (ex. `/transactions/{id}` will never change, unless we change response struct).
=> Send Cache-Control header

services/horizon/internal/docs/reference/endpoints/effects-all.md, services/horizon/internal/docs/reference/endpoints/effects-for-account.md, services/horizon/internal/docs/reference/endpoints/ledgers-all.md, services/horizon/internal/docs/reference/endpoints/offers-for-account.md, services/horizon/internal/docs/reference/endpoints/operations-all.md, services/horizon/internal/docs/reference/endpoints/operations-for-account.md, services/horizon/internal/docs/reference/endpoints/orderbook-details.md, services/horizon/internal/docs/reference/endpoints/payments-all.md, services/horizon/internal/docs/reference/endpoints/payments-for-account.md, services/horizon/internal/docs/reference/endpoints/transactions-all.md, services/horizon/internal/docs/reference/endpoints/transactions-for-account.md, services/horizon/internal/docs/reference/responses.md, services/horizon/internal/docs/reference/streaming.md
Closes #362 
I created a completely new streaming page where I copy-pasta what we had before and then add a bullet-list of endpoints that support streaming.
This may break some links/references that refer to the old streaming paragraph in the response.md. I found all those references within the horizon docs (and docs within the monorepo).
Besides those, these are the only known links that will break that I have found so far:  
* [Reference in JS SDK](https://github.com/stellar/js-stellar-sdk/blob/6fc33fc6f2e9b93818c69046c99a41d454331836/docs/reference/readme.md
)
=> Add seperate streaming page to api reference w/ endpoints list

protocols/horizon/main.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_offer_test.go, services/horizon/internal/docs/reference/resources/offer.md, services/horizon/internal/resourceadapter/offer.go
Add a `LedgerCache` to `OffersByAccountAction` and populate the offer resource with ledger sequence number and `closed_at` time.  
closes #478
=> fix offers for account timestamps

services/horizon/CHANGELOG.md
Decided to release it as 0.13.0 instead of 0.12.4 because we change a field type in `/assets` but also add a new field to Effect resource (and such change should be released as a new minor version according to SemVer spec). Since we haven't agreed to use SemVer yet, I'm OK with changing the version to 0.12.4 for this release.
=> v0.13.0 Changelog

services/compliance/main.go, services/federation/main.go, services/friendbot/main.go, support/http/main.go
Validating optional structs like this:
```go
type Config struct {
TLS config.TLS `valid:"optional"`
}
```
is broken after merging: https://github.com/stellar/go/pull/484. It reports errors:
```
ERRO[0000] config file: invalid fields: PrivateKeyFile,CertificateFile  pid=60167
```
even when there is no `[tls]` section in a config file.
I tried to check [diff](https://github.com/stellar/govalidator/compare/f0666aa80d7dcf75bd564ae8717b952d74a29d6a...asaskevich:7d2e70ef918f16bd6455529af38304d6d025c952) between our fork and `asaskevich/govalidator` master branch but couldn't find anything related. Instead, I changed all `config.TLS` to pointers: `*config.TLS`. Also changed `http.Config` so no `nil` checks are needed when using it.
=> Fix validating optional structs

protocols/horizon/README.md
Created this doc to find out and start tracking which SDK version fully supports given Horizon API version. This should help us update SDKs to support all the endpoints.
[Human readable version](https://github.com/stellar/go/blob/horizon-protocol-doc/protocols/horizon/README.md)
=> Horizon API protocol doc

services/horizon/internal/simplepath/order_book.go, services/horizon/internal/simplepath/order_book_test.go, services/horizon/internal/simplepath/path.go
order_book.go was very confusing as it was not very clear as to what it did.
That orderbook struct is essentially a one-way orderbook that is selling an asset to you. I've updated the struct and functions to represent that --it's also the only way we use it in production.
The test was not testing that codepath, now it does.
The name for the function has changed from `Cost` to `CostToConsumeLiquidity` along with clear explanations of what it does. The tests have also been updated to use the case based approach with subtests.
=> findpaths: simplify simplepath/order_book.go and fix order_book_test.go

protocols/horizon/README.md
While working on: https://github.com/stellar/java-stellar-sdk/pull/106 I found out that:
* `/offers` + streaming is not implemented yet in Horizon,
* `/offers/{offer_id}` is not implemented yet in Horizon,
* There is no `price` field in `/trades` endpoint responses in Java SDK.
=> Update Horizon SDK support table

.travis.yml, services/horizon/CHANGELOG.md, services/horizon/README.md, services/horizon/internal/simplepath/order_book.go, services/horizon/internal/simplepath/order_book_test.go
updated the multiplication logic for findpaths which now uses the rounding formula specified in the orderbook doc.
included test for this function
=> findpaths rounding fix: renamed order_book#mul to convertToBuyingUnits

services/bridge/CHANGELOG.md, services/compliance/CHANGELOG.md
Adding two separate `CHANGELOG` files as `bridge` and `compliance` were released together in [bridge-server](https://github.com/stellar/bridge-server) repo. The release process in monorepo allows releasing projects independently.
=> Add CHANGELOG to bridge compliance

protocols/horizon/README.md
Java SDK 0.2.1 released today: https://github.com/stellar/java-stellar-sdk/releases/tag/0.2.1
=> Update Horizon API compatibility table with Java SDK 0.2.1

clients/horizon/main.go, clients/horizon/mocks.go
When I added the `LoadTransaction` method to the horizon client, I forgot to add it to the interface.
=> Add LoadTransaction to horizon client interface

services/horizon/internal/docs/reference/endpoints/payments-all.md, services/horizon/internal/docs/reference/endpoints/payments-for-account.md, services/horizon/internal/docs/reference/endpoints/payments-for-ledger.md, services/horizon/internal/docs/reference/endpoints/payments-for-transaction.md
It's not clear that `/payments` endpoint can return operations like `create_account` or `account_merge`.
Releated: https://github.com/stellar/js-stellar-sdk/issues/182
=> Update /payments endpoints with operations

services/horizon/internal/docs/reference/endpoints/payments-for-account.md
In some examples this was `/account` while it really is `/accounts`.
=> Fix resource URL for account

services/horizon/internal/docs/reference/endpoints/trades.md
it appears these are implemented for /trade_aggregation but not /trades so removing them from the request example.
=> remove unsupported parameters start_time and end_time from the /trades request documentation

clients/horizon/client.go, clients/horizon/internal.go
Rewrite `horizon.Client.stream()` to use `bufio.Reader` (fix #548). I'm not super proud of this solution because it requires 2 additional loops:
* Main loop to read events until `io.EOF` error is returned by `reader.ReadString`.
* Internal loop to read lines until an empty line (SSE event delimiter) is found.
This basically duplicates code in `github.com/manucorporat/sse.decode` but is required because `sse.decode` is [using](https://github.com/manucorporat/sse/blob/master/sse-decoder.go#L40) `ioutils.ReadAll` for `io.Reader` provided in the `sse.decode` method argument.
Without doing this streaming method would wait until all events in the current streaming request are sent instead of dispatching them one by one as they arrive (what happens in most cases for `cursor=now`).
The ideal …
=> Rewrite horizon.Client.stream() to use bufio.Reader

services/horizon/internal/actions_operation_test.go
Finished tests started in https://github.com/stellar/go/pull/561.
=> Bump sequence test update

clients/horizon/client.go
Now it's misleading saying that only incoming payments are streamed
=> Update docs for horizon client StreamPayments func

amount/main.go, amount/main_test.go, services/horizon/internal/actions_assets.go, services/horizon/internal/resourceadapter/asset_stat.go, services/horizon/internal/resourceadapter/asset_stat_test.go
This change allows parsing string integers larger than `int64` in `amount.IntStringToAmount`. This function is used in `/assets` endpoint and currently does not work for larger amounts. The bug was introduced in https://github.com/stellar/go/commit/5bf53ca1550b70f00e6294589d4fcb2497264b31.
This also adds error check in `AssetsAction.loadPage` (that's why it hasn't been caught earler).
Close #606.
=> AllowOverInt64 in amount.IntStringToAmount

services/horizon/internal/ingest/system.go
This PR fixes random DB constraint errors like (and similar):
```
import session failed: Ingestion.Flush error: Error adding values while inserting to history_effects: Error adding values while inserting to history_effects: exec failed: pq: duplicate key value violates unique constraint "hist_e_by_order"
```
The reason is a synchronization issue between `App.UpdateLedgerState` and `ingest.System.runOnce` go routines. Both go routines are executed every second by the application ticker. The following sequence of events is possible:
Time | Tick1 | Tick2
-|-|-
1 | `UpdateLedgerState` result = `[horizon ledger = 10, core ledger = 11]` |
2 | Start ingest session `ledgers: [11, 11]` |
3 | | `UpdateLedgerState` result = `[horizon ledger = 10, core ledger = 11]`
4 | Finish ingest session …
=> Use the updated ledger state in ingest

services/horizon/internal/actions_offer_test.go
Every time test scenarios are rebuilt this test needs to be updated. It doesn't need to check the exact date, it's there just to ensure this is not a ledger sequence parsed as time (#480).
=> Fix actions_offer_test.go

protocols/horizon/main.go, services/horizon/internal/actions_root.go, services/horizon/internal/config.go, services/horizon/internal/init_web.go, services/horizon/internal/resourceadapter/root.go, services/horizon/internal/resourceadapter/root_test.go, services/horizon/main.go
Implements part of #239 
I've presented this change is several commits for clarity's sake. I'd be happy to squash it down to one before merging, if that's the custom.
The change here makes the friendbotURL show up only when it's set in the configured environment. This, to me, feels more correct than depending on a mainnet vs. testnet configuration because it's much more specific. It supposes that configuration (eg. environment variables) can be easily changed. In the issue (#239) a conventional approach for distinguishing mainnet vs testnet was alluded to but was not described - I was not able to find any code implementing a conventional approach. If that's still a strong preference, I can change this PR to match the convention.
This change also removes the redirect functionality that has …
=> Improve friendbot linking in root resource

protocols/horizon/main.go, protocols/horizon/main_test.go
- resolves #149, where the "memo" field does not exist in the JSON response for a transaction whose memo_type is text and the memo happens to be an empty string.
- Fix is to define a custom JSON marshaler that converts the Memo field to be a string pointer. That way if the memo_type is none, it can be set to nil and the resulting JSON response doesn't have a memo field. In all other cases, it points to a string (possibly the empty string), which would cause the JSON response to include "memo" as a field.
- Add some test cases to ensure this behavior, and also make sure that the default marshalling and unmarshalling of Transactions still work.
=> Fix empty memo field in JSON when memo_type is text

services/horizon/internal/init_web.go
There's no correct redirect route available when no friendbot URL is specified, we must 404.
=> horizon: Use redirect routes in cases where friendbot is configured

services/horizon/internal/assets/main_test.go
- Remove dependency on GoConvey for horizon/internal/assets/main_test.go
- Convert these tests to use testify. Functionality remains the same
- Addresses issue #638
=> Convert GoConvey from horizon/internal/assets

protocols/horizon/main_test.go
- Addresses #638 in an effort to remove GoConvey from existing tests
- All the original tests' functionality haven't changed. Just uses Testify instead of Convey
=> Remove goconvey dependency in protocols/horizon/main_test.go

services/horizon/internal/render/sse/main_test.go
- Addresses #638
- Removes GoConvey as a test depedency for services/internal/horizon/render/sse
=> Refactor test to not use GoConvey for render/sse

xdr/xdr_generated.go
Uses the version of `xdrgen` from https://github.com/stellar/xdrgen/commit/2008a1b741361b512eb1aa3e79c2b6063acc918a to get `MarshalBinary` and `UnmarshalBinary` methods for generated types.
Output also formatted with `go fmt`.
=> xdr: regenerate xdr_generated.go with new xdrgen

Gopkg.lock, xdr/xdr_generated.go
Fixes #374.
`XdrStream.ReadOne` decodes XDR directly into the provided receiver interface, so it requires a fresh instance of the target type on every iteration (otherwise since XDR has union types and variable-length lists, some data from previous iteration is not being overwritten and leaks into the current iteration).
I'm not a big fan of using reflection here, but I cannot come up with any other clean and concise solution.
/cc @bartekn @nullstyle
=> archivist: fix duplicated data when dumping an archive file

services/horizon/internal/logmetrics/main_test.go
- Addresses #638 to remove GoConvey in services/horizon/internal/logmetrics
=> Remove GoConvey dependency in services/horizon/internal/logmetrics

services/horizon/internal/toid/main_test.go
- Addresses #638 
- Rewrite tests for Parse and ToInt64 using test tables.
=> Remove GoConvey from toid. Use test tables

services/bridge/CHANGELOG.md, services/bridge/README.md, services/bridge/internal/listener/payment_listener.go
Bridge server currently  uses `HTTP_PAYLOAD_MAC` header to sign the callback requests, which can be troublesome because Nginx by default [marks such headers as invalid](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers) and silently drops them. This can become especially tricky in environments like AWS ElasticBeanstalk, which use Nginx under the hood, but don't provide easy access to its configuration.
This PR leaves the old header in place for backward compatibility, and duplicates MAC signature  into `X-Payload-Mac` header, which follows the (now deprecated) convention for application-level custom headers and shouldn't cause any issues in most popular web servers.
Although this provides a quick and easy fix for the problem, I think in the long run it would …
=> bridge: use nginx-safe header for MAC auth

services/horizon/db.go, services/horizon/internal/actions_assets_test.go, services/horizon/internal/config.go, services/horizon/internal/ingest/ingestion_test.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/main_test.go, services/horizon/internal/ingest/session.go, services/horizon/internal/ingest/session_test.go, services/horizon/internal/ingest/system_test.go, services/horizon/internal/init_ingester.go, services/horizon/internal/init_web.go, services/horizon/main.go
Asset stats calculations have become very CPU intensive with the recent growth of operations per ledger and assets in, both, public and test networks. Because it's part of the ingestion session it sometimes caused delays in ingesting new ledgers but also slows down connected stellar-core DB (calculations are done in core DB).
The original plan I discussed with @MonsieurNicolas was to extract asset stats calculations outside ingestion and make it run every X seconds, independently of ingestion. The problem is that it's a huge architectural change and requires much more work than I expected to make it right and test it properly. Given all the arguments above and the fact that it's already causing operational issues for some organizations I think we should design it along with the upcoming …
=> Feature flag to disable asset stats

protocols/horizon/main.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_offer_test.go, services/horizon/internal/config.go, services/horizon/internal/resourceadapter/offer.go, services/horizon/main.go
This PR is a _quickfix_ for #650 (and #538, #649). It introduces a new feature flag `ALLOW_EMPTY_LEDGER_DATA_RESPONSES` (default: `false`). When set to `true` it renders unavailable ledger data (like `close_time`) as `null` instead of sending `500 Internal Server Error` response. This is not a breaking change as the default value is `false`. It can be released in 0.14.1 patch release.
=> Feature flag to allow null ledger data in responses

services/horizon/internal/render/sse/main.go
- Add lock in sse/main Pumped() to protect usage of nextTick
=> Add lock in Pumped. Remove init function

Gemfile.lock
Most importantly, the current `stellar-base` version, 0.16.0, is not sufficient for building all test scenarios.
=> update ruby bundle dependencies

services/horizon/internal/ingest/session.go
`is.Cursor.NextLedger` can fail but it's not checked anywhere.
=> Check ingest.Cursor errors in Session

services/horizon/internal/actions/base.go, services/horizon/internal/actions_effects.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_operation.go, services/horizon/internal/actions_payment.go, services/horizon/internal/render/sse/main.go, services/horizon/internal/render/sse/main_test.go
Errors sent to clients via SSE stream are not necessarily the same level at the system layer. Currently every error passed to `stream.Err` is logged with `level=error`. Because of this we can often see `level=error` entries like: `sql: no rows in result set` in the logs, for example when streamed account has been removed.
This commit removes logging in `render/sse` package and reports errors in `actions_*.go` files. It also changes `actions.Base` to hide internal errors from the client: it returns "Object not found" for `sql.ErrNoRows` errors and "Unexpected stream error" for others. All occurrences of `stream.Err` have been updated with log reporting.
=> Improve stream error reporting

services/horizon/internal/actions/base.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_trade.go, services/horizon/internal/render/sse/stream.go
- Addresses the alternate solution laid out by Bartek in #687 
- This PR adds an Init method to stream that sends the preamble message.
- If there were any initial errors in validating the SSE request, base.execute will render a HTTP error code as the response
- Otherwise (upon success) it will send the preamble right away
=> Add Init method to stream

services/horizon/internal/actions_trade.go, services/horizon/internal/actions_trade_test.go, services/horizon/internal/db2/history/trade_aggregation.go
- Closes #545 
- Adds an offset parameter to TradeAggregationsQ and a WithOffset method.
- Change actions_trade.go so that an offset filter can be created and used.
- Add test
=> Add offset parameter to trade aggregations

Gopkg.lock
- closes #638 
- updates Gopkg.lock to remove GoConvey and its dependencies.
=> Update gopkg after removing goconvey

services/horizon/internal/actions_trade_test.go, services/horizon/internal/test/t.go
I started investigating https://github.com/stellar/go/issues/615 and I've found it was actually fixed by https://github.com/stellar/go/pull/654 but couldn't find any test that covers the problem described in the issue.
I've added a test to assert that error messages are returned as expected in the JSON response.
=> Improve test coverage for TradeIndexAction

services/horizon/internal/db2/history/main.go, services/horizon/internal/resourceadapter/trade.go
This can happen requesting `/trades` with `base_offer_id` or `counter_offer_id` equal `null` (if data has not been or is still being reingestested):
```
select failed: sql: Scan error on column index 4: converting driver.Value type <nil> ("<nil>") to a int64: invalid syntax
```
=> Display empty values when base_offer_id or counter_offer_id are null

services/horizon/db.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/session.go, services/horizon/internal/ingest/system.go, services/horizon/main.go
`horizon db backfill` command was not working because the global ledger
state (`ledger` package) was not updated before starting the ledger
backfill process.
Fix #718
CC @lechengfan
=> Fix `horizon db backfill` command

Gopkg.lock, services/horizon/internal/actions/base.go, services/horizon/internal/actions/rate_limiter_provider.go, services/horizon/internal/actions_account.go, services/horizon/internal/app.go, services/horizon/internal/config.go, services/horizon/internal/context/context_key.go, services/horizon/internal/helpers_test.go, services/horizon/internal/httpx/client.go, services/horizon/internal/httpx/request.go, services/horizon/internal/init_redis.go, services/horizon/internal/init_redis_test.go, services/horizon/internal/init_web.go, services/horizon/internal/middleware_logger.go, services/horizon/internal/middleware_rate_limit.go, services/horizon/internal/middleware_rate_limit_test.go, services/horizon/main.go
* fixes #715 @bartekn 
* Add an extra rate limit call for every call to stream.SSE in base.go so that clients are rate limited based on their DB queries
* Upgrade throttled package and refactor all the deprecated methods
=> Add rate limiting to stream requests

clients/horizon/client.go
Fixes a bug where requests exceeded the rate-limit but wouldn't return errors, so `stream` would continue reading data, blocking the calling function from being able to back off and retry and avoid continual rate-limiting.
=> clients/horizon: return error on bad http status

services/horizon/internal/actions/base.go
I misunderstood how unbuffered channels work in Go (from [Effective Go](https://golang.org/doc/effective_go.html#channels)):
> Receivers always block until there is data to receive. If the channel is unbuffered, the sender blocks until the receiver has received the value. If the channel has a buffer, the sender blocks only until the value has been copied to the buffer; if the buffer is full, this means waiting until some receiver has retrieved a value.
The fix is to change unbuffered channel to a buffered channel of size `1`.
=> Fix memory leak in stream

.travis.yml
In general new Go releases build faster binaries. Go 1.10 introduced faster [GC](https://golang.org/doc/go1.10#gc), Go 1.11 has [performance](https://golang.org/doc/go1.11#performance) changes in `math/big`. We should switch to latest version.
=> Go 1.11 builds

services/horizon/db.go, services/horizon/internal/db2/core/trustline.go, services/horizon/internal/ingest/asset_stat.go, services/horizon/internal/ingest/asset_stat_test.go, services/horizon/internal/ingest/ingestion.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/session.go
Something we discussed in https://github.com/stellar/go/pull/147 but never implemented.
Adds a command `horizon db init-asset-stats` that calculates the stats from the current state of core DB. To achieve this I refactored `AssetsModified` to remove dependency on `ingest.Session` struct and to allow to use it outside ingestion context.
=> Init asset stats command

services/horizon/README.md
It seems that `glide` is no more used as a dependency manager for the Horizon, and developers should now use the `dep` instead. But docs don't reflect that. This PR is tightly related to #734, which is devoted to admin documentation fix.
=> Change `glide` to `dep` in Horizon README

services/horizon/internal/db2/history/trade.go
Exactly the same issue as in #315.
---
Old query:
```
horizon=> EXPLAIN ANALYZE SELECT history_operation_id, htrd."order", htrd.ledger_closed_at, htrd.offer_id, htrd.base_offer_id, base_accounts.address as base_account, base_assets.asset_type as base_asset_type, base_assets.asset_code as base_asset_code, base_assets.asset_issuer as base_asset_issuer, htrd.base_amount, htrd.counter_offer_id, counter_accounts.address as counter_account, counter_assets.asset_type as counter_asset_type, counter_assets.asset_code as counter_asset_code, counter_assets.asset_issuer as counter_asset_issuer, htrd.counter_amount, htrd.base_is_seller, htrd.price_n, htrd.price_d FROM history_trades htrd JOIN history_accounts base_accounts ON base_account_id = base_accounts.id JOIN history_accounts counter_accounts ON …
```
=> Fix slow trades page query

services/horizon/internal/actions/helpers.go, services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions_assets.go, services/horizon/internal/actions_trade.go, services/horizon/internal/db2/core/offer_test.go, services/horizon/internal/db2/history/trade_test.go, services/horizon/internal/db2/page_query.go, services/horizon/internal/db2/page_query_test.go, services/horizon/internal/ingest/session_test.go
Fixed multiple issues in query checking code:
* Invalid `cursor` no longer generate `ERROR` level logs.
* Internal errors (like `strconv.ParseInt`, `amount.Parse` errors) are
no longer sent with an error response.
=> Fix query checking

services/horizon/internal/reap/system.go
When the reap function is turned on, this operation will always be performed due to a conditional error.
=> Fix horizon reap.

services/horizon/internal/actions/helpers.go, services/horizon/internal/actions_account.go, services/horizon/internal/actions_data.go, services/horizon/internal/actions_effects.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_operation.go, services/horizon/internal/actions_operation_test.go, services/horizon/internal/actions_path.go, services/horizon/internal/actions_payment.go, services/horizon/internal/actions_trade.go, services/horizon/internal/actions_transaction.go
Invalid UTF-8 byte sequence passed to Postgres triggers errors like:
```
invalid byte sequence for encoding "UTF8"
```
=> Validate UTF-8 strings in params

services/horizon/db.go
=> Fix panic when missing an argument for horizon db backfill

services/horizon/internal/action.go, services/horizon/internal/actions/base.go, services/horizon/internal/app.go
This commit fixes two issues connected to graceful shutdown in Horizon. First, application context was not correctly handled in actions. Because of this, streaming connections were not closed gracefully.
Streaming body during shutdown before the change:
```
retry: 1000
event: open
data: "hello"
curl: (18) transfer closed with outstanding read data remaining
```
Streaming body during shutdown after the change:
```
retry: 1000
event: open
data: "hello"
retry: 10
event: close
data: "byebye"
```
Second, DB connections were closed before requests handling was finished. This caused generation of `ERROR`-level log entries like `sql: database is closed` during shutdown. This commit runs the code that closes DB connections after the requests are properly closed.
Close #777.
=> Fix graceful shutdown

services/horizon/internal/docs/reference/resources/orderbook.md
Update horizon docs for the orderbook resource.
=> fix links and update orderbook field names

services/horizon/internal/docs/developing.md
Let me know if instructions are clear and, if not, how to improve them.
=> Add information about test scenarios to docs

services/horizon/internal/actions_root.go, services/horizon/internal/actions_root_test.go, services/horizon/internal/app.go, services/horizon/internal/config.go, services/horizon/internal/helpers_test.go, services/horizon/internal/init_ingester.go, services/horizon/internal/init_txsub.go, services/horizon/internal/txsub/open_submission_list.go, services/horizon/internal/txsub/system.go, services/horizon/internal/txsub/system_test.go, services/horizon/internal/txsub/test_helpers.go, services/horizon/main.go
This commit fixes two issues in `txsub` package. First, issue was a
deadlock in `Tick()` function:
```go
sys.tickMutex.Lock()
if sys.tickInProgress {
logger.Debug("ticking in progress")
return
}
sys.tickInProgress = true
sys.tickMutex.Unlock()
```
When two `Tick()` methods were called simultanously one of them could
`Lock()` the mutex without calling `Unlock()` properly. This could
basically break the `txsub` system as sequence number could not be
updated.
The second issue was a problem with `App` initialization.
`App.networkPassphrase` was set to test network passphrase by default.
If `txsub` system was initialized before updating the network passphrase
using connected `stellar-core`, the system would not be able to
correctly find the transaction result in a database as calculated hash …
=> Fix deadlock in `txsub.System.Tick()` and `tx_bad_seq` errors

services/horizon/internal/db2/schema/main.go, services/horizon/main.go
When a user runs a newer or older version of Horizon that is incompatible with the current DB state, Horizon should fail with a descriptive error message indicating the migration(s) that need to be performed, and their direction. This avoids the situation described in #778, where Horizon may run in a broken way without alerting the user.
We do not run the migration automatically, since the user should understand what is happening, and take responsibility for backing up their data if necessary.
Example command line output when a new migration is detected:
```
$horizon --db-url="postgres://localhost/horizon_schema" --stellar-core-db-url="postgres://stellar:postgres@localhost:8002/core" --stellar-core-url="http://localhost:11626" --port 8001 --network-passphrase "Test SDF Network ; September …
```
=> Require migration to run Horizon version successfully (fixes #778)

services/horizon/internal/db2/history/effect.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/session.go, services/horizon/internal/ingest/session_test.go
`account_debited` should indicate the `source_amount` instead.
Close #744
=> fix wrong effect of a circular path payment

services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/operation.go, services/horizon/internal/db2/history/operation_test.go
This PR is the result of https://github.com/stellar/go/pull/811#issuecomment-455382632. This is basically a modified version of https://github.com/stellar/go/pull/439
Close #515
=> horizon/db2/history: optimize account queries for payments and operations

protocols/horizon/main.go, protocols/stellarcore/info_response.go, services/horizon/internal/actions_account.go, services/horizon/internal/actions_path.go, services/horizon/internal/actions_root.go, services/horizon/internal/actions_root_test.go, services/horizon/internal/app.go, services/horizon/internal/resourceadapter/root.go, services/horizon/internal/resourceadapter/root_test.go
Addresses #580 
As stated in https://github.com/stellar/stellar-core/issues/1740, I take here current protocol version from the `ledger.version` attribute of stellar-core info command response
I am a quite newbie in both Stellar and Go, so I will appreciate any comments, which help me improve this PR 🙏
=> Report right protocol version in horizon root path

.travis.yml, protocols/horizon/main.go
Simple script to find all deprecated fields/methods during a release build. See in [action](https://travis-ci.org/stellar/go/jobs/485460472#L222).
Close #833.
Close #536.
=> Deprecated check

services/horizon/internal/actions/responders.go
Although every single object streamer has `JSON()`, we might have a single object streamer who doesn't have `JSON()` in the future. Keeping the interface minimal makes it easier for future developers to make changes.
Details: https://github.com/stellar/go/pull/828#discussion_r251932368
=> horizon/actions: remove JSON from SingleObjectStreamer

services/horizon/internal/actions_offer.go, services/horizon/internal/actions_offer_test.go, services/horizon/internal/helpers_test.go
We used to load `action.Records` per `SSE()` call with the same cursor and use `SentCount()` to paginate for the next call. It is problematic if an offer gets added or dropped. This PR sets the cursor every time we send an event back so that we don't rely on `SentCount()`.
Close #637
=> horizon/actions: fix slice looping for offers in an account

services/horizon/internal/actions/base.go, services/horizon/internal/actions/helpers.go, services/horizon/internal/actions/responders.go, services/horizon/internal/actions_account.go, services/horizon/internal/actions_data.go, services/horizon/internal/actions_effects.go, services/horizon/internal/actions_ledger.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_operation.go, services/horizon/internal/actions_order_book.go, services/horizon/internal/actions_payment.go, services/horizon/internal/actions_trade.go, services/horizon/internal/actions_transaction.go, services/horizon/internal/assets/main.go, services/horizon/internal/render/sse/main.go, services/horizon/internal/render/sse/stream.go, services/horizon/internal/render/sse/stream_test.go, services/horizon/internal/resourceadapter/trade.go, services/horizon/internal/resourceadapter/transaction.go
This PR does the following:
1. removes unnecessary empty lines.
2. removes `Stream` interface and exports `stream` struct.
3. makes both `SSE()` and `LoadEvent` return an error directly.
4. consolidates errors returned when streaming into `sse/stream.go`.
5. fixes `TestStream_Err()` so that we don't send preamble when encountering an error before sending an event.
=> horizon/actions: improve streaming error handling

services/horizon/internal/actions/base.go, services/horizon/internal/actions/responders.go, services/horizon/internal/actions_account.go, services/horizon/internal/actions_assets.go, services/horizon/internal/actions_data.go, services/horizon/internal/actions_effects.go, services/horizon/internal/actions_ledger.go, services/horizon/internal/actions_metrics.go, services/horizon/internal/actions_not_found.go, services/horizon/internal/actions_not_implemented.go, services/horizon/internal/actions_offer.go, services/horizon/internal/actions_operation.go, services/horizon/internal/actions_operation_fee_stats.go, services/horizon/internal/actions_order_book.go, services/horizon/internal/actions_path.go, services/horizon/internal/actions_payment.go, services/horizon/internal/actions_root.go, services/horizon/internal/actions_trade.go, services/horizon/internal/actions_transaction.go, services/horizon/internal/render/sse/stream_test.go, support/render/hal/main.go
This PR does the following:
1. Renames `JSON`, `Raw`, and `SSE` responder to `JSONer`, `RawDataResponder`, and `EventStreamer` respectively.
2. Has JSON() and Raw() return an error
3. Adds the corresponding interface verifications
Close #870
=> horizon/actions: have JSON() and Raw() return an error

services/horizon/cmd/db.go, services/horizon/cmd/root.go, services/horizon/cmd/serve.go, services/horizon/internal/app.go
Previously, `horizon` worked the same as `horizon serve`. I don't see much benefit for this shortcut, and this is a little unexpected as a horizon user. This PR also piggybacks some of the code cleanup.
=> horizon/cmd: require at least one argument for rootCmd

services/horizon/cmd/root.go, services/horizon/internal/actions_assets_test.go, services/horizon/internal/app.go, services/horizon/internal/app_test.go, services/horizon/internal/helpers_test.go, services/horizon/internal/init_redis_test.go, services/horizon/internal/init_web.go, services/horizon/internal/middleware_test.go
We always return `nil` in this function.
=> horizon: remove redundant return param from NewApp()

services/horizon/cmd/root.go
Currently, when running `horizon db migrate` cmd, the error message points to:
https://github.com/stellar/horizon/blob/master/CHANGELOG.md
This change points it to the current repo's changelog:
https://github.com/stellar/go/blob/master/services/horizon/CHANGELOG.md
=> horizon/cmd: point to current horizon repo changelog on migration cmd error

services/horizon/cmd/db.go, services/horizon/cmd/root.go
We can't run the migration checks on every single command like `horizon db init` and `horizon db migrate` themselves. This PR removes `cobra.OnInitialize()` and places `initConfig()` at commands where we need it.
=> horizon/cmd: fix migration checks

services/horizon/internal/docs/reference/endpoints/trades.md
Example response showed uppercase N and D, but the Horizon API returns lowercase n and d.
=> Fix case of `price` keys in example response

services/horizon/internal/docs/reference/resources/trade.md
Other resources like Offer do have both `price` (float) and `price_r` (rational number). 
However for Trade, there is just `price`, and is the rational number version.
See:
https://github.com/stellar/go/blob/4791a38ef2611994db9b841f0d2181f5ed4a20ca/protocols/horizon/main.go#L290
=> Fix name of `price` field on Trade

services/horizon/internal/middleware.go
We had a variable that was intended to be used here.
=> horizon: log undefined when a request is blocked 

services/horizon/internal/actions_operation_fee_stats.go, services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/app.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/transaction.go, services/horizon/internal/operationfeestats/main.go, services/horizon/internal/test/t.go
It seems that percentile stats are much better for estimating the required fee. Would be great to release it in the next version.
=> Add percentiles to /operation_fee_stats

services/horizon/CHANGELOG.md, services/horizon/cmd/root.go
A lot of scripts are using `horizon` without specifying `serve` explicitly. This PR removes the requirement.
=> horizon/cmd: remove the requirement of specifying "serve"

services/horizon/internal/init_web.go, services/horizon/internal/render/sse/stream.go
The `ErrRateLimited` error was returned with `WriteEvent` not through `problem.Render` before https://github.com/stellar/go/pull/856/. The problem was that we didn't register `sse.ErrRateLimited` in `errToProblemMap` and when `sent count` is zero, we used `problem.Render` to process the error. Hence, we were logging `ErrRateLimited` in the last deploy.
Close #908
=> horizon/actions: fix stream logging

services/horizon/cmd/db.go
Simple command to support ledger range reingestion. Can be used to distribute reingestion of ledgers across multiple machines:
```
horizon1> horizon db reingest range 1 10000
horizon2> horizon db reingest range 10001 20000
horizon3> horizon db reingest range 20001 30000
...
```
=> Add `db reingest range` command

services/horizon/internal/db2/history/transaction.go
It's possible that for some fee distribution returned values are floats, we want to return ints.
=> horizon: Ceil() operation fee stats

services/horizon/CHANGELOG.md, services/horizon/internal/actions_operation_fee_stats.go, services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/app.go, services/horizon/internal/db2/history/ledger.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/operation.go, services/horizon/internal/db2/history/transaction.go, services/horizon/internal/init_web.go, services/horizon/internal/operationfeestats/main.go
I'm wondering if we should rename `/operation_fee_stats` to simply `/fee_stats`.
Also, renamed `TransactionsForLastXLedgers` to `OperationFeeStatsForXLedgers`.
Deployed `ledger-capacity-stats` branch to: https://horizon-dev-pubnet.stellar.org/operation_fee_stats and https://horizon-testnet.stellar.org/operation_fee_stats.
Close #891.
=> horizon: Add ledger capacity stats

services/horizon/internal/docs/reference/resources/transaction.md
I noticed that `account` was no longer present in the newest responses, and while updating that, caught a couple other difference as well. 
* Links are full URLs, not just paths
* `account` -> `source_account`
* `account_sequence` -> `source_account_sequence`
* `successful`
* `signatures`
* `memo`/`memo_type`
* `valid_after`, but I'm not sure if this is always present, and I'm not sure how to note that in the table.
* `created_at`, I'm not sure if the type should just be `string`
I completely replaced the examples with a new transaction, since it seemed wrong to mix the data (even for example purposes).
=> Update documentation for transaction attributes

services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/app.go, services/horizon/internal/db2/history/ledger.go, services/horizon/internal/db2/history/operation.go, services/horizon/internal/operationfeestats/main.go
We need to log what went wrong more clearly in order to have an easier life for debugging.
=> horizon: improve logging for update operation fee stats

Gopkg.lock, Gopkg.toml, services/horizon/internal/init_redis.go, support/log/entry.go, support/log/main.go
Logrus changed the type of `Hook.Entries` last year in May. This incompatible type issues have been raised many times by community members, and I don't see a reason of not upgrading logrus.
Close #786
=> all: upgrade logrus library

services/horizon/internal/db2/history/operation.go
`ceil()` function in PostgreSQL returns the same type as input. It's possible that percentile value will be returned in e-notation (like `2.000081e+06`) and Go drivers have problems with converting such values into `int` returning an error:
```
sql: Scan error on column index 10, name "p90": converting driver.Value type float64 ("2.000081e+06") to a int64: invalid syntax
```
We cast values to `bigint` to prevent such errors.
=> Cast fee stats to bigint

protocols/horizon/main.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions_account_test.go, services/horizon/internal/db2/core/account.go, services/horizon/internal/db2/core/main.go, services/horizon/internal/db2/core/trustline.go, services/horizon/internal/resourceadapter/account.go, services/horizon/internal/resourceadapter/balance.go
this PR exposes the `lastModified` field on an account (native balance) and on trustlines (non-native balance).
This allows us to easily get the ledger number when an account's balance was last modified.
=> include lastModified field in account balances

clients/horizon/error.go, exp/clients/horizon/account_request.go, exp/clients/horizon/account_request_test.go, exp/clients/horizon/asset_request.go, exp/clients/horizon/asset_request_test.go, exp/clients/horizon/client.go, exp/clients/horizon/effect_request.go, exp/clients/horizon/effect_request_test.go, exp/clients/horizon/error.go, exp/clients/horizon/internal.go, exp/clients/horizon/main.go, exp/clients/horizon/main_test.go, exp/clients/horizon/mocks.go, exp/clients/horizon/responses.go
This is the first attempt in redesigning the `horizon client` of the Go SDK as described in #844. The idea is to implement the proposed pattern for a few endpoints, review, then implement for the others.
The endpoints implemented here are for getting account details and effects from horizon.
I have tried to maintain the same file structure as the current `horizon` client so that it might be easier to just copy this experimental package over when the time is right.
`responses.go` still maps `protocols\horizon`. Any new response `structs` are created in this file.
Because horizon server API usually require just one parameter e.g: `/accounts/{account}/effects` the requests structs can usually only have one parameter set when building a url to be queried.
There are some exceptions to this …
=> exp/clients/horizon: initial endpoints

services/horizon/internal/actions_transaction_test.go, services/horizon/internal/txsub/results/db/main.go, services/horizon/internal/txsub/results/db/main_test.go
Since #875 `POST /transactions` returned `200 OK` status for old, failed transactions (that are not present in core DB) if a node was ingesting failed transactions. This PR fixes the code responsible for checking the transaction status and returns correct HTTP code and response.
=> Return correct status for resubmitting old, failed transactions

services/horizon/cmd/db.go, services/horizon/cmd/root.go, services/horizon/internal/ingest/system.go
This issue is caused by reverting a PR on the release branch for quickly unblocking, not caused by the `logrus` library update. That temporary PR was brought back to `master` after we published the release, and the PR reverting the revert didn't clean it up everything properly. Thus we ended up in this state.
This PR uses `Logger.SetLevel` to properly set the level of the logger in an `Entry`.
Close #966
=> horizon/cmd: fix configuring logging level

services/horizon/cmd/db.go
We've been using the wrong timer for showing clear-ledger mean time
=> horizon/cmd: fix logging wrong info during reingestion

services/horizon/internal/actions_operation.go, services/horizon/internal/actions_operation_test.go, services/horizon/internal/actions_payment.go, services/horizon/internal/actions_payment_test.go, services/horizon/internal/actions_transaction.go, services/horizon/internal/actions_transaction_test.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/operation.go, services/horizon/internal/db2/history/operation_test.go, services/horizon/internal/db2/history/transaction.go, services/horizon/internal/db2/history/transaction_test.go, services/horizon/internal/test/scenarios/failed_transactions.rb
As proved by 2cf045bc11febe413feb1af03c7493e955c9f792 the code in #875 was not safe. The default queries for `TransactionsQ` and `OperationsQ` were retuning both successful and failed objects. This is not how a default query should behave as it can have a critical implications when `SuccessfulOnly()` method is not called.
This PR changes the default query to return successful objects only and adds `IncludeFailed()` method to include failed objects. It also adds extra checks in query structs and actions to check if objects are correct and tests for `/payments` endpoint.
**Please do not merge without extensive check of the code.**
=> Improve queries getting failed objects

services/horizon/cmd/db.go, services/horizon/internal/ingest/system.go
This PR adds two subcommands to `horizon db reingest`, one is `range`, one is `outdated`. This PR also fixes the case when a user input `horizon db reingest unknown`. It used to show
```
[timestamp] strconv.Atoi: parsing "unknown": invalid syntax
INFO[timestamp] reingest: complete                            count=0 means="load: 0s clear: 0s ingest: 0s" pid=58924 rate=0
```
Finally it improves the documentation on the usage for all `horizon db reingest` commands. 
Close #917
=> horizon/cmd:  add subcommands to horizon db reingest

Gopkg.toml, exp/clients/horizon/asset_request.go, exp/clients/horizon/asset_request_test.go, exp/clients/horizon/client.go, exp/clients/horizon/effect_request.go, exp/clients/horizon/ledger_request.go, exp/clients/horizon/ledger_request_test.go, exp/clients/horizon/main.go, exp/clients/horizon/main_test.go, exp/clients/horizon/mocks.go, exp/clients/horizon/responses.go
Still building out the horizon client.
This PR add /assets endpoint, adds sdk identifiers to requests which closes #962 and implements streaming on the /effects endpoint.
Will appreciate some feedback especially on the streaming implementation.
=> exp/clients/horizonclient: assets and streaming

services/horizon/internal/app.go, services/horizon/internal/init.go, support/log/entry.go, support/log/main.go
We've been using `log.Panic` for initialization. Panic should be used on
unexpected things. In our case, it is likely that the user doesn't have
the right configs to spin up our server.
=> support/log: add log fatal functions

.travis.yml
It looks like build times are comparable vs. not using caching because some updates have been happening to the builds for the first few times. If these settle down, the caching will be about 40 secs faster per build. In addition the caching approach may be more redundant to network outages like the one we saw yesterday.
=> all: cache go dependency in Travis

services/horizon/internal/actions/helpers.go, services/horizon/internal/actions_effects.go, services/horizon/internal/actions_effects_test.go, services/horizon/internal/actions_operation.go, services/horizon/internal/actions_operation_test.go, services/horizon/internal/actions_payment.go, services/horizon/internal/actions_payment_test.go, services/horizon/internal/actions_transaction.go, services/horizon/internal/actions_transaction_test.go, services/horizon/internal/helpers.go
This commit fixes multiple issues with parameter handling in actions. The main problem was connected to `base.GetString` method that gets values from the URLParams, form or query string (in this order). It was possible that extra GET parameter changed the internal query. For example:
```
/ledgers/100/effects?account_id=GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H
```
doesn't return effects for ledger 100 but for a given account ID because if `account_id` is set the rest of the parameters are ignored (`switch`). Obviously, this is not how the actions should be used but for extra security I think this should be fixed.
To solve this issue:
* We count applied filters, if it's larger than 1 we return `400 Bad Request` response.
* We ensure that `tx_id` parameter is only checked in …
=> Check if multiple filters are set

services/horizon/cmd/root.go, services/horizon/internal/actions_rate_limit_exceeded.go, services/horizon/internal/app.go, services/horizon/internal/config.go, services/horizon/internal/helpers_test.go, services/horizon/internal/middleware_test.go, services/horizon/internal/web.go
Action.Prepare method has already assigned the app in the context to the
action, which makes This `App` field redundant.
This PR also renames `config.RateLimit` to `config.RateLimitQuota` to be specific.
=> horizon: remove redundant field App in the rate limiter

exp/txnbuild/change_trust.go, exp/txnbuild/cmd/txnbuild_examples/main.go, exp/txnbuild/transaction_test.go
Very small PR to abstract the details of how you delete trustlines. Part of #982.
=> exp/txnbuild: user-facing function to wrap delete trustline functionality

exp/clients/horizon/client.go, exp/clients/horizon/fee_stats_request.go, exp/clients/horizon/main.go, exp/clients/horizon/main_test.go, exp/clients/horizon/mocks.go, exp/clients/horizon/offer_request.go, exp/clients/horizon/offer_request_test.go, protocols/horizon/main.go
This PR  adds support for getting fee_stats and getting offers made by an account from horizon.
This closes #954
=> exp/client/horizon: support fee_stats and account offers

exp/txnbuild/allow_trust.go, exp/txnbuild/asset.go, exp/txnbuild/cmd/txnbuild_examples/main.go, exp/txnbuild/transaction_test.go
Adds allow trust operation to `txnbuild`. Verified by running operation manually and inspecting returned XDR for flag change.
As usual, feel free to skip scratchpad code in `/txnbuild_examples/main.go`.
This closes #982.
=> txnbuild allow trust (#982)

protocols/horizon/main.go, services/horizon/internal/actions_account_test.go, services/horizon/internal/resourceadapter/balance.go, services/horizon/internal/resourceadapter/balance_test.go
We don't want to show the flag for XLM.
=> horizon: hide is_authorized flag for native asset

Gopkg.lock, Gopkg.toml, services/horizon/internal/app_test.go, services/horizon/internal/web.go
This removes the dependency to `github.com/rs/xhandler`. We are using a pretty outdated version released in June 2016. This PR bumps the version to the latest release in Feb. 2018.
Note that the behavior had been changed [here](https://github.com/rs/cors/issues/30).
Close #164
=> all: update cors library

.travis.yml, exp/txnbuild/transaction.go, gofmt.sh, govet.sh
Addresses the problem of `go fmt` changes between versions of go described in #1030 by only running `gofmt` on the recommended developer version (currently 1.11).
This PR also changes the output of `gofmt` to `-d` to provide more context for failing format checks. This is important information since the developer may potentially have the wrong version of the `gofmt` binary in their devel environment and be unable to reproduce.
=> only run go fmt on one Go version

exp/clients/horizon/client.go, exp/clients/horizon/main.go, exp/clients/horizon/main_test.go, exp/clients/horizon/mocks.go, exp/clients/horizon/transaction_request.go, exp/clients/horizon/transaction_request_test.go, protocols/horizon/main.go
This PR add support for retrieving transaction information for accounts, ledgers, a transaction hash and all transactions.
Closes #957 
Closes #1018
=> exp/client/horizon: support transactions endpoints

services/horizon/internal/actions_account.go, services/horizon/internal/resourceadapter/account.go, services/horizon/internal/resourceadapter/balance.go, services/horizon/internal/resourceadapter/balance_test.go
This PR removes the `history.Account` from AccountShowAction since it's
not used. It also wraps the errors we return in some associated functions.
=> horizon: remove unused param in populating account

exp/clients/horizon/client.go, exp/clients/horizon/internal.go, exp/clients/horizon/main.go, exp/clients/horizon/main_test.go, exp/clients/horizon/mocks.go, exp/clients/horizon/order_book_request.go, exp/clients/horizon/order_book_request_test.go
This PR adds support for querying the orderbook of asset pairs.
This is part of the tasks to be done in #1021
=> exp/clients/horizon: orderbook

exp/clients/horizon/client.go, exp/clients/horizon/main.go, exp/clients/horizon/mocks.go, exp/clients/horizon/trade_request.go, exp/clients/horizon/trade_request_test.go
This PR supports querying all trades, trades for an account and trades for an offer.
Closes #1020
=> exp/clients/horizon: support trades endpoint

support/render/problem/main.go, support/render/problem/main_test.go
There is an inconsistency in the `type` returned by `friendbot` when making request which fail in `Horizon`. The following is an example taken from a failed request (notice the prefix in type):
```
{
"type":"https://stellar.org/horizon-errors/https://stellar.org/horizon-errors/not_found",
"title":"Resource Missing",
"status":404,
"detail":"The resource at the url requested was not found.  This is
usually occurs for one of two reasons:  The url requested is not
valid, or no data in our database could be found with the parameters
provided."
}
```
The issue was on the `Inflate` method which is used across different projects. Horizon was returning the type already "inflated" and then`friendbot` was inflating it again, appending the prefix twice.
=> Don't repeat Horizon prefix if it's present when inflating problems.

exp/txnbuild/README.md
Add a short README for `txnbuild`.
1. This will be updated with some short examples once #1070 is done.
2. This will be linked to a top-level README covering both the client and txnbuild once #1067 is done.
Closes #1027.
=> txnbuild: Initial README

exp/clients/horizon/client.go, exp/clients/horizon/main.go, services/horizon/internal/middleware.go
this allows any app using the new SDK to set the client app name and version explicitly
=> set client app name and app version explicitly in exp Go SDK

exp/clients/horizon/client.go
stream() method added onto `Client` in https://github.com/stellar/go/commit/9aeb3da0e1a5bc5527b74604fac1040fbedf78e9 so set app name and header in stream() method as well
=> setClientAppHeaders on stream() for exp package

exp/clients/horizon/error.go, exp/txnbuild/account_merge.go, exp/txnbuild/allow_trust.go, exp/txnbuild/bump_sequence.go, exp/txnbuild/change_trust.go, exp/txnbuild/create_account.go, exp/txnbuild/create_passive_offer.go, exp/txnbuild/inflation.go, exp/txnbuild/manage_data.go, exp/txnbuild/manage_offer.go, exp/txnbuild/path_payment.go, exp/txnbuild/payment.go, exp/txnbuild/set_options.go
This small refactoring PR moves the internal `xdrOp` field out of each `Operation`'s struct to a local variable (see #1040 for rationale).
`CreatePassiveOffer` is missing because it was already done.
`SetOptions` was not changed because it has multiple methods that manipulate the state of the internal xdr, so a struct-level variable is actually useful there.
This closes #1040.
=> exp/txnbuild: reduce xdr scope

exp/clients/horizon/client.go, exp/clients/horizon/main.go, exp/clients/horizon/mocks.go, exp/clients/horizon/trade_request.go, exp/clients/horizon/trade_request_test.go
This PR supports streaming trades that occur on the network.
Closes #1076
=> exp/clients/horizon: support streaming trades

exp/clients/horizon/client.go, exp/clients/horizon/main.go, exp/clients/horizon/mocks.go, exp/clients/horizon/transaction_request.go, exp/clients/horizon/transaction_request_test.go
This PR adds supports for streaming transactions that occur on the network. It allows users to stream all transactions and transactions for an account.
Closes #1075 
Closes #261
=> exp/clients/horizon: stream transactions

exp/clients/horizon/client.go, exp/clients/horizon/ledger_request.go, exp/clients/horizon/ledger_request_test.go, exp/clients/horizon/main.go, exp/clients/horizon/mocks.go
This PR modifies streaming for ledgers to use the new `StreamLedgers` function.
=> exp/clients/horizon: StreamLedgers

services/horizon/internal/docs/reference/endpoints/offers-for-account.md, services/horizon/internal/docs/reference/endpoints/orderbook-details.md, services/horizon/internal/docs/reference/endpoints/trade_aggregations.md, services/horizon/internal/docs/reference/endpoints/trades-for-account.md, services/horizon/internal/docs/reference/endpoints/trades.md
Updated examples for all of the trade endpoints (ran in testnet) based on the changes in #549.
Intentionally deleted the streaming example from the trades endpoint, as it was a JavaScript object (copied from the node console) rather than a JSON response, and the JSON response was identical to the existing example.
=> Add updated orderbook examples.

exp/txnbuild/cmd/txnbuild_examples/main.go, exp/txnbuild/transaction.go, exp/txnbuild/transaction_test.go, protocols/horizon/main.go, protocols/horizon/main_test.go
This closes #1126 and does the following:
- Removes the custom `Account` object from `txnbuild`, and instead depend on a new `Account` interface
- Modifies `protocols/horizon` to allow it to conform to the new interface, and in particular to add methods to manipulate the account sequence number, which needs to be be manipulated as a number, but stored as a string. `GetAccountID` protects the caller from the underlying ID implementation (which is helpful since there are more than one, and only one is correct to use).
- Improves unit tests by abstracting account type to a helper, and making test strings more explicit
- Addresses some golint naming warnings
The code from this PR is needed to unblock #1070.
=> Increment sequence number during tx build

exp/txnbuild/change_trust.go, exp/txnbuild/cmd/txnbuild_examples/main.go, exp/txnbuild/manage_offer.go, exp/txnbuild/transaction_test.go
Quick refactoring PR to fix some unwieldy names which caused confusion for multiple reviewers.
Closes #1039.
=> exp/txnbuild: rename constructor functions

exp/txnbuild/allow_trust.go, exp/txnbuild/asset.go, xdr/allow_trust_op_asset.go, xdr/asset.go, xdr/asset_test.go
Move allow trust asset helper func from `txnbuild` to the XDR library, where similar things already exist. Closes #1013.
=> xdr: move allow trust converter to XDR lib

exp/ticker/cmd/generate.go, exp/ticker/internal/actions_asset.go, exp/ticker/internal/actions_market.go, exp/ticker/internal/main.go, exp/ticker/internal/tickerdb/main.go, exp/ticker/internal/tickerdb/queries_market.go, exp/ticker/internal/tickerdb/queries_market_test.go, exp/ticker/internal/utils/main.go
This PR:
- Closes #1083.
It aims to:
- Add support for calculating the following attributes from all the stored (and validated) trade pairs in a given time window (e.g. 24h, 7d):
```
- base_volume
- counter_volume
- trade_pair_name
- price (last price)
- trade_count
- volume24h
- price_change_24h
- volume_7d
- price_change_7d
```
- Provide a CLI command for outputting aggregated market data to a JSON file.
=> exp/ticker: Market data aggregation

exp/ticker/cmd/generate.go, exp/ticker/internal/actions_asset.go, exp/ticker/internal/actions_market.go, exp/ticker/internal/main.go, exp/ticker/internal/scraper/main.go, exp/ticker/internal/tickerdb/queries_asset.go, exp/ticker/internal/utils/main.go
This PR:
- Closes #1085.
It aims to:
- Provide a CLI command for retrieving the asset data from the database and dumping it to a JSON file.
=> exp/ticker: create CLI command to output asset data to a file

exp/txnbuild/memo.go, exp/txnbuild/transaction.go, exp/txnbuild/transaction_test.go
This PR adds support for [transaction memos](https://www.stellar.org/developers/guides/concepts/transactions.html#memo) to `txnbuild`.
Closes #1147.
=> txnbuild: memo support

exp/txnbuild/allow_trust.go, exp/txnbuild/asset.go, exp/txnbuild/asset_test.go, exp/txnbuild/change_trust.go, exp/txnbuild/cmd/txnbuild_examples/main.go, exp/txnbuild/create_account.go, exp/txnbuild/create_passive_offer.go, exp/txnbuild/manage_offer.go, exp/txnbuild/path_payment.go, exp/txnbuild/payment.go, exp/txnbuild/transaction.go, exp/txnbuild/transaction_test.go
As discussed in #1029, this PR replaces the use of `*Asset` with a new `Asset` interface. This allows us to maintain the convention that pointers are optional, while producing concrete asset types that have sensible default behaviour.
This change makes the existing syntactic sugar helper methods redundant, which is a nice bonus.
One consequence of the move to an interface is the need to add methods for `Code` and `Issuer`. This is required because no fields can be relied on when an interface is passed.
A second consequence is that methods like `func (ca CreditAsset) GetType() (AssetType, error)` are not pointer receivers, to avoid having to pass pointers in to conform to the interface. Luckily there are no mutable operations here.
Effective Go …
=> txnbuild: move asset from pointer to interface

exp/ticker/internal/actions_market.go, exp/ticker/internal/main.go, exp/ticker/internal/tickerdb/main.go, exp/ticker/internal/tickerdb/queries_market.go, exp/ticker/internal/tickerdb/queries_market_test.go
This PR aims to add the following fields to the aggregated market data:
```
- open
- low
- high
- open_7d
- low_7d
- high_7d
```
It also changes some of the output field names to avoid the verbosity of the `_price` word, so `close_price` now becomes `close`, for instance.
=> exp/ticker: new market data fields

.gitignore, exp/clients/horizon/client.go, exp/clients/horizon/main.go, exp/clients/horizon/main_test.go, exp/clients/horizon/mocks.go
This PR add support for allowing users to submit transaction objects and not only transaction envelopes as XDR strings.
Closes #1043
=> exp/clients/horizon: submit tx object

exp/clients/horizon/client.go, exp/clients/horizon/main.go, exp/clients/horizon/mocks.go, exp/txnbuild/cmd/txnbuild_examples/main.go
This small PR adds a small helper method, `Fund()`, which funds the provided address from friendbot. This saves users (and us) from having to cut and paste the friendbot usage code in tests and examples.
Closes #1117.
=> horizonclient: Fund() method from friendbot

exp/ticker/cmd/serve.go, exp/ticker/docker/conf/nginx.conf, exp/ticker/docker/conf/supervisord.conf, exp/ticker/docker/setup
This PR:
- Closes #1163 
It aims to:
- Integrate the GraphQL server in the docker container setup, by adding a service that is monitored by Supervisor and forwarding the GraphQL queries from Nginx directly to the Go service.
=> exp/ticker: GraphQL server Docker integration

exp/ticker/internal/tickerdb/queries_market.go, exp/ticker/internal/tickerdb/queries_market_test.go
This PR aims to:
- Optimize the market aggregation query used to generate the Ticker's `market.json` file.
- Fix the wrong signal on the `price_change_xx` attributes, which was computed using `oldest_price - newest_price` instead of `newest_price - oldest_price`.
=> exp/ticker: optimize global market aggregation query

build/manage_offer.go, build/manage_offer_test.go, build/transaction.go, build/transaction_test.go, exp/clients/horizon/main_test.go, exp/txnbuild/cmd/txnbuild_examples/main.go, exp/txnbuild/create_passive_offer.go, exp/txnbuild/manage_offer.go, exp/txnbuild/transaction.go, exp/txnbuild/transaction_test.go, protocols/horizon/operations/main.go, protocols/stellarcore/tx_response.go, services/horizon/internal/actions_operation_test.go, services/horizon/internal/codes/main.go, services/horizon/internal/docs/reference/resources/account.md, services/horizon/internal/docs/reference/resources/effect.md, services/horizon/internal/docs/reference/resources/operation.md, services/horizon/internal/ingest/asset_stat.go, services/horizon/internal/ingest/asset_stat_test.go, services/horizon/internal/ingest/ingestion_test.go, services/horizon/internal/ingest/participants/main.go, services/horizon/internal/ingest/session.go, services/horizon/internal/resourceadapter/operations.go, services/horizon/internal/txsub/submitter.go, xdr/Stellar-ledger-entries.x, xdr/Stellar-ledger.x, xdr/Stellar-transaction.x, xdr/ledger_key.go, xdr/xdr_generated.go
This PR updates XDR files to be up to date with stellar-core v11. Changes affecting this repository:
* Operation type names changes:
* `manage_offer` -> `manage_sell_offer`,
* `create_passive_offer` -> `create_passive_sell_offer`,
* New `manage_buy_offer` operation.
* Offer IDs are now of `int64` type.
For backward compatibility, `manage_offer` and `create_passive_offer` type names have not been changed in Horizon. This will be a breaking change in Horizon 0.18.0.
Builders for `manage_buy_offer` operation has **not** been added in this PR (new issue: https://github.com/stellar/go/issues/1165).
=> Protocol v11 XDR changes

services/horizon/internal/db2/core/main.go, services/horizon/internal/db2/core/main_test.go, services/horizon/internal/db2/core/order_book_summary_test.go, services/horizon/internal/db2/core/price_level.go, services/horizon/internal/resourceadapter/order_book_summary.go
It's possible that sum of ask/bid offers at a given price level in the order book summary exceeds `INT64_MAX` as issuers can send `INT64_MAX` of the asset to each trust line. In such cases, Horizon was logging errors like:
```
select failed: sql: Scan error on column index 3, name \"amount\": converting driver.Value type []uint8 (\"10700325238000000000\") to a int64: value out of range
```
To support this, `PriceLevel.Amount` field type was changed from `int64` to `string`.
=> Support amounts that exceed int64 max in order book

clients/horizon/client.go, clients/horizon/main.go
as part of the work to release the new client. We are adding depracated tags to the current horizon client package and methods.
closes #1175
=> clients/horizon: add deprecated tags

services/horizon/cmd/root.go, services/horizon/internal/config.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/main_test.go, services/horizon/internal/ingest/session.go, services/horizon/internal/ingest/system_test.go, services/horizon/internal/init.go
fixes #194, and also relates to #183 but DOES NOT fix that issue
you can now override the default cursor name used by horizon
to ingest new ledgers from stellar-core database.
default value is "HORIZON" for backwards compatibility
we have been using this for scaling horizon horizontally (accidental pun i swear :) ) - using multiple horizons to ingest from a single core instance, some used for "read" operations such as SSE requests and some for "write" i.e. submitting transactions.
=> set stellar-core ingestion cursor name

tools/horizon-cmp/internal/response.go, tools/horizon-cmp/main.go, tools/horizon-verify/main.go
Adds a simple command to compare responses of two horizon servers. Can be used to check differences between the latest stable version and release candidate.
EDIT: forgot about "Work in Progress" option in GH, can't change the status once PR is added.
TODO:
=> Add horizon-cmp command

build/README.md, build/account_merge.go, build/allow_trust.go, build/bump_sequence.go, build/change_trust.go, build/create_account.go, build/inflation.go, build/main.go, build/manage_data.go, build/manage_offer.go, build/payment.go, build/set_options.go, build/transaction.go, clients/horizon/README.md, clients/horizon/main.go
This PR add deprecated tags to the `build` package. 
It also adds readme files to the `build` and `clients/horizon` packages with  a notice that these packages are deprecated. 
This is to be merged after `txnbuild` is moved from the `exp` folder
=> build: add deprecated tags

clients/horizonclient/main.go, docs/reference/examples.md, docs/reference/readme.md, txnbuild/transaction.go
This PR adds minimal developer docs for `horizonclient` and `txnbuild`, the components of the new Go SDK.
This does enough to close #863, although more examples (at least payment) on these pages in due course would be good.
=> horizonclient, txnbuild: dev docs

clients/horizonclient/CHANGELOG.md, clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go, clients/horizonclient/root_test.go
- Added `Root()` method
- Added `sendRequestURL` method
- Included tests for new endpoint
This PR closes #1200
=> clients/horizonclient: support root endpoint

support/scripts/build_release_artifacts/main.go
Fixes the situation where a tagged semVer release leads to the build system producing junk binary releases, when there is nothing to build. Closes #1208.
See #1208.
Build script exits with a log message if there is nothing to build.
This was tested locally with hardcoded variable names.
=> support/scripts/build_release_artifacts: don't build binaries based solely on semver

README.md, clients/README.md, clients/horizon/main.go, clients/horizonclient/README.md, txnbuild/README.md
This PR updates various READMEs relevant to the new Go SDK, to
* point at correct docs
* remove out of date info
* make deprecation of old SDK more obvious
=> horizonclient/txnbuild README fixes

clients/horizonclient/CHANGELOG.md, clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go, clients/horizonclient/mocks.go
This PR updates the Fund method that is used to fund new accounts on testnet.
It now uses the internal http client which allows us to set the app headers.
Also it returns TransactionSuccess struct instead of a http response.
Closes #1201
=> horizonclient: update Fund method

CHANGELOG.md, txnbuild/CHANGELOG.md
This is a small PR to fix up the root CHANGELOG to point to all the project CHANGELOGs.
I tried to roughly order the list by importance. If you think it should be different, please comment.
=> root repo changelog links to sub-projects

services/keystore/spec.md
We need an endpoint to update the encrypted private key atomically when users forget their
passwords.
=> keystore: add update-keys endpoints to spec

clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go
This PR adds more comments indicating required and optional fields in the exported structs.
Closes #1206
=> horizonclient: add more documentation

clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go
This PR sets the default HTTP client if non is provided. 
It closes #1182.
=> horizonclient: Set default HTTP client

clients/horizonclient/client.go, clients/horizonclient/version.go
This PR adds a version file `version.go` to the `horizonclient` package which is used to track the released versions. 
We decided to go this route because we don't release binaries for this package so we can't leverage `app.Version` from the `support/app` package which depends on the version tag being populated during the build process.
Note that this file should be updated for every release.
Closes #1227
=> horizonclient: add version

.github/pull_request_template.md
Clean up some typos, and point to an example docs folder in the go repo
rather than just the external docs hosted on our site.
=> Make PR template a bit more helpful.

exp/services/keystore/cmd/keystored/dev.go, exp/services/keystore/cmd/keystored/main.go, exp/services/keystore/service.go, support/env/env.go
This is the skeleton of the keystored. It doesn't do anything.
This PR introduces the lightweight package env to deal with environment
variables.
Next I'm going add `keystored migrate` command to handle migration.
=> keystore/cmd: implement basic keystored

clients/horizonclient/CHANGELOG.md, clients/horizonclient/client.go, clients/horizonclient/effect_request.go, clients/horizonclient/effect_request_test.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go, clients/horizonclient/mocks.go, clients/horizonclient/version.go, protocols/horizon/effects/main.go, protocols/horizon/main.go, txnbuild/CHANGELOG.md
Merge features added to these two libraries back to master.
Unfortunately the diff is misleading, because I accidentally merged a few extra master commits into the branch while trying to pick up the multisig change, which had been merged to master by accident.
I'm not sure why it is showing changes which are already on both master and the branch. For example the top level CHANGELOG is identical between both, but shows up as a change.
=> horizonclient v1.1.0 & txnbuild v1.1.0

.gitignore, exp/services/keystore/cmd/keystored/main.go, exp/services/keystore/tls/localhost.conf, exp/services/keystore/tls/regen.sh
This PR adds tls config to the keystore server. It copies the regen script and the localhost config from Horizon. Of course, it updates the config file so that it points to the right port.
After istalling keystored, one can do `keystored -tls-cert=path_to_cert
-tls-key=path_to_key serve` to start keystored. I will add a README as the next step.
=> keystore/cmd: add tls config to keystore

exp/services/keystore/cmd/keystored/README.md
This README file adds the instructions to start keystored with TLS
properly.
=> keystore: add a README file

exp/services/keystore/cmd/keystored/README.md, exp/services/keystore/cmd/keystored/main.go, exp/services/keystore/migrations/2019-05-07.0.initial-migrations.sql
This PR introduces `keystored migrate up/down` command to handle
migrations. It also defines an initial migration for the `encrypted_keys`
table.
=> keystore: add migrate command to handle migrations

exp/ticker/internal/tickerdb/queries_market.go, exp/ticker/internal/tickerdb/queries_market_test.go
This PR closes #1218. It aims to provide more accurate market data by making the 24h OHLC stats fall back to the 7-day close value on `markets.json`.
Updated the markets db query and added some tests to make sure the system is behaving accordingly.
Database query tests require a lot of preparations steps – skipping to the end of the test functions might be a good idea to get a better understanding of what's actually being tested :)
=> exp/ticker: ensure 24h OHLC values fall back to 7d close value on markets.json

exp/ticker/docs/API.md, exp/ticker/internal/actions_asset.go, exp/ticker/internal/actions_market.go, exp/ticker/internal/main.go, exp/ticker/internal/utils/main.go
This PR closes #1219. It aims to provide human-readable date/times through `markets.json` and `assets.json`. The GraphQL interfaces already provide dates in the RFC 3339 format. 
- Update data structs and Market and Asset data generators to use new time format.
- Update API documentation 🎉 to add the new fields and formats.
The `generated_at` field is still provided as a UNIX Timestamp for legacy reasons, but a new field called `generated_at_rfc3339` is also added to both `markets.json` and  `assets.json`. 
N/A
=> exp/ticker: provide times in RFC 3339 format

exp/ticker/internal/actions_trade.go, exp/ticker/internal/scraper/main.go, exp/ticker/internal/scraper/trade_scraper.go, exp/ticker/internal/scraper/trade_scraper_test.go
This PR fixes an issue through which trades ingested via streaming were not being pre-processed.
With this fix, trade pairs are normalized (in the same way we do for the trade backfill process), and native assets receive an `XLM` code.
=> exp/ticker: fix process of ingesting trades through streaming

exp/ticker/cmd/clean.go, exp/ticker/internal/tickerdb/queries_trade.go, exp/ticker/internal/tickerdb/queries_trade_test.go
If you're making a doc PR or something tiny where the below is irrelevant, just delete this
template and use a short description.
otherwise).
This PR closes #1086. It creates a script to clean up old database entries, since the Ticker APIs provide 7-day volume data at most.
- Created a query on tickerdb to delete old db entries
- Created a CLI command that uses that …
=> exp/ticker: Create script to delete old trade data

exp/ticker/internal/tickerdb/queries_asset_test.go
This PR fixes #1205 – an issue that occurs sporadically during CI tests.
Since we're rounding times when performing comparisons (as dbs don't store times in the same precision level as the Go language itself), there would be some cases in which the time difference was lower than the precision level we're comparing. In those cases, rounding would make times look equal, and tests with `NotEqual` assertion would consequently fail.
To fix this, we're changing `NotEqual` tests with `Before` and `After` comparisons (without rounding), which should be more accurate.
=> exp/ticker: fix db tests that would sporadically break due to rounding issues

txnbuild/CHANGELOG.md, txnbuild/change_trust.go, txnbuild/change_trust_test.go
This PR adds the maximum trustline limit to a change trust operation when no limit is set. 
Closes #1265
=> txnbuild: add max limit to change trust

txnbuild/CHANGELOG.md, txnbuild/change_trust_test.go, txnbuild/signers_test.go, txnbuild/simple_account.go, txnbuild/transaction.go, txnbuild/transaction_test.go
This PR adds a `SimpleAccount` struct that implements the `Account` interface. 
The `Account` interface is also updated with a `GetSequenceNumber` method.
`NewSimpleAccount` is a factory method for creating `SimpleAccount` it replaces `makeTestAccount` in all the tests. 
This PR closes #1266
=> txnbuild: SimpleAccount implementation

clients/horizonclient/internal.go, clients/horizonclient/main.go
This PR makes the new Horizon client goroutine compatible. It (un)locks around access to the `ServerTimeMap`; concurrent access to this shared resource resulted in an error documented in #1254 . Accordingly, this PR closes that issue.
=> clients/horizonclient: support goroutines

txnbuild/CHANGELOG.md, txnbuild/example_test.go, txnbuild/manage_buy_offer.go, txnbuild/transaction_test.go
This PR adds support for building `ManageBuyOffer` operations. 
Closes #1165
=> txnbuild: add support for ManageBuyOffer

clients/horizonclient/asset_request_test.go, clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go
This is the first set of PRs to add methods to get the previous and next pages of a response from horizon. 
This PR implements this method for the assets page. Other pages will be implemented as listed in #985
=> horizonclient: assets next and prev methods

services/friendbot/friendbot.cfg, services/friendbot/init_friendbot.go, services/friendbot/internal/account.go, services/friendbot/internal/friendbot.go, services/friendbot/internal/friendbot_handler.go, services/friendbot/internal/friendbot_test.go, services/friendbot/internal/minion.go, services/friendbot/loadtest/loadtest.go, services/friendbot/main.go
This PR adds Stellar channels to friendbot. The goal is to reduce bad sequence errors (`tx_bad_seq`) and general slowness during heavy load. The new `Minion` struct contains the Stellar channel, a sequence number, and associated methods that are moved from `Bot`. `Bot` contains a list of `Minions`. This also updates friendbot to use the new Go SDK. Closes #1156, #1249  .
=> services/friendbot: adds Stellar channels to friendbot

services/horizon/internal/docs/readme.md, services/horizon/internal/docs/reference/readme.md
If you're making a doc PR or something tiny where the below is irrelevant, just delete this
template and use a short description.
otherwise).
Updated the order of the SDK's for Horizon's docs to match the sidebar ordering on the docs site. I was tempted to remove them, but I figured it would be good for these links to exist in the go repository themselves — could be …
=> docs: Update order of SDK's to reflect docs sidebar.

clients/horizonclient/client.go, clients/horizonclient/effect_request_test.go, clients/horizonclient/ledger_request_test.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go
This is part of a set of PRs to add methods to get the previous and next pages of a response from horizon.
This PR implements these methods for the ledgers and effects page. 
Other pages will be implemented as listed in #985
=> horizonclient: next and prev methods

clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go, clients/horizonclient/offer_request_test.go, clients/horizonclient/trade_request_test.go
This is part of a set of PRs to add methods to get the previous and next pages of a response from horizon.
This PR implements these methods for the trades and offers page.
Other pages will be implemented as listed in #985.
=> horizonclient: trades and offers next/prev methods

clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go, clients/horizonclient/operation_request_test.go, clients/horizonclient/transaction_request_test.go
This is last set of PRs to add methods to get the previous and next pages of a response from horizon.
This PR implements these methods for transactions and operation pages.
Other pages will be implemented as listed in #985.
=> horizonclient: tx and ops prev/next methods

README.md
This PR aims to replace the monorepo's `README.md` build status badge (currently based on Travis CI's status report) with the one Circle CI provides.
=> docs: update README.md to use Circle CI status badge

clients/horizonclient/internal.go
This PR adds two small fixes to the storage of Horizon server times in the shared server time map.
1) It follows #1276 by locking when getting from the map.
2) It checks for an empty server date when setting in the map.
=> clients/horizonclient: fix server time storage

services/friendbot/internal/minion.go
This PR logs the TransactionResult XDR from Horizon, rather than the error code, to hopefully get more complete information than just `tx_failed`.
=> services/friendbot: improve horizon error logging

exp/ticker/internal/scraper/trade_scraper.go
This PR aims to fix a logic error in the trade db backfill logic, which previously only performed asset cleanup / checks on the last page of scraped trades.
=> exp/ticker: fix trade db backfill logic

exp/ticker/internal/scraper/asset_scraper.go
This PR updates the ticker's TOML scraper requests to use a specific user agent (`Stellar Ticker v1.0`). This has been done to:
- Allow servers to identify which requests are made by the ticker
- Bypass some filters created by asset issuers to prevent unknown bots from scraping their TOML data
=> exp/ticker: use a specific User Agent to identify ticker requests

support/historyarchive/archive.go
Allows to retreive history archives with https scheme (`stellar-archivist scan https://...`)
=> support/historyarchives - allow https scheme

services/horizon/CHANGELOG.md, services/horizon/internal/actions_trade_test.go, services/horizon/internal/db2/history/trade_aggregation.go, services/horizon/internal/resourceadapter/trade_aggregation.go
otherwise).
Sum of traded assets can exceed `INT64_MAX` in a single bucket. In this
commit destination types have been changed to `string` and are converted
to decimal amounts (divide by `10^7`) using `amount.IntStringToAmount`.
If you're making a doc PR or something tiny where the below is irrelevant, just delete this
template and use a short description.
Close #1268.
=> Fix "int64: value out of range" in trade aggregations

services/bridge/internal/handlers/main.go, services/bridge/internal/handlers/request_handler_admin.go, services/bridge/internal/handlers/request_handler_authorize.go, services/bridge/internal/handlers/request_handler_builder.go, services/bridge/internal/handlers/request_handler_create_keypair.go, services/bridge/internal/handlers/request_handler_payment.go, services/bridge/internal/handlers/request_handler_reprocess.go, services/bridge/internal/listener/payment_listener.go, services/bridge/internal/submitter/transaction_submitter.go, services/bridge/main.go, services/internal/bridge-compliance-shared/protocols/bridge/payment.go
This PR starts the process of swapping out the old sdk for the new one in the bridge server.
It focuses on replacing clients/horizon with clients/horizonclient.
We still need to replace the builder with txnbuild and implement some tests. The plan is to cover those in future PRs. 
This is part of the work required in #1251
=> services/bridge: use horizonclient

clients/horizon/error.go, services/horizon/internal/assertions_test.go, services/horizon/internal/render/problem/problem.go, services/horizon/internal/render/problem/problem_test.go, support/render/problem/problem.go, txnbuild/cmd/demo/operations/demo.go
This PR makes the service host configurable by introducing `RegisterHost`
so we don't always have `https://www.stellar.org/horizon-errors` prepended
in the problem type. This makes the package more generic so it can be used
by the keystore.
This PR also removes an unused function `Inflate` in horizon internal as
well as removes an unused field `Instance` in `P`.
Finally, it makes `Render` more readable by removing `renderErr`.
=> support/render/problem: make service host configurable

support/render/hal/handler.go, support/render/hal/handler_test.go, support/render/hal/io.go
This PR adds a helper function so that we can conveniently decode the
request body into the function param.
This is not related to Horizon at all, meaning that nothing will be affected in Horizon by this change. This new function `PostHandler` will be used by keystore solely at this moment.
=> support/render/hal: add a helper function for http post

clients/horizonclient/client.go, clients/horizonclient/operation_request.go, protocols/horizon/operations/main.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/web.go
@poliha I changed the way `UnmarshalOperation` function works to make it compatible with versions pre 0.18.0 and 0.18.x. It's now using `type_i` to determine operation type.
=> Horizon 0.18.0 CHANGELOG

services/compliance/internal/handlers/request_handler_send.go, services/internal/bridge-compliance-shared/main.go
This PR is part of the work required in #1251. It replaces the old builder with the new txnbuild within the compliance server. I am basing this PR off the bridge-new-sdk branch because most of the changes so far are in that branch. Will merge that with master once it has the changes of this PR.
=> services/compliance: use txnbuild

services/horizon/CHANGELOG.md, services/horizon/cmd/root.go, services/horizon/internal/config.go
otherwise).
This PR fixes #915 to be backward compatible. When `max-db-connections` is set, new DB params are ignored.
=> services/horizon: Revert max-db-connections config param

.circleci/config.yml
This PR fixes #1348 by preventing the release from being deleted when Circle CI uploads its artifacts.
=> ci: ensure Circle CI does not delete release when uploading artifacts

services/bridge/internal/handlers/request_handler_authorize.go, services/bridge/internal/handlers/request_handler_builder.go, services/bridge/internal/handlers/request_handler_payment.go, services/bridge/internal/submitter/transaction_submitter.go, services/compliance/internal/handlers/request_handler_send.go, services/internal/bridge-compliance-shared/main.go, services/internal/bridge-compliance-shared/protocols/asset.go, services/internal/bridge-compliance-shared/protocols/bridge/builder.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_account_merge.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_allow_trust.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_change_trust.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_create_account.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_inflation.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_manage_data.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_manage_offer.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_path_payment.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_payment.go, services/internal/bridge-compliance-shared/protocols/bridge/builder_set_options.go
This PR adds the changes made in #1327 and #1340  to master. Bridge and compliance servers now use the new sdk packages, `horizonclient` and `txnbuild`. Once this is merged, we will work on features that will go into the new release for bridge and compliance.
closes #1250 
closes #1251 
closes #1252 
closes #1062
=> Use new sdk for bridge and compliance. 

exp/services/keystore/spec.md
We decided to encrypt all users' public keys in case the keystore gets
hacked. As a result, each user will only have one row in the database of
the keystore, and all keys belonging to a user will be stored in the same blob.
This means the `/update-key` endpoint will be implemented on the client
side such that it will call `/load-keys` endpoint, decrypt the blob,
modified the blob, re-encrypt the blob, and finally call `/store-keys`
endpoint. Similar logic applies to `/remove-key` endpoint.
=> exp/keystore: update spec

exp/services/keystore/keys.go
Our wallet sdk is written in typescript, and typrscript prefers to use
camelcase encoding. This PR makes the keystore render the request
correctly.
=> exp/keystore: use camelcase for json encoding

exp/services/keystore/api.go, exp/services/keystore/api_test.go, exp/services/keystore/keys.go, exp/services/keystore/problems.go, support/render/hal/handler.go, support/render/hal/handler_test.go
We have updated the keystore spec so that we will conform REST
convention. We are going to be using HTTP GET/PUT/DELETE to manipulate
our encrypted keys blob.
This PR renames the `PostHandler` in `support/hal/render` to
`ReqBodyHandler` because it can actually be used by all kinds of http
methods as long as we don't put the param in the URL.
This PR adds a `keysHTTPMethodHandler` so that we know which function to
call based on the method we receive. Because of this, we introduced a new problem `probMethodNotAllowed` in this PR in the case of getting a method we don't support.
=> exp/keystore: use http put request to store keys

services/ticker/cmd/generate.go, services/ticker/internal/actions_market.go
We need to invert the prices for some markets in order to ensure they correctly show up on CoinMarketCap. 
This is a temporary solution, since we've already reached out to their support to change how they compute SDEX data, but we haven't heard back from them so far.
This needs to be done because the previous ticker implemented the price for a trade pair as:
https://github.com/stellar/ticker-py/blob/master/ticker.py#L151
And we currently do as:
https://github.com/stellar/go/blob/master/services/ticker/internal/actions_trade.go#L146
=> services/ticker: add logic and command to invert prices for CMC markets

exp/services/keystore/api.go, exp/services/keystore/api_test.go, exp/services/keystore/keys.go, exp/services/keystore/keys_test.go
This PR adds HTTP `GET` method to `/keys`. This PR also renames `storeKeys` to `putKeys` so that it is consistent with the spec.
=> exp/keystore: add get keys endpoint

exp/ingest/pipeline/main.go, exp/ingest/pipeline/pipeline.go, exp/ingest/pipeline/pipeline_test.go, exp/tools/accounts-for-signer/filters.go, exp/tools/accounts-for-signer/main.go
otherwise).
This PR passes `ctx` with cancel to processors and return errors channel in `pipeline.ProcessState`. This is done to gracefully exit all go routines in case of errors and when processing is done.
This has been tested using "Accounts for Signer" pipeline.
Close #1342.
It seems that even though go routines exit properly (`runtime.NumGoroutine()` returns 1: …
=> exp/ingest/pipeline: Pass ctx with cancel to processors and return errors channel

.circleci/config.yml, protocols/horizon/main.go, protocols/horizon/operations/main.go, services/horizon/CHANGELOG.md, services/horizon/internal/resourceadapter/transaction.go, services/horizon/internal/web.go
In #833 we introduced Horizon deprecation tags that act like a reminder to remove deprecated fields in a given version. It seems that deprecations are not the only thing you want to be reminded about. I propose to change this tag to:
```
Action needed before: $CIRCLE_TAG
```
and the following line explains what need to be done before releasing a given version.
=> "Action needed" tag

exp/services/keystore/api.go, exp/services/keystore/api_test.go, exp/services/keystore/keys.go, exp/services/keystore/keys_test.go, exp/services/keystore/spec.md, support/render/hal/handler.go
This PR adds HTTP `DELETE` method to `/keys`. This PR updates the spec so that we return a default response `{message: "ok"}` once the operation is successful.
=> exp/keystore: add delete keys endpoint

exp/services/keystore/keys.go, exp/services/keystore/keys_test.go, support/render/hal/handler.go, support/render/hal/handler_test.go
This PR relaxes the two-return-value constraint in the function type check. We will return a default response if there's no return value. If there's one return value, we will return something based on whether that single return value is an error or not.
The motivation behind this improvement is that in keystore we have a HTTP DELETE endpoint, where we only return a default response if it's successful.
=> support/render/hal: relax the return value constraint

.circleci/config.yml
This PR ensures CircleCI checks for deprecations before publishing artifacts to tagged releases.
=> ci: ensure check_deprecations runs on tagged releases

services/ticker/docker/setup
The ticker Docker config originally pulled the ticker binary from a separate repo. This PR aims to change this config, so Docker pulls the ticker bin directly from `stellar/go` releases. 
After merging, we should create a `ticker-v1.0.0` release targeting the squashed commit of this PR.
=> services/ticker: ensure docker pulls ticker binary from stellar/go releases

exp/services/keystore/api.go, exp/services/keystore/api_test.go
Without this PR, the GET keys endpoint will result in an internal error when there is no entry existing in the database for the associated user.
=> exp/keystore: return Not_Found error when no entry

exp/services/keystore/cmd/keystored/README.md, exp/services/keystore/cmd/keystored/dev.go, exp/services/keystore/cmd/keystored/main.go, exp/services/keystore/service.go
This PR adds `KEYSTORE_LISTENER_PORT` environment variable so that one can
start keystored at a preferred port number.
=> exp/keystore: make port number configurable

exp/services/keystore/api.go, exp/services/keystore/api_test.go, exp/services/keystore/cmd/keystored/README.md, exp/services/keystore/cmd/keystored/dev.go, exp/services/keystore/cmd/keystored/main.go, exp/services/keystore/keys_test.go, exp/services/keystore/service.go
This PR introduces one environment variable `KEYSTORE_AUTHFORWARDING_URL` in order to relay client requests for the purpose of authentication. This PR also introduces a command line flag `auth` to turn the auth forwarding off for easy testing.
We simply grab all headers in the request and add a `X-FORWARDED-FOR` field and send it to the designated URL with HTTP GET and expect a plaintext response. If everything goes well, we use the response as the userid and pass it along with the context.
=> exp/keystore: add auth forwarding mechanism with HTTP GET

support/historyarchive/mirror.go, tools/stellar-archivist/CHANGELOG.md
Use an error variable scoped to the goroutine function instead of the
outer function. Otherwise there can be a race condition where different
goroutines overwrite each others error variable.
This led to errors such as:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4629e5]
goroutine 15 [running]:
errors.(*errorString).Error(0x0, 0xc4205df648, 0x4c5d67)
/usr/lib/go-1.10/src/errors/errors.go:19 +0x5
github.com/stellar/go/support/historyarchive.noteError(0xbd7140, 0x0, 0x1)
/home/enode/go/src/github.com/stellar/go/support/historyarchive/util.go:122 +0x3e
github.com/stellar/go/support/historyarchive.Mirror.func2(0xc42008e0c0, 0xc42025f950, 0xc4200282a8, 0xc4200282a0, 0xc420168360, 0xc42025f9e0, …
=> Fix race condition in `mirror` command

exp/services/keystore/api.go, exp/services/keystore/api_test.go, exp/services/keystore/spec.md
This PR defines a minimal json struct that keystore clients have to
return in order to authenticate their users. This is to avoid all the
edge cases when handling `text/plain` responses.
=> exp/keystore: define a json format for the auth endpoint

exp/services/keystore/api.go
This PR adds a `/health` endpoint so we know whether keystore is up or
not.
=> exp/keystore: add a health endpoint

.github/pull_request_template.md
I realized that you can create expandable sections in GitHub markdown and use comments. I think it's a good idea to keep PR Checklist hidden (developer still see it while editing PR description).
The example below:
-----
<details>
otherwise).
</details>
[TODO]
[TODO]
[TODO]
[TODO]
[TODO]
=> Expandable PR Checklist

.circleci/config.yml
This PR fixes an issue that occurs with tests run through CI that depend on `go-sqlite3`, such as:
https://circleci.com/gh/stellar/go/2116
https://circleci.com/gh/stellar/go/2120
The fix is done by running `go install` for the go-sqlite3 package prior to running tests, as suggested on https://github.com/mattn/go-sqlite3/issues/224.
=> ci: fix issue with go-sqlite3 build

services/friendbot/internal/friendbot.go, services/friendbot/internal/friendbot_test.go
This PR fixes an issue in the friendbot `Pay` function. Previously, the minion index and update were not being locked. As a result, tests that attempted concurrent access detected a race condition, as seen [here](https://circleci.com/gh/stellar/go/1985)
=> services/friendbot: fix race condition in Bot.Pay

exp/ingest/io/memory_state_reader.go, exp/tools/accounts-for-signer/filters.go, exp/tools/accounts-for-signer/main.go
[CAP-0020](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0020.md) makes some improvements in buckets structure. We should update `MemoryStateReader` code to support v11 buckets.
Close #1389.
* Added a new code that supports new `BucketEntry` types: `INITENTRY` and `METAENTRY`. Additionally removed `removed` map as it's redundant (`seen` map is enough).
* Added new `MemoryStateReader.error` function to remove code duplication (instantiating empty `xdr.LedgerEntry` object).
No tests - update #1365 after merging this PR.
otherwise).
needed with deprecations, added …
=> exp/ingest: Add support for protocol v11 buckets

exp/services/keystore/cmd/keystored/README.md, exp/services/keystore/cmd/keystored/main.go, exp/services/keystore/service.go
We haven't really started to log anything in a log file. With this PR,
dev-ops can easily create a file and use the flag `-log-file=LOG_FILE_PATH`
to start logging.
=> exp/keystore: add log-file and log-level flags

exp/ingest/adapters/history_archive_adapter_test.go, exp/ingest/io/main.go, exp/ingest/io/memory_state_reader.go, exp/ingest/pipeline/buffered_state_read_write_closer.go, exp/ingest/pipeline/main.go, exp/ingest/pipeline/multi_write_closer.go, exp/ingest/pipeline/pipeline_test.go, exp/tools/accounts-for-signer/filters.go, tools/archive-reader/archive_reader.go
In preparation for `ingest.Session` object implementation we change object type processed by `StateProcessor` from `LedgerEntry` to `LedgerEntryChange`.
`ingest.Session` responsibility is to connect and synchronize history and ledger backend pipelines. The main session types are:
* Checkpoint only session: in this session we build a state from a checkpoint history bucket and apply changes using aggregated ledger entry changes available in history archives (so called ["low resolution custom view"](https://github.com/stellar/stellar-core/blob/master/docs/integration.md#low-resolution-custom-view)).
* Live session: in this session we build a state from a checkpoint history bucket and apply changes using stellar-core real-time metadata, available for each transaction (so called ["high …
=> Process LedgerEntryChange instead of LedgerEntry

services/ticker/internal/tickerdb/queries_market_test.go, services/ticker/internal/tickerdb/queries_orderbook_test.go, services/ticker/internal/tickerdb/queries_trade_test.go
This PR fixes #1403 by using a lower precision when comparing times on database tests.
This shouldn't impact the effectiveness/accuracy of the tests, since none of them rely on time differences in the order of milliseconds – they're mostly in the order of seconds, minutes, or even days.
=> services/ticker: use a different strategy for comparing times on db tests

services/horizon/internal/ingest/ingestion.go, services/horizon/internal/ingest/main.go, services/horizon/internal/ingest/system_test.go, support/db/session.go
<details>
otherwise).
</details>
```Ingestion.ClearAll()``` truncates all tables instead of deleting by range.
The goal is make ```db clear``` command operate as intended. Reference: https://github.com/stellar/go/issues/1371
- added missing ```TableName```s const declarations
- modified ```Ingestion.ClearAll()``` to truncate all tables
- …
=> services/horizon - db clear command truncates all tables

services/horizon/CHANGELOG.md, services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/db2/history/ledger.go
In protocol version 11 that implemented [CAP-0005](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0005.md) the number of operations is used as the indicator of ledger capacity. `/fee_stats` endpoint is incorrectly using transaction count for ledger capacity stats.
Rewrite a query that calculates ledger capacity usage to correctly report fee stats.
The query that calculates ledger capacity in the last 5 ledgers has been rewritten. Because we don't have access to number of failed operations in `history_ledgers` table (#1385) we first run subquery that returns number of operations for ledgers in question along with `max_tx_set_size` for each ledger and then calculate the capacity in the parent query.
* The query can be simplified when #1385 is implemented.
otherwise). …
=> services/horizon: Fix ledger capacity usage in fee stats

exp/services/keystore/spec.md
This PRs updates the spec so that it shows all errors it returns. The
client will be able to act based on the error returned.
=> exp/keystore: document returned errors

exp/ingest/adapters/history_archive_adapter.go, exp/ingest/io/memory_state_reader.go, exp/ingest/io/memory_state_reader_test.go, support/historyarchive/archive.go, support/historyarchive/mocks.go, support/historyarchive/xdrstream.go, xdr/account_id.go
Adds simple tests for `exp/ingest/io.MemoryStateReader`.
=> exp/ingest: io.MemoryStateReader tests

exp/ingest/io/memory_state_reader_test.go
Merging two conflicting PRs (#1365, #1370) caused tests to fail. We should probably require rebasing before merge to prevent similar situations in the future.
=> Fix memory state reader tests

services/keystore/api.go
While the keystore works locally, the hosted keystore is not being able to receive the right response. It looks like the response is compressed with gzip somewhere in our cluster. We might also have to disable the compression in the transport layer if this fix is not sufficient.
=> keystore: avoid the response body being compressed

txnbuild/transaction.go
Instead of building the transaction envelope at the start of Sign we can do this at the end of build. This allows an unsigned envelope to be returned for signing offline/elsewhere
Fix for: https://github.com/stellar/go/issues/956
This is my first ever PR on Github so hopefully I got this bit right :)
=> txnbuild: Initialise transaction envelope in build

clients/horizonclient/main_test.go, support/http/httptest/client_expectation.go
This PR updates the tests for FetchTimebounds from sending requests to pubnet horizon server to mocking the horizon server responses. Prior to this, we were unable to mock this response because we could not return headers with the response. 
This PR also updates the `support/httptest` package to allow users mock responses with headers.
Closes #1322 
Closes #1323
=> horizonclient: fix FetchTimebounds test

txnbuild/CHANGELOG.md, txnbuild/transaction.go, txnbuild/transaction_test.go
This PR adds two new methods to the transaction struct
- `TxEnvelope`: This returns a the `xdr.TransactionEnvelope` struct for the transaction. Closes #1415 
- `HashHex`: This returns the transaction hash as a hex string
=> txnbuild: add new methods to transaction

txnbuild/CHANGELOG.md, txnbuild/allow_trust.go, txnbuild/transaction_test.go
This PR removes the need for an asset issuer to be specified when building an `AllowTrust` operation. 
This operation only needs the asset code to be specified.
Closes #1330
=> txnbuild: remove asset issuer requirement for allow_trust

txnbuild/CHANGELOG.md, txnbuild/example_test.go, txnbuild/examplehorizonclient/examplehorizonclient.go, txnbuild/transaction.go, txnbuild/transaction_test.go
This PR does the following
- Adds a warning that `Transaction.SetDefaultFee` is deprecated and will be removed.
- Adds an example showing how to set `Transaction.BaseFee` by querying horizon for fee stats.
- Add an unexported method `Transaction.setTransactionFee` for setting the transaction fee.
- Validates accountID before building a transaction
closes #1221
=> txnbuild: add deprecate warning to default fee

services/bridge/CHANGELOG.md, services/bridge/internal/handlers/request_handler_payment.go
This PR fixes the bug where `PathPayment` operations gets overwritten by `Payment` operations.
Unblocks #1453
=> services/bridge: path payment bug fix

services/keystore/cmd/keystored/README.md
keystored actually uses five different environment variables, not four.
This PR makes it more clear.
=> keystore: update keystored README

txnbuild/CHANGELOG.md, txnbuild/transaction.go, txnbuild/transaction_test.go
This PR adds support for signing transactions with signatures other than `ed25519` keys.
- Pre-authorized Transaction signatures were already supported so a test was added for it.
- `Transaction.SignHashX` method added to support Hash(x) signatures.
- Changelog updated.
Closes #955
=> txnbuild: support alternate signatures

clients/federation/client.go, clients/federation/client_test.go, clients/federation/main.go, clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go
This PR swaps out the deprecated `horizon` package with the new `horizonclient` package. This is a fairly straightforward swap and no changes has been made to the federation client features.
=> clients/federation: use horizonclient

support/render/httpjson/encoding.go, support/render/httpjson/encoding_test.go
This PR makes the intention of the manual type more clear. It renames `Object` to `RawObject` as well as adds examples of the usage.
=>  support/render/httpjson: add comments and tests for encoding 

.circleci/config.yml
This PR checks if the `./dist` directory is present before attempting to publish for binaries. 
This is needed for packages that do not release binaries such as `horizonclient` and `txnbuild`.
Fixes #1304
=> CircleCI: check for binaries before publishing release artifacts 

services/ticker/internal/scraper/asset_scraper.go, services/ticker/internal/scraper/orderbook_scraper.go, services/ticker/internal/scraper/trade_scraper.go, services/ticker/internal/utils/main.go
This PR adds a retry logic to the ticker when scraping `assets`, `trades` and `orderbooks`, so it can overcome Horizon's rate limiting.
=> services/ticker: ensure ticker ingestion scripts can overcome Horizon's rate limiting

services/horizon/cmd/root.go, services/horizon/internal/config.go
<details>
* [x ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
* [x ] This PR's title starts with name of package that is most changed in the PR, ex.
* [x ] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
[semver](https://semver.org/), or if it's mainly a patch change. The PR is targeted at the …
=> services/horizon: history archive url + accounts for signer feature flag

services/keystore/api.go, services/keystore/spec.md
This PR addresses the issue [here](https://github.com/stellar/go/pull/1498#discussion_r302265272) in this thread. Caching headers may cause trouble or confuses for the auth server.
=> keystore: forward only Authorization and Cookie headers for auth

exp/ingest/live_session.go, exp/ingest/main.go, exp/ingest/single_ledger_session.go, exp/tools/horizon-demo/main.go, exp/tools/horizon-demo/pipelines.go, exp/tools/horizon-demo/reporter.go
<details>
* [ x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
* [x ] This PR's title starts with name of package that is most changed in the PR, ex.
</details>
A Reporter is used by a session to report …
=> exp/ingest: Add Reporter interface for sessions

services/horizon/internal/actions_operation.go, services/horizon/internal/actions_operation_test.go
<details>
* [x ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
* [ x] This PR's title starts with name of package that is most changed in the PR, ex.
* [x ] This PR adds tests for the most critical parts of the new functionality or fixes.
release …
=> services/horizon/internal: Fix slice bounds out of range error in operations action

services/horizon/CHANGELOG.md, services/horizon/cmd/root.go, support/historyarchive/archive.go
In https://github.com/stellar/go/pull/1490#pullrequestreview-259451959 I suggested to set default values of `history-archive-urls` to SDF archives. The problem with this is that Horizon may be connected to another network (ex. testnet) and this will cause checksum errors. It's probably better to remove defaults because "error creating history archive: URL is empty" is more clear.
=> Remove default values for history archives

services/horizon/internal/docs/admin.md
See [release](https://github.com/stellar/go/blob/master/services/horizon/CHANGELOG.md#v0180) requiring 9.5.
=> Postgres 9.5 is now required

support/render/httpjson/encoding.go, support/render/httpjson/encoding_test.go
This PR adds a OptString type to differentiate the cases where a json
key is not presented and a json key's value is an empty string.
This is useful when it comes to patching a resource's attribute. We
can't patch a resource attribute to an empty string if it's not even
provided in the request.
=> support/render/httpjson: add OptString type

.circleci/config.yml
This PR ensures our CI tests / builds run on Debian Stretch, so that we can continue installing Postgres 9.6 and MariaDB 10.1 normally through `apt-get`.
=> ci: Ensure tests / builds run on Debian "stretch"

services/friendbot/init_friendbot.go, services/friendbot/internal/friendbot_handler.go, services/friendbot/internal/minion.go
fixes #1511 
<details>
otherwise).
</details>
Funding an account with friendbot used to return an HTTP 500. This PR addresses that and returns a HTTP 400
Fix error code returned with an informative error message
Register the friendbot account exists error so we treat it as a bad request HTTP 400 
None that i can think of
N/A
=> [services/friendbot] Return HTTP 400 when the account submitted to friendbot already exists

services/ticker/CHANGELOG.md, services/ticker/cmd/generate.go, services/ticker/docker/setup, services/ticker/internal/actions_market.go
This PR:
- updates the `CHANGELOG.md` in preparation for the release of v1.1.0 of the ticker. 
- removes some functions/logic that aimed to temporarily solve an issue with CMC (see #1364), which has already been addressed by them.
=> services/ticker: prepare for v1.1.0 release

services/horizon/internal/db2/history/key_value.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go
<details>
otherwise).
</details>
Track version number of ingestion system to simplify migrations.
This commit adds `CurrentVersion` const that defines the current version of the ingestion system that is stored after pipeline processing is finished. This is done to simplify migrations/reingestion when new version of the system is …
=> services/horizon/expingest: Store ingestion system version

support/render/httpjson/encoding.go
The previous comment wasn't wrong, but it could be achieved by just using a pointer to the type. What's special about this type is that it is able to differentiate JSON null value and key being absence.
=> support/render/httpjson: update comments for OptString

staticcheck.sh
When installing `staticcheck` using `go get honnef.co/go/tools/cmd/staticcheck` the master branch is pulled in by default. This branch is unstable and it will be better to use the stable release branch.
This workaround is suggested by the docs: https://staticcheck.io/docs/
>If you use Go modules, you can simply run go get honnef.co/go/tools/cmd/staticcheck to obtain the latest released version. If you're still using a GOPATH-based workflow, then the above command will instead fetch the master branch. It is suggested that you explicitly check out the latest release branch instead, which is currently 2019.2. One way of doing so would be as follows:
```bash
cd $GOPATH/src/honnef.co/go/tools/cmd/staticcheck
git checkout 2019.2
go get
go install
```
=> use staticcheck-2019.2

services/ticker/CHANGELOG.md, services/ticker/internal/actions_asset.go, services/ticker/internal/main.go, services/ticker/internal/tickerdb/helpers.go, services/ticker/internal/tickerdb/main.go, services/ticker/internal/tickerdb/queries_asset.go
This PR closes #1541 
It aims to add a nested `issuer_detail` field for each asset on the `/assets.json` endpoint. 
**Note:** I've opted to add a separate `"issuer_detail"` field instead of simply using `issuer` to ensure backwards compatibility, since an `"issuer"` field was already being used to provide the issuer's public key.
=> services/ticker: add nested issuer_detail field on assets.json

staticcheck.sh, tools/horizon-cmp/internal/response.go, tools/horizon-cmp/main.go
This PR adds streaming endpoint tests and improves the code. Also, cherry-picked 9af9d5dae373bcfd14017e69de3e3354829ae98e to fix `staticcheck` errors.
Close #1184.
=> tools/horizon-cmp: Add streaming endpoints tests

txnbuild/memo.go, txnbuild/memo_test.go, txnbuild/operation_test.go, txnbuild/set_options.go, txnbuild/transaction_test.go
This PR adds unit tests for the FromXDR methods implemented by txnbuild operations.
It covers tests for the following operations
- SetOptions
- ChangeTrust
- AllowTrust
- AccountMerge
- Inflation
- ManageData
- BumpSequence
The test case for checking if the same xdr is returned if we build and encode will be added when #1448 is fixed. 
Closes #1329
=> txnbuild: more unit tests for FromXDR methods

clients/horizonclient/CHANGELOG.md, clients/horizonclient/internal.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go, clients/horizonclient/operation_request.go, clients/horizonclient/operation_request_test.go
otherwise).
</details>
Allow users to get transaction information when querying an operation endpoint.
Closes #1521 
Add the `join` parameter to operations and payments request. This allows horizon server to return transaction information along with an operation response
- Added `join` param type
- Updated OperationRequest struct
- Added tests to check that the URL is …
=> horizonclient: add support for join param.

exp/ingest/live_session.go, exp/ingest/main.go, exp/ingest/single_ledger_session.go, exp/ingest/standard_session.go, exp/support/pipeline/main.go, exp/support/pipeline/pipeline.go, exp/support/pipeline/pipeline_test.go, exp/tools/horizon-demo/pipelines.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/app.go, services/horizon/internal/db2/history/key_value.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/q_signers_mock.go, services/horizon/internal/db2/schema/bindata.go, services/horizon/internal/db2/schema/migrations/19_offers.sql, services/horizon/internal/expingest/load_orderbook_graph_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/context_filter.go, services/horizon/internal/expingest/processors/main.go
<details>
otherwise).
</details>
This PR changes new ingestion system in Horizon to allow distributed ingestion. This means that ingestion will be running on all Horizon nodes but only one, random node will be a leader that updates a database (at the same time all of the nodes will update in-memory order book graph).
Close #1529.
In …
=> services/horizon: Distributed ingestion

exp/ingest/io/postgres_temp_set.go, services/horizon/internal/expingest/main.go
<details>
otherwise).
</details>
This PR updates Horizon to use `PostgresTempSet` created in #1539 instead of `MemoryTempSet` to lower memory requirements.
Close #1565.
=> services/horizon: Use PostgresTempSet in Horizon

exp/orderbook/graph.go
<details>
otherwise).
</details>
Exit `consumeOffers()` early if we have no asset units to sell.
Improve performance of `consumeOffers()`
It's not necessary to iterate through all the offers if we've already consumed enough offers to sell all units of our current asset.
N / A
N / A
=> exp/orderbook: improvement to consumeOffers

services/horizon/internal/docs/reference/resources/transaction.md
Let's make it clear that we are returning an RFC3339 date-time and not ISO8601. There are some deviations between both formats, specifically, RFC3339 expects the years to be in the current era.
See https://github.com/stellar/go/issues/1381 for more info.
=> Update timebounds format from ISO8601 to RFC3339.

services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go
This commit fixes a scenario when a state is cleared because of the ingestion system upgrade. In the pipelines post-processing hook we have an extra check to ensure that the ledger sequence of the last locally processed ledger is exactly +1 the the ledger sequence of the last processed ledger in a database. This fails for init state if there are some ledgers ingested because `LastLedgerExpIngest` was not reset during clearing state.
=> services/horizon: Fix upgrade when database not empty

txnbuild/transaction.go, txnbuild/transaction_test.go
This PR uses the correct length of bytes for the manage data value. 
As per the protocol
>The value must be 64 bytes long. It contains a 48 byte cryptographic-quality random string encoded using base64 (for a total of 64 bytes after encoding).
Closes #1562
=> txnbuild: Fix manage data value in sep10 challenge

txnbuild/CHANGELOG.md, txnbuild/transaction.go, txnbuild/transaction_test.go
otherwise).
</details>
This PR prevents multiple calls to `Transaction.Build` from modifying the number of operations
Fix #1448 
- Prevent signed transactions from being rebuilt
- `Transaction.xdrTransaction` is reset at the start of a build process
- Tests were added for Build and FromXDR
- Changelog has been updated
- When the `Build`  method is called multiple …
=> txnbuild: prevent multiple build calls from incrementing operations

strkey/main.go, strkey/main_test.go
This PR adds 2 methods to the `strkey` package for validating public and secret keys.
- `strkey.IsValidEd25519PublicKey`
- `strkey.IsValidEd25519SecretSeed`
Note: there are similar methods in `support/config` we should probably retire those?
Closes #1447
=> Strkey: validation methods

txnbuild/CHANGELOG.md, txnbuild/transaction.go, txnbuild/transaction_test.go
This PR adds a function  `VerifyChallengeTx` to the txnbuild package that verifies a SEP 10 challenge transaction according to the spec. 
This complements the `BuildChallengeTx` function which builds a challenge transaction.
This PR closes #1530
=> txnbuild: function to verify sep10 challenge tx

txnbuild/transaction.go, txnbuild/transaction_test.go
This PR add validation for sequence number and the value of the manage_data operation in a SEP10 challenge transaction
It checks that
- Sequence number for the transaction is 0
- The base64 encoded nonce is 64 bytes
- The decoded nonce is 48 bytes long
Relevant tests have been added.
=> txnbuild: sep10 verify sequence and manage_data value

clients/horizonclient/CHANGELOG.md, clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/mocks.go, clients/horizonclient/trade_aggregation_request_test.go
This PR adds helper methods for getting prev and next trade aggregations from a current trade aggregations response.
The following methods have been added to the Client 
- `Client.NextTradeAggregationsPage`
- `Client.PrevTradeAggregationsPage`
=> horizonclient: add methods for next and prev trade aggregations

.circleci/config.yml
CircleCI workflow fails when it tries to publish binaries for releases that dont have any, like the horizonclient package. 
This PR adjusts the check for binaries by checking if the `dist` folder is empty. 
Previously, it check if this folder existed. This worked for a while but seems to be failing now: https://circleci.com/gh/stellar/go/5385
=> CircleCI: fix publish artifacts

services/keystore/api.go
This PR adds the header Access-Control-Allow-Origin: * to all responses by
keystore.
=> keystore: add Access-Control-Allow-Origin header

services/friendbot/friendbot.cfg, services/friendbot/init_friendbot.go, services/friendbot/internal/minion.go, services/friendbot/main.go
This Pull Request enables the base fee used by Friendbot's transactions to be configured through `friendbot.cfg`.
=> Enable Friendbot's base fee to be configured via friendbot.cfg

support/historyarchive/archive.go, support/historyarchive/fs_archive.go, support/historyarchive/http_archive.go, support/historyarchive/log.go, support/historyarchive/mock_archive.go, support/historyarchive/s3_archive.go, tools/stellar-archivist/main.go
otherwise).
</details>
This PR adds a new `log` subcommand to stellar-archivist. It includes a very little bit of refactoring of the backends to support a new size query of files in an archive. The output of `log` looks like this:
~~~
$ stellar-archivist log file:///usr/local/stellar-local-archive --last 100000
Log of checkpoint files in range: [0x01810f3f, 0x0182963f] …
=> tools/stellar-archivist: add "log" subcommand to list archive checkpoints.

protocols/horizon/effects/main.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions_operation_test.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/resourceadapter/effects.go
<details>
* [ X] This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
</details>
Change data type for field `NewSeq` in `SequenceBumped` effect from `int64` to `string.` Fixes #1363.
Update horizon's `JSON `response for field `new_seq` in `NewSequenceBumped` effect to return a `string` instead of …
=> services/horizon: Change NewSeq attribute in SequenceBumped to be a string.

exp/orderbook/dfs.go, exp/orderbook/edges.go, exp/orderbook/graph.go, exp/orderbook/graph_test.go, price/main.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions_fixed_path.go, services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/main_generated.go, services/horizon/internal/paths/main.go, services/horizon/internal/resourceadapter/path.go, services/horizon/internal/simplepath/finder.go, services/horizon/internal/simplepath/finder_test.go, services/horizon/internal/simplepath/inmemory.go, services/horizon/internal/simplepath/search.go, services/horizon/internal/web.go
<details>
otherwise).
</details>
Add path finding endpoint where source and destination are fixed
Fixes https://github.com/stellar/go/issues/1489
Path payments don't handle the case where you have a fixed amount of the source asset. For example "Get me the most EUR possible for my 10 USD". This case is becoming increasingly important for …
=> exp/services/horizon: Add path finding endpoint where source and destination are fixed

.circleci/config.yml, .travis.yml, Dockerfile, README.md, clients/horizonclient/CHANGELOG.md, clients/horizonclient/README.md, govet.sh, services/bridge/CHANGELOG.md, services/compliance/CHANGELOG.md, services/federation/CHANGELOG.md, services/horizon/CHANGELOG.md, services/horizon/internal/docs/admin.md, services/horizon/internal/docs/developing.md, services/keystore/CHANGELOG.md, services/ticker/CHANGELOG.md, tools/stellar-archivist/CHANGELOG.md, tools/stellar-hd-wallet/CHANGELOG.md, tools/stellar-sign/CHANGELOG.md, tools/stellar-vanity-gen/CHANGELOG.md, txnbuild/CHANGELOG.md, txnbuild/README.md
<details>
otherwise).
</details>
Drop support for Go 1.10, which makes the official supported versions:
- Go 1.11
- Go 1.12
The code in this repository is used in critical systems and we should encourage its use with versions of Go that receive security updates.
The officially supported versions of Go are only the last two releases. …
=> all: drop support for go 1.10

services/friendbot/internal/friendbot_handler.go
This PR fixes Error 1 of issue #1512
Friendbot was returning a 500 on requests that provided non-url-escaped values for the `addr` parameter, as see on the logs:
**Request**
`time=“2019-07-30T08:19:47.697Z” level=info msg=“finished request” bytes=444 duration=“53.107µs” method=GET path=“/?addr=%s” pid=15931 req=frontend-friendbot-001a/HlNPxBapp5-053399 status=500 subsys=http`
**Log**
`time=“2019-07-30T08:19:47.697Z” level=error msg=“invalid URL escape \”%s\”” pid=15931 stack=unknown`
This PR fixes that issue by ensuring we return a Bad Request (400) status whenever we're unable to correctly parse the provided request parameters.
=> services/friendbot: ensure Friendbot does not return a 500 due to unescaped params

protocols/horizon/effects/main.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions_operation_test.go
Reverting the change which fixes #1363 -- we'll introduce this breaking change in Horizon 0.22
=> Change NewSeq back to int64 in horizon response.

services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/db2/core/trustline.go, services/horizon/internal/db2/core/trustline_test.go
<details>
otherwise).
</details>
If you send a path finding request where there is no account for the
source account address, the endpoint will respond with a 404.
In this case we should instead respond with an empty list of paths.
=> services/horizon/internal: Fix path finding bug with empty source account

protocols/horizon/effects/main.go, protocols/horizon/main.go, protocols/horizon/operations/main.go, services/horizon/CHANGELOG.md, services/horizon/internal/expingest/main.go
* Updates CHANGELOG with old deprecated, postponed fields.
* Adds `Action Needed` tag for deprecated fields.
* Changes `expingest.CurrentVersion` to `2` (no need to increment it more than once in a single release).
=> Pre-release updates to Horizon 0.20.0

.circleci/config.yml, support/scripts/run_tests
<details>
otherwise).
</details>
Occasionally CircleCI jobs triggered by PRs fail because of OOM errors (see https://circleci.com/gh/stellar/go/6268#usage-queue/containers/0 for an example). The cause and fix for this issue is outlined here:
https://github.com/golang/go/issues/26186#issuecomment-435544512
=> circleci: Fix CircleCI OOM errors

Gopkg.lock, Gopkg.toml
<details>
otherwise).
</details>
Remove the `source` parameter for the `github.com/asaskevich/govalidator` dependency in the dep Gopkg.* files.
This change is being made to simplify the `go.mod` file that will be generated when we move to Modules (#1634).
The `source` parameter for the `github.com/asaskevich/govalidator` dependency is …
=> all: remove dep source for govalidator

services/horizon/internal/expingest/reporter.go
Change `sequence` field to `ledger` to be consistent with the rest of `expingest` package and make the logs easier to read.
=> services/horizon: Make ledger sequence field name consistent

services/horizon/CHANGELOG.md, services/horizon/cmd/root.go, services/horizon/internal/config.go, services/horizon/internal/expingest/main.go, services/horizon/internal/init.go
<details>
otherwise).
</details>
Horizon 0.20.0 shipped with [`PostgresTempSet`](https://godoc.org/github.com/stellar/go/exp/ingest/io#PostgresTempSet) used for a temporary objects storage in state ingestion in the new ingestion system. Unfortunately it's extremely slow in highly used DBs. This commit adds a new option that allows admins …
=> services/horizon: ingest-state-reader-temp-set option

services/horizon/internal/middleware.go
Add `Referer` header to Horizon logs to better understand who is using it.
=> services/horizon: Add referer to Horizon logs

services/horizon/internal/app.go, services/horizon/internal/app_test.go, services/horizon/internal/init.go
Change `PANIC` entries level to `FATAL` to not print stack trace that can be misleading for users (see: https://github.com/stellar/go/issues/1643#issue-484760269).
=> services/horizon: Change "panic" log level entries to "fatal"

exp/ingest/io/single_ledger_state_reader.go, support/historyarchive/xdrstream.go
After deploying `release-horizon-v0.20.1` branch to staging server it stopped processing ledger entries after around 300k entries with an error:
```
Read wrong number of bytes from XDR
```
returned from `XdrStream.ReadOne`. First, I changed the code to return `err` values before proceeding to the next checks. This reveal the real error:
```
stream error: stream ID 311; PROTOCOL_ERROR
```
I couldn't find any information online about this but I suspect this is happening because of the idle timeout. In `SingleLedgerStateReader` we preload entries for a better performance (smaller round-trip time) when getting temporary data from `TempSet`. When entries are being processed the connection stays idle. The second fix (actually: quickfix) was decreasing `preloadedEntries` to `20000` what makes a …
=> support/historyarchive: Fix error reporting

services/horizon/CHANGELOG.md, services/horizon/internal/actions_effects.go
<details>
otherwise).
</details>
This commit fixes the code to compile regexp in `actions_effects.go` only once. I noticed a correlation between CPU spikes and number of requests to effects endpoints and probably this is the reason.
=> services/horizon: Fix regexp in actions_effects

.circleci/config.yml
<details>
otherwise).
</details>
Use go 1.12 to build artifacts
The optimization introduced in https://github.com/stellar/go/pull/1543 requires go 1.12. We should build the horizon artifacts using go 1.12 so that the next releases can benefit from the optimization.
=> circleci: Use go 1.12 to build artifacts

Gopkg.lock, Gopkg.toml
<details>
otherwise).
packages.
</details>
Update `ginkgo` and `gomega` to newer versions.
The transition to Modules (#1634) requires some modules to be updated because Modules requires the same minor versions to be used across test dependencies of our dependencies. There are …
=> all: update ginkgo and gomega for modules transition

services/horizon/CHANGELOG.md
Update Horizon v0.20.0 CHANGELOG informing experimental ingestion testers to skip to 0.20.1.
See: #1673.
=> Horizon 0.20.0 CHANGELOG update

services/horizon/CHANGELOG.md, services/horizon/cmd/db.go, services/horizon/cmd/root.go, services/horizon/docker/Dockerfile, services/horizon/docker/docker-compose.yml, services/horizon/docker/horizon-entry.sh, services/horizon/internal/config.go, services/horizon/internal/db2/schema/main.go
<details>
otherwise).
packages.
</details>
Add flag to apply migrations before running horizon. Fixes https://github.com/stellar/go/issues/1668
If there are pending migrations, previously you needed to run `horizon db migrate up` before running `horizon`. Those two steps can be …
=> all: Add flag to apply migrations before running horizon

Gopkg.lock, Gopkg.toml
<details>
otherwise).
packages.
</details>
Update `gopkg.in/yaml.v2` for transition to Modules (#1634).
From: `gopkg.in/yaml.v2@7ad95dd0798a`
To: `gopkg.in/yaml.v2@v2.2.2`
Diff: https://github.com/go-yaml/yaml/compare/7ad95dd0798a...v2.2.2 (96 commits)
To make the transition to …
=> all: update gopkg.in/yaml.v2 7ad95dd0798a => v2.2.2

.circleci/config.yml, services/horizon/internal/docs/developing.md, services/horizon/internal/docs/notes_for_developers.md, support/scripts/run_tests
* Sends coverage reports to codecov.io
* Removes `run_tests` script as it looks like `go test` ignores `vendors` directory when Go Modules are used.
Close #1686.
=> Send coverage reports to codecov.io

exp/orderbook/dfs.go, exp/orderbook/graph.go, exp/orderbook/graph_test.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/paths/main.go, services/horizon/internal/simplepath/finder.go, services/horizon/internal/simplepath/inmemory.go, services/horizon/internal/web.go
<details>
otherwise).
</details>
Add destination account parameter to path finding endpoint.
This PR addresses the feedback on the `paths/strict-send` endpoint from:
https://github.com/stellar/go/issues/1489#issuecomment-524524803
* update graph interface
* update action
* add tests
* update change log
=> services/horizon/internal: Add destination account parameter to path finding endpoint

go.mod, services/horizon/internal/app.go, support/http/main.go
<details>
otherwise).
packages.
</details>
Use the default `net/http` transport which supports http2, instead of using `x/net/http2`.
At some point early on we adopted using `x/net/http2` as the http2 transport in our servers. It was probably necessary at the time, I'm not …
=> all: use net/http instead of x/net/http2

support/historyarchive/mirror.go, support/historyarchive/range.go, tools/stellar-archivist/CHANGELOG.md, tools/stellar-archivist/README.md, tools/stellar-archivist/main.go, tools/stellar-archivist/main_test.go
<details>
otherwise).
</details>
Add a `--recent` mode for `mirror`. This saves the user from guessing the appropriate `N` for `--last N`, or a range for `--low` / `--high`. Simply call `stellar-archivist mirror --recent src dst` and it will copy the range from dst's most recent HAS to src's. Running this in a loop should be sufficient …
=> Archivist: Mirror --recent mode

support/historyarchive/archive_test.go, support/historyarchive/s3_archive.go, support/historyarchive/scan.go, tools/stellar-archivist/main.go
<details>
otherwise).
</details>
Fixes to the S3 backend for stellar-archivist. The S3 APIs changed semantics since I last tested it.
=> archivist: fix recent semantic drift in S3 SDK

txnbuild/account_merge.go, txnbuild/account_merge_test.go, txnbuild/allow_trust.go, txnbuild/allow_trust_test.go, txnbuild/asset.go, txnbuild/bump_sequence.go, txnbuild/bump_sequence_test.go, txnbuild/change_trust.go, txnbuild/change_trust_test.go, txnbuild/create_account.go, txnbuild/create_account_test.go, txnbuild/create_passive_offer.go, txnbuild/create_passive_offer_test.go, txnbuild/helpers.go, txnbuild/helpers_test.go, txnbuild/inflation.go, txnbuild/manage_buy_offer.go, txnbuild/manage_buy_offer_test.go, txnbuild/manage_data.go, txnbuild/manage_data_test.go, txnbuild/manage_offer.go, txnbuild/manage_offer_test.go, txnbuild/operation.go, txnbuild/path_payment.go, txnbuild/path_payment_test.go, txnbuild/payment.go, txnbuild/payment_test.go, txnbuild/set_options.go, txnbuild/transaction.go, txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
This PR adds validation logic to the txnbuilds operation structs so that invalid fields can be returned with the appropriate error message.
- Validate required fields in the txnbuild's operation structs
- Return clear error messages …
=> txnbuild: validate operation structs

exp/ingest/live_session.go, exp/ingest/main.go, exp/ingest/single_ledger_session.go, exp/ingest/standard_session.go, services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
This PR fixes a bug in `expingest.System` session resume code. Check the existing code for `resumeFromLedger` method:
```go
func (s *System) resumeFromLedger(lastIngestedLedger uint32) {
retryOnError(time.Second, func() error {
err := …
```
=> horizon/expingest: Fix ingest session resume

services/bridge/internal/config/main.go, services/bridge/internal/config/main_test.go, services/compliance/internal/config/main.go, services/compliance/internal/config/main_test.go
<details>
otherwise).
packages.
release branch if it's not a patch change.~
</details>
Remove MySQL support from config parsing in Bridge and Compliance services.
Clean up code that is no longer supported. We announced that MySQL was no longer supported for Bridge and Compliance a few months ago in commits 9d0a49bee411 …
=> services/{bridge,compliance}/internal/config: remove mysql support

.codecov.yml
<details>
otherwise).
packages.
release branch if it's not a patch change.~
</details>
Disable codecov PR comments and replace with status check.
Codecov was added recently by @bartekn and is a good tool for giving us visibility into what code coverage new and existing code we write has, but it's default PR comments are …
=> codecov: disable pr comments, enable status check

services/horizon/CHANGELOG.md, services/horizon/internal/db2/history/account_signers_batch_insert_builder.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/mock_account_signers_batch_insert_builder.go, services/horizon/internal/db2/history/mock_offers_batch_insert_builder.go, services/horizon/internal/db2/history/offers_batch_insert_builder.go, services/horizon/internal/db2/history/q_offers_mock.go, services/horizon/internal/db2/history/q_signers_mock.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/accounts_signer_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/main.go, services/horizon/internal/expingest/processors/offers_processor_test.go, support/db/batch_insert_builder.go, support/db/batch_insert_builder_test.go, support/db/main.go
<details>
otherwise).
packages.
</details>
During state ingestion we add a large number of ledger entries to a database. To make the process faster the code in this commit adds them in batches instead of one by one. Public network state ingestion that's using batch inserts takes …
=> services/horizon/expingest: Batch insert ledger entries during state ingestion

go.list, go.mod, go.sum
Update a dependency to pull in new ordering assertions (like `assert.Less` and `assert.Greater`)
=> go.mod: update github.com/stretchr/testify to v1.4.0 for ordering assertions.

support/historyarchive/archive_test.go, support/historyarchive/mirror.go, support/historyarchive/range.go, support/historyarchive/range_test.go, support/historyarchive/scan.go
<details>
otherwise).
packages.
</details>
Fix a couple bugs with ranges in stellar-archivist. This just makes it behave more like it's documented to / how users would expect:
- Treat the range values as inclusive rather than excluding the high endpoint.
- Don't clobber the …
=> archivist: range fixes

services/horizon/internal/expingest/verify.go
After deploying the latest commit from 0.21.0 release branch to staging environment it looks like a delay between a checkpoint ledger and root HAS update sometimes is longer than 20 seconds. This commit is increasing a wait time to 40 seconds.
=> services/horizon: Increase HAS publish delay

CONTRIBUTING.md, README.md
<details>
otherwise).
packages.
</details>
Move Go coding conventions from the README.md into the CONTRIBUTING.md file which discusses other requirements for code contributed.
I'm in the process of adding a developing document that includes finer details about how to do things …
=> docs: move coding conventions into contributing.md

CONTRIBUTING.md, DEVELOPING.md, README.md
<details>
otherwise).
packages.
</details>
Add a `DEVELOPING.md` capturing some basic instructions on how to develop in this repository, including instructions on how to use Modules to add, update and remove dependencies.
To make a clear path for folks to add, update and remove …
=> docs: add a developing.md

exp/ingest/io/ledger_transaction.go, exp/ingest/io/ledger_transaction_test.go, services/horizon/CHANGELOG.md, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
This commit fixes a bug in `exp/ingest/io.Changes.AccountSignersChanged()` helper method. This method returns `true` when tx meta indicates that signers on account have changed. It was returning invalid `false` when master weight is `0` …
=> exp/ingest/io: Fix AccountSignersChanged for account merge

services/horizon/internal/actions_path_test.go, services/horizon/internal/middleware.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
This commit moves checking if the state was found to be invalid to `requiresExperimentalIngestion` middleware that is run before all new experimental ingestion endpoints.
Since #1691 Horizon checks if the state is correct every 64 …
=> services/horizon: Check state in all exp endpoints

exp/ingest/verify/main.go, services/horizon/internal/action_offers_expingest_test.go, services/horizon/internal/actions/offer_test.go, services/horizon/internal/db2/history/account_signers.go, services/horizon/internal/db2/history/account_signers_test.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/offers.go, services/horizon/internal/db2/history/offers_test.go, services/horizon/internal/db2/history/q_offers_mock.go, services/horizon/internal/db2/history/q_signers_mock.go, services/horizon/internal/expingest/load_orderbook_graph_test.go, services/horizon/internal/expingest/pipeline_hooks_test.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/accounts_signer_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/offers_processor_test.go
<details>
otherwise).
packages.
</details>
This commit checks rows affected value for CUD operations in `DatabaseProcessor`. This is done to ensure state correctness in Horizon database.
Close #1723.
When inserting/updating/deleting rows in state connected tables we ignore rows …
=> services/horizon: Check rows affected in DatabaseProcessor

.circleci/config.yml
<details>
otherwise).
packages.
</details>
Change the Debian version that the Go 1.13 checks, tests, and publishing occurs with to Debian Stretch, instead of Debian Buster.
When we added tests for Go 1.13 the only image available on DockerHub was based on Debian Stretch. We …
=> all: use stretch instead of buster for all builds

services/ticker/internal/tickerdb/queries_asset_test.go
<details>
otherwise).
packages.
</details>
Change the `TestInsertOrUpdateAsset` test to `Round` instead of `Truncate` time values that are being compared with time that was stored in Postgres.
Intermittently the `TestInsertOrUpdateAsset` test will fail because a time value …
=> services/ticker: fix flakey spec comparing time with postgres stored time

govet.sh
<details>
otherwise).
packages.
</details>
Run the go vet tool `shadow` for all Go versions, specifically making it possible to run it with Go 1.13.
We should have consistent checks and tests across the versions of Go we have running. When I initially added the Go 1.13 block …
=> all: run go vet shadow for all go versions

gofmt.sh
<details>
otherwise).
packages.
</details>
Remove the ls xargs dance from the gofmt and just get gofmt to run it's checks over everything of what's different.
I was looking at copying this script to another repository and noticed that the dance with excluding certain folders …
=> all: simplify gofmt script

services/ticker/docs/API.md
<details>
otherwise).
packages.
</details>
Add docs about which asset in a trade pair is the base, and which is the counter.
To make it less confusing for new comers looking at the API to determine what the values returned by the API mean in the context of a trade pair.
It was …
=> services/ticker: add docs about which asset in a pair is the base

amount/main.go, exp/orderbook/graph.go, exp/orderbook/graph_test.go, services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/offer_test.go, services/horizon/internal/actions/orderbook.go, services/horizon/internal/actions/orderbook_test.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/app.go, services/horizon/internal/handler.go, services/horizon/internal/ledger/ledger_source.go, services/horizon/internal/stream_handler_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
Implement `/order_book` implement using the in memory order book graph populated by the experimental ingestion system.
Fixes https://github.com/stellar/go/issues/1705
The current `/order_book` endpoint queries Stellar Core's database to …
=> services/horizon/internal/actions: Add /order_book ingestion endpoint

exp/tools/dump-ledger-state/diff_test.sh
`sort` is using 90% of available memory by default. We reduced it to 1GB what was working fine however it seems that `sort` process gets killed by CI container system. This commit reduces it even more to 500MB.
=> Reduce memory requirements of ingest_state_diff job

govet.sh
<details>
otherwise).
packages.
</details>
Change the `govet.sh` script so that it runs the shadows check the same way for Go 1.12 and Go 1.13 builds, wrapping the shadow analyzer in a tiny main function that catches and ignores the `unsafeptr` flag that gets passed through by …
=> all: attempt to make method for shadow checks consistent with 1.12 and 1.13

support/render/problem/problem.go, support/render/problem/problem_test.go
This PR adds a function type used to report unknown errors to a
destination you like. It can be a log, sentry, or other services as long
as the function you used matches ReportFunc signature.
This PR is a part of https://github.com/stellar/go/pull/1795. We decided
to split it up since we don't want to introduce too many dependencies in
the mono-repo.
=> support/render/problem: add ReportFunc to report unknown errors

.circleci/config.yml, exp/tools/dump-ledger-state/Dockerfile, exp/tools/dump-ledger-state/docker-entrypoint.sh, exp/tools/dump-ledger-state/run_test.sh
<details>
otherwise).
packages.
</details>
* Add a docker image which encapsulates everything needed to run `exp/tools/dump-ledger-state/run_test.sh` along with alerting via slack in case the script fails.
* Publish the docker image upon every merge to master.
Fixes …
=> exp/tools/dump-ledger-state: Publish docker image to run state diff checks

support/render/problem/problem_test.go
This PR resets the global variable reportFn after the unit test to
prevent it from affecting other tests.
=> support/render/problem: reset reportFn after test

exp/tools/dump-ledger-state/docker-entrypoint.sh
The script should only send alerts if run_test.sh fails.
=> exp/tools/dump-ledger-state: Fix typo in ledger state diff script

exp/tools/dump-ledger-state/docker-entrypoint.sh
This reverts commit b5a8b22d9eb52db92bfb0ecb291813094e96c731.
The original code was correct.
=> Revert "Fix typo in ledger state diff script"

txnbuild/CHANGELOG.md, txnbuild/example_test.go, txnbuild/path_payment.go, txnbuild/path_payment_test.go
<details>
otherwise).
packages.
</details>
Fixes `PathPaymentStrictReceive`, so we can release `txnbuild` support for v12. Prior to this fix methods on this struct are not usable.
* Used an [alias definition](https://yourbasic.org/golang/type-alias/) to allow methods on …
=> txnbuild: support protocol 12

services/horizon/internal/action.go, services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/actions_account_test.go, services/horizon/internal/handler.go, services/horizon/internal/urlparams.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
Use the new action handling pattern on `/accounts`. This removes the tight coupling between the `signers` query parameter and the action. It will allow us to implement new functionalities like #442.
- Remove old action handling pattern …
=> services/horizon/internal/actions: Refactor accounts to use new actions system.

exp/orderbook/batch.go, exp/orderbook/graph.go, exp/orderbook/graph_test.go, exp/tools/horizon-demo/pipelines.go, services/horizon/CHANGELOG.md, services/horizon/internal/action_offers_expingest_test.go, services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/offer.go, services/horizon/internal/actions/offer_test.go, services/horizon/internal/actions/orderbook.go, services/horizon/internal/actions/orderbook_test.go, services/horizon/internal/actions/session.go, services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/context/context_key.go, services/horizon/internal/expingest/load_orderbook_graph_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/orderbook_processor_test.go, services/horizon/internal/handler.go, services/horizon/internal/middleware.go, services/horizon/internal/middleware_test.go, services/horizon/internal/paths/main.go, services/horizon/internal/simplepath/finder.go, services/horizon/internal/simplepath/finder_test.go, services/horizon/internal/simplepath/inmemory.go, services/horizon/internal/stream_handler_test.go, services/horizon/internal/web.go
Include a Latest-Ledger header with the sequence number of the last processed ledger by the
experimental ingestion system. Also, ensure the endpoint responses contains only data consistent
with the sequence number included in the header
<details>
otherwise).
packages.
</details> …
=> services/horizon/internal/actions: Add latest ingested ledger in experimental ingestion endpoints

services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/accounts_signer_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/main.go, services/horizon/internal/expingest/processors/offers_processor_test.go, services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
The ingestion pipelines are structured so that all processor nodes in the pipeline tree share the same transaction instance. Sibling processor nodes in the pipeline tree are executed concurrently which means that multiple goroutines end …
=> services/horizon/internal/expingest: Execute all ledger processors in one node

clients/horizonclient/client.go, clients/horizonclient/internal.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go, support/clock/clocktest/fixed.go, support/clock/clocktest/fixed_test.go, support/clock/main.go, support/clock/main_test.go
<details>
otherwise).
packages.
</details>
Add a mockable `Clock` type that by default uses real time (`time.Now()`) for the current time, but supports wrapping any other source of time.
Default clock:
```go
clock := clock.Clock{}
clock.Now()
```
Mockable with a fixed clock: …
=> support/clock,clients/horizonclient: add a mockable clock

services/horizon/internal/actions/asset.go, services/horizon/internal/actions/asset_test.go, services/horizon/internal/actions/helpers.go, services/horizon/internal/resourceadapter/asset_stat.go, services/horizon/internal/resourceadapter/asset_stat_test.go, services/horizon/internal/web.go, xdr/account_id.go, xdr/asset.go
<details>
otherwise).
packages.
</details>
The current `/assets` endpoint relies on the legacy ingestion system to populate the `asset_stats` table. In https://github.com/stellar/go/pull/1810 we added a new table, `exp_asset_stats`. `exp_asset_stats` contains asset stats …
=> services/horizon/internal/actions: Implement experimental ingestion asset stats endpoint

services/horizon/CHANGELOG.md, services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/db2/history/operation.go
<details>
otherwise).
packages.
</details>
When looking at the [Dashboard](https://dashboard.stellar.org/) I realized that when there are a lot of transactions with _normal_ fees and one tx with a much bigger fee the p99 can be interpolated to a huge number. See:
I checked the …
=> services/horizon: Use percentile_disc in fee stats query

services/horizon/internal/actions/account_test.go, services/horizon/internal/actions_account_test.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/app.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipeline_hooks_test.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/middleware.go, services/horizon/internal/middleware_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
Disable ingestion endpoints while state pipeline is still running
Fixes https://github.com/stellar/go/issues/1663
https://github.com/stellar/go/issues/1663
>When ingest version is upgraded (expingest.CurrentVersion++) Horizon will clear …
=> services/horizon/internal, services/horizon/internal/expingest: Ingestion readiness check

exp/orderbook/dfs.go, exp/orderbook/graph.go, exp/orderbook/graph_test.go, services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
There is a bug in `consumeOffersForBuyingAsset()` which manifests when `currentAssetAmount` is not high enough to purchase the selling asset. In such cases `consumeOffersForBuyingAsset()` should return -1, nil but because of the bug the …
=>  exp/orderbook: Fix bug in strict send path finding search

go.list, go.mod, go.sum, services/horizon/internal/actions/helpers.go, services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/offer.go, services/horizon/internal/actions/offer_test.go, services/horizon/internal/actions/query_params.go, services/horizon/internal/actions/query_params_test.go, services/horizon/internal/actions/validators.go, services/horizon/internal/actions/validators_test.go, xdr/account_id_test.go, xdr/asset.go, xdr/asset_test.go
Automate query params reading and validation. 
Define your struct, specifying the url schema tags and validations as defined in [schema](https://www.gorillatoolkit.org/pkg/schema) and [govalidator](https://github.com/asaskevich/govalidator).
Let's suppose you are working on an end-point that requires a  Stellar account, like `/accounts/{account_id}/offers`, the following struct will pull the required data from the query params and validate that it is a valid address.
```go
type AccountOffersQuery struct {
AccountID string `schema:"account_id" valid:"accountID"`
}
```
Use it in the context of an account like:
```go
func (handler GetAccountOffersHandler) GetResourcePage(r *http.Request) ([]hal.Pageable, error) {
ctx := r.Context()
qp := OffersQuery{}
qp := AccountOffersQuery{}
err := …
```
=> services/horizon/internal/actions: Query struct with gorilla/schema and govalidators.

build/main.go, clients/horizonclient/client.go, clients/horizonclient/main.go, clients/horizonclient/operation_request.go
This fixes lines with an unintended two-space prefix in code comments. The extra space prefix causes godoc to render those lines as a code block. For example, see [horizonclient#Client.StreamOperations](https://godoc.org/github.com/stellar/go/clients/horizonclient#Client.StreamOperations).
=> Remove unnecessary whitespace and fix typo in godoc comments

protocols/horizon/main.go, services/horizon/internal/db2/history/account_test.go, services/horizon/internal/db2/history/accounts.go, services/horizon/internal/db2/history/trust_lines.go, services/horizon/internal/db2/history/trust_lines_test.go, services/horizon/internal/resourceadapter/account_entry.go, services/horizon/internal/resourceadapter/account_entry_test.go, services/horizon/internal/resourceadapter/balance.go, services/horizon/internal/resourceadapter/balance_test.go, xdr/account_flags.go, xdr/account_flags_test.go, xdr/trust_line_flags.go, xdr/trust_line_flags_test.go
<details>
otherwise).
packages.
</details>
Add resource adapter for `history.AccountEntry`. This is paving the way for https://github.com/stellar/go/pull/1835
- Allow JSON serialization for `history.AccountEntry`
- Add a new resource adapter for `history.AccountEntry` and related …
=> Add resource adapter for history.AccountEntry

services/horizon/internal/middleware.go
This commit sets `referer` value to `undefined` if `Referer` HTTP header is empty. This is to help support logging in system that have problems parsing empty values.
=> services/horizon: Set  for empty referer

exp/tools/dump-ledger-state/docker-entrypoint.sh
<details>
otherwise).
packages.
</details>
`--retry-connrefused` will consider ECONNREFUSED as a transient error too for --retry
`-v` will output extra logs which are useful for debugging failures
=> exp/tools/dump-ledger-state: Add extra flags to LATEST_LEDGER curl request

services/horizon/CHANGELOG.md, services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/actions/helpers.go, services/horizon/internal/actions/query_params.go, services/horizon/internal/db2/history/account_data.go, services/horizon/internal/db2/history/account_data_test.go, services/horizon/internal/db2/history/account_signers.go, services/horizon/internal/db2/history/accounts.go, services/horizon/internal/db2/history/accounts_test.go, services/horizon/internal/db2/history/trust_lines.go, services/horizon/internal/db2/history/trust_lines_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
Extend the `/accounts` end-point to support finding all accounts who are trustees to an asset. 
The following request:
https://horizon-testnet.stellar.org/accounts?asset_type=credit_alphanum4&asset_code=USD&asset_issuer=GAXT72C4PLIRVD4DI5 …
=> services/horizon/internal/actions:  Find all accounts who are trustees to an asset.

services/horizon/CHANGELOG.md, services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/db2/history/accounts.go, services/horizon/internal/db2/history/accounts_test.go
<details>
otherwise).
packages.
</details>
Account for signers was using a partial representation of accounts since we didn't have all the necessary information in the database to build the full representation. Since #1819 we are now ingesting account data and can return all the …
=> services/horizon/internal/actions: Update payload for "Accounts For Signers" end-point.

services/horizon/internal/init.go, support/env/env.go, support/env/env_test.go
<details>
otherwise).
packages.
</details>
Add `env.Duration` that functions the same as the existing functions `env.Int` and `env.String` but parses the environment variable as a duration string, e.g. `5m30s`, and returns a `time.Duration`.
I'm writing some code that already …
=> support/env: add env.Duration

support/env/env_test.go
<details>
otherwise).
packages.
</details>
Use `t.Fatal` instead of `panic` in tests in `support/env`.
In #1877 I added a helper function `randomStr` which called `panic` in the event there was an error retrieving random data. A `panic` will terminate all tests running and …
=> support/env: use t.Fatal instead of panic in test

exp/ingest/io/ledger_reader.go, exp/ingest/io/ledger_transaction.go, exp/ingest/io/main.go, exp/ingest/io/mock_ledger_reader.go, exp/ingest/ledgerbackend/database_backend.go, exp/ingest/ledgerbackend/ledger_backend.go, exp/ingest/main.go, exp/ingest/pipeline/ledger_pipeline_test.go, exp/ingest/pipeline/main.go, exp/ingest/pipeline/wrappers.go, exp/ingest/processors/csv_printer.go, exp/ingest/processors/root_processor.go, services/horizon/internal/expingest/processors/accounts_data_processor_test.go, services/horizon/internal/expingest/processors/accounts_processor_test.go, services/horizon/internal/expingest/processors/accounts_signer_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/offers_processor_test.go, services/horizon/internal/expingest/processors/orderbook_processor.go, services/horizon/internal/expingest/processors/orderbook_processor_test.go, services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
This commits adds support for getting ledger upgrade changes from `exp/ingest/io.LedgerReader` and updates ledger processors in Horizon to process ledger upgrade meta.
Requirement for #1848.
Close #1470.
As described in …
=> exp/ingest: Process ledger upgrade meta

support/env/env_test.go
<details>
otherwise).
packages.
</details>
Rename the `randomStr` test helper that is used in the `support/env` package to `randomEnvName` and make it self contain the length and test name prefix logic.
I added the `randomStr` func in #1877 with the original intention I'd be …
=> support/env: make test helpers more specific and better named

support/env/env_test.go
<details>
otherwise).
packages.
release branch if it's not a patch change.~
</details>
Replace `time.Duration(330000000000)` with `5*time.Minute + 30*time.Second`.
I added the hardcoded value in a test in #1877. @howardtw pointed out it'd be easier to read if it used the `time.Duration` constants.
- Replace nanoseconds …
=> support/env: use readable presentation of time.Duration value in test

services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/actions/helpers.go, services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/offer.go, services/horizon/internal/actions/offer_test.go, services/horizon/internal/actions_root.go, services/horizon/internal/actions_root_test.go, services/horizon/internal/resourceadapter/root.go, services/horizon/internal/resourceadapter/root_test.go
<details>
otherwise).
packages.
</details>
Automate URI template generation using query struct and schema tag. Fixes #1884. This will also help us towards #1839
- Use query structs to generate a valid rfc6570 URI template
- Extend helper to read schema value from a given struct. …
=> services/horizon/internal: Automate root url generation with query structs.

.github/pull_request_template.md
<details>
otherwise).
release branch if it's not a patch change.~
</details>
Change the PR template to use simple language and less concepts. Change
the `goal and scope` question to simply `why`, asking that question
directly and as simply as possible.
- Change `Summary` to `What`.
- Change `Goal and scope` to `Why`.
- Remove `Summary of changes`
- Remove `What shouldn't be …
=> doc: lower the barrier-to-entry of writing great pr descriptions

services/bridge/README.md
<details>
otherwise).
packages.
</details>
Change the releases and example config links in `services/bridge`'s README to point to the new location under the `stellar/go` repository instead of the `bridge-server` repository.
The `bridge-server` was imported into the `stellar/go` …
=> services/bridge: fix links in readme

services/compliance/README.md
<details>
otherwise).
packages.
</details>
Change the releases and example config links in `services/compliance`'s README to point to the new location under the `stellar/go` repository instead of the `compliance-server` repository.
The `compliance-server` was imported into the …
=> services/compliance: fix links in readme

services/horizon/CHANGELOG.md, services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/actions/validators.go, services/horizon/internal/actions/validators_test.go, services/horizon/internal/actions_root_test.go, services/horizon/internal/docs/reference/endpoints/accounts.md
<details>
otherwise).
packages.
</details>
Use canonical representation for issued assets as defined in SEP0011 to filter accounts who have a trustline to an asset.
Being able to specify  an asset using a single parameter  `AssetCode:Issuer` is more ergonomic than having to …
=> services/horizon/internal/actions: Update asset filter on accounts

protocols/horizon/main.go, services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/actions_root.go, services/horizon/internal/actions_root_test.go, services/horizon/internal/resourceadapter/root.go, services/horizon/internal/resourceadapter/root_test.go
<details>
otherwise).
packages.
</details>
Update strict receive path action to use query structs.
We are in the process of documenting all the experimental endpoints and paths/strict-receive does not get listed on the root resource in Horizon. To facilite documentation, this PR …
=> services/horizon/internal/actions: Update strict receive path action to use query struct.

support/env/env.go, support/env/env_test.go
<details>
otherwise).
packages.
</details>
Replace use of `os.Exit(1)` and logging in the `support/env` package
with `panic`s.
When we call `os.Exit` in a library it gives the applications that is
using the library no opportunity to respond to something going wrong.
The …
=> support/env: replace os.Exit(1) with panic

keypair/main.go, keypair/main_test.go
<details>
otherwise).
packages.
</details>
Add `MustRandom()` that wraps `Random()` and works the same as `MustParse()`, converting any error returned by `Random()` into a `panic`.
Make it easier to hack on prototypes where keys are needed, and make `Random` functionally …
=> keypair: add MustRandom

txnbuild/account_merge.go, txnbuild/allow_trust.go, txnbuild/bump_sequence.go, txnbuild/change_trust.go, txnbuild/create_account.go, txnbuild/create_passive_offer.go, txnbuild/inflation.go, txnbuild/manage_buy_offer.go, txnbuild/manage_data.go, txnbuild/manage_offer.go, txnbuild/operation.go, txnbuild/path_payment.go, txnbuild/path_payment_strict_send.go, txnbuild/payment.go, txnbuild/set_options.go
<details>
otherwise).
packages.
</details>
Add `GetSourceAccount()` function to the `txnbuild.Operation` interface and to all implementers, surfacing the source account that exists on every implementer.
I was working with the txnbuild package and was trying to validate that a …
=> txnbuild: add GetSourceAccount to all operations

clients/horizonclient/effect_request_test.go, protocols/horizon/effects/main.go
<details>
otherwise).
packages.
</details>
Add `UnmarshalJSON` to `SequenceBumped`,  this method supports `new_seq` as a `string` or a `int64` in the JSON payload. This will allow us to cut a new release for the horizon client which won't break once we change the data type on the …
=> protocols/horizon/effects: Add UnmarshalJSON to SequenceBumped.

README.md
Update developer docs to indicate that Horizon's `main.go`/`internal.go` is deprecated.
Historically, Horizon has used `main.go` to hold public symbols, and `internal.go` to hold private symbols. Going forward, we'd like to adopt the standard approach (used in e.g. the Go [standard library](https://golang.org/src/context/context.go)) of placing structs and their related methods in the same file (with files created based on logical groupings) . This should be easier to understand and also reduce the quirkiness of the Horizon codebase with respect to our other projects and the rest of the world.
Since we aren't going to port everything in one go, it's appropriate to mention the convention but also clearly indicate that it's deprecated.
[N/A]
=> docs: deprecate the main.go/internal.go Horizon convention

services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
Implement state verifier for order book graph
Close https://github.com/stellar/go/issues/1872
> We check the state correctness in Horizon DB using ingest/verify.StateVerifier but we don't check in-memory order book graph.
=> services/horizon/internal/expingest: Implement state verifier for order book graph

services/horizon/internal/actions/asset.go, services/horizon/internal/actions/asset_test.go
<details>
otherwise).
packages.
</details>
Fix asset issuer does not exist bug in /assets endpoint
Close https://github.com/stellar/go/issues/1928
It seems that account can be removed when there are empty trust lines pointing to it. So Horizon should continue populating asset …
=> services/horizon/internal/actions: Fix asset issuer does not exist bug in /assets endpoint

exp/ingest/ledgerbackend/database_backend.go, services/horizon/internal/expingest/database_backend_test.go
<details>
otherwise).
packages.
* [] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
</details>
If there are no rows in the `ledgerheaders` table then `DatabaseBackend.GetLatestLedgerSequence()` crashes with an index out of range …
=> exp/ingest/ledgerbackend: Fix index out of range error in GetLatestLedgerSequence()

clients/horizonclient/effect_request_test.go, clients/horizonclient/offer_request_test.go, clients/horizonclient/operation_request_test.go, clients/horizonclient/trade_aggregation_request_test.go, protocols/horizon/base/main.go, protocols/horizon/effects/main.go, protocols/horizon/main.go, protocols/horizon/operations/main.go
<details>
otherwise).
packages.
</details>
Add `UnmarshalJSON` to `Trade`,  this method supports parsing of `int64` fields as as `json.Number` which might be a `string` or  `int64`. This will allow us to cut a new release for the horizon client which won't break once we change …
=> protocols/horizon: Add custom UnmarshalJSON to struct with int64 fields.

services/horizon/internal/app.go
<details>
otherwise).
packages.
</details>
Create and use a new `http.ServeMux` instead of using `http.DefaultServeMux`.
TBA
=> services/horizon: Use http.NewServeMux to create mux

services/horizon/CHANGELOG.md
- Improved the spacing to break up the wall of text for readability
- Added a little more detail
- Added links to PRs
=> add PR links to 0.23 Horizon changelog

services/horizon/internal/app.go
<details>
otherwise).
packages.
</details>
Remove the extra serve mux http handler layer between the http.Server and the chi.Router, which itself is a http.Handler.
The chi.Router is a handler, and we don't need to wrap it in another serve mux, whether it be the default or our …
=> services/horizon/internal: remove unused layer of router

services/horizon/internal/actions/asset.go, services/horizon/internal/actions/asset_test.go, services/horizon/internal/db2/history/asset_stats.go, services/horizon/internal/db2/history/asset_stats_test.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/expingest/processors/asset_stats_set.go, services/horizon/internal/expingest/processors/asset_stats_set_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
The experimental ingestion pipeline has a bug in that it counts unauthorized trustlines when computing asset stats. Only authorized trustlines should be included.
Another issue fixed in this PR is that the cursor for the new asset stats …
=> services/horizon/internal/expingest/processors: Only process authorized trustlines when updating asset stats 

services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/verify.go
Bumps `expingest.CurrentVersion` to recreate state due to a bug fixed in #1936.
We need to reingest existing state due to a rules change connected to trust lines authorization.
=> services/horizon: Bump expingest version

services/horizon/internal/db2/history/main.go
Updates `ExperimentalIngestionTables` with `exp_asset_stats` that contains asset stats populated by experimental ingestion pipeline.
When `expingest` rebuilds state it truncates state tables to start from scratch. One of the new tables introduced in 0.23.0 were not truncated what resulted in: `duplicate key value violates unique constraint` error.
We should add tests to not forget about truncating new tables in the future. Created: https://github.com/stellar/go/issues/1941
=> services/horizon: Truncate exp_asset_stats table when reingesting state

services/horizon/internal/render/sse/stream_handler.go, services/horizon/internal/render/sse/stream_handler_test.go
<details>
otherwise).
packages.
</details>
We should be sending a bye bye event before closing an SSE request.
But we neglect to do so when the StreamHandler context terminates the request.
Close https://github.com/stellar/go/issues/1934
=> services/horizon/internal/render/sse: Send bye bye event before exiting a StreamHandler

.circleci/config.yml
<details>
otherwise).
packages.
</details>
This PR removes the `go mod`-related checks for Go 1.12. 
Go 1.13-specific projects like [Hubble](https://github.com/stellar/go/tree/master/exp/hubble) creates divergence in the dependencies, and the spread of 1.13 in the larger …
=> .circleci: remove go mod checks for go 1.12

services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go
Currently we emit error log every time there's a problem with state validation, however, sometimes temporary errors like network connection issues happen. To avoid spamming the error log we only use the error log level after encountering 3 consecutive state validation errors
<details>
otherwise).
packages.
release branch …
=> services/horizon/internal/expingest: Emit error log after 3 failed attempts to validate state

services/horizon/internal/docs/reference/endpoints/fee-stats.md
<details>
otherwise).
packages.
</details>
Remove mention to deleted end-point.
This is not longer relevant, `/operation_fee_stats` was removed with
Horizon `0.18.0`.
[TODO or N/A]
=> services/horizon/internal/docs: Remove reference to operation_fee_stats.

services/keystore/CHANGELOG.md
<details>
otherwise).~
packages.
</details>
Update the Keystore CHANGELOG to signal that the current revision is v1.2.0.
Also, I re-ordered the versions so they are in descending order, like our other changelogs.
An important fix was made to Keystore and we should signal that …
=> services/keystore: update changelog to signal current revision as v1.2.0

services/federation/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Set version on CHANGELOG for Federation v0.3.0.
To release v0.3.0 of Federation.
N/A
=> services/federation: set version on changelog for v0.3.0

services/ticker/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Set version for the next release of Ticker, v1.2.0.
To release pending unreleased changes to Ticker.
N/A
=> services/ticker: set version for release v1.2.0

services/horizon/CHANGELOG.md, services/horizon/internal/actions_operation_fee_stats.go, services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/app.go, services/horizon/internal/db2/history/operation.go, services/horizon/internal/main_generated.go, services/horizon/internal/web.go
Renames `OperationFeeStats` to `FeeStats` across the horizon service.
Fixes #1952 
N/A
=> services/horizon: Rename `OperationFeeStats` to `FeeStats`

services/horizon/internal/actions/helpers.go, services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/offer.go, services/horizon/internal/actions/offer_test.go
<details>
otherwise).
packages.
</details>
Fix index out of range for requests with empty named url params #1965 
Making a request without passing the named URL params can cause the following error
```
runtime.boundsError runtime error: index out of range [0] with length 0
``` …
=> services/horizon/internal: Fix index out of range for requests with empty named url params.

exp/ingest/adapters/history_archive_adapter.go, exp/ingest/adapters/history_archive_adapter_test.go, exp/ingest/io/single_ledger_state_reader.go, exp/ingest/io/single_ledger_state_reader_test.go, exp/ingest/live_session.go, exp/ingest/main.go, exp/ingest/single_ledger_session.go, exp/tools/dump-ledger-state/main.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/reporter.go, services/horizon/internal/expingest/verify.go, services/horizon/internal/init.go, support/historyarchive/xdrstream.go, support/historyarchive/xdrstream_test.go, tools/archive-reader/archive_reader.go
<details>
otherwise).
packages.
</details>
If a SingleLedgerStateReader fails to read a single bucket entry the reading process is aborted.
This commit provides a retry mechanism which creates new XDR streams in case of XDR stream errors.
Close …
=> support/historyarchive: Provide mechanism for retrying XDR stream errors

exp/ingest/live_session.go, exp/ingest/single_ledger_session.go, exp/support/pipeline/main.go, exp/support/pipeline/pipeline.go, exp/support/pipeline/pipeline_test.go, services/horizon/internal/app.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/reporter.go
<details>
otherwise).
packages.
</details>
Fixes multiple issues connected to graceful shutdown of pipelines.
Shutting down pipelines gracefully is important due to multiple reasons, most importantly data integrity.
When `Pipeline.Shutdown()` was called post-processing hooks had …
=> exp/pipeline: Graceful shutdown of Pipeline

exp/ingest/io/single_ledger_state_reader.go, exp/ingest/io/single_ledger_state_reader_test.go, support/historyarchive/xdrstream.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/1979
If we encounter errors when we read a bucket entry from the history archive snapshot we attempt to retry the operation by creating a new stream. However, before creating a new stream we …
=> exp/ingest/io: Ignore PROTOCOL_ERROR when retrying xdr streams

services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/run_ingestion_test.go, services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
Graceful shutdown state verifier if it is running when the app gets shut down. Fix #1976 
If the app gets shutdown and the state verifier is running, it should wait for the verifier to gracefully shutdown instead of just killing the …
=>  services/horizon/internal/expingest: Graceful shutdown StateVerifier

services/horizon/CHANGELOG.md, services/horizon/internal/expingest/processors/asset_stats_set.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/main.go, services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
Fixes performance of asset stats processor.
For each ledger entry change connected to trust lines existing asset stats processor sends two DB queries. In order to decrease number of DB queries the code was changed to track delta change …
=> services/horizon: Improve performance of AssetStats processor

services/horizon/internal/ingest/asset_stat_test.go, services/horizon/internal/ingest/ingestion_test.go, services/horizon/internal/middleware.go, services/horizon/internal/web.go, services/ticker/internal/tickerdb/main.go, services/ticker/internal/tickerdb/queries_asset_test.go, services/ticker/internal/tickerdb/queries_issuer_test.go, services/ticker/internal/tickerdb/queries_market_test.go, services/ticker/internal/tickerdb/queries_orderbook_test.go, services/ticker/internal/tickerdb/queries_trade_test.go, support/db/batch_insert_builder_test.go, support/db/delete_builder_test.go, support/db/get_builder_test.go, support/db/insert_builder_test.go, support/db/main.go, support/db/main_test.go, support/db/select_builder_test.go, support/db/session.go, support/db/session_test.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/1950 , https://github.com/stellar/go/issues/1974
Use the context in `db.Session` when executing sql queries and statements on the session connection. A consequence of this change is that the …
=> all: Use context from session in sqlx functions

services/horizon/internal/docs/reference/endpoints/fee-stats.md
<details>
otherwise).
packages.
</details>
Update fee stats docs with changes from  #1964. Fixes #1990.
PR #1964 added new fields. 
N/A
=> services/horizon/internal/docs: Update /fee_stats with max_fee and fee_charged.

services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/ledgers_processor_test.go
<details>
otherwise).
packages.
</details>
Fixes ledger processor to not insert data into a DB when not in a DB ingestion.
All processors updating a database are ancestors of `ContextFilter` with `IngestUpdateDatabase` set. `ContextFilter` will only pass transactions to the …
=> services/horizon: Fix ledger processor when not ingesting into a DB

services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
This commit checks for shut down signal in `expingest/System.resumeFromLedger` and exits when signal has been received.
Ingestion pipeline (built using `exp/support/pipeline`) always returns an error (if occurred), even when shut down …
=> services/horizon: Graceful shutdown when session errors

services/horizon/internal/db2/history/asset_stats.go, services/horizon/internal/render/problem/problem.go, services/horizon/internal/web.go, support/db/main.go, support/db/session.go
<details>
otherwise).
packages.
</details>
This commit adds `ErrCancelled` error to `support/db` package. The error is returned when query is cancelled.
We add a new error to be able to compare is easily (instead of using `strings.Contains`).
=> support/db: Return ErrCancelled when query cancelled

xdr/account_id.go
This PR adds a method to the `xdr.AccountId` struct that returns the address with an error. The existing `Address` method is now a thin wrapper around this method.
In long-running, data-intensive applications, like the Hubble project, we want to avoid panics wherever possible. A `panic` on a single malformed input can abort the entire pipeline. A panic-free method to get the address of an `xdr.AccountId` struct helps reduce such possible failures.
N/A
=> xdr: get address from AccountId without panic

tools/horizon-cmp/README.md, xdr/ledger_entry_change.go
This PR gets the entry from an `xdr.LedgerEntryChange`, and an error if that cannot be retrieved.
Working with `xdr.LedgerEntryChange` structs involves a great deal of boilerplate to get the contained entry. This boilerplate also requires calling many `Must*` functions in the `xdr` package, which panics when processing malformed inputs. In long-running data applications, like the ingestion pipeline and the Hubble project, we want to avoid panics wherever possible, as a `panic` on a single malformed input can abort the entire pipeline. This helper thus makes overall development easier and reduces the risk of panicking.
N/A
=> xdr: get entry from ledger entry change

services/horizon/internal/render/sse/stream.go, services/horizon/internal/render/sse/stream_test.go, support/render/problem/problem.go, support/render/problem/problem_test.go
<details>
otherwise).
packages.
</details>
Use `problem.RegisterErrors` in streaming code and extend `support/problems` to expose register errors to its consumers.
#2007 and  #2005 were occurring because we were not handling properly `context.DeadlineExceeded`, `context.Canceled` …
=> services/horizon/internal: Use registered errors to recover from errors in streaming.

services/horizon/internal/render/sse/stream.go, services/horizon/internal/render/sse/stream_test.go
<details>
otherwise).
packages.
</details>
Fix #2011: `Object not found` error.
We change the implementation in https://github.com/stellar/go/pull/2008/files#diff-0a5d051d9afdb26132d468c0138c21bbR115 to look directly at the err and not `rootError`. This was causing the code not …
=> Remove custom handler for sql.ErrNoRows in stream.

services/horizon/internal/actions_operation_fee_stats.go, services/horizon/internal/actions_operation_fee_stats_test.go, services/horizon/internal/app.go, services/horizon/internal/operationfeestats/main.go
<details>
otherwise).
packages.
</details>
Fix ParseFloat bug in /fee_stats endpoint.
Close https://github.com/stellar/go/issues/2006
`operationfeestats.CurrentState()` returns a struct with the following fields:
https://github.com/stellar/go/blob/release-horizon-v0.24.0/services/ …
=> services/horizon/internal: Fix ParseFloat bug in /fee_stats

services/compliance/README.md
<details>
otherwise).
packages.
</details>
Change the link to the Compliance Protocol to be the new developers
guide link.
The old link resolves to a 404. Looks like the URL changed at some point
and we didn't update it here.
Fixes #2016
N/A
=> services/compliance: fix broken link in README

services/horizon/internal/middleware.go
<details>
otherwise).
packages.
</details>
This commit changes `ExperimentalIngestionMiddleware` to pass wrapped errors to `problem.Render` instead of logging them directly. This prevents errors connected to context timeout/deadline to be logged with `error` level.
=> services/horizon: Pass errors to problem.Render in ExperimentalIngestionMiddleware

services/horizon/internal/expingest/main.go, support/db/main.go, support/db/session.go, support/db/session_test.go
<details>
otherwise).
packages.
</details>
This commit adds `Synchronized` flag to `support/db.Session`. When set to `true` and `Session` runs a transaction all `Exec*` and `Select*` methods are protected by mutex what allows running them in multiple goroutines.
This is an …
=> support/db: Support concurrent queries in a transaction

exp/hubble/helper_functions_test.go, exp/hubble/processors.go, exp/hubble/schema_factory.go, exp/hubble/schema_factory_test.go
<details>
otherwise).
packages.
</details>
This PR rewrites the tests of the factory functions for our Elasticsearch schema to be table-based.
Table-based tests are more appropriate for testing the existence, or lack thereof, of errors. That is the primary goal of these tests. …
=> exp/hubble: convert schema factory tests to table-based

xdr/signer_key.go, xdr/signer_key_test.go
This PR adds a panic-free method to return the address from an `xdr.SignerKey` 
This PR adds a method to the `xdr.SignerKey` struct that returns the address with an error. The existing `Address` method is now a thin wrapper around this method.
In long-running, data-intensive applications, like the Hubble project, we want to avoid panics wherever possible. A panic on a single malformed input can abort the entire pipeline. A panic-free method to get the address of an `xdr.SignerKey` struct helps reduce such possible failures.
N/A
=> xdr: get address from signer key without panic

services/horizon/internal/docs/quickstart.md
change the horizon query port from 8001 to 8000
following the horizon quickstart, horizon is exposed on port 8000 not 8001
=> doc: change horizon query port

exp/tools/dump-ledger-state/docker-entrypoint.sh
Also, do not override LATEST_LEDGER if the variable is already set
<details>
otherwise).
packages.
</details>
* Use @horizon-team in slack alert
* Only populate `LATEST_LEDGER` if it is not set
* `@horizon-team` will notify all members of the horizon team on slack
* It will be …
=> exp/tools/dump-ledger-state: Use @horizon-team in slack alert

keypair/main.go, keypair/main_test.go
<details>
otherwise).
packages.
</details>
Add `keypair.ParseFull` function that behaves the same as
`keypair.Parse`, but returns a `keypair.Full` instead of a `keypair.KP`.
A couple times in my own coding I've found that my code knows that I
have a seed, not an address, and I …
=> keypair: add ParseFull function

services/horizon/cmd/root.go, support/config/config_option.go
<details>
otherwise).
packages.
</details>
Adds a `ConfigOptions` type that is a slice of `ConfigOptions`, and wraps up initializing and setting the values of all the options. Also updates Horizon to use those new functions.
I had a go of using the `ConfigOption` type and …
=> support/config: simplify initing and setting multiple ConfigOptions

services/horizon/cmd/root.go, support/config/config_option.go
<details>
otherwise).
packages.
</details>
Move the call to `viper.BindPFlags` from our services that use the `support/config` package, into the config package `Init` function.
The `support/config` package does a good job of wrapping up cobra and viper functionality so that an …
=> support/config: move viper bindpflag into init

.circleci/config.yml
<details>
otherwise).
packages.
</details>
Because CircleCI does not build tags by default, any child jobs that rely on a job that only builds on tags will also require the tag filter. In this case, the `hold` and `publish_latest_horizon_docker_image` jobs will need the filter …
=> .circleci: Fix circleci publish_latest_horizon_docker_image job

keypair/from_address.go, keypair/full.go, keypair/main.go, keypair/main_test.go
<details>
otherwise).
packages.
</details>
Add a `FromAddress()` function to all `KP` implementers that returns the public key, or address only, version of the keypair.
I have an application that will use a Stellar account seed/key, and some of the handlers in that application …
=> keypair: make simple to get FromAddress from any KP

.circleci/config.yml
This commit was previously reviewed https://github.com/stellar/go/pull/2047 .  But, I'd like to make sure #2047 is also included in the horizon v0.24.1 release so we can test out the publish docker circleci job
=> Fix circleci for 0.24.1 release

exp/ingest/io/ledger_transaction.go, exp/ingest/io/ledger_transaction_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/processors/accounts_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
This commit changes `io.LedgerTransaction` to return fee and tx meta separately and updates Horizon processors to apply changes in correct order. This issue was found by `StateVerifier`.
Close #2038.
The order of applying meta changes in …
=> exp/ingest: Fix fee and transaction meta processing

support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
Add package documentation that clearly states that this package implements an RFC. Add a link to the RFC, now that the RFC has a number.
It isn't clear without digging into the code that this package implements an RFC. There is a …
=> support/render/problem: add and update docs

services/horizon/internal/db2/history/ledger.go, services/horizon/internal/db2/history/ledger_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipeline_hooks_test.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/run_ingestion_test.go
<details>
otherwise).
packages.
</details>
Trim experimental ingestion historical data when starting ingestion from a history archive snapshot.
Close https://github.com/stellar/go/issues/2052
Horizon always reingests state using the latest checkpoint ledger and in most cases the …
=> services/horizon/internal/expingest/main.go: Trim experimental ingestion historical data when starting ingestion

services/bridge/main.go, services/compliance/main.go, services/federation/main.go, services/friendbot/main.go, support/http/mux.go
<details>
otherwise).
packages.
</details>
Remove the ability to configure `support/http` muxes/routers with the behind proxy flag.
We use these mux functions in five places across four applications, but always with behind proxy as false. We never offer a way to configure it, …
=> support/http: remove behind proxy option for muxes

services/horizon/internal/assertions_test.go, support/render/problem/default.go, support/render/problem/default_test.go, support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
Make the `problem` package usable without needing to use a single global state.
Move all package functionality into a new type that has the same interface as the package and can be instantiated with `New` and used and tested in …
=> support/render/problem: make problem package in an isolated instance without globals

support/render/httpjson/io.go, support/render/httpjson/io_test.go
<details>
otherwise).
packages.
</details>
Add `RenderStatus` function to `support/render/httpjson` that behaves exactly the same as `Render` but allows setting a non-`200 OK` status code for the response.
It is not possible to use `Render` to render a response that doesn't …
=> support/render/httpjson: add RenderStatus for rendering with non-200 status codes

exp/ingest/live_session.go, exp/support/pipeline/pipeline.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/run_ingestion_test.go
<details>
otherwise).
packages.
</details>
This commit fixes data race in `exp/ingest/pipeline` that can occur when `LiveSession` (and Horizon) is shut down.
It also removes `updateStats` method that was known to have a data race (see comment in that method). It is not actively …
=> exp/ingest/pipeline: Fix pipeline data race during shutdown

services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
@abuiles could not run the experimental ingestion system locally because there was a deadlock which prevented ingestion from starting. Adolfo was able to isolate the commit which caused the deadlock to …
=> services/horizon/internal/expingest: Fix deadlock in experimental ingestion

txnbuild/transaction.go, txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Remove the `ok` bool value that the `verifyTxSignature` function returns alongside its `error` value.
The `bool` is redundant.
The `verifyTxSignature` function returns both a `bool` and an `error` but both are communicating the same …
=> txnbuild: remove redundant ok from internal verify functions

services/ticker/internal/tickerdb/queries_asset_test.go
<details>
otherwise).
packages.
</details>
Add logs to the `TestInsertOrUpdateAsset` that print out the exact times that are being used.
The test has been reported as flaky a couple times, first in #1733 then in #2063. There was an imperfect fix put in place in 3e23070 but …
=> services/ticker: add test logs to identify inputs that make test flaky

.circleci/config.yml, exp/ingest/errors/main.go, exp/ingest/io/ledger_entry_change_cache.go, exp/ingest/io/ledger_entry_change_cache_test.go, exp/ingest/io/ledger_transaction.go, exp/ingest/io/ledger_transaction_test.go, exp/ingest/live_session.go, exp/ingest/verify/main.go, exp/ingest/verify/main_test.go, exp/support/pipeline/pipeline.go, services/horizon/CHANGELOG.md, services/horizon/internal/db2/history/ledger.go, services/horizon/internal/db2/history/ledger_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipeline_hooks_test.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/accounts_data_processor_test.go, services/horizon/internal/expingest/processors/accounts_processor_test.go, services/horizon/internal/expingest/processors/accounts_signer_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/ledgers_processor_test.go, services/horizon/internal/expingest/processors/offers_processor_test.go, services/horizon/internal/expingest/processors/trust_lines_processor_test.go, services/horizon/internal/expingest/run_ingestion_test.go, services/horizon/internal/expingest/verify.go, xdr/ledger_entry_change.go, xdr/ledger_key.go
Update master with commits from v0.24.1
=> Merge horizon v0.24.1 into master

txnbuild/transaction.go
<details>
otherwise).
packages.
</details>
Check that a transaction has an xdrEnvelope before calculating the transactions hash or doing any other tasks when verifying a challenge transaction has a signature.
This check is really inexpensive and simple but we don't do it until …
=> txnbuild: check tx.xdrEnvelope first before other checks

keypair/main.go, keypair/main_test.go
<details>
otherwise).
packages.
</details>
Add `ParseAddress` function to `keypair` package.
Similar to why we recently added the `ParseFull` function sometimes we want to parse a keypair and we specifically only want an address. Encouraging use of `Parse` that does both seeds …
=> keypair: add ParseAddress

services/horizon/internal/db2/history/accounts.go, services/horizon/internal/db2/history/accounts_test.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/mock_q_accounts.go, services/horizon/internal/db2/history/mock_q_trust_lines.go, services/horizon/internal/db2/history/trust_lines.go, services/horizon/internal/db2/history/trust_lines_test.go, services/horizon/internal/expingest/processors/accounts_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/main.go, services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
This commit changes `DatabaseProcessor` to insert/update (upsert) accounts and trust lines in batches.
In #2004 we added `LedgerEntryChangeCache` that aims to decrease number of DB updates: all the changes connected to a single ledger …
=> services/horizon: Batch Upsert Accounts and Trust Lines

support/http/httpdecode/httpdecode.go, support/http/httpdecode/httpdecode_test.go, support/render/httpjson/handler.go, support/render/httpjson/io.go
<details>
otherwise).
packages.
</details>
Move the http decoding logic we use for decoding JSON messages to its own package.
This logic is at the moment buried as an not-exported function in the `support/render/httpjson` package. I think it belongs in its own package because: …
=> support/http/httpdecode: move http decoding to its own package

support/http/httpdecode/httpdecode.go, support/http/httpdecode/httpdecode_test.go
<details>
otherwise).
packages.
</details>
Add functions `DecodeForm` that decodes form URL encoded post bodies and `Decode` for combined decoding of requests that contain either form URL encoded or JSON bodies.
In some of our SEPs we are required to parse requests that can be …
=> support/http/httpdecode: add funcs for form and form+json decoding

services/keystore/api.go
<details>
otherwise).
packages.
</details>
Use CORS handler we use in other apps that implements CORS more completely.
The frontend folks are saying their seeing issues with the CORS OPTIONS handshake with the keystore.
I think our implementation of CORS is missing a step …
=> services/keystore: use cors handler like our other apps

services/horizon/internal/docs/reference/endpoints/accounts-single.md
Changing the [Account Details](https://www.stellar.org/developers/horizon/reference/endpoints/accounts-single.html) documentation page, in the example data of a REST read request.
Adds a field `is_authorized` in the `balances` section, missing on the page, and seen on https://www.stellar.org/laboratory/#explorer?resource=accounts&endpoint=single&network=test 
Also, in the documentation example, the `signers` there have a field `public_key`, always equals to the sibling `key`. Since they are several types of keys, maybe there here for a reason. But it's not here in the laboratory for a single-signing *ed25519_public_key* account.
=> [Doc] Adds the "balance.is_authorized" field in example

exp/ingest/io/single_ledger_state_reader.go, exp/ingest/io/single_ledger_state_reader_test.go
<details>
otherwise).
packages.
</details>
If creating a new xdr stream or discarding from the new stream fails the retry process aborts.
This commit extends the retry logic to cover these failures.
We encountered failures caused by `stream.Discard(currentPosition)` which …
=> exp/ingest/io: Extend SingleLedgerStateReader retry logic

services/horizon/internal/expingest/load_orderbook_graph_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/run_ingestion_test.go
<details>
otherwise).
packages.
</details>
This PR rewrites `System` to a state machine as described in #1969.
Close #1969.
The new code is easier to test because it's possible to start test from any state without having to add a bunch of mocked methods to reach the code we want …
=> services/horizon/expingest: Rewrite System to a state machine

services/horizon/internal/ingest/ingestion.go
<details>
otherwise).
packages.
</details>
Remove dead code from legacy ingestion system.
The code which ingests trades is located here:
https://github.com/stellar/go/blob/54d2e97fc84239192c91af22e7e89c5b4537beea/services/horizon/internal/ingest/session.go#L536
As far as I can …
=> services/horizon/internal/ingest/ingestion: Remove dead code from legacy ingestion system

services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
Fixes a but in tests that are mocking `UpsertTrustLines` method.
Because all of the ledger entry changes are cached using `LedgerEntryChangeCache` it's possible that the order of trustlines in `UpsertTrustLines` will be different between …
=> services/horizon: Fix tests mocking UpsertTrustLines

exp/ingest/io/genesis_ledger_state_reader.go, exp/ingest/io/genesis_ledger_state_reader_test.go, exp/ingest/main.go, exp/ingest/range_session.go, exp/orderbook/graph.go, services/horizon/cmd/db.go, services/horizon/cmd/ingest.go, services/horizon/cmd/root.go, services/horizon/internal/expingest/load_orderbook_graph_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/operations_processor.go, services/horizon/internal/expingest/processors/participants_processor.go, services/horizon/internal/expingest/processors/transactions_processor.go, services/horizon/internal/expingest/run_ingestion_test.go, services/horizon/internal/expingest/verify.go, support/config/config_option.go, xdr/db.go
<details>
otherwise).
packages.
</details>
Adds `horizon expingest verify-range` command and `exp/ingest.RangeSession`. It also adds `GenesisLedgerStateReader` to that streams master account in a given network to allow ingesting ledger entry changes from ledger 1.
Close #1848. …
=> services/horizon: verify-range command

exp/ingest/main.go, exp/ingest/range_session.go
This commit changes `RangeSession` to return error when ledger not found.
Contrary to `LiveSession` that needs to wait for next ledger closed by the network `RangeSession` assumes that all ledgers within a range exist. Instead of waiting it should just return error if ledger is not found.
=> exp/ingest: RangeSession return error when ledger not found

services/horizon/internal/db2/history/ingestion.go, services/horizon/internal/db2/history/ingestion_test.go, services/horizon/internal/db2/history/trade.go, services/horizon/internal/db2/history/trade_batch_insert_builder.go, services/horizon/internal/db2/history/trade_test.go, services/horizon/internal/db2/schema/bindata.go, services/horizon/internal/db2/schema/migrations/30_exp_history_trades.sql, services/horizon/internal/expingest/pipeline_hooks_test.go
<details>
otherwise).
packages.
</details>
Add a migration for the `exp_history_trades` table. Also add functions to insert and query the table. These functions will be used by the trades ingestion processor.
The trades processor in the experimental ingestion system will populate …
=> services/horizon/internal/db2: Add exp_history_trades table

exp/ingest/io/ledger_transaction.go, exp/ingest/io/ledger_transaction_test.go, xdr/Stellar-ledger.x, xdr/Stellar-overlay.x, xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
This commit adds support for ingesting `TransactionMeta` when `V=2` and updates XDR files.
Close #1902.
As explained by @MonsieurNicolas in #1902.
> There is some missing meta in protocol version older than version 10. This impacts …
=> exp/ingest/io: Add support for ingesting txmeta v2

exp/ingest/ledgerbackend/database_backend.go
<details>
otherwise).
packages.
</details>
This commit adds a code that checks if tx meta version is v2 for protocol version <10 ledgers.
Close #2095.
As explained by @MonsieurNicolas in #1902:
> There is some missing meta in protocol version older than version 10. This impacts …
=> exp/ingest/ledgerbackend: Ensure tx meta is v2 when getting protocol version <10 ledgers

exp/ingest/io/ledger_transaction.go, exp/ingest/io/ledger_transaction_test.go, exp/tools/horizon-demo/database_processor.go, exp/tools/horizon-demo/orderbook_processor.go, services/horizon/internal/expingest/processors/accounts_processor_test.go, services/horizon/internal/expingest/processors/database_processor.go, services/horizon/internal/expingest/processors/offers_processor_test.go, services/horizon/internal/expingest/processors/orderbook_processor.go, services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
This commit removes support for ingesting `TransactionMeta.V=0` in `io.LedgerTransaction.GetChanges`.
Close #2097.
The code generating V0 meta was changed in stellar-core but without upgrading the V param. Some V0 meta has only one …
=> exp/ingest/io: Remove support for TransactionMeta.V=0

services/horizon/internal/expingest/processors/operations_processor_test.go, services/horizon/internal/expingest/processors/participants_processor.go, services/horizon/internal/expingest/processors/participants_processor_test.go, services/horizon/internal/expingest/processors/transactions_processor_test.go
<details>
otherwise).
packages.
</details>
Remove sort on addresses in ParticipantsProcessor
Previously, we sorted addresses before calling `ParticipantsQ.CreateExpAccounts()`.
The only purpose of the sort was to make it easier to mock the expected arguments of …
=> services/horizon/internal/expingest/processors: Remove sort on addresses in ParticipantsProcessor

services/horizon/internal/db2/history/accounts_test.go, services/horizon/internal/db2/page_query.go
<details>
otherwise).
packages.
</details>
Fix page query in descending order with empty string. 
When using a string as a cursor and without cursor validation, sorting in descending order will produce a SQL which will always return 0 results, as seen …
=> services/horizon/internal/db2: Fix page query in descending order with empty string.

services/horizon/internal/db2/history/asset.go, services/horizon/internal/db2/history/asset_test.go, services/horizon/internal/db2/history/mock_q_trades.go, services/horizon/internal/db2/history/trade.go, services/horizon/internal/db2/history/trade_test.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/expingest/processors/trades_processor.go, services/horizon/internal/expingest/processors/trades_processor_test.go
<details>
otherwise).
packages.
</details>
Add ingestion processor for trades.
We need to populate the historical trades table in order to serve trade endpoints.
[N/A]
=> services/horizon/internal/expingest: Add Trades processor

services/horizon/internal/expingest/processors/effects_processor.go, services/horizon/internal/expingest/processors/effects_processor_test.go, services/horizon/internal/ingest/session.go, services/horizon/internal/ingest/session_test.go
<details>
otherwise).
packages.
</details>
Save effect details order by address when ingesting set_option operations.
We got some failures when running `CheckExpOperationEffects`, however, after analyzing the data, we found out that  we have the desired result but the order was …
=> Sort signers before creating event.

exp/ingest/io/ledger_transaction.go, exp/ingest/io/ledger_transaction_test.go
<details>
otherwise).
packages.
</details>
Ignore operation and txChangesAfter meta if tx result is txInternalError.
Due to a tx meta generation bug in stellar-core (https://github.com/stellar/stellar-core/pull/2383) it's possible that tx meta is incorrect for transactions with …
=> exp/ingest/io: Ignore operation and txChangesAfter meta if tx result is txInternalError.

exp/services/webauth/README.md
<details>
otherwise).
packages.
</details>
Remove an extra tilde from the webauth README.
It's a typo and it breaks the rendering of the code blocks.
N/A
=> exp/services/webauth: fix typo in readme

services/horizon/internal/action.go, services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/actions_account_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2102
> Currently we still serve account data from the core DB and just compare the data to the new ingestion system. We should switch to the new ingestion data but keep the compare code there. …
=> services/horizon/internal/actions: Serve /accounts/{id} using expingest data

services/horizon/internal/app.go, services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
This commit removes `ingest` initialization code.
The new `expingest` system will become the default ingestion system in 0.25.0 so we remove the old system init code and start `expingest` when `INGEST` flag is set.
Starting `expingest` …
=> services/horizon: Remove ingest initialization code

exp/ingest/io/single_ledger_state_reader.go, exp/ingest/io/single_ledger_state_reader_test.go, exp/services/webauth/README.md, exp/services/webauth/internal/commands/genjwtkey.go, exp/services/webauth/internal/commands/serve.go, exp/services/webauth/internal/serve/challenge.go, exp/services/webauth/internal/serve/challenge_test.go, exp/services/webauth/internal/serve/errors.go, exp/services/webauth/internal/serve/errors_test.go, exp/services/webauth/internal/serve/serve.go, exp/services/webauth/internal/serve/token.go, exp/services/webauth/internal/serve/token_test.go, exp/services/webauth/main.go, exp/support/jwtkey/jwtkey.go, exp/support/jwtkey/jwtkey_test.go, go.list, go.mod, go.sum, keypair/main.go, keypair/main_test.go, services/keystore/api.go, services/ticker/internal/tickerdb/queries_asset_test.go, support/http/httpdecode/httpdecode.go, support/http/httpdecode/httpdecode_test.go, support/render/httpjson/handler.go, support/render/httpjson/io.go, support/render/httpjson/io_test.go, txnbuild/transaction.go, txnbuild/transaction_test.go
While testing old ledgers I came across:
```
Error while reading from buckets: Error on XDR record 179999 of hash '8d2a036cfdf8da352aaa00bb0c9706906ee5c01563e1f348b92773e86330dc64': stream error: stream ID 59; PROTOCOL_ERROR
```
type of errors when downloading state from buckets. I wanted to cherry-pick https://github.com/stellar/go/commit/54d2e97fc84239192c91af22e7e89c5b4537beea that should fix it but it looks like the rest of the commits on `master` aren't changing anything related to Horizon.
=> Merge master into release-horizon-v0.25.0

services/horizon/internal/actions_trade.go, services/horizon/internal/actions_trade_test.go, services/horizon/internal/render/problem/problem_test.go, support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
Remove `GetCreateAssetID` usage from actions. Fix #2061
`GetCreateAssetID` writes data to the DB when an asset is not found, but Horizon shouldn't need write access to a DB outside `ingest` package, this also causes some errors as …
=> services/horizon/internal/actions: Remove GetCreateAssetID usage from actions.

services/horizon/internal/actions_path_test.go, services/horizon/internal/app.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/pipeline_hooks_test.go, services/horizon/internal/expingest/pipelines.go, services/horizon/internal/middleware.go, services/horizon/internal/middleware_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2110
* remove `StateReady()` and related functions in ingestion system
* update ingestion middleware to respond with status `StillIngesting` if the ingestion version is out of date, or the last …
=> services/horizon/internal: Replace StateReady() check

clients/horizon/main_test.go, clients/horizonclient/effect_request_test.go, clients/horizonclient/main_test.go, clients/horizonclient/offer_request_test.go, clients/horizonclient/operation_request_test.go, clients/horizonclient/trade_aggregation_request_test.go, protocols/horizon/base/main.go, protocols/horizon/effects/main.go, protocols/horizon/main.go, protocols/horizon/operations/main.go, services/horizon/internal/actions_operation_test.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/resourceadapter/effects.go, services/horizon/internal/resourceadapter/operations.go
<details>
otherwise).
packages.
</details>
Change the type for multiple JSON fields using `int64` to be of type `string`:
- Attribute `offer_id` in [manage buy offer](https://www.stellar.org/developers/horizon/reference/resources/operation.html#manage-buy-offer) and [manage sell …
=> protocols/horizon: Change JSON response from int64 to string in multiple places.

services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/actions_account_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2135
> When account data in Horizon table does not match Stellar-Core data, we should return (and log) error instead of returning invalid data.
The data account data populated by horizon …
=> services/horizon/internal/actions: Respond with error if core account does not match horizon account

services/horizon/cmd/db.go
<details>
otherwise).
packages.
</details>
Removes old `horizon db` commands.
Most of the methods can be replaced with `db reingest range` command:
* `db backfill` - `reingest range` can be used instead,
* `db rebase` - can be added back in one of the future versions but is …
=> services/horizon: Remove old db commands

services/horizon/internal/expingest/processors/participants_processor.go, services/horizon/internal/expingest/processors/participants_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2145
The `ParticipantsProcessor` uses the ingest/participants package to extract participants from a transaction.
This commit copies the code from the ingest/participants package to the …
=> services/horizon/internal/expingest/processors: Remove dependency on legacy ingestion package

support/config/config_option.go, support/config/config_option_test.go
<details>
otherwise).
packages.
</details>
Append the environment variable for config options to their usage text.
The first dozen times I ran Horizon I had no idea that I could use environment variables to configure it. I was hand building options on the command line. I only …
=> support/config: append env var to usage text of options

exp/services/webauth/README.md
<details>
otherwise).
packages.
</details>
Update the `webauth`'s README usage text to match the usage text generated by the command, showing the environment variables that can be used to configure the application.
So that by looking at the README you can see what environment …
=> exp/services/webauth: update readme usage text

services/horizon/internal/actions/helpers.go, services/horizon/internal/actions_account_test.go, services/horizon/internal/actions_data_test.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/app.go, services/horizon/internal/middleware.go, services/horizon/internal/middleware_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
This commit cleans the code responsible for Horizon webserver init.
* Moved all routes using the `StateMiddleware` (previously `ExperimentalIngestionMiddleware`) to avoid code duplication.
* Start routes using order book graph only if …
=> services/horizon: Cleanup routes in webserver init code

services/horizon/internal/actions_effects_test.go, services/horizon/internal/actions_payment_test.go, services/horizon/internal/actions_transaction_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
Fixes a bug introduced in #2152. Paths like: `/accounts//payments` return all payments instead of 404. This can lead to dangerous bugs when account ID is omited in request by accident.
=> services/horizon: Fix empty route param bug

exp/services/webauth/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Add a `/health` endpoint to the webauth service.
So that deployment environments can test if the service is up and ready, and it is healthy.
The health endpoint is just to test if the service is up because the service has no critical …
=> exp/services/webauth: add health endpoint

clients/horizonclient/CHANGELOG.md, clients/horizonclient/error_helpers.go, clients/horizonclient/error_helpers_test.go, txnbuild/transaction_challenge_example_test.go
<details>
otherwise).
packages.
</details>
Add `horizonclient.IsNotFoundError` that returns true if an `error` is a Horizon `not_found` problem error.
It is remarkably verbose and difficult to detect if an account exists in Horizon. The code to do so must unwrap the …
=> clients/horizonclient: add IsNotFoundError

exp/services/webauth/README.md, exp/services/webauth/internal/commands/serve.go, exp/services/webauth/internal/serve/serve.go, exp/services/webauth/internal/serve/token.go, exp/services/webauth/internal/serve/token_test.go
<details>
otherwise).
packages.
</details>
Add support for verifying accounts that do not exist behind an application option. When enabled the webauth application will allow a client to authenticate with an account that has not been created using the accounts master key. …
=> exp/services/webauth: add support for verifying accounts that do not exist

services/horizon/internal/expingest/processors.go
<details>
otherwise).
packages.
</details>
Close state reader in `runHistoryArchiveIngestion()`
The state reader needs to be closed to release the http connection to the history archives.
[N/A]
=> services/horizon/internal/expingest: Close state reader in runHistoryArchiveIngestion()

exp/ingest/io/processors_test.go, services/horizon/internal/expingest/logger_state_reader.go, services/horizon/internal/expingest/logger_state_reader_test.go, services/horizon/internal/expingest/processors.go
<details>
otherwise).
packages.
</details>
Report number of processed entries in state processing every 100k entries. Fix #2182
Ingesting from the history archives can take 15-20 minutes. We need a mechanism for logging the current progress of reading through the history …
=> services/horizon/internal/expingest: Report number of processed entries in state ingestion.

exp/ingest/io/ledger_change_reader_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2184
Add tests on the LedgerChangeReader implementation. 
To improve test coverage.
[N/A]
=> exp/ingest/io: Add LedgerChangeReader tests

services/horizon/internal/db2/history/effect.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/participants.go, services/horizon/internal/db2/history/trade.go, services/horizon/internal/expingest/init_state_test.go, services/horizon/internal/expingest/load_orderbook_graph_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/main_test.go, services/horizon/internal/expingest/run_ingestion_test.go, services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
This commit is reverting removal of `buildState` state and adds initial tests (starting with `init` state tests).
Close #2183.
With separate state that build state from history archives it will be easier to test and understand the …
=> services/horizon/expingest: Revert buildState removal, add tests

exp/services/webauth/internal/serve/token_test.go
<details>
otherwise).
packages.
</details>
Remove duplicate expectation from test.
The line was duplicated seemingly by accident.
N/A
=> exp/services/webauth: remove duplicate test expectation

services/horizon/internal/expingest/main.go
The following log was emitted during shutdown:
```
ERRO[2020-01-31T14:42:51.443+01:00] Error in ingestion state machine              current_state="{buildState 0 28009855 0 0 false false false false}" error="Error ingesting history archive: Error streaming changes from HAS: could not process change: error in Commit: errors in UpsertTrustLines: canceling statement due to user request" next_state="{init 0 0 0 0 false false false false}" pid=13545 service=expingest
```
This commit makes sure `db.ErrCancelled` is also skipped when it comes to logging
=> services/horizon/internal/expingest: Dont log db.ErrCancelled errors

services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/mock_q_data.go, services/horizon/internal/db2/history/mock_q_offers.go, services/horizon/internal/db2/history/mock_q_signers.go, services/horizon/internal/db2/history/mock_q_trust_lines.go, services/horizon/internal/expingest/ingest_history_range_state_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/main_test.go, services/horizon/internal/expingest/processors_runner.go, services/horizon/internal/expingest/verify.go, services/horizon/internal/expingest/verify_range_state_test.go
<details>
otherwise).
packages.
</details>
This commit adds tests to `verifyState` state and updates `IngestionQ` interface to allow cloning. More tests will be added in a separate PR.
=> services/horizon/expingest: Add verifyState tests

services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/main_test.go
This commit fixes initialization code of `ProcessorRunner`. It also adds initial test to checj `NewSystem`.
=> services/horizon/expingest: Fix ProcessorRunner init code

exp/services/webauth/README.md, exp/services/webauth/internal/commands/serve.go, exp/services/webauth/internal/serve/serve.go, exp/services/webauth/internal/serve/token.go, exp/services/webauth/internal/serve/token_test.go
<details>
otherwise).
packages.
</details>
Add a parameter to configure the value of the JWT issuer that is
included in the `iss` claim of JWTs issued by the webauth service.
The issuer is hardcoded as the server signing key, but @JakeUrban
pointed out that the SEP-10 …
=> exp/services/webauth: make jwt issuer a uri and configurable

services/horizon/internal/expingest/processors/signer_processor_test.go, services/horizon/internal/expingest/processors/signers_processor.go
<details>
otherwise).
packages.
</details>
This commit fixes performance issue in `Signers` processor.
While refactoring state processors #2176 I omitted the condition to check if signers on account have actually changed before updating a database. Without it, the signers table …
=> services/horizon/expingest: Fix Signers processor performace

keypair/main.go, keypair/main_test.go
<details>
otherwise).
packages.
</details>
Add MustParseAddress and MustParseFull functions that are the
panic-on-fail versions of ParseAddress and ParseFull.
It is useful to be able to use functions that do not return an error,
especially in tests when we are often parsing …
=> keypair: add MustParseAddress, MustParseFull

txnbuild/transaction.go, txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Ignore txhash (T...) signers, used for preauth transactions, xhash (X...)
signers, and other future types of signers the server might not know
about, during SEP-10 verification.
Developers will likely pass through to the verification …
=> txnbuild: ignore txhash (preauth) and xhash signers in sep-10

exp/ingest/adapters/history_archive_adapter.go, exp/ingest/io/single_ledger_state_reader.go
<details>
otherwise).
packages.
</details>
There are several places in exp/ingest/adapters/history_archive_adapter.go and exp/ingest/io/single_ledger_state_reader.go where we forget to use `errors.Wrap()` to propagate errors.
It's important to wrap errors because the ingestion …
=> exp/ingest: Use errors.Wrap to propagate errors

services/horizon/internal/expingest/build_state_test.go, services/horizon/internal/expingest/fsm.go, services/horizon/internal/expingest/ingest_history_range_state_test.go, services/horizon/internal/expingest/init_state_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/main_test.go, services/horizon/internal/expingest/resume_state_test.go, services/horizon/internal/expingest/verify.go, services/horizon/internal/expingest/verify_range_state_test.go
<details>
otherwise).
packages.
</details>
The ingestion system uses a finite state machine to model its behaviors (see https://github.com/stellar/go/issues/1969 ). In the current implementation the state machine is represented by the following struct:
```golang
type systemState …
```
=> services/horizon/internal/expingest: Refactor ingestion system to use explicit FSM

services/horizon/internal/expingest/main_test.go, support/db/main.go, support/db/session.go, support/db/session_test.go
This commit reverts 9bbfc3c81bdaab65bda5dc6d39f19d24e44e636b.
We decided to not use this experimental feature and it's no longer needed.
=> Revert "support/db: Support concurrent queries in a transaction (#2024)"

clients/horizonclient/accounts_request.go, clients/horizonclient/client.go, clients/horizonclient/examples_test.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go, clients/horizonclient/mocks.go, protocols/horizon/main.go
<details>
otherwise).
packages.
</details>
Extend the horizonclient to support accounts filtering. It allows
account retrival by signer or with a trustline to an asset.
```go
client := horizonclient.DefaultPublicNetClient
accountID := …
```
=> clients/horizonclient: Add support for Accounts endpoint.

services/horizon/cmd/root.go
After talking with one of Horizon users I realized that the usage message of `--max-path-length` is missing the information about the performance implications of changing the value.
=> services/horizon: Update the usage message of `--max-path-length`

clients/horizonclient/examples_test.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go, clients/horizonclient/offer_request.go
<details>
otherwise).
packages.
</details>
Extend SDK to allow fetching offers from the `/offers` endpoint, supporting any of its current filters.
This endpoint will be availabe on Horizon 1.0.
[TODO or N/A]
=> client/horizonclient: Extend offers to support new filters.

clients/horizonclient/client.go, clients/horizonclient/examples_test.go, clients/horizonclient/main.go, clients/horizonclient/paths_request.go, clients/horizonclient/paths_request_test.go, clients/horizonclient/strict_send_paths_request.go, clients/horizonclient/strict_send_paths_request_test.go
<details>
otherwise).
packages.
</details>
Extend horizonclient to support request to [/paths/strict-send](https://www.stellar.org/developers/horizon/reference/endpoints/path-finding-strict-send.html)  and [/paths/strict-receive](https://www.stellar.org/developers/horizon/referenc …
=> clients/horizonclient: Support paths/strict-send and paths/strict-receive requests.

support/http/httpdecode/httpdecode.go, support/http/httpdecode/httpdecode_test.go
<details>
otherwise).
packages.
</details>
Add decoding of queries from requests into structs to the `httpdecode` package in a new `DecodeQuery` function and into the existing `Decode` function.
We use httpdecode to decode requests into structs and this works really well for …
=> support/http/httpdecode: add decoding of querys

services/horizon/cmd/db.go, services/horizon/internal/expingest/fsm.go, services/horizon/internal/expingest/ingest_history_range_state_test.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/main_test.go
<details>
otherwise).
packages.
</details>
* Separate `horizon db reingest range` code from `historyRangeState`
* Add a force flag to the `horizon db reingest range` command
Fixes https://github.com/stellar/go/issues/2231
Currently when you run `horizon db reingest range` horizon …
=> services/horizon/internal/expingest: Allow horizon db reingest range to run concurrently with Horizon

keypair/from_address.go, keypair/from_address_test.go, keypair/full.go, keypair/full_test.go, keypair/main.go
<details>
otherwise).
packages.
</details>
keypair: add SignBase64 that returns signatures strings
Add `SignBase64` to the `keypair.KP`, `keypair.Full`, and
`keypair.FromAddress` types that performs the same operation as `Sign`
but returns the signature as a base64 encoded …
=> keypair: add SignBase64 that returns signatures strings

services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/offer.go, services/horizon/internal/actions/offer_test.go, services/horizon/internal/actions/query_params.go, services/horizon/internal/actions/query_params_test.go, services/horizon/internal/actions_root_test.go, services/horizon/internal/docs/reference/endpoints/offers.md
<details>
otherwise).
packages.
</details>
Extend the offer end-point to support filtering using the canonical representation of an asset in the `selling` and `buying` query parameter.
Fix #2225.
Using `native` for Lumens or `AssetCode:AssetIssuer` for issued, brings a better …
=> services/horizon/internal: Support filtering offers by `buying` or `selling`.

keypair/full.go
<details>
otherwise).
packages.
</details>
Remove unnecessary cast of a `[]byte` to an `xdr.Signature` in the `keypair` packages `Sign` function.
The value is already a `[]byte` and doesn't need to be converted to an `xdr.Signature` and back to a `[]byte` again. The unnecessary …
=> keypair: remove unnecessary cast

go.list, go.mod, go.sum, support/http/httpdecode/httpdecode.go, support/http/httpdecode/httpdecode_test.go
<details>
otherwise).
packages.
</details>
Add decoding of path parameters from requests into structs to the `httpdecode` package in a new `DecodePath` function and into the existing `Decode` function.
We use httpdecode to decode requests into structs and this works really well …
=> support/http/httpdecode: add decoding of path params

services/horizon/CHANGELOG.md, services/horizon/cmd/root.go, services/horizon/internal/app.go, services/horizon/internal/config.go, services/horizon/internal/docs/reference/endpoints/metrics.md, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
This commit moves `/metrics` endpoint to the new internal server running on `INTERNAL_PORT`.
After reviewing metrics exposed in `/metrics` it seems that none of the values should be exposed publicly. It will also allow us to expose more …
=> services/horizon: Move /metrics to internal server

protocols/horizon/main.go, services/horizon/internal/actions_metrics.go, services/horizon/internal/expingest/verify.go, services/horizon/internal/resourceadapter/root.go
This commit fixes misc issues connected to `/metrics`:
* Fix metrics name to follow Prometheus metric name convention (thanks @jacekn).
* Remove `/metrics` from root resource `_links`. (fix #2268)
* Update `state_verify` metrics only when state was fully checked.
=> services/horizon: Fix misc /metrics issues

services/horizon/internal/expingest/processors_runner.go
<details>
otherwise).
packages.
</details>
This commit fixes the return value in `ProcessorRunner.RunOrderBookProcessorOnLedger`.
The value of `changeStats.GetResults()` was calculated before running the processors (`s.runChangeProcessorOnLedger` call) so all the stats were equal …
=> /services/horizon: Fix stats return value in RunOrderBookProcessorOnLedger

services/horizon/internal/actions/query_params_test.go
<details>
otherwise).
packages.
</details>
Add a regression test to make sure we validate selilng and buying via
validation tags.
This can help us catch regressions. For example, someone removes or
edits the validation tag by mistake.
=> services/horizon/internal: Add test for invalid buying/selling asset.

services/horizon/internal/expingest/group_processors_test.go
<details>
otherwise).
packages.
</details>
Add test for group processors. Fix #2262.
We want to expand our test coverage at least to 80%.
[TODO or N/A]
=> services/horizon/internal/expingest: Add group processors test

exp/ingest/io/stats_change_processor.go, exp/ingest/io/stats_ledger_transaction_processor.go, exp/ingest/io/stats_ledger_transaction_processor_test.go, services/horizon/internal/expingest/fsm.go, services/horizon/internal/expingest/ingest_history_range_state_test.go, services/horizon/internal/expingest/main_test.go, services/horizon/internal/expingest/processors_runner.go, services/horizon/internal/expingest/resume_state_test.go, services/horizon/internal/expingest/stress_test.go, services/horizon/internal/expingest/verify_range_state_test.go
<details>
otherwise).
packages.
</details>
This commit adds `exp/ingest/io.StatsLedgerTransactionProcessor` struct responsible for reporting transactions stats and adds it to Horizon processors.
Close #2208
Transaction stats are essential to understanding possible performance …
=> exp/ingest/io: Add StatsLedgerTransactionProcessor

services/horizon/internal/init.go, services/horizon/internal/txsub/results/db/main.go, services/horizon/internal/txsub/results/db/main_test.go
<details>
otherwise).
packages.
</details>
Skip checking Stellar-Core DB for transaction results if Horizon is ingesting failed transactions.
Due to a delay between Stellar-Core closing a ledger and Horizon ingesting it, it's possible that results of transaction submitted to …
=> services/horizon/txsub: Skip checking Core DB if Horizon is ingesting failed txs

txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Remove superfluous signing key in challenge transaction test that is used to sign the transaction twice when it only needs to sign the transaction once.
The key is added twice which was probably the result of a copy and paste from …
=> txnbuild: remove superfluous signing key in challenge txn test

exp/services/webauth/cmd/genjwtkey.go, exp/services/webauth/cmd/serve.go, exp/services/webauth/main.go
<details>
otherwise).
packages.
</details>
Rename the `exp/services/webauth/internal/commands` package to `exp/services/webauth/cmd`.
The cobra commands for the `webauth` app live in the `internal/commands` package but we have a couple apps that are using the convention to put …
=> exp/services/webauth: rename commands package to cmd

exp/orderbook/graph.go, services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/mock_orderbook_graph.go, services/horizon/internal/expingest/processor_runner.go, services/horizon/internal/expingest/processor_runner_test.go, services/horizon/internal/expingest/processors/new_orderbook_processor.go, tools/horizon-cmp/history.go
<details>
otherwise).
packages.
</details>
This commit is adding tests to `ProcessorRunner`.
=> services/horizon/expingest: ProcessorRunner tests

services/horizon/CHANGELOG.md, services/horizon/cmd/root.go, services/horizon/internal/app.go, services/horizon/internal/config.go, services/horizon/internal/docs/reference/endpoints/metrics.md
<details>
otherwise).
packages.
</details>
This commit changes `INTERNAL_PORT` to `ADMIN_PORT`.
The previous config name was confusing, ex. it could suggest that internal server is started on loopback interface only.
=> services/horizon: Change INTERNAL_PORT to ADMIN_PORT

tools/horizon-cmp/internal/response.go, tools/horizon-cmp/main.go
<details>
otherwise).
packages.
</details>
This commit queues a path to retry later when `Latest-Ledger` header is not equal.
If `Latest-Ledger` is not equal horizon-cmp can report the given path even though it's fine if responses are not equal.
Close #2017.
=> tools/horizon-cmp: Retry on Latest-Ledger header mismatch

services/horizon/internal/init.go, services/horizon/internal/txsub/results/db/main.go, services/horizon/internal/txsub/results/db/main_test.go
<details>
otherwise).
packages.
</details>
This commit fixes a bug introduced in https://github.com/stellar/go/pull/2277. It adds `core.Q` back to `txsub/results.DB` and uses a new `SkipCoreChecks` fields to decide if core DB should be used or not.
`core.Q` is also needed to …
=> services/horizon/txsub: Use CoreDB for SequenceProvider

services/horizon/cmd/root.go
This commit changes the default value of `max-path-length` to `3`.
=> services/horizon: Change default of max-path-length to 3

clients/horizonclient/client.go, clients/horizonclient/main_test.go
<details>
otherwise).
packages.
</details>
Make the client compatible with fee stats data from Horizon 1.X or 0.X.
There are a couple of breaking changes in the Horizon response which we are handling in horizonclient 2.0 in a backward compatibility manner, for example, being able …
=> Backfill fee stats data to make the  client compatible with horizon 1.X and 0.X.

keypair/from_address.go
<details>
otherwise).
packages.
</details>
Add check that FromAddress implements encoding.Unmarshaler.
We check that it implements Marshaler, but not Unmarshaler, and we have
it implementing both so it is worthwhile adding the check to ensure if
we were cause the type to not …
=> keypair: add check that FromAddress implements encoding.Unmarshaler

services/horizon/docker/docker-compose.yml
<details>
otherwise).
packages.
</details>
Fix the authentication of the Horizon container against the Postgres Horizon container at
`services/horizon/docker/docker-compose.yml`.
By not pinning the full Postgres version, authentication stopped working since now it requires either …
=> services/horizon: Fix docker-compose Postgres' auth

services/horizon/cmd/root.go
Makes an error message about empty `--history-archive-urls` explicit.
The previous message was not clear enough:
```
error creating history archive: URL is empty
```
The new message is as follows:
```
--history-archive-urls must be set when --ingest is set
```
=> services/horizon: Check for --history-archive-urls flag when --ingest set

clients/horizonclient/client.go, clients/horizonclient/examples_test.go, clients/horizonclient/main.go, clients/horizonclient/main_test.go, clients/horizonclient/mocks.go, clients/horizonclient/offer_request.go, clients/horizonclient/offer_request_test.go
<details>
otherwise).
packages.
</details>
Extend horizonclient with offer details support - `client.OfferDetails("1234")`.
Now you can fetch the details for a single offer, this will allow you to use that new end-point.
[TODO or N/A]
=> clients/horizon:  Extend client with Offer details support

exp/tools/dump-ledger-state/main.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2188
> The dump ledger state job in exp/tools/dump-ledger-state is commented out because it uses the previous ingestion pipelines and sessions. We should rewrite this job to use the new …
=> exp/tools/dump-ledger-state: Rewrite dump ledger state job to use new ingestion design

exp/services/webauth/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Set the Horizon timeout to 1 minute for both the HTTP client and the horizonclient SDK.
While it looks like the same timeout is being used by the HTTP client and the horizonclient SDK it is not. The horizonclient SDK uses units of …
=> exp/services/webauth: fix the horizon timeout

exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Set the Horizon timeout to 1 minute for both the HTTP client and the horizonclient SDK.
While it looks like the same timeout is being used by the HTTP client and the horizonclient SDK it is not. The horizonclient SDK uses units of …
=> exp/services/recoverysigner: fix the horizon timeout

exp/services/recoverysigner/internal/serve/serve.go, exp/services/webauth/internal/serve/serve.go, services/bridge/main.go, services/compliance/main.go, services/federation/main.go, services/friendbot/main.go, support/http/logging_middleware.go, support/http/logging_middleware_test.go, support/http/mux.go, support/render/health/example_test.go
<details>
otherwise).
packages.
</details>
Allow services to specify the logger used by the logging middleware.
`LoggingMiddleware` gets the logger from the context using `"support/log".Ctx(...)`. If none is specified in the context the `"support/log".DefaultLogger` is used. …
=> support/http: allow services to specify the logger used by the logging middleware

services/horizon/internal/web.go
closes #2315
~**do not merge yet**~
=> services/horizon: expose date header

services/ticker/internal/scraper/asset_scraper.go, services/ticker/internal/scraper/asset_scraper_test.go
Ensure the Ticker can gracefully handle invalid TOML urls.
This PR fixes #2326. We were missing an error check after creating an HTTP request to catch invalid URLs / requests.
=> services/ticker: handle invalid TOML urls gracefully

exp/services/recoverysigner/internal/account/account.go, exp/services/recoverysigner/internal/account/account_test.go, exp/services/recoverysigner/internal/serve/account_list.go, exp/services/recoverysigner/internal/serve/account_list_test.go, exp/services/recoverysigner/internal/serve/account_post.go, exp/services/recoverysigner/internal/serve/account_post_test.go, exp/services/recoverysigner/internal/serve/account_response.go
<details>
otherwise).
packages.
</details>
Remove the `type` parameter stored alongside registered accounts and replace it with exposing information about which identities are set on an account to clients.
Remove the `type` request and response parameters. Add the `identities` …
=> exp/services/recoverysigner: remove type, add identities

clients/horizonclient/error_helpers.go, clients/horizonclient/error_helpers_test.go
This PR adds a helper function `GetError` to check whether if an error can be interpreted as a horizon-related error. If it can't, a nil error is returned.
People who use `horizonclient` to submit a transaction often need to check the error returned and look into what the problem is when something went wrong. However, there are two types of errors that can be returned by this package, one is Error, and the other is `*Error`. This function function makes it convenient to always get back a `*Error` even if the input is `Error`.
N/A
=> horizonclient: add GetError func for retrieving a horizon error

exp/services/recoverysigner/internal/serve/account_sign.go, exp/services/recoverysigner/internal/serve/account_sign_test.go
<details>
otherwise).
packages.
</details>
Rename response field `public_key` to `signer` for the
`/accounts/<account-id>/sign` endpoint.
The `public_key` field contains the address of the signer that has
generated the signature. Elsewhere in the API we use the term `signer`
for …
=> exp/services/recoverysigner: rename public_key to signer

.circleci/config.yml, DEVELOPING.md, Dockerfile, README.md, clients/horizonclient/README.md, go.mod, services/horizon/internal/docs/admin.md, services/horizon/internal/docs/developing.md, services/horizon/internal/web.go, services/ticker/docker/Dockerfile-dev, services/ticker/internal/scraper/asset_scraper_test.go, staticcheck.sh, txnbuild/README.md
<details>
otherwise).
packages.
</details>
Add Go 1.14, deprecate Go 1.12.
Go 1.14 was released yesterday. We support the last two versions of Go. With the release of 1.14, 1.12 becomes an unsupported version of Go and the Go team will no longer ship security patches to it.
For …
=> all: add Go 1.14, deprecate Go 1.12

exp/services/recoverysigner/internal/serve/account_post_test.go, exp/services/recoverysigner/internal/serve/account_sign_test.go
<details>
otherwise).
packages.
</details>
Add tests that test that form url-encoded requests are supported.
The application is intended to support both form url-encoded and JSON request bodies, and actually does support it because our `support/http/httpdecode` package supports …
=> exp/services/recoverysigner: add form url-encoded tests

services/horizon/CHANGELOG.md, services/horizon/cmd/db.go, services/horizon/internal/reap/main.go, services/horizon/internal/reap/system.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/2307
When the db reap command is called, `ledger.CurrentState()` returns an uninitialized struct where the latest history ledger sequence is set to 0. Consequently, the reap system always …
=> Fix horizon db reap command

clients/horizonclient/CHANGELOG.md, services/bridge/CHANGELOG.md, services/compliance/CHANGELOG.md, services/federation/CHANGELOG.md, services/horizon/CHANGELOG.md, services/keystore/CHANGELOG.md, services/ticker/CHANGELOG.md, tools/stellar-archivist/CHANGELOG.md, tools/stellar-hd-wallet/CHANGELOG.md, tools/stellar-sign/CHANGELOG.md, tools/stellar-vanity-gen/CHANGELOG.md, txnbuild/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update all CHANGELOG.md's mentioning that Go 1.12 support has been
dropped.
I dropped Go 1.12 support in #2325 but I overlooked adding a note to the
changelogs.
N/A
=> doc: update changelogs with drop of Go 1.12 support

clients/horizonclient/CHANGELOG.md, clients/horizonclient/client.go, clients/horizonclient/examples_test.go, clients/horizonclient/main.go, exp/services/recoverysigner/internal/serve/serve.go, exp/services/webauth/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Remove HorizonTimeOut and its related functions and fields that operate
on a value of seconds and replace with HorizonTimeout that operates on a
value of nanoseconds.
The HorizonTimeOut identifier is defined as a time.Duration, and by …
=> clients/horizonclient: fix inconsistent units of time in HorizonTimeOut 

services/horizon/docker/docker-compose.yml
Followup from https://github.com/stellar/go/pull/2306
Running `docker/start.sh` led to error `--history-archive-urls must be set when --ingest is set`
=> services/horizon: Add HISTORY_ARCHIVE_URLS to docker-compose

exp/services/recoverysigner/docker/Dockerfile, exp/services/webauth/docker/Dockerfile, services/horizon/docker/Dockerfile, services/keystore/docker/Dockerfile, services/ticker/docker/Dockerfile
<details>
otherwise).
packages.
</details>
Use Go 1.14 for building in docker images.
We recently switched to building with Go 1.13 and 1.14 in #2325 and we should use the latest version for our builds.
N/A
=> all: use Go 1.14 for building in docker images

Gemfile.lock
<details>
otherwise).
packages.
</details>
Update versions of rake from 12.3.1 to 13.0.1.
CVE-2020-8130 outlines that there is an OS command injection vulnerability in Ruby Rake before 12.3.3 in Rake::FileList when supplying a filename that begins with the pipe character |.
I …
=> all: update version of rake from 12.3.1 to 13.0.1

services/horizon/internal/expingest/processors/effects_processor.go, services/horizon/internal/expingest/processors/effects_processor_test.go
<details>
otherwise).
packages.
</details>
Don't show signer update effect if weight didn't change (fix #2136).
As described in #2136, we were showing a signer update effect even when the weight wasn't changing. This adds a check and if the weight changed, then include the …
=> services/horizon/internal/expingest: Fix signer update effects.

services/ticker/internal/utils/main.go
This PR fixes #2361 – see original issue for further context.
=> services/ticker: update *.json files atomically

services/horizon/internal/actions/account.go, services/horizon/internal/handler.go, services/horizon/internal/stream_handler_test.go, support/db/main.go, support/db/mock_session.go
<details>
otherwise).
packages.
</details>
* Execute SSE handlers in repeatable read transactions
* Obtain account info from stellar core db using repeatable read transaction 
Close https://github.com/stellar/go/issues/2331
> I noticed Some extra balances error in /accounts/{id} …
=> services/horizon/internal/actions: Wrap SSE handlers in repeatable read tx

support/db/dbtest/db.go
<details>
otherwise).
packages.
</details>
Log the name of the database in use for the each test.
We can add logs to tests to make the self describe what they are
testing. The logs are only visible when the test is run in verbose mode,
or when the test fails. Each test that uses …
=> support/db/dbtest: log the name of the database in use for the each test

README.md
Update the URL for the Stellar logo image displayed at the top of the
README.
A new version of the stellar.org website was deployed and the image we
were using is no longer available there. In stellar/.github#9 we added
the logo to a GitHub repository so that we could reference it from one
location that won't be affected by website changes.
=> doc: fix Stellar logo image

services/bridge/internal/db/bindata.go, services/bridge/internal/db/main.go, services/compliance/internal/db/bindata.go, services/compliance/internal/db/main.go, services/horizon/internal/db2/schema/bindata.go, services/horizon/internal/db2/schema/main.go, services/horizon/internal/test/scenarios/bindata.go, services/horizon/internal/test/scenarios/main.go, services/ticker/internal/gql/static/bindata.go, services/ticker/internal/gql/static/schema.go, services/ticker/internal/tickerdb/main.go, services/ticker/internal/tickerdb/migrations/bindata.go
<details>
otherwise).
packages.
</details>
Disable including file metadata in Go files that are generated using
the go-bindata tool.
The go-bindata tool takes files and puts them into Go files so that our
applications can be compiled with all their dependency files built
within …
=> all: make migration go-bindata files stable

.circleci/config.yml, gogenerate.sh
<details>
otherwise).
packages.
</details>
Run `go generate` during ci builds.
We use `go generate` to trigger builds of our bindata files for SQL
migrations but we don't have any broad checks on CI that ensure that the
generated files are up to date. This ensures whenever we …
=> all: run go generate during ci builds to check all files updated

services/horizon/internal/expingest/main.go, services/horizon/internal/expingest/main_test.go
<details>
otherwise).
packages.
</details>
Ignore db.ErrCanceled and ctx.Canceled returned by verifyState.
Fix #2224
If the system is shutdown during state verification, there is a warning inthe log showing
``` WARN[2020-02-04T18:14:19.987+01:00] State verification errored …
```
=> services/horizon: Ignore db.ErrCanceled and ctx.Canceled returned by verifyState.

services/horizon/internal/actions/account_test.go, services/horizon/internal/actions/asset_test.go, services/horizon/internal/db2/history/account.go, services/horizon/internal/db2/history/account_test.go, services/horizon/internal/db2/history/accounts.go, services/horizon/internal/db2/history/accounts_batch_insert_builder.go, services/horizon/internal/db2/history/accounts_test.go, services/horizon/internal/db2/history/asset.go, services/horizon/internal/db2/history/asset_test.go, services/horizon/internal/db2/history/main.go, services/horizon/internal/db2/history/trade.go, services/horizon/internal/db2/history/trade_test.go, services/horizon/internal/expingest/fsm.go, services/horizon/internal/expingest/ingest_history_range_state_test.go, services/horizon/internal/test/trades/main.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2370
* Remove database functions which were previously used by legacy ingestion but now are unused
* Sort assets before inserting rows into `history_assets` 
* Sort accounts before inserting …
=> services/horizon/internal/db2/history: Mitigate deadlock when running reingest range

exp/services/recoverysigner/cmd/db.go, exp/services/recoverysigner/cmd/db_test.go
<details>
otherwise).
packages.
</details>
Disallow the recoverysigner's `db migrate [up|down] [count]` command with a zero (`0`) count.
If you pass zero as the count value to the command the command will run all possible migrations up or down. This isn't intuitive even though …
=> exp/services/recoverysigner: disallow db migrate with a zero count

exp/services/recoverysigner/cmd/db.go, exp/services/recoverysigner/cmd/db_test.go
<details>
otherwise).
packages.
</details>
Change the error outputted when an invalid value is provided to the
recoverysigner's `db migrate [up|down] [count]` command as hte count
value from:
```
Invalid migration count, must be a number or not provided.
```
To:
```
Invalid …
```
=> exp/services/recoverysigner: make the db migrate invalid count error simpler

exp/services/recoverysigner/internal/account/account.go, exp/services/recoverysigner/internal/serve/account_post.go, exp/services/recoverysigner/internal/serve/account_post_test.go
<details>
otherwise).
packages.
</details>
Add some validations to the account post endpoint request body:
- Require at least one identity.
- Require a value for the `role` field.
- Require at least one authentication method for each identity.
The change also updates the …
=> exp/services/recoverysigner: add validations for account post endpoint role, identities and auth methods

exp/orderbook/edges.go, exp/orderbook/graph.go, exp/orderbook/graph_test.go, services/horizon/CHANGELOG.md, services/horizon/internal/actions/orderbook.go, services/horizon/internal/actions/orderbook_test.go, xdr/price.go, xdr/price_test.go
<details>
otherwise).
packages.
</details>
Fixes #2010 
Due to the non-canonical rational representation of offer prices, they were not being compared properly in a bunch of places, leading to an incorrect result of `GET order_book` (the `limit`
parameter wasn't respected and …
=> services/horizon: Gracefully handle non-canonical prices in GET /order_book

services/horizon/cmd/root.go
<details>
otherwise).
packages.
</details>
Followup from #2409 (see https://github.com/stellar/go/pull/2409#discussion_r397416598 )
To be merged into master in a later PR
=> services/horizon: Add machine-readable comment for Redis flag removal

.circleci/config.yml, support/db/dbtest/db.go, support/db/dbtest/postgres_test.go
<details>
otherwise).
packages.
</details>
Run tests on Postgres v10 and add function to `support/db/dbtest` that exposes the current version of Postgres that's running.
Recoverysigner (`exp/services/recoverysigner`) is going to be using the IDENTITY feature of Postgres that was …
=> all: run tests on postgres v10

exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Correct which value is included in the log line that is outputting the
database error, so that we're printing the database error and not some
prior error.
Looks like we're printing the wrong error. We're printing `err`, but
`dbErr` is …
=> exp/services/recoverysigner: fix db error logged

go.mod, services/horizon/cmd/db.go, services/horizon/cmd/root.go, support/config/config_option.go, support/config/config_option_test.go
<details>
otherwise).
packages.
</details>
Allow multiple flags to be defined with the same name that are attached to different commands.
Cobra allows the definition of flags on different commands that have the same name. There can be good reasons to do this like two subcommands …
=> support/config: allow multiple flags to be defined with the same name across commands

services/horizon/docker/verify-range/start
<details>
otherwise).
packages.
</details>
Update verify-range to use Horizon 1.0.0 as the base. We'll use a special branch with ingestion related changes cherry-picked into it. 
Fix #2389 
Now that we have 2 release of Horizon 1.0.0, we can move to Horizon 1.0.0 as the base. …
=> services/horizon/docker: Update verify-range to use 1.0.0 as base.

tools/horizon-cmp/internal/response.go
<details>
otherwise).
packages.
</details>
Remove fields added in Horizon 1.1.0 to avoid false positives.
Horizon 1.1.0 adds a couple of new fields, if we were to run horizon-cmp  between 1.0.1 and 1.1.0, then we'll get failures on new fields. 
[TODO or N/A]
=> tools/horizon-cmp: Remove fields added in Horizon 1.1.0

services/horizon/internal/resourceadapter/root.go
Followup to #2407 
It fixes a problem found by @JakeUrban , see https://github.com/stellar/go/issues/2402#issuecomment-608014439
Fixes #2402
=> services/horizon: Fix typo in GET /ledger(s) hal link

services/horizon/CHANGELOG.md, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
In https://github.com/stellar/go/pull/2416 we extended the Last-Ledger header to cover additional endpoints which were not immutable.
@2opremio raised the following point before working on the PR:
> After giving this quite a bit of …
=> services/horizon/internal: Only use repeatable read transactions on state endpoints

exp/services/recoverysigner/cmd/serve.go, exp/services/recoverysigner/internal/serve/account_post.go, exp/services/recoverysigner/internal/serve/serve.go
Remove HorizonClient field from accountPostHandler
It is unused.
=> exp/recoverysigner: remove HorizonClient from accountPostHandler

services/horizon/docker/README.md, services/horizon/docker/core-start.sh, services/horizon/docker/docker-compose.standalone.yml, services/horizon/docker/docker-compose.yml
<details>
otherwise).
packages.
</details>
When you start Stellar Core in standalone mode it defaults to generating ledgers with protocol version equal to 0.
To upgrade the Stellar Core protocol version you need to run an "upgrades" command: …
=> services/horizon/docker: Upgrade Stellar Core docker container to protocol 13

support/http/httpdecode/httpdecode.go, support/http/httpdecode/httpdecode_test.go
Check request body before calling DecodeJSON in `Decode`.
`Decode` calls `DecodePath`, `DecodeQuery`, and `DecodeJSON` unconditionally. However, GET requests don't usually have a request body, so calling `DecodeJSON` is problematic since it uses the request body for unmarshaling. This PR simply adds a check before calling `DecodeJSON`.
N/A
=> support/httpdecode: avoid calling DecodeJSON for GET requests

support/http/httpdecode/httpdecode.go, support/http/httpdecode/httpdecode_test.go
Add a check for `http.NoBody` before calling `DecodeJSON`.
`For server requests, the Request Body is always non-nil but will return EOF immediately when no body is present.`. We use `httptest.NewRequest` extensively throughout the codebase for testing, and that function returns a serve request with non-nil body. Without this change, use the request returned from `httptest.NewRequest` as a param of `Decode` or `DecodeJSON` will cause the `EOF` error.
N/A
=> support/httpdecode: check for http.NoBody before calling DecodeJSON

services/horizon/internal/handler.go, services/horizon/internal/ledger/ledger_source.go, services/horizon/internal/stream_handler_test.go
<details>
otherwise).
packages.
</details>
Fix flakiness in `TestRepeatableReadStream/page_stream_creates_repeatable_read_tx`  (see https://github.com/stellar/go/pull/2460#issuecomment-610072451)
=> services/horizon/internal: Fix stream handler tests

services/horizon/CHANGELOG.md
Horizon 1.1 changelog improvements, copied from shared markdown editing session.
1. Group similar changes
2. Motivate and emphasise importance of DB migration
3. Add PR links to all changes
N/A
=> Horizon 1.1 changelog cleanup

exp/services/recoverysigner/internal/serve/account_get.go, exp/services/recoverysigner/internal/serve/account_get_test.go, exp/services/recoverysigner/internal/serve/errors.go, exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
This PR adds GET /accounts/{address} endpoint specified in the [spec](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0030.md#get-accountsaddress). This PR also adds `notPermitted` error for the case where a user is authenticated, but her credential does not match any of the identities in the requested account. 
This PR implements the missing endpoint.
N/A
=> exp/recoverysigner: add GET /accounts/{address} endpoint

services/horizon/internal/db2/history/mock_q_accounts.go, services/horizon/internal/expingest/verify_range_state_test.go
<details>
otherwise).
packages.
</details>
Addresses part of #2264 
There isn't full coverage yet (I left a TODO), but accounts and offers are now tested.
This increases the coverage of verify.go to 60% from 9% .
=> services/horizon: Improve testing of verify.go

exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Remove use of dbErr in code that is no longer nested.
In one of the `if dbErr != nil` blocks we are calling `errors.Wrap(err, ...)` when we should be calling `errors.Wrap(dbErr, ...)`. We have `dbErr` in this code because this code used …
=> exp/services/recoverysigner: fix incorrect error wrapped

exp/services/webauth/README.md, exp/services/webauth/cmd/convjwt2jwk.go, exp/services/webauth/cmd/convjwtkey.go, exp/services/webauth/cmd/genjwk.go, exp/services/webauth/cmd/genjwtkey.go, exp/services/webauth/cmd/serve.go, exp/services/webauth/internal/serve/serve.go, exp/services/webauth/internal/serve/token.go, exp/services/webauth/internal/serve/token_test.go, exp/services/webauth/main.go, go.list, go.mod, go.sum
<details>
otherwise).
packages.
</details>
Change to using the JSON Web Key (JWK) format for configuring the JWK key used by the webauth service to sign JWTs.
The JSON Web Key (JWK) format is defined in [RFC7517] and makes it easy to configure a web service in a standard way …
=> exp/services/webauth: change JWT key config option to a JWK

services/ticker/internal/actions_asset.go
<details>
otherwise).
packages.
</details>
Reduce the number of parallel requests to fetch `stellar.toml` files.
This is mostly empirical, but with `parallelism = 500,` I've noticed fetching `stellar.toml` files for some assets is always timing out (probably because the requests …
=> services/ticker: reduce parallelism on asset ingestion

services/horizon/internal/docs/readme.md, services/horizon/internal/docs/reference/readme.md
Evil Martians (https://github.com/astroband/) have now taken ownership of the Ruby SDK. Update links to point at the [new repo location](https://github.com/astroband/ruby-stellar-sdk).
Note: this content is duplicated in these files and also in the docs repo (https://github.com/stellar/docs/pull/565). For now I'm just fixing the links, but there's a need to do a pass over all these docs once the new SDK site is live and remove the redundancy.
=> change Ruby SDK links to point to new astroband org

exp/services/recoverysigner/internal/serve/account_post_test.go
This PR removes an obsolete field `type` used in our account memory store prototype in the post requests in testing.
This makes the code read better. Reading test files is a good way to understand how the system behaves, so making it clear can boost the readability of our code base.
N/A
=> exp/recoverysigner/serve: remove obsolete request field

exp/services/recoverysigner/internal/account/db_store_delete.go
This PR adds comments to explain the ON DETETE CASCADE effect when deleting an account to avoid confusion.
Make the code more readable.
N/A
=> exp/recoverysigner/account: add comments for the cascade delete

exp/services/recoverysigner/internal/serve/auth/sep10.go, exp/services/recoverysigner/internal/serve/auth/sep10_test.go
<details>
otherwise).
packages.
</details>
Add validation that SEP-10 JWTs contain an `exp` and `iat` field.
To ensure if there was ever an upstream issue with the generation of JWTs and a field was missing but the JWT was otherwise valid, we'd disregard the JWT since it's …
=> exp/services/recoverysigner: add JWT exp, iat as required

exp/services/recoverysigner/internal/serve/auth/sep10.go, exp/services/recoverysigner/internal/serve/auth/sep10_test.go
<details>
otherwise).
packages.
</details>
Add tests for JWT confirming if the `sub` field is missing or invalid it will be considered invalid.
We had a TODO in the code to add the check, but the code already does the check we were just missing tests. The code lives in another …
=> exp/services/recoverysigner: add tests for JWT confirming if sub is missing or invalid it will be considered invalid

exp/services/recoverysigner/cmd/serve.go, exp/services/recoverysigner/internal/serve/auth/sep10.go, exp/services/recoverysigner/internal/serve/auth/sep10_test.go, exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Validate JWT `iss` field has a specific value if the service is run with an expected value defined with the new `--sep10-jwt-issuer` (`SEP10_JWT_ISSUER`) config option.
In some setups it can be important to verify the issuer within the …
=> exp/services/recoverysigner: validate JWT iss field optionally has specific value

exp/services/recoverysigner/README.md, exp/services/recoverysigner/cmd/serve.go, exp/services/recoverysigner/internal/serve/serve.go, exp/services/recoverysigner/main.go
<details>
otherwise).
packages.
</details>
Change `SEP-XX` to `SEP-30` in the usage text of recoversigner.
The recoverysigner code was written before the SEP was assigned a number. It has a number now.
N/A
=> exp/services/recoverysigner: update SEP number in usage

network/main_test.go, services/horizon/internal/db2/history/fee_bump_scenario.go, services/horizon/internal/db2/history/transaction_batch_insert_builder.go, services/horizon/internal/db2/history/transaction_batch_insert_builder_test.go, services/horizon/internal/expingest/processors/participants_processor.go, services/horizon/internal/expingest/processors/participants_processor_test.go, services/horizon/internal/resourceadapter/transaction_test.go, xdr/Stellar-ledger.x, xdr/Stellar-overlay.x, xdr/Stellar-transaction.x, xdr/Stellar-types.x, xdr/transaction_envelope.go, xdr/transaction_envelope_test.go, xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
This PR updates the XDR definitions to match https://github.com/stellar/stellar-core/commit/b5dad7d2db7e2ad05e80a23a125569f70070b2d9 
The most significant update to the XDR definitions is that the `FeeSource` of a fee bump transaction is …
=> xdr: update xdr definitions

protocols/horizon/effects/main.go, services/horizon/internal/resourceadapter/balance.go, services/horizon/internal/resourceadapter/balance_test.go, services/horizon/internal/resourceadapter/effects_test.go
<details>
otherwise).
packages.
</details>
`EffectTrustlineAuthorizedToMaintainLiabilities` was configured to unmarshal into a `TrustlineAuthorized` instance.
We should be unmarshalling into a `TrustlineAuthorizedToMaintainLiabilities` instance.
=> protocols/horizon/effects: Fix unmarshalling of TrustlineAuthorizedToMaintainLiabilities

exp/services/recoverysigner/internal/serve/auth/firebase.go, exp/services/recoverysigner/internal/serve/auth/firebase_test.go
<details>
otherwise).
packages.
</details>
Require the `email_verified` field to be present in the JWT used for validating the email address of the authenticated client. Treat the a non-verified email as if the token does not satisfy the claim of owning the email.
If an email …
=> exp/services/recoverysigner: require email_verified true in email authenticated JWT

exp/services/recoverysigner/internal/account/db_store_update.go, exp/services/recoverysigner/internal/account/db_store_update_test.go, exp/services/recoverysigner/internal/account/store.go, exp/services/recoverysigner/internal/serve/account_put.go, exp/services/recoverysigner/internal/serve/account_put_test.go, exp/services/recoverysigner/internal/serve/serve.go
This PR implements the PUT /accounts/{address} endpoint specified [here](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0030.md#put-accountsaddress).
Note that this endpoint replaces the original identities with the identities provided in the request, and not merged.
`db_store_update.go` and its test file are added to support this PR.
Though 996+, 1- seems intimidating, 777+ of it are for testing.
This PR adds the final endpoint in the spec that is not yet implemented.
N/A
Close https://github.com/stellar/go/issues/2340
=> exp/recoverysigner: add PUT /accounts/{address} endpoint

services/horizon/docker/README.md
The documentation stated that the root account seed was configured with the `NODE_SEED` variable in the stellar core config. That is incorrect. The `NODE_SEED` variable configures the seed for the validator account. The root account which holds the lumen supply is derived from the network passphrase and is printed in the stellar core logs.
=> services/horizon/docker: Fix documentation for running stand alone network

protocols/horizon/main.go, protocols/horizon/main_test.go, services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
This PR fixes a problem similar to https://github.com/stellar/go/issues/149: `memo_bytes` was not present in transaction response for empty string memo.
=> protocols/horizon: Display memo_bytes even when memo text is an empty string

tools/horizon-cmp/internal/response.go
<details>
otherwise).
packages.
</details>
Remove new field "memo_bytes"
It was introduced in horizon 1.2, causing false positives in horizon-cmp when comparing the out of requests with that of horizon 1.1
N/A
=> Update horizon-cmp for 1.2 release

services/horizon/internal/actions/account.go, services/horizon/internal/actions/account_test.go, services/horizon/internal/db2/history/trust_lines.go, services/horizon/internal/db2/history/trust_lines_test.go
<details>
otherwise).
packages.
</details>
When obtaining trustlines from the DB, for rendering into the `GET /accounts` endpoint, order them by asset code (and issuer) so that the output is stable (postgres doesn't guarantee a consistent ordering).
`horizon-cmp` outputs a large …
=> services/horizon: Sort trustlines by asset code and issuer

protocols/horizon/effects/main.go, protocols/horizon/main.go, protocols/horizon/main_test.go, services/horizon/CHANGELOG.md, services/horizon/internal/resourceadapter/balance.go, services/horizon/internal/resourceadapter/balance_test.go, services/horizon/internal/resourceadapter/effects_test.go, tools/horizon-cmp/internal/response.go
Earlier I merged the horizon 1.2.0 release branch into the v3 horizonclient release branch: https://github.com/stellar/go/pull/2493.
Since then there have been a few commits that were added to the horizon 1.2.0 release. This PR adds all remaining commits from horizon 1.2.0 into the horizonclient release branch.
=> horizonclient: Merge remaining horizon 1.2.0 commits

clients/horizonclient/examples_test.go, clients/horizonclient/main_test.go, exp/services/recoverysigner/internal/serve/account_sign.go, exp/services/recoverysigner/internal/serve/account_sign_test.go, txnbuild/fee_bump_test.go, txnbuild/transaction.go, txnbuild/transaction_test.go
When I was working on https://github.com/stellar/go/pull/2495 I originally named the `Transaction` type as `SimpleTransaction`.
I eventually changed the name of the struct but I forgot to change the name of the Simple() function.
=> txnbuild: Rename Simple() function to Transaction()

clients/horizonclient/client.go, clients/horizonclient/main_test.go, txnbuild/account_merge.go, txnbuild/account_merge_test.go, txnbuild/helpers.go, txnbuild/path_payment.go, txnbuild/path_payment_strict_send.go, txnbuild/path_payment_strict_send_test.go, txnbuild/path_payment_test.go, txnbuild/payment.go, txnbuild/payment_test.go
<details>
otherwise).
packages.
</details>
Update SEP29 implementation to skip checks on muxed account addresses which contain a memo id.
We should skip the check if the destination is an M address since M addresses essentially encode a memo within them.
[N/A]
=> horizonclient: Update SEP29 implementation to skip checks on memo id destinations

support/http/logging_middleware.go, support/http/logging_middleware_test.go
<details>
otherwise).
packages.
</details>
Propagate the request ID to the requests context logger making the request ID show up in all logs for a request.
For every request we receive in Friendbot, Webauth, Recoverysigner, and other applications are assigned a request ID which …
=> support/http: propagate request id to all logs

services/horizon/CHANGELOG.md, services/horizon/internal/db2/schema/bindata.go, services/horizon/internal/db2/schema/migrations/35_drop_participant_id.sql
<details>
otherwise).
packages.
</details>
Drop id columns from history_transaction_participants and history_operation_participants.
The id columns in the history_transaction_participants and history_operation_participants table are never used.
These columns are auto incremented …
=> services/horizon/internal/db2/schema: Drop participant id columns

services/horizon/CHANGELOG.md
Update CHANGELOG to include DB migration instructions.
=> Update Horizon v1.2.1 CHANGELOG

support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
Tweak the text returned when a HTTP 500 error occurs to stop encouraging users to create an issue at https://github.com/stellar/go
Prompting users to create GitHub issues has shown to add noise, particularly when the Horizon instances …
=> services/horizon: Tweak the copy of the 500-error problem

services/horizon/CHANGELOG.md, services/horizon/internal/ledger/ledger_source.go, services/horizon/internal/render/sse/stream_handler.go, services/horizon/internal/render/sse/stream_handler_test.go, services/horizon/internal/stream_handler_test.go, services/horizon/internal/web.go, txnbuild/README.md
<details>
otherwise).
packages.
</details>
This commit fixes a memory leak in `HistoryDBSource.NextLedger` method. The method is usually used like in `stream_handler.go`:
https://github.com/stellar/go/blob/00d7d2f8600e5389b20c3142b5b90550e9b75168/services/horizon/internal/render/s …
=> services/horizon/ledger: Fix memory leak in HistoryDBSource

services/horizon/internal/init.go, services/horizon/internal/txsub/system.go
<details>
otherwise).
packages.
</details>
Add metrics to track which types of transaction (v0, v1, or fee bump) Horizon is receiving.
Prior to protocol 13 there was only kind of transaction you could submit to Horizon. With these metrics we can monitor how many people actually …
=> services/horizon/internal/txsub: Add metrics to track which types of transaction Horizon is receiving

protocols/horizon/main.go, services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Marshall int64 MaxFee and FeeCharged fields as JSON strings
Javascript does not support 64 bit integers so to represent 64 bit values we need to represent them as strings.
[N/A]
=> protocols/horizon: Marshall int64 MaxFee and FeeCharged fields as JSON strings

services/horizon/internal/db2/history/transaction_batch_insert_builder.go
Fix for error:
```
Error running processors on ledger: Error streaming changes from ledger: could not process transaction 2: error in *processors.TransactionProcessor.ProcessTransaction: Error batch inserting transaction rows: invalid number of columns (expected=20, actual=24)
```
=> Fix TransactionBatchInsertBuilder

services/horizon/internal/expingest/fsm.go, services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
Log context cancelled errors using info level in the ingestion package.
These logs will help debug cases where ingestion is behaving unexpectedly.
[N/A]
=> services/horizon/internal/expingest: Log context cancelled errors using info level

services/horizon/internal/expingest/main.go, services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2018
Create separate db connections to the horizon and stellar core databases for ingestion.
> Currently, all of the Horizon services share the same DB connection pool. In case of increased …
=> services/horizon/internal: Create separate db connections for ingestion

exp/services/recoverysigner/internal/serve/account_delete.go, exp/services/recoverysigner/internal/serve/account_get.go, exp/services/recoverysigner/internal/serve/account_list.go, exp/services/recoverysigner/internal/serve/account_post.go, exp/services/recoverysigner/internal/serve/account_put.go, exp/services/recoverysigner/internal/serve/account_sign.go, exp/services/recoverysigner/internal/serve/auth/firebase.go, exp/services/recoverysigner/internal/serve/auth/sep10.go
<details>
otherwise).
packages.
</details>
Add basic logs for each action the service can perform that describe what's happening to help with identifying issues. Also fixes logs so that all existing logs carry the request ID and account ID for the current request.
This is a young …
=> exp/services/recoverysigner: add basic logs

txnbuild/CHANGELOG.md, txnbuild/manage_data.go, txnbuild/manage_data_test.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/2572
Fix bug which occurs when parsing transactions with manage data operations containing nil values.
It seems like this bug has been present in older versions of txnbuild. I ran the following …
=> txnbuild: Fix bug in parsing MangeData xdr operations

services/horizon/CHANGELOG.md, services/horizon/internal/actions/base.go
This is equivalent of #2548 but for the old actions code.
=> services/horizon: Fix memory leak in actions.Base.Execute

services/horizon/internal/docs/admin.md
<details>
otherwise).
packages.
</details>
Fixes #2561 
`horizon db backfill` doesn't exist anymore (it was removed in https://github.com/stellar/go/pull/2147 )
N/A
=> services/horizon/docs: Remove `db backfill` command from admin guide

txnbuild/transaction.go, txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
This PR adds `AddSignatureBase64` function to both `Transaction` object and `FeeBumpTransaction` object.
In JS SDK, there is [addSignature](https://stellar.github.io/js-stellar-sdk/Transaction.html#addSignature) function to add a base64 …
=> txnbuild: add AddSignatureBase64 function

services/horizon/internal/actions/account.go, services/horizon/internal/db2/history/trust_lines.go, services/horizon/internal/db2/history/trust_lines_test.go
<details>
otherwise).
packages.
</details>
Followup from #2516 , Fixes #2447 
#2516 sorts the balances for `GET /accounts` but not `GET /accounts/{id}`. This PR ties the loop.
`horizon-cmp` outputs a large amount of false positives because of this, plus it's always a good idea to …
=> services/horizon: Sort trustlines by asset code and issuer in `GET /acounts/{id}`

exp/ingest/ledgerbackend/captive_core_backend.go, exp/ingest/ledgerbackend/captive_core_backend_test.go, go.list, services/horizon/cmd/db.go, services/horizon/cmd/ingest.go, services/horizon/cmd/root.go, services/horizon/docker/Dockerfile, services/horizon/internal/config.go, services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/2584
* add `StellarCoreBinaryPath` to config which stores the path to the stellar core binary
* add `EnableCaptiveCoreIngestion` to config which is a feature flag for using the captive core …
=> services/horizon/cmd: Add configuration for captive core ingestion

services/federation/CHANGELOG.md, services/friendbot/CHANGELOG.md, support/http/logging_middleware.go, support/http/logging_middleware_test.go
<details>
otherwise).
packages.
</details>
Log the `User-Agent` header at request start.
Identifying which agent sent a request can be useful in the reference
implementations that accept inbound requests. It can be useful for
debugging strange issues, understanding broad usage …
=> support/http: log user agent header at request start

tools/horizon-cmp/internal/response.go
Summary:
* Remove `latest_modified_time` field (introduced for accounts in Horizon 1.3)
* Quote `fee_changed` and `max_fee` fields since Horizon 1.3 changed them to strings (from ints)
=> tools/horizon_cmp: Adapt horizon-cmp to Horizon 1.3

services/horizon/internal/actions.go, services/horizon/internal/actions/helpers.go, services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/operation.go, services/horizon/internal/actions/operation_test.go, services/horizon/internal/actions/validators.go, services/horizon/internal/actions/validators_test.go, services/horizon/internal/actions_operation.go, services/horizon/internal/actions_operation_test.go, services/horizon/internal/actions_payment_test.go, services/horizon/internal/db2/history/operation.go, services/horizon/internal/db2/history/operation_test.go, services/horizon/internal/handler.go, services/horizon/internal/helpers.go, services/horizon/internal/middleware.go, services/horizon/internal/middleware_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
Create a new action handler for fetching operations, using the new architecture for actions. 
We have different way to handle actions, as explained in #997 we want to use the same pattern across different routes to avoid code duplication …
=> services/horizon/internal: Move operations end-points to new actions architecture.

docs/reference/examples.md
Example was not working due changes to the sdk. Updated code to work with the recent changes to txnbuild.Transaction struct.
otherwise).
packages.
</details>
Fixing published basic example as it wasn't working with latest version (downloaded sdk on may 21, 2020)
The idea is to provide an updated example.
N/A
=> doc: Update basic example to use latest sdk version.

exp/ingest/io/single_ledger_state_reader_test.go, exp/ingest/ledgerbackend/captive_core_backend.go, exp/ingest/ledgerbackend/captive_core_backend_test.go, exp/ingest/ledgerbackend/stellar_core_runner.go, exp/ingest/ledgerbackend/stellar_core_runner_posix.go, exp/ingest/ledgerbackend/stellar_core_runner_windows.go, services/horizon/internal/expingest/ingest_history_range_state_test.go, services/horizon/internal/expingest/main_test.go, support/historyarchive/verify.go, support/historyarchive/xdrstream.go, support/historyarchive/xdrstream_test.go, xdr/main.go
<details>
otherwise).
packages.
</details>
This commit refactors `captiveStellarCore` ledger backend and adds tests.
Close #2585.
`stellarCoreRunner` has been extracted from `captiveStellarCore` to allow mocking stellar-core runs. This makes it possible to write tests that do not …
=> exp/ingest/ledgerbackend: Add captiveStellarCore tests

exp/orderbook/batch.go, exp/orderbook/graph_test.go, services/horizon/internal/app.go, services/horizon/internal/expingest/orderbook.go, services/horizon/internal/expingest/orderbook_test.go, services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Before https://github.com/stellar/go/pull/2639 we were updating the order book graph via ingestion on every single ledger. The order book graph was implemented with the expectation that you must apply changes for every single ledger and …
=> exp/orderbook: Allow updates to the order book graph which span multiple ledgers

services/horizon/internal/handler.go, services/horizon/internal/middleware.go, services/horizon/internal/stream_handler_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
This commit clones DB session for each history request that is using history middleware.
In https://github.com/stellar/go/pull/2597 operations handlers have been refactored to the new actions architecture. A new middleware used for …
=> services/horizon: Clone DB session for each history endpoint request

services/horizon/internal/init.go
Just passing the config allow us to start using captive on online mode. It seems to work fine but it's very slow.
=> Update prototype to run captive on online ingestion mode.

services/horizon/internal/middleware.go
<details>
otherwise).
packages.
</details>
Include request context when cloning session for request
The context of a db session is used to cancel a db query. When you set the context of the db session to the request context you ensure that if there are any db queries still …
=> services/horizon/internal: Include request context when cloning session for request

txnbuild/fee_bump_test.go, txnbuild/transaction.go
<details>
otherwise).
packages.
</details>
Currently when you try to create a fee bump transaction from a v0 transaction we return an error. This PR does not return an error and instead converts the v0 transaction to a v1 transaction before wrapping it with a fee bump …
=> txnbuild: Allow fee bump transactions to bump v0 transactions

txnbuild/CHANGELOG.md, txnbuild/signers_test.go, txnbuild/transaction.go
<details>
otherwise).
packages.
</details>
Add `ToXDR()` functions for `Transaction` and `FeeBumpTransaction` instances which return xdr transaction envelopes without errors.
The reason why `TxEnvelope()` returns an error is that it copies the internal transaction envelope by …
=> txnbuild: Add ToXDR functions which do not return errors

services/horizon/internal/expingest/orderbook.go, services/horizon/internal/expingest/orderbook_test.go
<details>
otherwise).
packages.
</details>
The condition which triggers a call to `verifyAllOffers()` is broken because it is only true when there is at least an hour in between updates. The problem is that the order book is updated every two seconds. The condition should …
=> services/horizon/internal/expingest: Fix OrderBookStream verification

services/horizon/internal/db2/history/trust_lines.go, services/horizon/internal/db2/history/trust_lines_test.go
<details>
otherwise).
packages.
</details>
Add `AssetForAddress` to `db2/history`.
The path finding action handler rely on core to load assets and balances for a given address. This PR adds the same method which returns `xdr.Assets` and their matching balances but using Horizon …
=> services/horizon/internal/db2/history: Add AssetsForAddress.

services/horizon/internal/actions/helpers_test.go, services/horizon/internal/actions/offer.go, services/horizon/internal/actions/offer_test.go, services/horizon/internal/actions/query_params.go, services/horizon/internal/actions/query_params_test.go, xdr/asset.go
<details>
otherwise).
packages.
</details>
Fixes #2466 
Gracefully handle incorrect assets in the query parameters of `GET /offers`.
Before this change, a panic happened and a ` 500` HTTP error was returned.
A `500` is incorrect and not helpful for the end user.
N/A
=> services/horizon: Gracefully handle incorrect assets in `GET /offers`

services/horizon/docker/verify-range/start
<details>
otherwise).
packages.
</details>
Update base branch for verify range job.
Recently we fixed a bug with how transaction fees were represented in postgres. Previously, we stored the fee as a 32 bit signed integer. But, it turns out that the range of fee values can reach …
=> services/horizon/docker/verify-range: Update base branch for verify range job

exp/ingest/ledgerbackend/stellar_core_runner.go
In macOS, captive-core blocks when writing to a pipe which isn't read from.
=> services/horizon: Write captive-core logs to /dev/null when discarding them

services/horizon/docker/Dockerfile
Also, upgrade the container to ubuntu 18.04 (16.04 didn't have a compatible libstdc++ library)
=> services/horizon: Add missing Core dependencies in Dockefile

exp/services/recoverysigner/README.md, exp/services/recoverysigner/cmd/serve.go, exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Fix a couple minor things in the usage text that were typos and out-dated or missing.
These things were changed or added recently and I failed to update the README and in some cases the usage text itself.
N/A
=> exp/services/recoverysigner: fix the usage text

services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/db2/history/trust_lines.go, services/horizon/internal/db2/history/trust_lines_test.go, services/horizon/internal/paths/mock_finder.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
- Drop `db2/core` dependency on path finding actions.
- Simplify tests for path finding, removing dependency on pre-built scenario.
- Add mock for `paths.Finder`
We are in the process of removing Horizon's dependency on `core`'s db. This …
=> services/horizon/interal/actions: Drop db2/core dependency in path finding actions.

exp/ingest/ledgerbackend/captive_core_backend.go, exp/ingest/ledgerbackend/stellar_core_runner_posix.go
<details>
otherwise).
packages.
</details>
Add read-ahead buffer for the metadata coming from captive core. Overrides #2664 , which is similar but doesn't contain decoded data structures.
It improves performance, metadata is decoded in parallel with the rest of the ingestion …
=> services/horizon: Add read-ahead buffer for decoded LedgerCloseMeta

go.list, go.mod, go.sum
<details>
otherwise).
packages.
</details>
Require at least `v0.3.3` of `golang.org/x/text`.
According to https://groups.google.com/d/topic/golang-announce/bXVeAmGOqz0 v0.3.3 which was released today contains a security fix for the `golang.org/x/text/transform` package.
The …
=> all: require at least v0.3.3 of golang.org/x/text

exp/ingest/ledgerbackend/captive_core_backend.go, exp/ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
This commit caches `LedgerCloseMeta` of the latest ledger fetched using `GetLedger`.
`GetLedger` is called multiple times while ingesting a single ledger (to get `ChangeReader` and `TransactionReader`). Because it's not possible to …
=> exp/ingest/ledgerbackend: Cache LedgerCloseMeta in captiveStellarCore

services/horizon/internal/expingest/orderbook.go
<details>
otherwise).
packages.
</details>
When ingestion state is not consistent with ingestion history the OrderBookStream emits "ingestion state is invalid" log messages using the warn log level. This message should only be logged if the ingestion state is invalid. When …
=> services/horizon/internal/expingest: Fix logging in OrderBookStream

services/horizon/docker/verify-range/start
This will save us from updating the verify-range image just for base branch change.
=> services/horizon: Make verify-range's base branch configurable (defaulting to 1.4)

exp/ingest/io/ledger_change_reader.go, exp/ingest/io/ledger_change_reader_test.go, exp/ingest/io/ledger_transaction_reader.go, exp/ingest/ledgerbackend/captive_core_backend.go, exp/ingest/ledgerbackend/database_backend.go, exp/ingest/ledgerbackend/ledger_backend.go, exp/ingest/ledgerbackend/mock_database_backend.go, services/horizon/internal/expingest/db_integration_test.go, services/horizon/internal/expingest/fake_ledger_backend.go, services/horizon/internal/expingest/main_test.go, services/horizon/internal/expingest/processor_runner.go, services/horizon/internal/expingest/processor_runner_test.go, xdr/ledger_close_meta.go, xdr/ledger_close_meta_test.go
<details>
otherwise).
packages.
</details>
Replace ledgerbackend.LedgerCloseMeta with xdr.LedgerCloseMeta.
Fixes https://github.com/stellar/go/issues/2633
> When exp/ingest prototype was created Stellar-Core didn't have LedgerCloseMeta type so we created a temporary …
=> exp/ingest/io: Replace ledgerbackend.LedgerCloseMeta with xdr.LedgerCloseMeta

exp/ingest/io/ledger_change_reader.go, exp/ingest/io/ledger_change_reader_test.go, exp/ingest/io/ledger_transaction_reader.go, services/horizon/internal/expingest/processor_runner.go
<details>
otherwise).
packages.
</details>
https://github.com/stellar/go/pull/2710 introduced a bug in LedgerTransactionReader which had the effect that transactions were not returned in the correct order.
The bug occurs because transactions in `xdr.LedgerCloseMeta.V0.TxSet` are …
=> exp/ingest/io: Fix bug in LedgerTransactionReader

exp/ingest/io/ledger_change_reader_test.go, exp/ingest/io/ledger_transaction_reader.go, exp/ingest/ledgerbackend/database_backend.go
<details>
otherwise).
packages.
</details>
Move the transaction meta check from the database backend to the LedgerTransactionReader.
Fix https://github.com/stellar/go/issues/2715
LedgerBackend should just return data, it should not interpret it and process it.
[N/A]
=> exp/ingest/io: Check TxMeta version in LedgerTransactionReader

services/horizon/internal/app.go, services/horizon/internal/app_test.go
<details>
otherwise).
packages.
</details>
Fix `/metrics` end-point.
Running Horizon with `ADMIN_PORT` enabled will cause a panic when trying to fetch the metrics since it was being setup before initializing the metrics registry. 
Fix #2714
=> services/horizon: Fix /metrics end-point.

services/horizon/internal/actions_root_test.go, services/horizon/internal/app.go, services/horizon/internal/app_test.go, services/horizon/internal/httpt_test.go
<details>
otherwise).
packages.
</details>
Use core's http end-point instead of core's db to load the latest ledger in core.
Horizon should not use Core DB outside of the ingestion package. This will help us remove the coupling between non-ingesting Horizon instances and Core's …
=> services/horizon/internal: Load Core Latest Ledger from core's http info end-point.

services/horizon/internal/docs/reference/endpoints/ledgers-all.md, services/horizon/internal/docs/reference/endpoints/ledgers-single.md, services/horizon/internal/docs/reference/resources/ledger.md
<details>
otherwise).
packages.
</details>
Document new field on `ledger` resource.
=> services/horizon/internal/docs: Document tx_set_operation_count.

exp/services/recoverysigner/cmd/keyset.go, exp/services/recoverysigner/cmd/keyset_test.go
<details>
otherwise).
packages.
</details>
This PR adds the `encryption-tink-keyset create` command to output three keysets in JSON:
1. the cleartext keyset containing the private key
2. the encrypted keyset containing the private key
3. the cleartext keyset containing the public …
=> exp/services/recoverysigner: add "encryption-tink-keyset create" cmd

services/horizon/docker/verify-range/stellar-core.cfg
Updates `stellar-core.cfg` in `verify-range` tests to use s3 domain.
We run `verify-range` in AWS and it's cheaper to use S3 directly.
=> services/horizon/docker/verify-range: Use S3 domain in verify-range

exp/ingest/ledgerbackend/stellar_core_runner_posix.go, exp/ingest/ledgerbackend/stellar_core_runner_windows.go
<details>
otherwise).
packages.
</details>
Remove unnecessary `cmd.Wait` call, fixing a data race.
This fixes the problem reported here #2738, based on Bartek's comment, we don't need to call Wait in both places since it waits for stdin, stdout, or stderr to complete.
[TODO or …
=> exp/ingest/ledgerbackend: Fix data race in stellar_core_runner. 

exp/services/recoverysigner/cmd/keyset.go, exp/services/recoverysigner/cmd/keyset_test.go, exp/services/recoverysigner/main.go
<details>
otherwise).
packages.
</details>
This PR adds a new sub-command `rotate` to `encryption-tink-keyset` to rotate the current keyset. The current keyset is taken as a new config `encryption-tink-keyset`. 
The key rotation will add a new key to the current keyset while …
=> exp/services/recoverysigner: add encryption-tink-keyset rotate cmd

services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go, services/horizon/internal/web.go
<details>
otherwise).
packages.
</details>
Get `historyQ` from `request`, which clones `db.Session`.
We noticed the following errors while testing the release candidate: 
```
  | Time | horizon_msg | horizon_level
-- | -- | -- | --
  | June 24th 2020, 22:10:46.238 | failed to …
```
=> services/horizon: Get historyQ from request, making sure that we use a clone of db.Session.

services/horizon/internal/actions_root.go, services/horizon/internal/app.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2737
There is a data race in the root endpoint when the action accesses `action.App.coreVersion` and other properties from `action.App`. These properties are updated in the `App.Tick()` …
=> services/horizon/internal: Fix data race in root endpoint

exp/ingest/ledgerbackend/database_backend.go, exp/ingest/ledgerbackend/hash_order_test.go, services/horizon/internal/expingest/database_backend_test.go, services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2721
Stellar core sorts the transaction envelopes in `LedgerCloseMetaV0.TxSet` by hash order. Hash order is defined as lexicographical byte-wise comparison (of the transaction hash) based on …
=> exp/ingest/ledgerbackend: Fix ordering of transaction envelopes in TxSet

services/horizon/internal/actions_path.go, services/horizon/internal/actions_path_test.go
<details>
otherwise).
packages.
</details>
Fix error while trying to do a path finding request.
We were manually setting up the transaction inside the `/paths` handler which was causing an error since getting `historyQ` from the request already prepares the transaction with the …
=> services/horizon/internal/actions: Don't setup repeatable read transaction in paths request.

exp/services/recoverysigner/internal/crypto/crypto_test.go, exp/services/recoverysigner/internal/crypto/encrypterdecrypter_insecure_test.go, exp/services/recoverysigner/internal/crypto/encrypterdecrypter_secure_test.go, exp/services/recoverysigner/internal/crypto/keygen_test.go
<details>
otherwise).
packages.
</details>
This PR adds tests to make sure that the system is able to be booted with a keyset that has been rotated, is able to do encryption and decryption correctly, even if the keyset contains the keys from different tink hybrid encryption …
=> exp/services/recoverysigner: add tests for starting with a rotated keyset
