stellar/go

- exp/services/recoverysigner/README.md
- exp/services/recoverysigner/cmd/keyset.go
- exp/services/recoverysigner/cmd/keyset_test.go
- exp/services/recoverysigner/cmd/serve.go
<details>
otherwise).
packages.
</details>
This PR adds two sub-commands `encrypt` and `decrypt` to `encryption-tink-keyset` to encrypt a cleartext keyset private or to decrypt an encrypted keyset private.
I was planning on adding a sub-command `reencrypt`. However,  I realized …
> exp/services/recoverysigner: add encrypt and decrypt commands

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/stellar_core_runner.go
- exp/ingest/ledgerbackend/stellar_core_runner_windows.go
<details>
otherwise).
packages.
</details>
Fixes stellar core runner on Windows.
Some changes on the runner code broke the windows build, which we just find out since we didn't test the build on windows.
[TODO or N/A]
> services/horizon/internal: Fix captive core runner for windows.

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/history_archive_backend.go
- exp/ingest/ledgerbackend/history_archive_backend_test.go
- exp/ingest/ledgerbackend/ledger_backend.go
<details>
otherwise).
packages.
</details>
This commit updates `ledgerbackend.HistoryArchiveBackend` to use updated `ledgerbackend.LedgerBackend` interface.
Unblocks https://github.com/stellar/go/pull/2756.
`ledgerbackend.LedgerBackend` has changed in `release-horizon-v1.5.0` …
> exp/ingest/ledgerbackend: Update HistoryArchiveBackend to use updated LedgerBackend interface

- exp/ingest/ledgerbackend/stellar_core_runner.go
Fix https://github.com/stellar/go/issues/2712
There is some code duplication around creating and running captive core subprocesses. This commit factors out common code and putting them in helper functions to create and run captive core subprocesses.
> exp/ingest/ledgerbackend: Add helper functions to create and run subprocesses

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
- services/horizon/internal/expingest/fsm.go
<details>
otherwise).
packages.
</details>
Fixes getting ledgers before the first checkpoint. It changes `roundDownToFirstReplayAfterCheckpointStart` function to return 2 as an expected ledger sequence when getting data before the first checkpoint sequence and updates …
> exp/ingest/ledgerbackend: Fix getting ledgers before the first checkpoint in CaptiveStellarCore

- exp/services/recoverysigner/internal/serve/account_delete.go
- exp/services/recoverysigner/internal/serve/account_get.go
- exp/services/recoverysigner/internal/serve/account_list.go
- exp/services/recoverysigner/internal/serve/account_post.go
- exp/services/recoverysigner/internal/serve/account_put.go
<details>
otherwise).
packages.
</details>
Rearrange the code that builds signers for account responses so that
signers are built  into the account response after the account response
value is created.
This is a small thing but it causes the building of the signers to occur
in …
> exp/services/recoverysigner: refactor how signers get built in responses

- exp/services/recoverysigner/internal/serve/account_post.go
<details>
otherwise).
packages.
</details>
Remove a line of code that has no effect.
This line of code sets the identifies field to be an empty slice. This was probably done at one point in time when we allowed empty identities to make sure the slice was instantiated but we don't …
> exp/services/recoverysigner: remove line of code that has no effect

- exp/services/recoverysigner/internal/serve/account_list.go
<details>
otherwise).
packages.
</details>
Make some repetitive code look similar that builds the signers into the API responses of registered accounts.
This was done in most places in 6643a542d1dc8c4f277fa070654282cea9b4ae53 but I missed these two places.
This repetitive code …
> exp/services/recoverysigner: make how signers are built in api responses consistent

- exp/services/recoverysigner/internal/account/db_store_add_test.go
- exp/services/recoverysigner/internal/account/db_store_delete_test.go
- exp/services/recoverysigner/internal/account/db_store_update_test.go
<details>
otherwise).
packages.
</details>
Add an ORDER BY to all SQL queries used in recoverysigner tests.
@howardtw pointed out that Postgres doesn't guarantee any particular
order in query results and the tests assume the results are ordered by
their primary key. We've never …
> exp/services/recoverysigner: make tests more resilient by ordering test queries

- exp/services/recoverysigner/internal/account/db_store_update_test.go
Add missing test to check that updates to an account do not change the
signers that are stored on the account.
Updates to an account should never change the signers and it's
important enough to test.
<details>
otherwise).
packages.
</details>
Add a test expectation to check that …
> exp/services/recoverysigner: add a test expectation to check that signers remain unchanged after updating an account

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
- exp/ingest/ledgerbackend/database_backend.go
- exp/ingest/ledgerbackend/ledger_backend.go
- exp/ingest/ledgerbackend/mock_database_backend.go
- services/horizon/internal/expingest/build_state_test.go
- services/horizon/internal/expingest/db_integration_test.go
- services/horizon/internal/expingest/fake_ledger_backend.go
- services/horizon/internal/expingest/fsm.go
- services/horizon/internal/expingest/ingest_history_range_state_test.go
- services/horizon/internal/expingest/main_test.go
- services/horizon/internal/expingest/resume_state_test.go
<details>
otherwise).
packages.
</details>
Add Range type with bounded and unbounded constructors.
Fixes https://github.com/stellar/go/issues/2711
Addresses the following comment from https://github.com/stellar/go/pull/2694
>Could you document the special meaning of 0.
>Even …
> Add Range type with bounded and unbounded constructors

- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/root.go
- services/horizon/internal/expingest/main.go
They shouldn't be required when captive core is used
<details>
otherwise).
* [ x This PR's title starts with name of package that is most changed in the PR, ex.
packages.
</details>
Only require `--stellar-core-db-url` and `--stellar-core-url` explicitly when they are really …
> services/horizon: Relax requirement on Core URL flags

- services/horizon/internal/docs/reference/endpoints/assets-all.md
Fix `assets-all` doc. Looks like it wasn't updated with 1.0.0 changes.
> services/horizon: Fix All Assets doc

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
Update `CaptiveStellarCore.GetLatestLedgerSequence` the latest sequence available in a buffer.
Close #2704.
Currently `CaptiveStellarCore` backend returns `nextLedger` (when meta channel is not empty) or `nextLedger-1` (when meta channel …
> exp/ingest/ledgerbackend: Update captive GetLatestLedgerSequence to return correct value

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
Unlike `DatabaseBackend` instances, there is an implicit expectation that a`CaptiveStellarCore` instance should not be called on ledgers with a random access pattern. `CaptiveStellarCore` expects  `GetLedger()` to be called on a sequence …
> exp/ingest/ledgerbackend: Only allow non-decreasing calls to GetLedger

- exp/services/recoverysigner/README.md
- exp/services/recoverysigner/cmd/keyset_create.go
- exp/services/recoverysigner/cmd/keyset_decrypt.go
- exp/services/recoverysigner/cmd/keyset_encrypt.go
- exp/services/recoverysigner/cmd/keyset_rotate.go
<details>
otherwise).
packages.
</details>
Move the long descriptions in the encryption-tink-keyset commands so that they display when viewing the help for each command, and make other small improvements to the usage text so that they contain all the information needed to use the …
> exp/services/recoverysigner: tidy the usage text of the encryption-tink-keyset commands

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/client.go
- clients/horizonclient/examples_test.go
- clients/horizonclient/main.go
- clients/horizonclient/mocks.go
<details>
otherwise).
packages.
</details>
Add NextAccountsPage function to Horizon Client.
It is not easy to iterate on pages of the `Accounts` function because there is no function to help get the next page. All the other entities have a next page function, but it looks like …
> clients/horizonclient: add missing NextAccountsPage

- services/horizon/CHANGELOG.md
- support/render/hal/link.go
<details>
otherwise).
packages.
</details>
Improve the performance of HAL response construction using `PopulateTemplated()` without involving calling Go regexp package. This improves response performance.
This is an updated version of https://github.com/stellar/go/pull/1582
> services/horizon: Use strings.Contains() instead of regex.Match() when populating HAL links.

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
- services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
Change the code to receive an archive interface instead of building it inside `getLatestCheckpointSequence`.
The previous version of the code would make a real connection to the given URL -- with this new design we can mock the archive …
> exp/ingest/captive_stellar_core_backend: Update backend to receive an archive interface.

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
- exp/ingest/ledgerbackend/stellar_core_runner.go
- exp/ingest/ledgerbackend/stellar_core_runner_posix.go
- exp/ingest/ledgerbackend/stellar_core_runner_windows.go
- services/horizon/internal/expingest/fsm.go
<details>
otherwise).
packages.
</details>
This commit adds a code that handles Stellar-Core process exit gracefully. Added `processExit` unbuffered channel to `stellarCoreRunner` that receives the error in case Stellar-Core crashed or was terminated with an error or nil error if …
> exp/ingest/ledgerbackend: Handle Stellar-Core process exit gracefully

- exp/services/recoverysigner/README-Unique-Signing-Keys.md
- exp/services/recoverysigner/README.md
<details>
otherwise).
packages.
</details>
Add high-level docs on enabling unique signing keys.
To provide some direction on where to start to use this feature.
Close #2795
The documentation does not go into detail about types of keys that should be used in KMS or even within the …
> exp/services/recoverysigner: add high-level docs on enabling unique signing keys

- go.list
- go.mod
- go.sum
<details>
otherwise).
packages.
</details>
Update stellar/go-xdr to 71a1e6d555f2.
There are no meaningful changes between the version of go-xdr we are
using and this new version. The changes between those versions were
all test fixes and linting fixes, most of which occurred when …
> all: update go-xdr to 71a1e6d555f2

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
- exp/ingest/ledgerbackend/database_backend.go
- exp/ingest/ledgerbackend/history_archive_backend.go
- exp/ingest/ledgerbackend/ledger_backend.go
- exp/ingest/ledgerbackend/mock_database_backend.go
- exp/ingest/ledgerbackend/stellar_core_runner.go
- exp/ingest/ledgerbackend/stellar_core_runner_posix.go
- exp/ingest/ledgerbackend/stellar_core_runner_windows.go
- services/horizon/internal/expingest/build_state_test.go
- services/horizon/internal/expingest/db_integration_test.go
- services/horizon/internal/expingest/fake_ledger_backend.go
- services/horizon/internal/expingest/fsm.go
- services/horizon/internal/expingest/ingest_history_range_state_test.go
- services/horizon/internal/expingest/init_state_test.go
- services/horizon/internal/expingest/main_test.go
- services/horizon/internal/expingest/resume_state_test.go
<details>
otherwise).
packages.
</details>
This commit updates ingestion state machine to not block entire cluster ingestion when captive core backend is not prepared. Specifically:
* In `buildState`, `resumeState` and `historyRangeState` added a check that ensures a range is …
> services/horizon/expingest: Update ingestion state machine to not block when captive backend is used

- services/horizon/CHANGELOG.md
- services/horizon/cmd/root.go
- services/horizon/internal/middleware.go
<details>
otherwise).
packages.
</details>
This commit changes the behaviour of `--connection-timeout` config param. Right now, it is ignored in `txsub` so if the value is less than 30s, `txsub` will still timeout after 30s.
If Horizon admin wants to set `--connection-timeout` to …
> services/horizon: Ignore ConnectionTimeout in txsub

- services/horizon/cmd/root.go
<details>
otherwise).
packages.
</details>
Update config validation to require both captive core options to be set or unset. This is done because captive core is started when `--stellar-core-binary-path` is set, without checking `--enable-captive-core-ingestion` value: …
> services/horizon: Require all captive Stellar-Core params or none

- exp/tools/dump-ledger-state/docker-entrypoint.sh
<details>
otherwise).
packages.
</details>
The dump ledger state job begins by requesting the latest snapshot ledger.
https://github.com/stellar/go/blob/master/exp/tools/dump-ledger-state/run_test.sh#L12
When this request fails `LATEST_LEDGER` is set to the empty string which …
> exp/tools/dump-ledger-state: Abort early if request to populate LATEST_LEDGER fails

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/captive_core_backend_test.go
- exp/ingest/ledgerbackend/stellar_core_runner.go
- exp/ingest/ledgerbackend/stellar_core_runner_posix.go
- exp/ingest/ledgerbackend/stellar_core_runner_windows.go
- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/root.go
- services/horizon/internal/config.go
- services/horizon/internal/expingest/main.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Adds `--stellar-core-config-path` config option to allow user to provide `stellar-core.cfg` file in an online mode.
Close #2706.
In an online mode Stellar-Core connects to the Stellar network so it requires quorum sets. Previously we …
> exp/ingest/ledgerbackend: Use provided stellar-core.cfg file in an online mode

- services/horizon/docker/verify-range/start
Use `horizon db reingest range` command when reingesting history using base Horizon version instead of `verify-range`. It is much faster.
> services/horizon/docker/verify-range: Run `reingest range` instead of `verify-range` for base

- services/horizon/internal/actions/path.go
- services/horizon/internal/actions/path_test.go
- services/horizon/internal/actions/trade.go
- services/horizon/internal/actions_path_test.go
- services/horizon/internal/actions_root.go
- services/horizon/internal/handler.go
- services/horizon/internal/httpt_test.go
- services/horizon/internal/test/assertion.go
- services/horizon/internal/web.go
- support/render/hal/paging_token.go
<details>
otherwise).
packages.
</details>
Move path finding handler to /actions and move assertions helper to a share package.
This is part of https://github.com/stellar/go/issues/2582.
For this handler we need to use `ServerHTTP` since they don't follow the same page building …
> services/horizon: Move path finding end-points to new actions.

- services/horizon/internal/app.go
- services/horizon/internal/context/context_key.go
- services/horizon/internal/middleware.go
- services/horizon/internal/web.go
It is not needed. It removes a context variable (which is implicit and ugly)
and reduces the dependecnies between App and http/web handling (which I plan to split into
a separate package but right now has a cyclic dependency due App).
I will help wrap up #2582
> services/horizon: Get rid of App context and middleware

- services/horizon/internal/actions/path.go
- services/horizon/internal/actions/trade.go
- services/horizon/internal/actions_path_test.go
- services/horizon/internal/handler.go
- services/horizon/internal/web.go
It just complicated things. If we are we are using a custom-rendered _thing_ we just return it as an object and
use `objectActionHandler`.
Leftover from #2582
> services/horizon: Get rid of custom page builder abstraction

- services/horizon/internal/app.go
- services/horizon/internal/web.go
> services/horizon: Get rid of unused App parameter

- services/horizon/cmd/db.go
Fixes #2867 
I introduced the unfortunate typo was introduced on #2724 , prompted by the `shadow` vet tool: https://github.com/stellar/go/pull/2724/files#diff-dd30f3045790051170cd58e06c2667b6L185-R250
`shadow` is right in many cases but in this case it would had been fine, I wonder if we can tune the tool to avoid situations like this.
> Fix panic on system creation failure from db command

- services/horizon/internal/docs/captive_core.md
Adds a doc explaining how to use Captive Stellar-Core in Horizon. This will be expanded with more info when we experiment with it more in SDF clusters.
Close #2815.
> services/horizon: Add Captive Stellar-Core doc

- exp/ingest/ledgerbackend/captive_core_backend.go
Updated `CaptiveStellarCore`:
* Added more info about how each mode operates and how it connects to `PrepareRange`.
* Removed internal details (like fast-forward ledgers).
* Removed outdated comments.
Part of https://github.com/stellar/go/issues/2815.
> exp/ingest/ledgerbackend: Update CaptiveStellarCore godoc

- services/horizon/cmd/version.go
Adds Golang runtime version to `horizon version` output. Will be helpful to debug potential issues in the future.
> services/horizon: Add Golang version to horizon version output

- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
Update XDR with changed operation names on CAP-0033.
There are some last minutes changes on CAP-0033 XDR.
> xdr: Update XDR definitions with updated sponsoring op names

- services/horizon/internal/db2/history/trade.go
<details>
otherwise).
packages.
</details>
Check `TradesQ.Err` before returning `TradesQ.Page call is required before calling Select` error in `Select`.
If any of the previous methods assign an error to `TradesQ.Err` it won't be visible in the logs.
We should remove …
> services/horizon/db2: Check previous errors before checking if TradesQ.Page was called

- tools/horizon-cmp/internal/response.go
Remove trailing data fix in SSE responses to avoid false positive diffs.
> Update horizon-cmp for 1.7 release

- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
Add placeholders for new operations and entry in verifier.
Without this trying to ingest state or new transactions makes Horizon panic.
> expingest: Add placeholder for new operations and verifier

- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
- xdr/asset.go
- xdr/asset_test.go
<details>
otherwise).
packages.
</details>
Ingest details and participants involved in `CreateClaimableBalanceOp` and `ClaimClaimableBalanceOp`.
CAP23 introduces 2 new operations, we need to ingest the details and participants involved in each operation. 
Fix #2886.
[TODO or N/A]
> services/horizon/internal/expingest: Ingest CAP23 Operations details and participants.

- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/claimable_balances_batch_insert_builder_test.go
- services/horizon/internal/db2/history/claimable_balances_test.go
- services/horizon/internal/db2/history/mock_q_claimable_balances.go
- services/horizon/internal/expingest/processors/claimable_balances_processor.go
- services/horizon/internal/expingest/processors/claimable_balances_processor_test.go
<details>
otherwise).
packages.
</details>
Ingest sponsor when updating and creating claimable balances.
This add CAP33 support to CAP23 ingestion.
Fix https://github.com/stellar/go/issues/2912
> Sponsored claimable services/horizon: Ingest sponsor while ingesting claimable balances.

- services/horizon/internal/db2/history/main.go
- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/expingest/processors/effects_processor_test.go
<details>
otherwise).
packages.
</details>
Ingest effects for `CreateClaimableBalanceOp` and `ClaimClaimableBalanceOp`.
CAP23 introduces 2 new operations, we need to effects from each operation. 
Fix #2885 
[TODO or N/A]
> services/horizon/internal/expingest: Ingest CAP23 Operations effects.

- services/horizon/cmd/ingest.go
- services/horizon/internal/expingest/build_state_test.go
- services/horizon/internal/expingest/fsm.go
- services/horizon/internal/expingest/main.go
- services/horizon/internal/expingest/main_test.go
<details>
otherwise).
packages.
</details>
Adds `horizon ingest init-genesis-state` command that ingest state as of genesis ledger (seq=1).
Horizon is using the latest History Archive State for checking the latest checkpoint ledger however Stellar-Core does not publish HAS until …
> services/horizon: Add `horizon ingest init-genesis-state` command

- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/mock_q_claimable_balances.go
- services/horizon/internal/expingest/verify.go
- services/horizon/internal/expingest/verify_range_state_test.go
- xdr/claimant.go
- xdr/claimant_test.go
<details>
otherwise).
packages.
</details>
Add Claimable Balance entries to state verifier.
We have a new ledger entry type and we need to check that we have the correct state.
Fixes https://github.com/stellar/go/issues/2882
> horizon/internal/ingest:Add Claimable Balances to state verifier.

- services/horizon/internal/db2/history/accounts_test.go
- services/horizon/internal/db2/history/sponsor.go
- services/horizon/internal/db2/history/trust_lines_test.go
- xdr/ledger_entry.go
- xdr/ledger_entry_test.go
* Avoid unnecessary casting
* Make sure we check for the version of the ledger entry extension
(to make the code future-proof)
* Fix flakey `UpsertTrustlines` test
> services/horizon: (protocol 14) Fix various SponsoringID minor issues

- services/horizon/internal/action_offers_test.go
- services/horizon/internal/httpx/router.go
<details>
otherwise).
packages.
</details>
Fix route query params for `offers/:offer_id`.
The route was defining the ID query param as `:id` but the action handler was trying to find `:offer_id` -- making all request of type `/offers/XX` to return `404`. 
This bug was introduced …
> services/horizon: Fix route query params for offers/:offer_id.

- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/database_backend.go
- exp/ingest/ledgerbackend/history_archive_backend.go
- exp/ingest/ledgerbackend/ledger_backend.go
- exp/ingest/ledgerbackend/mock_database_backend.go
- exp/ingest/ledgerbackend/remote_captive_core.go
- exp/services/captivecore/internal/api.go
- exp/services/captivecore/internal/api_test.go
- exp/services/captivecore/internal/server_test.go
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/root.go
- services/horizon/internal/config.go
- services/horizon/internal/expingest/build_state_test.go
- services/horizon/internal/expingest/db_integration_test.go
- services/horizon/internal/expingest/fake_ledger_backend.go
- services/horizon/internal/expingest/fsm.go
- services/horizon/internal/expingest/ingest_history_range_state_test.go
- services/horizon/internal/expingest/main.go
- services/horizon/internal/expingest/main_test.go
- services/horizon/internal/expingest/resume_state_test.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/2841
This PR is a follow up to https://github.com/stellar/go/pull/2896 . In https://github.com/stellar/go/pull/2896 we added an http server wrapper around stellar core so that we could run a …
> exp/services/captivecore/internal: Implement RemoteCaptiveCore HTTP client

- services/horizon/internal/expingest/main.go
- services/horizon/internal/expingest/verify.go
- services/horizon/internal/expingest/verify_range_state_test.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Update state verification metrics:
* Do not update `horizon_ingest_state_verify_duration_seconds` in case of shutdown.
* Add `horizon_ingest_state_invalid` gauge: 1 if state is invalid, 0 otherwise.
> services/horizon: Update state verify metrics

- protocols/horizon/main.go
- services/horizon/internal/actions/claimable_balance.go
- services/horizon/internal/actions/claimable_balance_test.go
- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/claimable_balances_test.go
- services/horizon/internal/httpx/router.go
- services/horizon/internal/resourceadapter/claimable_balances.go
- services/horizon/internal/resourceadapter/claimable_balances_test.go
<details>
otherwise).
packages.
</details>
Introduce end-point to fetch a single claimable balance by ID `/claimable_balances/id.`
User should be able to fetch claimable balances from Horizon using the its ID.
> services/horizon: Add /claimable_balances/:id.

- exp/ingest/io/ledger_change_reader_test.go
- exp/ingest/io/ledger_transaction_reader.go
<details>
otherwise).
packages.
</details>
Due to a bug in Stellar-Core (more info in https://github.com/stellar/go/pull/2099) we check if the meta version is at least 2 for protocol version < 10. However, some backend like `HistoryArchiveBackend` do not return tx meta. For such …
> exp/ingest/io: Fix LedgerTransactionReader tx meta check

- services/horizon/internal/init.go
The name says `seconds` but `time.Duration` is in nanoseconds.
Close #2913.
> services/horizon: Fix horizon_db_wait_duration_seconds_total metric

- services/horizon/internal/app.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
This commit adds `horizon_db_max_open_connections` metric that indicates the max number of possible open DB connections. This is static right now but we want this to be exposed to create alert for in_use/max_open connections in …
> services/horizon: Add horizon_db_max_open_connections metric

- services/horizon/internal/app.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
This commit adds `horizon_build_info` to `/metrics` with the Horizon and Go runtime versions.
The metric labels will be used in Horizon dashboard to ensure all nodes are running the same version.
> services/horizon: Export horizon_build_info in /metrics

- go.list
- go.mod
- go.sum
- services/horizon/internal/render/main.go
<details>
otherwise).
packages.
</details>
Go modules have been updated to replace a [necessary dependency](https://github.com/adjust/goautoneg/).
BitBucket dropped the one we used previously because it was a Mercurial repository (see #2039).
> services/horizon: Update goautoneg dep to not use BitBucket repo.

- exp/tools/dump-ledger-state/Dockerfile
Fix `publish_state_diff_docker_image` broken due to changes in the stellar/packages repo config.
> Fix publish_state_diff_docker_image Circle-CI job

- .circleci/config.yml
As noticed by @2opremio the problem with `approve` job is that it makes the overall PR status to be pending until approved. Unfortunately, this is still an open feature request in [Circle-CI tracker](https://ideas.circleci.com/ideas/CCI-I-445).
This PR changes the Circle-CI config to run integration tests on each PR because it takes just 2 minutes to complete. When it's too slow we can switch to a schedule trigger in Circle-CI (ex. run integration tests once a day).
> services/horizon: Run integration tests on each PR

- clients/horizonclient/error_helpers.go
- clients/horizonclient/error_helpers_test.go
<details>
otherwise).
packages.
</details>
This PR changes two error checking helpers `IsNotFoundError` and `GetError` to use the root error for horizon error checking.
When clients use these helper functions, they intended to supply the error directly to them regardless whether …
> horizonclient: use root error to check horizon error

- services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
Clone a DB session before using in `initMetrics/GetExpStateInvalid`.
The same session is used in ledgers ingestion in a different go routine what can result in connection errors.
> services/horizon: Clone a DB session in System.initMetrics/GetExpStateInvalid

- services/horizon/docker/docker-compose.yml
<details>
otherwise).
packages.
</details>
Specifies the port for the core PostgreSQL database so that `docker-compose` works on Linux.
Docker uses the `host` networking mode on Linux when setting up Horizon (see the [startup …
> services/horizon: Add port specification to work on host network mode

- exp/services/recoverysigner/cmd/serve.go
- exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
This PR sets the max database open connections and idle connections to 20. If we find it problematic, we can just the flag `-db-max-open-conns`  or the env `DB_MAX_OPEN_CONNS` to adjust the number.
We had a problem where all connections …
> recoverysigner: set max db open conns to 20

- services/horizon/internal/app.go
- services/horizon/internal/httpx/server.go
Instead of using locks I simply initialize the servers during creation.
In that way there are no writes while serving.
Fixes #2957
> Fix server shutdown race

- tools/horizon-cmp/init_routes.go
- tools/horizon-cmp/internal/response.go
- tools/horizon-cmp/internal/route_counter.go
- tools/horizon-cmp/internal/route_counter_test.go
- tools/horizon-cmp/main.go
This commit adds routes coverage printed after `horizon-cmp` session. The list of routes is currently created manually because Horizon's router is in `internal` package. The routes are matches using a simple regexp (see `MakeRoute`) that seems to be working well.
I also fixed a misc issues:
* Retry when size of any response is 0 (connection issues).
* `log` variable overwrites by multiple go routines.
* Crash after `503` error code.
> tools/horizon-cmp: Add routes coverage and misc fixes

- services/horizon/internal/expingest/orderbook.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/2960
When horizon is shutting down we expect that the context embedded in the db connection to be cancelled. When that happens any pending calls to the db will return context cancelled errors. …
> services/horizon/internal/expingest: Exclude shutdown errors from logs in OrderBookStream

- services/horizon/CHANGELOG.md
Let's also do https://github.com/stellar/go/issues/2965 before 1.8.0 release so users know how to configure `captivecore`.
> Horizon 1.8.0 CHANGELOG

- exp/services/captivecore/README.md
Close https://github.com/stellar/go/issues/2965
This commit adds a README for the captive core server which details its API and its command line flags.
> exp/services/captivecore: Add README for captivecore server

- services/horizon/docker/Dockerfile
A quickfix for an issue found by @2opremio in https://github.com/stellar/go/pull/2821#issuecomment-680250393 so `stellar/horizon` image can start properly. The Horizon config code will be fixed in the next version.
> services/horizon/docker: Comment-out STELLAR_CORE_BINARY_PATH

- protocols/horizon/operations/main.go
- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/resourceadapter/operations.go
- services/horizon/internal/resourceadapter/operations_test.go
- xdr/json_test.go
<details>
otherwise).
packages.
</details>
Implements new operations and its' resource adapters.
Close #2940.
Close #2941.
Unit tests are really simple and don't really check if claimants are rendered correctly. Let's check it out in integration tests.
> services/horizon: Protocol 14 operations' resource adapters

- services/horizon/internal/codes/main.go
<details>
otherwise).
packages.
</details>
This commit adds Protocol 14 error codes to `txsub`.
> services/horizon/txsub: Add Protocol 14 error codes

- services/horizon/internal/codes/main.go
<details>
otherwise).
packages.
</details>
I forgot to add new ops to `ForOperationResult` in https://github.com/stellar/go/pull/2981. Now, the codes are correctly returned. I'm sorry for two similar PRs.
> services/horizon/txsub: Add Protocol 14 ops in ForOperationResult

- services/horizon/internal/expingest/processors/operations_processor.go
It turns out Core can process transactions with a badly-formed sponsoring sandwich, which shouldn't cause the ingestion process to abort.
Closes #2987
> services/horizon: Do not error on missing BeginSponsoringOp

- exp/services/recoverysigner/internal/account/db_store_add.go
- exp/services/recoverysigner/internal/account/db_store_add_test.go
<details>
otherwise).
packages.
</details>
Call `tx.Rollback()` when returning an error from `func (s *DBStore) Add(a Account) error`.
You need to call `tx.Rollback()` in order to abort the database transaction. Without calling it, the transactions may stack up indefinitely until …
> exp/services/recoverysigner: call database transaction `.Rollback()` when returning an error

- exp/services/recoverysigner/internal/account/db_store_add_test.go
- exp/services/recoverysigner/internal/account/db_store_update.go
- exp/services/recoverysigner/internal/account/db_store_update_test.go
<details>
otherwise).
packages.
</details>
Call `tx.Rollback()` when returning an error from `func (s *DBStore) Update(a Account) error`.
We need to call `tx.Rollback()` in order to abort the database transaction. Without calling it, the transactions may stack up indefinitely …
> exp/services/recoverysigner: call database transaction `.Rollback()` when returning an error from db_store_update

- services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
- services/horizon/internal/integration/protocol14_test.go
- services/horizon/internal/txnbuild/create_claimable_balance.go
<details>
otherwise).
packages.
</details>
Add a simple scenario testing CAP23 operations and effects.
It adds e2e testing for new features of Horizon and Stellar.
This is done on top of #2991 - the relevant commit here is 40dace2f16b5b75273aaa547846126416dfca62a
> services/horizon: Add basic integration test scenario for CAP23.

- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/expingest/processors/effects_processor_test.go
<details>
otherwise).
packages.
</details>
Fix bug when trying to ingest claim claimable balances operations. 
We can't rely on a 1:1 comparison between claimable balances since the discriminant value might not be the same in memory.  A safer approach would be to convert to hex …
> services/horizon/internal/expingest: Fix claim claimable balances effects processor.

- services/horizon/CHANGELOG.md
- services/horizon/internal/httpx/server.go
<details>
otherwise).
packages.
</details>
The `Server` struct was refactored in https://github.com/stellar/go/pull/2958/files so that the TLS configuration was stored in `ServerConfig`. However, the `ServerConfig` instance was never assigned in the `NewServer()` constructor. …
> services/horizon/internal/httpx: Fix TLS configuration

- services/horizon/internal/integration/protocol14_test.go
- services/horizon/internal/test/integration.go
<details>
otherwise).
packages.
</details>
Extend ` CreateAccounts` to receive initial balance.
This would allow us to create accounts with a custom balance and test scenarios like not having enough reserve. 
[TODO or N/A]
> services/horizon: Extend CreateAccounts to take initial balance.

- exp/services/recoverysigner/internal/account/db_store_add_test.go
- exp/services/recoverysigner/internal/account/db_store_update_test.go
<details>
otherwise).
packages.
</details>
Add comment to make the tests approach clearer about closing the database transaction.
It was pointed out in https://github.com/stellar/go/pull/3002#discussion_r488945239 that the test approach could be made clearer.
[TODO or N/A]
> exp/services/recoverysigner: add comment to make the tests approach clearer about closing the dbTx

- services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
- services/horizon/internal/test/integration.go
<details>
otherwise).
packages.
</details>
Add a failing claimable balance and check the operation details and effects.
This help us test the scenario where a claimable balance operation fails and then:
1. Verify that the operation is ingested.
2. Check that no effects are …
> services/horizon: Add integration test for invalid claimable balance operation.

- exp/tools/dump-ledger-state/Dockerfile
Fixes CircleCI in master.
Installing Core led to the following error:
```
The following packages have unmet dependencies:
stellar-core : Depends: libc++1-8 but it is not installable
Depends: libc++abi1-8 but it is not installable
```
It seems like the `golang:*buster` images no longer meet the dependencies
of Core (and Buster is the latest Debian release).
I could use a separate stage for building ... except the scripts use `go run`.
Thus, I just changed the base image to `ubuntu:18.04` and installed Go manually.
> Fix dump-ledger-state Dockerfile

- .circleci/config.yml
- protocols/horizon/main.go
- services/horizon/internal/actions/account_data.go
- services/horizon/internal/actions/root.go
- services/horizon/internal/db2/history/account_data_batch_insert_builder.go
- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/integration/protocol14_state_verifier_test.go
- services/horizon/internal/resourceadapter/balance.go
- services/horizon/internal/resourceadapter/root.go
- services/horizon/internal/test/integration.go
Adds a new integration tests checking if state is correctly verified when ledger entries have sponsors and a new entry type: `ClaimableBalance`. It adds ledger entries and then gets `:[admin_port]/metrics` to check if state verification is finished and state is correct.
Part of #2939.
While working on this I fixed some bugs:
* `/accounts/{id}/data/{name}` data value was incorrectly rendered (overwritten by a sponsor),
* Sponsor missing in account's balances.
* `accountDataBatchInsertBuilder` not adding sponsor,
* `GetClaimableBalancesByID` didn't work at all (invalid query).
We want to ensure that a new code added to state verifier is working correctly.
* Currently it's not possible to speed ledger close times easily so test needs to wait until the first checkpoint ledger (63) is closed. …
> services/horizon: Add state verifier integration tests connected to Protocol 14

- services/ticker/internal/tickerdb/tickerdb_test/queries_market_test.go
<details>
otherwise).
packages.
</details>
This PR substantially increases the time tolerance for database testing of `services/ticker`. 
This fixes repeated flakiness observed in continuous integration for various pull requests. We cannot control the environment in which tests are run, so extending the testing time avoids intermittent failures that trigger CI failures and slow development.
N/A
> services/ticker: increase db test time tolerance

- services/horizon/internal/integration/protocol14_test.go
<details>
otherwise).
packages.
</details>
This is a simple addition to existing tests. 
It adds checks to the "claiming a claimable balance" tests to ensure that:
- a random account for whom a CB is not destined cannot claim the CB
- the actual balance of an account updates …
> services/horizon: Check more details when we test claiming a claimable balance.

- services/horizon/internal/actions_data_test.go
- services/horizon/internal/db2/history/account_data_batch_insert_builder_test.go
- services/horizon/internal/db2/history/account_data_test.go
- services/horizon/internal/db2/history/claimable_balances_test.go
<details>
otherwise).
packages.
</details>
Add missing tests for account data ingestion helpers and claimable balances query helpers.
Bartek found some bugs here https://github.com/stellar/go/pull/2998  - this adds regression tests for his fixes.
> services/horizon: Improve tests for account data sponsor and claimable balance helpers.

- services/horizon/internal/integration/protocol14_state_verifier_test.go
<details>
otherwise).
packages.
</details>
Add a sponsored signer to the state verifier integration tests.
This help us confirm that state verification works when a signer is being sponsored.
> services/horizon: Add sponsored signer to state verifier integration test.

- services/horizon/internal/integration/protocol14_state_verifier_test.go
- services/horizon/internal/integration/protocol14_test.go
- services/horizon/internal/txnbuild/transaction_challenge_example_test.go
<details>
otherwise).
packages.
</details>
This adds tests for predicates on claimable balances. 
It first checks the happy paths, ensuring that all predicate types can be created and that valid predicates result in actually claimable balances. 
It also checks that predicates …
> services/horizon: Add integration tests for predicates on claimable balances. 

- protocols/horizon/operations/main.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
Addresses part of #2939 
It also fixes a bug: the operation sponsor was being exposed in the Horizon responses.
It doesn't yet include `RevokeSponsorhip`, since it depends on https://github.com/stellar/go/pull/3036
> services/horizon: Add Basic sponsorship integration test

- services/horizon/internal/integration/protocol14_test.go
- services/horizon/internal/test/integration.go
- services/horizon/internal/txnbuild/create_claimable_balance.go
<details>
otherwise).
packages.
</details>
Add tests to try claiming a claimable balance (CB) twice within both a separate and the same transaction. 
Double-claim would be a problem.
> services/horizon: Add integration test to ensure double-claiming a CB won't work.

- services/horizon/internal/txnbuild/begin_sponsoring_future_reserves.go
- services/horizon/internal/txnbuild/helpers.go
- services/horizon/internal/txnbuild/revoke_sponsorship.go
- services/horizon/internal/txnbuild/revoke_sponsorship_test.go
Fixes #3001 .
It also fixes a small bug in `BeginSponsoringFutureReserves`
I am not too happy using pointers to represent a union type. If we only needed to build XDR operations, an interface would be enough. But since users need to be able to parse XDR (and inspect the resulting structure) I don't see a much better approach.
* [Using an interface + type inspection](https://eli.thegreenplace.net/2018/go-and-algebraic-data-types/) is an option, but I don't think it's much better than representing the union type explicitly. On top of that, our users are probably used to the `xdr` package's approach which uses pointers.
* [Using a visitor pattern](https://making.pusher.com/alternatives-to-sum-types-in-go/) is safer, but unnecessarily complicated.
> services/horizon: Implement support for RevokeSponsorship in txnbuild

- protocols/horizon/main.go
- protocols/horizon/main_test.go
<details>
otherwise).
packages.
</details>
Change the paging token for trade aggregations (that isn't actually used) from being a single character that matches the unicode value of the timestamp, to being a string format of the timestamp integer.
For timestamp: `64`
Before: `"@"` …
> protocols/horizon: fix trade aggregation paging token

- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
I have decided it makes sense to have the account whose sponsorship is revoked as a participant in the RevokeSponsorhip operation. For consistency I have bit the bullet and incorporated all other participants from the possible RevokeSponsorship operation.
Let me know if you think that's overkill.
> Expand Sponsorhip integration tests and participants for RevokeSponsorship

- services/horizon/internal/test/integration.go
<details>
otherwise).
packages.
</details>
Your local horizon binary is now copied to `/usr/bin/stellar-horizon` for integration testing.
Changes introduced in stellar/docker-stellar-core-horizon#201 make `stellar/quickstart:testing` look for a different binary name.
> services/horizon/integration: Update binary name to match new stellar:quickstart image.

- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/expingest/processors/signers_processor.go
- xdr/account_entry.go
- xdr/account_entry_test.go
Having two simultaneous mechanisms to check whether a map entry is empty (whether there is no entry and whether the entry is `nil`) leads to problems like:
https://github.com/stellar/go/blob/e3e145b5ed548fb7f19102b8853a9cba7cd05ac3/services/horizon/internal/expingest/processors/effects_processor.go#L284-L286
Note how the existence in the map is checked, but not whether the entry is nil.
I am not sure that causes an actual bug, but it could certainly have.
> Avoid nils in signer sponsorship map

- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
We were not obtaining the signer sponsor detail (we were only obtaining it for ledger key sponsors)
> Fix sponsor ingestion bug and add Sponsored preauth signer integration test

- services/horizon/internal/expingest/processors/operations_processor.go
PR #3050 was misaligned with PR #3051 at merge time, causing the problem
(even if both PRs passed all the checks individually).
Found by @Shaptic (thanks! 🙇 )
> Fix compilation error due to merge misalignment

- .circleci/config.yml
This change ensures we expand paths before cloning code from git
If `CIRCLE_WORKING_DIRECTORY` contains `~` character it's by default treated as string literal.
> Improve circleci checkout workdir handling

- services/horizon/internal/test/integration.go
<details>
otherwise).
packages.
</details>
Add several integration test framework improvements:
- add ability to run tests offline (for ex. if your Internet goes out or [docker.io](https://docker.io) dies)
- remove noisy messages on (possibly intentionally) failing TXs (see …
> services/horizon: Improve integration test framework

- exp/services/recoverysigner/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Remove the setting of the max idle database connections that was added in 3ad0378.
To fix the issue that 3ad0378 was addressing we only needed to set the maximum number of total open connections. We set the max idle connections to the …
> exp/services/recoverysigner: do not set max idle db connections

- services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
<details>
otherwise).
packages.
</details>
Combines two similar tests into one via subtests to avoid unnecessary container startup/teardown.
**Note**: If you view the [diff with whitespace disabled](https://github.com/stellar/go/pull/3058/files?diff=unified&w=1), it should be …
> services/horizon: Consolidate two tests into one so that runtime is faster.

- protocols/horizon/effects/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- services/horizon/internal/resourceadapter/effects.go
We were not parsing data effects properly (even if they were already being emitted) due to missing Data effect `struct`s. That [led us to think](https://github.com/stellar/go/pull/2951#issuecomment-699021498) we didn't have to add Data Sponsorship effects (for consistency).
This PR adds:
1. An integration test for Data sponsorships
2. Effects for Data sponsorships
3. Data structures (and parsing) of Data effects.
Part of #2939 , followup for #2951
> Add data sponsoring integration test and fix Data effects

- support/http/main.go
- support/http/main_test.go
<details>
otherwise).
packages.
</details>
This PR adds the ability to configure ReadTimeout, WriteTimout, IdleTimeout on the http server.
We want to apply timeout to have a better control over our resources. A default http server comes with zero timeout. It's good that we have …
> support/http: add ReadTimeout, WriteTimeout, IdleTimeout configs

- protocols/horizon/main.go
- services/horizon/internal/actions/claimable_balance.go
- services/horizon/internal/resourceadapter/claimable_balances.go
- services/horizon/internal/resourceadapter/claimable_balances_test.go
<details>
otherwise).
packages.
</details>
Add `last_modfied_time` to claimable balance response.
Whenever horizon includes a `last_modified_sequence` we should also have a corresponding `last_modfied_time` field in the response. API consumers should not need to send another …
> protocols/horizon: Add last_modfied_time to claimable balance response

- services/horizon/internal/resourceadapter/operations_test.go
- xdr/json.go
- xdr/json_test.go
<details>
otherwise).
packages.
</details>
Marshal int64 value in JSON Predicate as a string instead of a number.
Since this can be an `int64`, it can cause an overflow when reading it in JavaScript.
[TODO or N/A]
> xdr: Return RelBefore as a String instead of Number when representing in JSON.

- services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- txnbuild/revoke_sponsorship.go
- txnbuild/revoke_sponsorship_test.go
Also:
* Refactor sponsored Claimable Balance test.
* Refactor sponsored Account test.
* Rename `Id` suffixes to `ID`.
Part of #2939
> services/horizon: Add sponsored trustline/offer integration test and expand data test

- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
<details>
otherwise).
packages.
</details>
Remove signer from participants of `RevokeSponsorship` operation.
Close #3065.
Signer can be an arbitrary Stellar account. Because of that a special set of operations with `RevokeSponsorship` (creating a sponsored signer and then …
> services/horizon: Remove signer from revoke_sponsorship participants

- protocols/horizon/effects/main.go
- protocols/horizon/operations/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- services/horizon/internal/resourceadapter/operations_test.go
- txnbuild/revoke_sponsorship.go
* Add Sponsorhip update checks
* Expand Claimable Balance test
* Add Signer test
* Fix type for RevokeSponsorship's OfferID field, which was causing a 500 error on `/operations` due to an unmarshalling error.
> services/horizon: Expand CAP 33 integration tests and fix 500 error bug

- services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- services/horizon/internal/integration/protocol14_state_verifier_test.go
- services/horizon/internal/integration/protocol14_test.go
- services/horizon/internal/test/integration.go
<details>
otherwise).
packages.
</details>
Uses `testing.T.Cleanup` to shut down the container rather than `defer`. 
Shoutout to @leighmcculloch for the pro-tip :1st_place_medal:! 
If a sub-test panics, the outer `defer itest.Close()` will not execute, leaving behind a …
> services/horizon: Improves test cleanup process in case of subtest panics.

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
> clients/horizonclient+txnbuild: Update CHANGELOGs for horizonclient 4.0 release

- services/horizon/CHANGELOG.md
We did not inform about state rebuild connected to this version and it stopped ingestion in Satoshipay nodes.
CC: @andrenarchy
> services/horizon: Update v1.9.0 CHANGELOG with state rebuild info

- exp/ingest/ledgerbackend/captive_core_backend.go
- historyarchive/archive.go
- historyarchive/archive_test.go
- historyarchive/history_archive_state.go
- services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
Add a code comparing network passphrase in HAS with expected network passphrase.
Stellar-Core 14.1.0 started publishing network passphrase in HAS (https://github.com/stellar/stellar-core/issues/2579). Checking this value will help debug …
> historyarchive: Check archive's network passphrase when getting HAS

- Makefile
- services/friendbot/Makefile
- services/friendbot/docker/Dockerfile
Add friendbot Dockerfile and Makefile
Copying the existing patterns we have in other applications. The
Dockerfile and Makefile were based on other services in the repository
> Add friendbot Dockerfile and Makefile

- services/horizon/internal/resourceadapter/operations_test.go
- xdr/json.go
- xdr/json_test.go
<details>
otherwise).
packages.
</details>
Use underscore in JSON fields for claim predicate.
Horizon uses underscore for payload fields,  this change updates JSON marshaling to use underscore. 
Fixes https://github.com/stellar/go/issues/3079
[TODO or N/A]
> xdr: Use underscore in JSON fields for claim predicate.

- services/horizon/internal/actions/claimable_balance.go
- services/horizon/internal/actions/claimable_balance_test.go
- services/horizon/internal/db2/history/claimable_balances.go
<details>
otherwise).
packages.
</details>
Wrap invalid cursor in claimable balances in `problem.P`
We do cursor validation, however, if there is an error we return a
plain error instead of a `problem.P` -- this causes horizon to handle
the error as a `500` instead of a `400`. …
> services/horizon: Wrap invalid cursor in claimable balances in problem.P

- services/horizon/internal/actions/claimable_balance.go
- services/horizon/internal/actions/claimable_balance_test.go
<details>
otherwise).
packages.
</details>
Re-write error message when cursor is invalid.
There was a typo on the first message.
[TODO or N/A]
> services/horizon: Fix typo on cursor error and improve message.

- services/horizon/internal/expingest/orderbook.go
<details>
otherwise).
packages.
</details>
Change the message logged when history ledger is not consistent with state ledger.
The message is scary and multiple users reached out asking what's going on.
> services/horizon/expingest: Change log message when history not consistent with state

- services/horizon/internal/expingest/db_integration_test.go
- services/horizon/internal/expingest/main.go
- services/horizon/internal/expingest/processor_runner.go
- services/horizon/internal/expingest/processor_runner_test.go
<details>
otherwise).
packages.
</details>
Check if Horizon version supports the protocol version in a ledger header.
Right now, when Horizon does not support the upcoming protocol version it prints ugly errors connected to errors in XDR unmarshalling. Checking a protocol version …
> service/horizon: Add protocol version support check

- support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
Silent errors in `Problem.Render` only when `LogNoErrors` set.
Close #3084.
We want to be notified about unknown errors with `error` level.
> support/render/problem: Silent errors only when LogNoErrors set

- services/horizon/internal/action_offers_test.go
- services/horizon/internal/actions/offer_test.go
- services/horizon/internal/actions/orderbook_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/mock_offers_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_q_offers.go
- services/horizon/internal/db2/history/offers.go
- services/horizon/internal/db2/history/offers_batch_insert_builder.go
- services/horizon/internal/db2/history/offers_test.go
- services/horizon/internal/db2/history/orderbook_test.go
- services/horizon/internal/expingest/orderbook.go
- services/horizon/internal/expingest/orderbook_test.go
- services/horizon/internal/expingest/processors/main.go
- services/horizon/internal/expingest/processors/offers_processor.go
- services/horizon/internal/expingest/processors/offers_processor_test.go
- services/horizon/internal/expingest/verify.go
- services/horizon/internal/expingest/verify_range_state_test.go
- services/horizon/internal/resourceadapter/offer.go
- support/db/main.go
- support/db/table.go
<details>
otherwise).
packages.
</details>
This commit aims to fix separation of concerns related to ingestion in Horizon: starting with offers. All methods in `QOffers` interface (and `OffersBatchInsertBuilder`) accept `services/horizon/db2/history.Offer` instead of …
> services/horizon: Fix separation of concerns related to offers ingestion

- services/horizon/internal/db2/history/ingestion.go
- services/horizon/internal/expingest/main.go
- services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
Add `claimable_balances` table to state tables so it's truncated when rebuilding state.
> services/horizon: Add claimable_balances table to state tables to truncate

- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/root.go
- services/horizon/internal/expingest/main.go
Containers and configurations should be allowed to set `--stellar-core-binary-path` regardless of the behavior we want from Horizon.
1. Do not assume that a non-empty `--stellar-core-binary-path` (or `--remote-captive-core-url`) implies captive core should be used (use the pre-existing `--enable-captive-core-ingestion` as a tollgate instead).
2. Allow setting both `--remote-captive-core-url` and `--stellar-core-binary-path` simultaneously, associating a higher priority to the URL.
Fixes #2973
> services/horizon: Refactor handling of stellar-core-binary-path

- services/horizon/internal/app.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Adds Go and process related metrics provided by Prometheus package.
Extra metrics can be useful to debug performance issues.
* Process metrics are available on operating systems with a Linux-style proc filesystem and on Microsoft …
> services/horizon: Add Go and process related metrics

- exp/services/webauth/README.md
- exp/services/webauth/cmd/serve.go
- exp/services/webauth/internal/serve/serve.go
<details>
otherwise).
packages.
</details>
Remove the stellar.toml domain checks that occur on application start. Essentially revert the changes relating to this specific feature that were introduced in 5e82f16273b7ce97e50866cba207bc52f498e9c7.
SEP-10 v2.0.0 highlighted an …
> exp/services/webauth: remove the stellar.toml domain checks

- txnbuild/CHANGELOG.md
- txnbuild/helpers.go
- txnbuild/helpers_test.go
<details>
otherwise).
packages.
</details>
Introduces `func ParseAssetString(string) txnbuild.Asset` and closes #2513.
Essentially, creating an asset from its string representation (and, specific to #2513, determining its type) should be easy and standardized. Refer to #2513 for …
> txnbuild: Adds a helper function to determine asset type from string.

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update the changelogs for clients/horizonclient and txnbuild for the combined v4.1.0 release. Also add a missing empty release details to clients/horizonclient changelog that was missing in the previous release which only changed …
> clients/horizonclient,txnbuild: update changelogs for v4.1.0

- .circleci/config.yml
- services/horizon/cmd/ingest.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Fix missing flag in system.Config.
We were not passing `app.config.EnableCaptiveCoreIngestion` when starting the system. Always disabling captive core.
[TODO or N/A]
> services/horizon: Pass EnableCaptiveCore to config.

- historyarchive/archive.go
- historyarchive/mocks.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
<details>
otherwise).
packages.
</details>
Use `--start-ledger` and `--start-hash` in captive core.
This allow us to do a fast catchup without having to call `new-db` and `catchup` before.
For now we are relying on the history archive to get the ledger header hash. We need to …
> Use --start-ledger and --start-hash in online captive core.

- txnbuild/operation_test.go
<details>
otherwise).
packages.
</details>
Adds a unit test to confirm zero-balance account creation can be done through the SDK.
In response to #3141, rather than just confirming it works once, we can confirm that it'll always work with a real unit test.
> txnbuild: Add unit test for zero-balance account creation

- services/horizon/internal/integration/protocol14_test.go
I broke it when resolving conflicts in https://github.com/stellar/go/pull/3140.
> services/horizon: Fix Protocol 15 integration test

- services/horizon/internal/ingest/main.go
<details>
otherwise).
packages.
</details>
Skip cursor update if using captive core.
Captive core doesn't require stellar-core to keep a cursor since we can control where to start meta data streaming.
[TODO or N/A]
> services/horizon/ingest: Don't try to set cursor if using captive core.

- services/horizon/internal/flags.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Disable stellar core database URL validation if captive core is enabled.
Fix #3129
[TODO or N/A]
> services/horizon: Make stellar core database URL optional if captive core is enabled.

- historyarchive/archive.go
<details>
otherwise).
packages.
</details>
Update `Archive.GetLedgerHeader` to get non-checkpoint ledgers.
History archives contain headers for all ledgers (not just checkpoints) so we should allow getting them. This is also required to sync in standalone network (ledgers <63). …
> historyarchive: Update Archive.GetLedgerHeader to get non-checkpoint headers

- clients/stellarcore/client.go
- clients/stellarcore/client_test.go
Add support for `MANUAL_CLOSE` endpoint to the Stellar Core HTTP client.
We plan to use `MANUAL_CLOSE` in the Horizon Captive Core integration tests. In particular need to quickly close the first 64 ledgers in order to reach the first ledger endpoint and avoid waiting for 5 minutes in each test. More context here https://github.com/stellar/go/pull/3144#issuecomment-713754936
Later on this will come handy to close ledgers right after submitting a transaction, which will remove the remaining waiting time in integration tests.
N/A
> clients/stellarcore: Add Manual Close endpoint to Core's client

- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/processor_runner_test.go
Changed `Protocol version not supported` to `Error checking protocol version is supported` message because an error can be unrelated to protocol version mismatch (ex. error connecting to ledger backend).
> services/horizon: Change protocol version check error

- ingest/io/stats_change_processor.go
- ingest/io/stats_change_processor_test.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Export ledger stats (number of ops and changes) in `/metrics`. Add claimable balances to changes stats.
Close #3133.
To be able to correlate slow ledger with network activitity.
> services/horizon: Export ledger stats in /metrics, add claimable_balance to change stats

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_posix.go
- ingest/ledgerbackend/stellar_core_runner_windows.go
1. Make sure we reset the runner properly (the backend caller was checking whether the runner was nil to re-create it, but it never set it to nil on `CaptiveCoreBackend.Close()`)
2. Avoid potential go-routine leaks by making sure the `start()` goroutine is done in `close()`
3. Guard callers from launching multiple core instances through the same runner.
4. Remove unnecesary generation of the tempdir path on demand (generate it once in the constructor). I think this was done as a workaround to (1)
Overrides #3154 
Fixes #3145 #3159 
N/A
> services/horizon: Make captive core runner more robust

- exp/tools/captive-core-start-tester/main.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/ledger_backend.go
<details>
otherwise).
packages.
</details>
Allow captive core to start from any ledger.
Previously we were limiting the ledgers where online captive core could start since we were always trying to start (captive core) from the previous check-point ledger.
This was probably …
> services/horizon: Allow captive core to start from any ledger.

- exp/tools/captive-core-start-tester/main.go
- historyarchive/archive.go
- historyarchive/mocks.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/ledger_backend.go
- ingest/ledgerbackend/stellar_core_runner.go
Merge a feature branch implementing _run-from_ more of Stellar-Core.
> Merge captive-run-from into master

- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- services/horizon/internal/integration/protocol14_state_verifier_test.go
- services/horizon/internal/test/integration/integration.go
Use Core's `MANUAL_CLOSE` mode in integration tests  so that we don't have to wait for ledgers to be closed (we close them explicitly).
It considerably reduces the execution time of integration tests (From ~13min to ~5min).
Also, it paves the way for enabling integration tests for Captive Core (https://github.com/stellar/go/issues/3153) and contributes towards #3037 .
We are changing the timing in which the production network operates, which makes the tests deviate from a production scenario.
> services/horizon: Update integration tests to use MANUAL_CLOSE

- go.list
- go.mod
- go.sum
Upgrade `go-xdr` to the latest version. The new version fixes two bugs in `Decoder`: https://github.com/stellar/go-xdr/pull/13 https://github.com/stellar/go-xdr/pull/14 ([diff](https://github.com/stellar/go-xdr/compare/71a1e6d555f2...f80a23dac78a))
> all: Update go-xdr to the latest version

- txnbuild/example_test.go
<details>
otherwise).
packages.
</details>
This ports the examples originally added to the documentation (see, for example, stellar/new-docs#263) to the `txnbuild` package as [testable examples](https://blog.golang.org/examples).
Closes #3120.
> txnbuild: Adds unit testable examples for Protocol 15 operations.

- services/horizon/internal/test/integration/integration.go
* Poll Core to close ledgers synchronously
* Wait for manual-closing goroutine when submitting transactions
> services/horizon: Add some manual-close improvements to integration tests

- xdr/json.go
- xdr/json_test.go
<details>
otherwise).
packages.
</details>
Add a custom marshaller for representing the `AbsBefore` timestamp.
Currently, claimable balances which have a `AbsBefore` timestamp beyond year 9999 causes Horizon ingestion to crash. The crash is due to the fact that the `time.Parse()` …
> xdr: Add a custom marshaller for claim predicate timestamp

- services/horizon/docker/Dockerfile
Bump Core in docker-compose image to version 15
I also had to update how core is installed  (using a debian repository instead of S3 because the latter is no longer supported).
It fixes #3169 
N/A
> services/horizon: Bump Core in docker-compose image to version 15

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/3191
The `horizon db migrate` and `horizon db init` commands share the `db-url` command line parameter with the horizon service flags defined in services/horizon/cmd/root.go. The horizon service …
> services/horizon/cmd: Fix db-url flag parsing in horizon db commands

- .circleci/config.yml
For every commit which reaches master, pushing a Horizon Docker image using the short commit commit hash.
It helps us test and run unreleased Horizon versions.
In my particular case, I need it to make changes the Kubernetes resource definitions of Captive Core.
N/A
> services/horizon: Publish a hash-tagged Horizon docker image for every master commit

- .circleci/config.yml
Followup to https://github.com/stellar/go/pull/3190
> services/horizon: Fix typo in Circle's horizon hash-tag image publishing

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
As discussed with @rokopt and @graydon , there is no need to provide a ledger hash when streaming from ledger before the first checkpoint.
It allows Horizon to start ingesting before the first checkpoint is reached (which incurs in a ~5min wait when ingesting from the beginning).
N/A
> services/horizon: Avoid waiting for the first checkpoint in captive-core online mode

- exp/services/webauth/internal/serve/token.go
- txnbuild/transaction.go
- txnbuild/transaction_challenge_example_test.go
- txnbuild/transaction_test.go
resolves stellar/go#3176
Updates tests and `readChallengeTx` function to check for the `homeDomain` parameter within the first Manage Data op key.
> SEP10 v3.0: Add back homeDomain matching constraint for SEP-10 helpers

- txnbuild/CHANGELOG.md
- txnbuild/fee_bump_test.go
- txnbuild/transaction.go
<details>
otherwise).
packages.
</details>
A few functions on the fee bump transaction struct were unintentionally removed in https://github.com/stellar/go/pull/3048/files
This commit reinstates those deleted functions and adds tests for the functions to prevent them from being …
> txnbuild: Reinstate missing fee bump transaction functions

- services/horizon/docker/Dockerfile
Add the experimenatal `captivecore` command from `exp/services/captivecore` to the Horizon container image
In order to test and run the remote captive core in containerized  workloads.
N/A
> services/horizon: Add captivecore command to Horizon container

- txnbuild/CHANGELOG.md
otherwise).
packages.
</details>
Adds a new version to the `txnbuild` changelog (v5.0.0) describing the breaking changes made to the SEP-10 helper functions.
To make the Go SDK compatible with SEP-10 v3.0 (adding back the homeDomain matching constraint)
> txnbuild: updated CHANGELOG.md for v5.0.0

- clients/horizonclient/CHANGELOG.md
Updates `clients/horizonclient`'s CHANGELOG.md by adding empty 4.2 and 5.0 release sections
horizonclient's version must match txnbuild
> horizonclient: updated CHANGELOG.md for v5.0.0

- exp/services/recoverysigner/Makefile
- exp/services/webauth/Makefile
- services/friendbot/Makefile
- services/keystore/Makefile
- services/ticker/Makefile
This change adds org.opencontainers.image.created label to all
docker images.
The label can be used to determine build timestamp which can be
different from image tag or layer push timestamp.
> Update Makefiles to label images with timestamps

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
Fixed `CaptiveStellarCore.IsPrepared` method and added tests. There were two issues:
- Cached ledger meta was not checked,
- Bounded range condition was invalid (last ledger not checked).
> ingest/ledgerbackend: Fix CaptiveStellarCore.IsPrepared to include cached ledger

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
Fixes off-by-one bug in `CaptiveStellarCore.runFromParams`. In https://github.com/stellar/go/commit/21e076a9cc28a959ff3c97e71f9672097cbde4f6 a `TrustedLedgerHashStore` interface was added and used in `CaptiveStellarCore`. However, due to …
> ingest/ledgerbackend: Fix off-by-one in CaptiveStellarCore.runFromParams

- exp/services/captivecore/internal/api.go
- exp/services/captivecore/main.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/3228
Close https://github.com/stellar/go/issues/3229
This commit correctly sets the log level in the captive core api logger. With this fix the captive core api logs are now visible and …
> exp/services/captivecore: Captive Core API fixes

- ingest/ledgerbackend/stellar_core_runner.go
<details>
otherwise).
packages.
</details>
Improves log output:
- `Infof` -> `Info` for non-formatted strings
- Lines w/o pubkey prefix are parsed correctly
When the line from Stellar Core's logs contains `%`, it's interpreted as a formatting directive by the output function …
> services/horizon: Trivial improvements to Stellar Core log parsing

- services/horizon/internal/db2/history/mock_q_offers.go
- services/horizon/internal/db2/history/offers.go
- services/horizon/internal/db2/history/offers_test.go
- services/horizon/internal/db2/history/orderbook_test.go
- services/horizon/internal/ingest/processors/offers_processor.go
- services/horizon/internal/ingest/processors/offers_processor_test.go
<details>
otherwise).
packages.
</details>
Improve performance of `OffersProcessor` by batching offers removals.
Close https://github.com/stellar/go/issues/3246.
Processor durations stats added in https://github.com/stellar/go/pull/3224 revealed that `OffersProcessor` is much …
> services/horizon/ingest: Batch remove offers

- exp/services/captivecore/internal/api.go
- exp/services/captivecore/main.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- services/horizon/CHANGELOG.md
@2opremio doing this sooner because I want to test https://github.com/stellar/go/pull/3249 makes any difference in stg.
> Merge release-horizon-v1.12.0 into master

- services/horizon/docker/Dockerfile
<details>
otherwise).
packages.
</details>
The `STELLAR_CORE_BINARY_PATH` environment variable in the horizon docker image is currently misconfigured. If you try to run the horizon docker image without overriding `STELLAR_CORE_BINARY_PATH` the container will crash with the …
> services/horizon/docker: Fix STELLAR_CORE_BINARY_PATH in horizon docker image

- services/horizon/internal/ingest/main_test.go
- services/horizon/internal/ingest/verify.go
<details>
otherwise).
packages.
</details>
This commit adds improvements to `system.verifyState`:
* Improves waiting time for checkpoint publish. Before this commit, it always waited for 40 seconds. In the new code it checks if checkpoint was published every 5 seconds for a …
> services/horizon/ingest: verifyState improvements

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
While investigating https://github.com/stellar/go/pull/3253 I observed the following crash:
```
horizon_1   | time="2020-11-25T13:16:55.358Z" level=info msg="Preparing range" ledger=462783 pid=1 service=ingest
horizon_1   | panic: …
```
> ingest/ledgerbackend: Fix nil pointer dereference in captive core close

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- xdr/hash.go
- xdr/ledger_close_meta.go
<details>
otherwise).
packages.
</details>
Adds an extra check in `GetLedger` checking if previously read ledger header match the current ledger previous hash.
Close #3256.
`CaptiveStellarCore` reads ledgers in a strict increasing order. It's worth checking if the previous hash …
> ingest/ledgerbackend: Add prev ledger hash check to CaptiveStellarCore

- ingest/ledgerbackend/buffered_meta_pipe_reader.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
<details>
otherwise).
packages.
</details>
Fixes a bug introduced in https://github.com/stellar/go/commit/a10c00015768d34d017b454254ab45377187848f because of which `PrepareRange` and `GetLedger` methods could return an error after Stellar-Core process exit but before all ledgers …
> ingest/ledgerbackend: Remove returning error on Stellar-Core process exit during catchup

- services/horizon/docker/stellar-core-integration-tests.cfg
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- services/horizon/internal/integration/protocol14_state_verifier_test.go
- services/horizon/internal/integration/protocol14_test.go
- services/horizon/internal/test/integration/integration.go
<details>
otherwise).
packages.
</details>
Use `ARTIFICIALLY_ACCELERATE_TIME_FOR_TESTING=true` in integration tests instead of manual close.
Running the horizon integration tests with captive core enabled has turned out to be very difficult due to issues with running Stellar Core …
> services/horizon/internal/test/integration: Use ARTIFICIALLY_ACCELERATE_TIME_FOR_TESTING in integration tests

- exp/services/captivecore/main.go
- exp/tools/captive-core-start-tester/main.go
- ingest/doc_test.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_test.go
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/internal/config.go
- services/horizon/internal/docs/captive_core.md
- services/horizon/internal/flags.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
- support/config/config_option.go
* Rename `--stellar-core-config-path` to `--stellar-captive-core-quorum-path`.
The core config path is automatically generated in captive-core online mode.
`--stellar-captive-core-quorum-path` should point to a toml config file containing
`[QUORUM_SET]` entries, with the same semantics as in the stellar core configuration.
* Add `--stellar-captive-core-http-port` to indicate what port (if any) captive core
shoulf listen on. If `--stellar-core-url` is unset and the local Captive core is enabled,
`--stellar-core-url` will be implicitly use `http://localhost:<stellar_captive_core_http_port>`
* Remove unused entries in `CaptiveStellarCore`
Closes #3211
> services/horizon: Refactor Captive Core configuration flags

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
- services/horizon/internal/test/integration/integration.go
<details>
otherwise).
packages.
</details>
In https://github.com/stellar/go/pull/3201 we assumed it was possible to omit the `--start-at-hash` parameter when starting from the genesis ledger. However, Stellar Core actually fails when attempting that command. The `--start-at-hash` …
> ingest/ledgerbackend: Fix captive core bug where --start-at-hash parameter is omitted

- exp/services/captivecore/main.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
- services/horizon/internal/ingest/main.go
<details>
otherwise).
packages.
</details>
There is a `log` field in the `stellarCoreRunner` struct. The field is considered optional and the intended behavior is that if `log` is nil then instead of using `log` to print a message we will print it to stdout using `fmt.Println()`. …
> ingest/ledgerbackend: Fix possible nil pointer when accessing captive core logger

- services/horizon/docker/stellar-core-standalone.cfg
<details>
otherwise).
packages.
</details>
Remove `RUN_STANDALONE=true` from the stand alone configuration for the docker compose setup. 
When `RUN_STANDALONE` is set to true it prevents stellar core from accepting any peer connections. This prevents you from running a stand …
> services/horizon/docker: Remove RUN_STANDALONE=true from stellare-core-standalone.cfg

- ingest/ledgerbackend/stellar_core_runner.go
<details>
otherwise).
packages.
</details>
When using a captive core append file consisting of:
```
PEER_PORT=11725
UNSAFE_QUORUM=true
FAILURE_SAFETY=0
[[VALIDATORS]]
NAME="local_core"
HOME_DOMAIN="core.local"
PUBLIC_KEY="GD5KD2KEZJIGTC63IGW6UMUSMVUVG5IHG64HUTFWCHVZH2N2IBOQN7PS" …
```
> ingest/ledgerbackend: Place history section at the end of the captive core config file

- services/horizon/cmd/db.go
- services/horizon/internal/ingest/parallel.go
- services/horizon/internal/integration/db_test.go
- services/horizon/internal/test/integration/integration.go
They required:
1. Adding new integration test infrastructure to:
* Shutdown the integration test early (needed for resuming a Horizon session)
* Obtain the Horizon configuration (in order to reuse it with the re-ingest command)
2. Modifying the `db reingest range` command (in order to make it testeable). The flag-parsing
part and intialization logic have been split out and the latter is used by the integration test.
Fixes https://github.com/stellar/go/issues/3248
> services/horizon: Add re-ingestion and resume integration tests

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
The stellarCoreRunnerFactory function can be simplified by removing the `captiveCoreConfigAppendPath string` argument. Also, I removed the `c.stellarCoreRunner == nil` check because it was not necessary.
[N/A]
> ingest/ledgerbackend: Clean up stellarCoreRunnerFactory

- support/http/main.go
- support/http/main_test.go
<details>
otherwise).
packages.
</details>
Adding the field `TCPKeepAlive` to support/http Config
Gives the option to specify a tcp keep alive timeout for the graceful server. Otherwise it always defaults to 0s
n/a
> support/http: add option for adding tcp keep alive to server

- .circleci/config.yml
- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
Flips a default value of `ENABLE_CAPTIVE_CORE_INGESTION` from `false` to `true`.
Close #3279.
Horizon 2.0.0 Beta will run `CaptiveStellarCore` backend by default.
I was thinking about creating a new flag `LEDGER_BACKEND` that would …
> services/horizon: Enable captive core by default

- protocols/horizon/main.go
- services/horizon/internal/app.go
- services/horizon/internal/app_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/main_test.go
- services/horizon/internal/init.go
- services/horizon/internal/ledger/main.go
- services/horizon/internal/resourceadapter/root.go
<details>
otherwise).
packages.
</details>
This commit adds:
* `history_latest_ledger_closed_at` to root resource that determines the latest ingested ledger close time,
* `horizon_history_latest_ledger_closed_ago_seconds` to `/metrics` that return time in seconds since the latest …
> services/horizon: Add latest ledger closed_at metrics

- exp/services/captivecore/main.go
- exp/tools/captive-core-start-tester/main.go
- ingest/doc_test.go
- ingest/ledgerbackend/buffered_meta_pipe_reader.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_posix.go
- ingest/ledgerbackend/stellar_core_runner_test.go
- ingest/ledgerbackend/stellar_core_runner_windows.go
- services/horizon/internal/ingest/main.go
<details>
otherwise).
packages.
</details>
This PR implements robust shutdown behavior in `CaptiveStellarCore` by embedding a context in `stellarCoreRunner`.
`CaptiveStellarCore` exposes the following functions:
* `PrepareRange()`
* `IsPrepared()`
* `GetLedger()`
* …
> ingest/ledgerbackend: Use context to handle termination and cleanup of captive core

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
Remove the behavior in `CaptiveStellarCore` where the instance is automatically closed after reading the last ledger in the range.
Once `CaptiveStellarCore` is closed functions like `GetLatestLedgerSequence()` return errors like "session …
> ingest/ledgerbackend: Dont automatically close after reading last ledger in range

- services/horizon/internal/docs/captive_core_migration.md
This should walk a user to transitioning from Horizon v1.x -> v2.0-beta. There are two scenarios covered:
- everything on a single machine, so essentially the user can drop Core and replace it w/ Captive Core
- three machines: two Horizons (with only one of them ingesting, just for diversity) and one (remote) Captive Core. It should be relatively self-explanatory to readers that Captive Core just replaces their existing Core instance. Though I did test all of these on the same machine (just varied ports, etc.), it should still be accurate.
Here's a [direct link](https://github.com/stellar/go/blob/66f3bab24f30f9a7ece39ecb2ceb587b15302d45/services/horizon/internal/docs/captive_core_migration.md) to the rendered Markdown. This should be merged into `captive_core.md` once @2opremio's #3283 is …
> services/horizon/docs: Adds migration/deployment guide for Captive Core.

- services/horizon/internal/docs/captive_core.md
In #3310, the Captive Core documentation merge undid some changes, likely due to the fact that I merged #3302 into master right before this merge.
This is pretty apparent when you look at [the diff of said file](https://github.com/stellar/go/pull/3310/files#diff-dcbfcf6a4881548aa52f3762303b0f1cf6ad6441a011cfee5273961012619e5eL50-R66) (e.g. capitilization fixes are undone, I dropped the TOML to keep them in one place, etc.), so this should be an easy approve :heavy_check_mark:.
> services/horizon: Restore old fixes to the Captive Core documentation

- services/friendbot/friendbot.cfg
- services/friendbot/init_friendbot.go
- services/friendbot/init_friendbot_test.go
- services/friendbot/internal/account.go
- services/friendbot/internal/friendbot_test.go
- services/friendbot/internal/minion.go
- services/friendbot/internal/minion_test.go
- services/friendbot/main.go
<details>
otherwise).
packages.
</details>
This PR is reducing the friendbot minion (channel account) creation batch from 100 to 50, and allows for retries.
Also, it adds tests for the `createMinionAccounts` method  
closes https://github.com/stellar/nebula/issues/84
When network …
> services/friendbot: reduce friendbot minion creation batch to 50, allow for retries, add tests

- ingest/stats_change_processor.go
- ingest/stats_ledger_transaction_processor.go
Ensure that `StatsLedgerTransactionProcessor` conforms to `LedgerTransactionProcessor` and `StatsChangeProcessor` conforms to `ChangeProcessor`.
This is our convention everywhere else.
> ingest: Conform processor implementations to their interfaces

- ingest/ledgerbackend/ledger_backend.go
- ingest/ledgerbackend/range.go
<details>
otherwise).
packages.
</details>
Moves `ingest.Range` to its own `range.go` rather than keeping it around in `ledger_backend.go`.
When I open a file called `ledger_backend.go`, I would expect the first thing I see to be, well, `type LedgerBackend ...` (cc #3110).
> ingest: Move the `Range` object to its own file.

- services/horizon/internal/docs/captive_core.md
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/3322
Add documentation for running Captive Core on a private Stellar network.
It may be possible to configure Captive Core so that it is a validator in the private network. However, I decided …
> services/horizon/internal/docs: Add documentation for running Captive Core on a private network

- protocols/horizon/main.go
- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/claimable_balances_batch_insert_builder_test.go
- services/horizon/internal/db2/schema/bindata.go
- services/horizon/internal/db2/schema/migrations/43_add_claimable_balances_flags.sql
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/verify.go
- services/horizon/internal/ingest/verify_range_state_test.go
- services/horizon/internal/ingest/verify_test.go
- services/horizon/internal/resourceadapter/claimable_balances.go
- services/horizon/internal/resourceadapter/claimable_balances_test.go
- xdr/account_flags.go
- xdr/account_flags_test.go
- xdr/claimable_balance_entry.go
- xdr/claimable_balance_entry_test.go
- xdr/claimable_balance_flags.go
- xdr/claimable_balance_flags_test.go
* ALTER the claimable_balances SQL table to add a flags column
* Add ingestion support for for the new flag (including verification)
* Add support to the Horizon Go client
* Extend Claimable balance effects to include the flag
Part of #3348
> [CAP 35] Add support for new Claimable Balance clawback flag

- historyarchive/range.go
- ingest/checkpoint_change_reader.go
- ingest/checkpoint_change_reader_test.go
- ingest/errors.go
<details>
otherwise).
packages.
</details>
Introduces a new error for when users pass a sequence number that doesn't correspond to a checkpoint ledger.
This may end up being a common issue for consumers of the ingestion library since checkpoint frequency is a subtle point mostly …
> ingest: Introduce a new error for invalid checkpoint sequences

- .circleci/config.yml
The circle ci jobs which build and publish docker images have been failing with the following error:
```
#!/bin/bash -eo pipefail
echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
TAG=$(git rev-parse --short HEAD)
docker build -f services/horizon/docker/Dockerfile -t stellar/horizon:$TAG .
docker push stellar/horizon:$TAG
/bin/bash: docker: command not found
Exited with code exit status 127
CircleCI received exit code 127
```
I believe the issue is that the `docker` client is not available in `buildpack-deps:stretch` so I have switched back to using `circleci/buildpack-deps:stretch`
> horizon: Fix circle ci jobs which publish docker images

- ingest/change_compactor.go
- ingest/change_compactor_test.go
- services/horizon/internal/ingest/processors/account_data_processor.go
- services/horizon/internal/ingest/processors/accounts_processor.go
- services/horizon/internal/ingest/processors/asset_stats_processor.go
- services/horizon/internal/ingest/processors/claimable_balances_processor.go
- services/horizon/internal/ingest/processors/offers_processor.go
- services/horizon/internal/ingest/processors/signers_processor.go
- services/horizon/internal/ingest/processors/trust_lines_processor.go
<details>
otherwise).
packages.
</details>
Renames `NewLedgerEntryChangeCache` to `NewChangeCompactor` within the library, its test suite, and all uses within horizon/internal/ingest.
#3332 started this process but left the constructor unchanged. This completes the rename so …
> ingest: Finish renaming LedgerEntryChangeCache to ChangeCompactor.

- .circleci/config.yml
<details>
otherwise).
packages.
</details>
Use the official docker images for publishing Horizon to docker.
This is a follow up to #3367 that changed us back to using the CircleCI convenience images after I made change #3347. Instead of returning to use the buildpack-deps images …
> all: use official docker images for publishing

- clients/horizonclient/client.go
Fix for  clients/horizonclient/client.go sendRequestURL method context timeout. 
Redundant multiply horizonTimeout on time.Second creates timeout equal to 10^18 nanoseconds (if horizonTimeout was set as 1 second (by default) )
>  clients/horizonclient fix request timeout

- protocols/horizon/effects/main.go
- protocols/horizon/operations/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/resourceadapter/effects.go
- services/horizon/internal/resourceadapter/operations.go
- txnbuild/allow_trust.go
- txnbuild/operation.go
- txnbuild/set_trust_line_flags.go
- txnbuild/set_trustline_flags_test.go
- xdr/xdr_generated.go
`SetTrustLineFlags` superseeds `AllowTrust` operation, which is now deprecated.
`SetTrustLineFlags` emits a new effect: `EffectTrustlineFlagsUpdated`, which is very similar to the
pre-existing `EffectAccountFlagsUpdated`.
The effects emitted by `AllowTrust` (`EffectTrustlineAuthorized`, `EffectTrustlineAuthorizedToMaintainLiabilities` and
`EffectTrustlineDeauthorized`) are now deprecated. `AllowTrust` will keep emitting them for now.
In addition`AllowTrust` will start emitting `EffectAccountFlagsUpdated`, so that users don't have to parse both sets of effects. Note that the contrary isn't true, `SetTrustLineFlags` won't emit `EffectTrustlineAuthorized`, `EffectTrustlineAuthorizedToMaintainLiabilities` nor `EffectTrustlineDeauthorized`.
Part of #3348
> [CAP35] Add support for SetTrustLineFlags operation

- txnbuild/CHANGELOG.md
- txnbuild/fee_bump_test.go
- txnbuild/helpers_test.go
- txnbuild/manage_data_test.go
- txnbuild/signers_test.go
- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Remove `TxEnvelope()` from `Transaction` and `FeeBumpTransaction`. Now `ToXDR()` is the only function which produces XDR transaction envelopes.
It simplifies the API to just have one function which produces an XDR transaction envelope. …
> txnbuild: Remove TxEnvelope() functions from txnbuild

- txnbuild/allow_trust.go
- txnbuild/begin_sponsoring_future_reserves_test.go
- txnbuild/clawback.go
- txnbuild/clawback_claimable_balance.go
- txnbuild/clawback_claimable_balance_test.go
- txnbuild/clawback_test.go
- txnbuild/create_claimable_balance_test.go
- txnbuild/end_sponsoring_future_reserves_test.go
- txnbuild/helpers.go
- txnbuild/helpers_test.go
- txnbuild/operation.go
- txnbuild/operation_test.go
- txnbuild/revoke_sponsorship_test.go
- txnbuild/set_trust_line_flags.go
- txnbuild/set_trustline_flags_test.go
* Add support for the ClawbackClaimableBalance Operation
* Improve testing (and fix a bug) for the Clawback Operation
* Rename `validateAllowTrustAsset` to `validateAssetCode`
* Move the `roundTrip` testing function to a common file and give it the more descriptive name `testOperationsMarshallingRoundtrip`
Part of #3348
> [CAP 35] Finish SDK support for CAP35

- .circleci/config.yml
<details>
otherwise).
packages.
</details>
Update Go 1.16 builds to use rc1 instead of beta1.
Release candidate 1 was released, we should try it out.
N/A
> all: run go1.16 builds with rc1

- .circleci/config.yml
Update golang to 1.14.14 and 1.15.7 because of CVE-2021-3115.
More information:
* https://groups.google.com/g/golang-announce/c/mperVMGa98w
* https://blog.golang.org/path-security
> Update golang to 1.14.14 and 1.15.7

- exp/services/recoverysigner/Makefile
- exp/services/webauth/Makefile
- services/friendbot/Makefile
- services/keystore/Makefile
- services/ticker/Makefile
Add --pull flag to docker builds
By default if images exist locally they are used for builds.
This change will ensure we always pull latest versions which ensures we get all security patches.
> Add --pull flag to docker builds

- historyarchive/archive.go
- historyarchive/mocks.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/3340
Previously, we had a HistoryArchiveBackend implementation which used the history archives to fetch transactions belonging to a specific ledger. We decided to remove the implementation in …
> Add function to fetch ledgers from history archive

- .github/workflows/codeql-analysis.yml
<details>
otherwise).
packages.
</details>
Enable GitHub's CodeQL static analysis to run periodically and on PRs to `master`. It will open issues in the Security tab when it finds problems.
To get feedback about issues we might miss.
I wanted to enable this a while ago but there …
> all: enable codeql code analysis

- services/horizon/internal/integration/protocol14_state_verifier_test.go
As explained in https://github.com/stellar/go/issues/3371#issuecomment-772003130 this commit is a quick fix for `TestProtocol14StateVerifier` test.
> services/horizon: Quick fix for TestProtocol14StateVerifier

- ingest/tutorial/getting-started.md
> ingest: Fixes the link to the Captive Core deployment docs

- .circleci/config.yml
<details>
otherwise).
packages.
</details>
Update go versions to latest minor versions
Go 1.14.15 and 1.15.8 were released yesterday.
Also it looks like we are using an older version of Go in one part of the build process.
N/A
> all: update go versions to latest minor versions

- support/scripts/build_release_artifacts/main.go
Update app version string in `build_release_artifacts` script to match build other pipelines.
We want final binaries to be the same to allow reproducible builds.
This will change the version string for other apps built by `build_release_artifacts`.
> all: Update app.version string build flag

- services/horizon/internal/scripts/check_release_hash/Dockerfile
- services/horizon/internal/scripts/check_release_hash/README.md
- services/horizon/internal/scripts/check_release_hash/check.sh
- support/scripts/build_release_artifacts/main.go
Adds a docker image to allow comparing hashes of GitHub builds and local builds. Remove `buildTime` flag from build tags in `build_release_artifacts` to make the builds reproducible.
Creating reproducible builds and checking them will make our release process more secure.
It doesn't check Debian packages yet. Will add this in a separate PR.
> services/horizon: Add docker image for checking reproducible builds

- services/horizon/internal/scripts/check_release_hash/Dockerfile
- support/scripts/build_release_artifacts/main.go
I checked for the last time before releasing Horizon if the binaries' hashes match and they didn't. This commit fixes the issues:
* Updates `check_release_hash` to use Golang version we use in Circle.
* Move `-ldflags` from command arguments to env variable. This has the same effect but apparently the hash was different than the binary built by `stellar/packages`.
> Fix minor issues connected to reproducible builds

- txnbuild/CHANGELOG.md
- txnbuild/create_claimable_balance_test.go
- txnbuild/transaction.go
<details>
otherwise).
packages.
</details>
ClaimableBalanceID() builds an xdr.OperationId using the operation source account and the sequence number of the operation source account. It seems like we should be using the transaction source account and the sequence number found in …
> txnbuild: Use correct account in ClaimableBalanceID()

- historyarchive/archive_pool.go
- historyarchive/pool.go
- ingest/ledgerbackend/captive_core_backend.go
<details>
otherwise).
packages.
</details>
This is an improvement over #3375 which just chooses a random URL from the list. Instead, we should actually create a pool of all history archive connections and cycle through them randomly for each HA-related operation we need.
With …
> historyarchive: Introduce a History Archive pool that's selected from for all calls

- historyarchive/archive_pool.go
<details>
otherwise).
packages.
</details>
`NewArchivePool() ` returns a `ArchivePool` instance which I expected to conform to `ArchiveInterface`. 
However, it turns out that `ArchivePool` does not conform to the interface because all of its functions are defined on pointer …
> historyarchive: Fix ArchivePool functions

- services/horizon/internal/docs/admin.md
- services/horizon/internal/httpx/middleware.go
This commit removes `Starting request` log entries from Horizon. It also changes `Finished request` to `HTTP request`
`Finished request` contains exactly the same subset of fields as `Starting request`. This change will decrease number of log entries from HTTP request by around a half.
N/A
> services/horizon: Remove "Starting request" log entries

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
Adds a new metric: `horizon_ingest_local_latest_ledger` that exposes the local latest ledger sequence which is the last ledger ingested by this ingesting instance.
While checking metrics after Horizon 2.0.0 RC deployment I noticed that existing metric: `horizon_history_latest_ledger` can be confusing because it loads the ledger sequence from DB. However, it's possible that one of ingesting instances is out of sync and is waiting for Stellar-Core sync. It would be great to be able to measure the delay in ledgers and a new metric allows this.
> services/horizon: Add metric with local latest ledger

- .circleci/config.yml
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- txnbuild/clawback.go
- txnbuild/clawback_test.go
- txnbuild/set_trust_line_flags.go
- txnbuild/set_trustline_flags_test.go
- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
This follows the latest XDR change from CAP35, which I somehow missed ( https://github.com/stellar/stellar-protocol/pull/852 )
Part of #3348
> [CAP 35] Replace AssetCode by Asset in new operations

- services/horizon/internal/actions/root.go
- services/horizon/internal/app.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
This commit adds two new metrics connected to Stellar-Core:
* `horizon_ ingest_captive_stellar_core_synced` determines if Captive Stellar-Core instance started by ingesting server is synced.
* `horizon_stellar_core_synced` determines if Stellar-Core defined by `--stellar-core-url` is synced.
We want to detect when connected Stellar-Core is out of sync without having to check Stellar-Core metrics.
The reason for adding two separate metrics is that in some deployments Stellar-Core connected via `--stellar-core-url` and Captive Stellar-Core are separate instances.
> services/horizon: Add Stellar-Core sync metrics

- Dockerfile
<details>
otherwise).
packages.
</details>
Remove the Dockerfile in the root directory of the monorepo.
Each individual service in the monorepo has their own Dockerfile (e.g. services/horizon/docker/Dockerfile). There are no CircleCI jobs or scripts which rely on the root …
> all: Remove monorepo Dockerfile

- services/horizon/internal/flags.go
This commit updates the message displayed when captive-core params are missing.
This is done to improve experience of users migrating from previous Horizon version
> services/horizon: Add a link to 2.0.0 Migration Guide on missing params

- services/horizon/internal/docs/captive_core.md
We don't need this table at the top of the file and it causes confusion due to the "fake" URL. We should put it back after the "Run an API Server" docs are updated with a Captive Core guide.
> services/horizon: Drop YAML header from Captive Core doc

- services/horizon/internal/scripts/check_release_hash/README.md
- services/horizon/internal/scripts/check_release_hash/check.sh
Update `check_release_hash` to check specific Debian package version. Also update the script to exit on errors.
> services/horizon: Install specific Debian package version in check_release_hash

- services/horizon/internal/docs/captive_core.md
The docs will now reference the stable 2.0 release.
They still reference the 2.0-beta release.
> services/horizon: Update the migration guide to reference v2.0 directly

- services/horizon/internal/actions/asset.go
<details>
otherwise).
packages.
</details>
The previous error message:
> cursor must contain exactly one colon
did not accurately reflect the actual problem which, according to the [relevant documentation](https://developers.stellar.org/api/resources/assets/list/), actually comes …
> services/horizon: Update asset error message to reflect the actual issue

- .circleci/config.yml
- services/horizon/docker/Dockerfile.dev
- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/internal/integration/protocol16_test.go
- services/horizon/internal/test/integration/integration.go
The idea behind this is to separate cap35 tests (which require an unreleased Core version) so that we can merge the `cap35` branch into master without tainting the other tests before Core makes an official release with CAP35 support.
Part of #3348
> [CAP 35] Separate CAP35 tests (so that we can merge cap35 to master)

- support/http/xff_middleware.go
- support/http/xff_middleware_test.go
<details>
otherwise).
packages.
</details>
This commit adds a new middleware: `XFFMiddleware` to `support/http` package.
The middleware we currently use in Horizon: `github.com/sebest/xff` does not have support for AWS in which the client header is …
> support/http: Add X-Forwarded-For middleware

- .circleci/config.yml
- exp/services/recoverysigner/docker/Dockerfile
- exp/services/webauth/docker/Dockerfile
- exp/tools/dump-ledger-state/Dockerfile
- services/friendbot/docker/Dockerfile
- services/horizon/docker/Dockerfile.dev
- services/horizon/internal/scripts/check_release_hash/Dockerfile
- services/keystore/docker/Dockerfile
- services/regulated-assets-approval-server/docker/Dockerfile
- services/ticker/docker/Dockerfile
- services/ticker/docker/Dockerfile-dev
Update all docker images to use Go 1.16.2 and Ubuntu 18.04.
Go 1.14 is no longer supported or receiving security updates. Ubuntu needs upgrading to align the versions of Ubuntu in the runtime images with the build images.
N/A
If I have requested you review this PR it is because I believe you own or are the most knowledgeable person for a service impacted by this change. Please review the PR, and handle, or delegate someone else to handle, any deployment after merge for your respective service.
@accordeiro Ticker
@bartekn @ire-and-curses Horizon
@marcelosalloum Friendbot, Regulated Assets
@leighmcculloch Webauth, Recoverysigner, Keystore
> all: update all docker images to use Go 1.16.2

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/stellar_core_runner.go
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
This introduces the `--captive-core-log-path` parameter, which sets Stellar Core's `LOG_FILE_PATH` in the auto-generated configuration accordingly. If it's not set, Horizon will continue to log Captive Core's output to its log path with …
> services/horizon: Allow customization of the Captive Core log file.

- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
This commit improves Captive Stellar-Core flags validation:
* Passing ingestion flags (Captive Stellar-Core or Stellar-Core DB params) without enabling ingestion (`--ingest`) throws an error. Close #3473.
* Allow starting HTTP server …
> services/horizon: Improve Captive Stellar-Core validation

- protocols/horizon/main.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/actions/asset_test.go
- services/horizon/internal/db2/history/asset_stats.go
- services/horizon/internal/db2/history/asset_stats_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/schema/bindata.go
- services/horizon/internal/db2/schema/migrations/43_asset_stat_trust_line_flags.sql
- services/horizon/internal/db2/schema/migrations/44_asset_stat_accounts_and_balances.sql
- services/horizon/internal/docs/reference/endpoints/assets-all.md
- services/horizon/internal/docs/reference/resources/asset.md
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/processors/asset_stats_processor.go
- services/horizon/internal/ingest/processors/asset_stats_processor_test.go
- services/horizon/internal/ingest/processors/asset_stats_set.go
- services/horizon/internal/ingest/processors/asset_stats_set_test.go
- services/horizon/internal/ingest/verify.go
- services/horizon/internal/ingest/verify_range_state_test.go
- services/horizon/internal/resourceadapter/asset_stat.go
- services/horizon/internal/resourceadapter/asset_stat_test.go
<details>
otherwise).
packages.
</details>
Include unauthorized assets on the /assets endpoint, and expose the trustline flags.
As per issue #3241.
[TODO or N/A]
> services/horizon: Issue #3241, Include unauthorized assets on /assets

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_test.go
- ingest/ledgerbackend/testdata/expected-offline-core.cfg
- ingest/ledgerbackend/testdata/expected-offline-with-appendix-core.cfg
- ingest/ledgerbackend/testdata/expected-online-core.cfg
- services/horizon/CHANGELOG.md
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
This introduces the `--captive-core-peer-port=11625` parameter, which allows users to control which port Captive Core binds to when joining the Stellar network swarm.
Closes #3441.
No validation is done on the actual value passed in (aside from type == uint), so non-port values work. However, then Core will fail to start (with an appropriate error message, of course). We could try to "fail fast" instead, but we don't do this for the HTTP port either.
> services/horizon: Add flag to choose a custom peering port for Captive Core

- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
Checks the PATH for `stellar-core` earlier.
After #3477, it's no longer possible to run Captive Core without setting the Core binary path. Demo:
```bash
export DATABASE_URL='postgres://postgres@localhost:5432/horizon?sslmode=disable' …
```
> services/horizon: Find the stellar-core binary in the PATH earlier, if possible

- services/horizon/docker/verify-range/start
<details>
otherwise).
packages.
</details>
In https://github.com/stellar/go/commit/06190c5aa74be0d699800dd96ba870ee13a9917b we added a new effect: `EffectTrustlineFlagsUpdated` that breaks diff checks in `verify-range` image. This PR removes all `EffectTrustlineFlagsUpdated` …
> services/horizon/docker/verify-range: Ignore EffectTrustlineFlagsUpdated effects

- services/horizon/docker/verify-range/start
This PR fixes the Horizon flags in the verify-range range container (namely due to #3507 and other flag issues in Horizon 2.0).
See https://github.com/stellar/go/pull/3509 for an alternative PR using Captive Core.
> verify-range: (alternative 1) Fix Horizon invocation flags

- services/horizon/docker/verify-range/start
This reverts commit 086f916f1b476f07a1278f64f09a8783f907f638 that was there just for diff testing between Horizon 2.0.0 and Horizon 2.1.0 (as explained in https://github.com/stellar/go/issues/3512).
Close #3512.
> Revert "services/horizon/docker/verify-range: Ignore EffectTrustlineFlagsUpdated effects (#3511)"

- historyarchive/archive_test.go
- historyarchive/scan.go
<details>
otherwise).
packages.
</details>
This change fixes a bug in archivist that causes it to mis-report archives as "not missing files" when they are, in fact, missing files. Fairly serious condition. It's caused on archives accessed through http -- which resorts to a …
> historyarchive: Archivist slow scan missing

- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/processor_runner_test.go
The CAP 35 release in core is scheduled for protocol 17 so we should set  `MaxSupportedProtocolVersion` to 17
> services/horizon/internal/ingest: Bump MaxSupportedProtocolVersion to 17

- strkey/main.go
Found this while working on #3527
> strkey: Check for leftover character to be in the expected alphabet

- exp/services/recoverysigner/internal/db/db_test.go
<details>
otherwise).
packages.
</details>
Extracted from https://github.com/stellar/go/pull/3545. I fixed `TestOpen_openAndPingFails`. The two issues were, Open on port 0, and sometimes the error would be different due to IPv6. Now it handles both ipv4 and ipv6, as well as …
> exp/services/recoverysigner: Fix TestOpen_openAndPingFails

- services/horizon/internal/config.go
- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
This commit adds `--skip-migrations-check` flag that, when set, will skip checking if there are any migrations required to start Horizon.
When checking if there are any migrations required Horizon calls `migrate.PlanMigration` which …
> services/horizon: Add --skip-migrations-check flag

- services/friendbot/docker/Dockerfile
Switch friendbot docker image to 20.04 base
We are migrating other images to 20.04, this change will keep friendbot consistent with other projects.
> Switch friendbot to 20.04 image

- services/horizon/internal/app.go
- services/horizon/internal/app_test.go
Fixes #3344
<details>
otherwise).
packages.
</details>
Add 1s timeout to total runtime of `horizon.App.Tick`.
See https://github.com/stellar/go/issues/3344
Just a single timeout, not per-item. But that seems to make sense given we want them all to complete within 1s total.
> services/horizon: Add 1s timeout to horizon.App.Tick

- ingest/ledger_transaction.go
- ingest/ledger_transaction_reader.go
- ingest/ledger_transaction_test.go
- services/horizon/internal/db2/history/fee_bump_scenario.go
- services/horizon/internal/db2/history/transaction_batch_insert_builder.go
- services/horizon/internal/db2/history/transaction_batch_insert_builder_test.go
- services/horizon/internal/ingest/processors/claimable_balances_transaction_processor_test.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/ledgers_processor_test.go
- services/horizon/internal/ingest/processors/participants_processor.go
- services/horizon/internal/ingest/processors/participants_test.go
- services/horizon/internal/ingest/processors/trades_processor_test.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/test/transactions/main.go
Fixes #3491 
Alternative to #3555
> services/horizon: Rename LedgerTransaction's Meta to UnsafeMeta

- protocols/horizon/effects/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/resourceadapter/effects.go
- services/horizon/internal/resourceadapter/effects_test.go
> horizon: Test consistency and coverage of effect typenames (and cleanup unused effects)

- protocols/horizon/operations/main_test.go
- services/horizon/internal/codes/main_test.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/stats_ledger_transaction_processor_test.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/resourceadapter/operations_test.go
- xdr/main.go
Part of #3430
I incorporated new tests, which use `xdr`'s  `operationTypeMap` (now  exported `OperationTypeToStringMap`) to go over all possible operations, even when we incorporate new ones.
The idea is that, from now on, every time we add a new XDR operation (i.e. through a CAP), the developer gets guided on what needs to be modified based on the failing tests.
The tests I added can be considered finicky, but it's hard to do it generically in a robust way.
> services/horizon: Test full coverage of operation type switches

- exp/services/recoverysigner/docker/Dockerfile
Move recoverysigner docker image to 20.04 base
We're moving other images to 20.04 so this change improves consistency.
> Move recoverysigner docker image to 20.04 base

- services/ticker/Makefile
- services/ticker/docker/Dockerfile
* switch to ubuntu 20.04 base image
* add --pull to the Makefile to ensure we always use latest images
* add image.created label
Ubuntu 16.04 is nearly EOL. Other changes improve consistency
> Switch to ubuntu 20.04 base image

- exp/services/webauth/docker/Dockerfile
Switch webauth to ubuntu 20.04 base
We are moving other images to 20.04, this change improves consistency across SDF docker images
> Switch webauth to ubuntu 20.04 base

- services/horizon/internal/config.go
- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
This commit reverts https://github.com/stellar/go/commit/7c92b23f34181a00a510914d80fc458372aa13b0 and changes the DB migrations behaviour to only trigger on ingesting instances.
When checking if there are any migrations required Horizon …
> services/horizon: Apply and check migrations on ingesting instances only

- .circleci/config.yml
- services/horizon/docker/verify-range/dependencies
> services/horizon: Build and test verify-range Docker image

- services/regulated-assets-approval-server/README.md
- services/regulated-assets-approval-server/cmd/migrate.go
- services/regulated-assets-approval-server/cmd/serve.go
- services/regulated-assets-approval-server/internal/db/db.go
- services/regulated-assets-approval-server/internal/db/db_test.go
- services/regulated-assets-approval-server/internal/db/dbmigrate/dbmigrate.go
- services/regulated-assets-approval-server/internal/db/dbmigrate/migrations/2021-05-05.0.initial.sql
- services/regulated-assets-approval-server/internal/db/dbtest/dbtest.go
- services/regulated-assets-approval-server/internal/db/dbtest/dbtest_test.go
- services/regulated-assets-approval-server/internal/serve/serve.go
- services/regulated-assets-approval-server/main.go
<details>
otherwise).
packages.
</details>
Add a database support to the sep8 regulated assets server.
To store the KYC statuses.
N/A
> `services/regulated-assets-approval-server/internal/db`: add a database support to the sep8 regulated assets server

- services/horizon/internal/app.go
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/httpx/middleware.go
- services/horizon/internal/httpx/router.go
- services/horizon/internal/httpx/server.go
- services/horizon/internal/init.go
- services/horizon/internal/render/problem/problem.go
<details>
otherwise).
packages.
</details>
* Adds a new `RO_DATABASE_URL` that allows setting a connection to a read-replica DB.
* When the flag is set:
* A new middleware checking if the read-replica is behind a primary DB will be enabled. If such check fails three times, the …
> services/horizon: Add middleware for checking read-replica lag

- .circleci/config.yml
- services/horizon/docker/Dockerfile.dev
- services/horizon/docker/core-start.sh
- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/internal/integration/protocol16_test.go
<details>
otherwise).
packages.
</details>
This reverts commit 72c01edaa63e8c903e5e99666545e5fd8d59ae2b. (#3585)
It resulted in captive core crashing, and the integration tests hanging.
- @2opremio wdyt?
> services/horizon: Revert "Use Core 17 for CI (and disable cap35-specific job) (#3585)"

- services/horizon/internal/httpx/middleware.go
<details>
otherwise).
packages.
</details>
If `Referer` is not set, log the `Origin` instead.
So we get more complete stats on inbound traffic sources. Browsers do not always set the `Referer` header, but do set `Origin` on all cross-origin requests (most of our requests).
[TODO …
> Fallback to Origin header if Referer is not set

- services/horizon/internal/db2/history/orderbook.go
- services/horizon/internal/db2/history/trade.go
- services/horizon/internal/init.go
- support/db/metrics.go
<details>
otherwise).
packages.
</details>
- Change db metric subsystem (e.g. `ingest`, or `history`), to a label for easier aggregation.
- Add an explicit query type to a couple complex raw-sql queries so they don't show up as `undefined` in the metrics.
[TODO or N/A]
> services/horizon: Fixup db metrics

- services/regulated-assets-approval-server/docker/Dockerfile
Include `/app/internal/db/dbmigrate/migrations/` and their files to docker image
The init deployed container is failing because the migration .sql files are not included in the image.
We need to copy them from the codebase into the image.
[Slack Thread](https://stellarfoundation.slack.com/archives/C02U19A2A/p1621380918020400)
> `regulated-assets-approval-server/`: Copy migrations to image

- services/regulated-assets-approval-server/internal/serve/kyc-status/get_detail_handler.go
<details>
otherwise).
packages.
</details>
Properly render kyc-status GET response
kyc-status GET response was failing to render due to the use of `httpjson.RenderStatus` without populating the status code.
Thus resulting in a 502 error
N/A
> regulated-assets-approval-server/internal/serve/kyc-status/get_detail_handler.go: BUGFIX get request render json

- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Add missing test for when time bounds are not provided, where an error is expected.
It looks like this behavior is not tested and I'm changing the behavior of this functionality for CAP-21, and it would be helpful if it was tested so …
> txnbuild: add missing test for timebounds

- txnbuild/CHANGELOG.md
- txnbuild/transaction.go
- txnbuild/transaction_fee_test.go
<details>
otherwise).
packages.
</details>
Allow the base fee to be zero when building transactions.
The `txnbuild.NewTransaction` function errors when creating a transaction with a base fee of zero.
This is a bug.
Transactions with a zero base fee are accepted to the Stellar …
> txnbuild: fix bug where base fee is not allowed to be zero

- protocols/horizon/effects/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/resourceadapter/effects.go
- services/horizon/internal/resourceadapter/effects_test.go
Addresses part of #3591 
Depends on #3603 (whose commits are included here for now)
TODO:
> services/horizon: Add Muxed Account details to effect responses 

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/root.go
- services/horizon/cmd/serve.go
- services/horizon/cmd/version.go
- services/horizon/internal/flags.go
- services/horizon/internal/integration/db_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/3580
The `horizon db reingest range` command failed because it requires that the top level horizon ingest flag to be true.
In other words, `horizon --ingest db reingest range` works but `horizon …
> services/horizon/cmd: Fix prepare range bug

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/error.go
- clients/horizonclient/error_test.go
- services/regulated-assets-approval-server/internal/serve/httperror/http_error_test.go
<details>
otherwise).
packages.
</details>
Include the transaction result codes in the horizonclient.Error string that is outputted when serializing the error to a string.
When developing the transaction failed error is very opaque, displaying only `"Transaction Failed"` in logs. …
> clients/horizonclient: make errors easier to understand at a glance

- txnbuild/CHANGELOG.md
- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Add `AddSignatureDecorated` function to `Transaction`.
The `Transaction` type has a `AddSignatureBase64` which is helpful when working with some SEPs where signatures and full signers are passed around, but sometimes people are …
> txnbuild: add AddSignatureDecorated

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/account_request.go
- clients/horizonclient/accounts_request.go
- clients/horizonclient/asset_request.go
- clients/horizonclient/claimable_balance_request.go
- clients/horizonclient/client.go
- clients/horizonclient/effect_request.go
- clients/horizonclient/fee_stats_request.go
- clients/horizonclient/ledger_request.go
- clients/horizonclient/main.go
- clients/horizonclient/main_test.go
- clients/horizonclient/offer_request.go
- clients/horizonclient/operation_request.go
- clients/horizonclient/order_book_request.go
- clients/horizonclient/paths_request.go
- clients/horizonclient/strict_send_paths_request.go
- clients/horizonclient/submit_request.go
- clients/horizonclient/trade_aggregation_request.go
- clients/horizonclient/trade_request.go
- clients/horizonclient/transaction_request.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/3621
The payload for the submit transaction endpoint is included as a query parameter in the horizon client. When a transaction has a lengthy XDR encoding, the request url can be too long which …
> Fix transaction submission when handling large transaction payloads

- services/horizon/internal/docs/admin.md
<details>
otherwise).
packages.
</details>
Add recommended Postgres `tcp_keepalives_*` config values to Horizon Admin guide to improve availability.
> services/horizon: Add recommended tcp_keepalives_* config to Admin guide

- xdr/db.go
<details>
otherwise).
packages.
</details>
This commit removes `xdr.Price.Scan` method (implements [`Scanner`](https://golang.org/pkg/database/sql/#Scanner) interface) because it's no longer used in `stellar/go` (since https://github.com/stellar/go/commit/599673d1b9746ace4701bfe26 …
> xdr: Remove Price.Scan method

- services/regulated-assets-approval-server/README.md
- services/regulated-assets-approval-server/cmd/serve.go
- services/regulated-assets-approval-server/internal/serve/api_tx_approve_test.go
- services/regulated-assets-approval-server/internal/serve/kyc-status/delete_handler.go
- services/regulated-assets-approval-server/internal/serve/kyc-status/get_detail_handler.go
- services/regulated-assets-approval-server/internal/serve/kyc-status/post_handler.go
- services/regulated-assets-approval-server/internal/serve/toml.go
- services/regulated-assets-approval-server/internal/serve/tx_approve.go
- services/regulated-assets-approval-server/internal/serve/tx_approve_test.go
<details>
otherwise).
packages.
</details>
Refactoring tx_approve.go file before we start supporting other SEP-8 responses.
Also, made some methods and variable names more consistent and removed an unneeded method
The structure of the tx_approve.go file needed some tidying before …
>  services/regulated-assets-approval-server: update README and refactor tx_approve.go file

- services/regulated-assets-approval-server/README.md
- services/regulated-assets-approval-server/internal/serve/api_tx_approve_test.go
- services/regulated-assets-approval-server/internal/serve/tx_approve_test.go
<details>
otherwise).
packages.
</details>
Refactor tests addressing the `/tx-approve` endpoint for revised/rejected/action_required responses.
Now the unit tests are covering not only the happy path but also all edge cases from the transaction approval logic. On the other hand, …
> services/regulated-assets-approval-server: refactor tests targeting the /tx-approve endpoint

- services/regulated-assets-approval-server/README.md
- services/regulated-assets-approval-server/internal/serve/api_tx_approve_test.go
- services/regulated-assets-approval-server/internal/serve/tx_approve.go
- services/regulated-assets-approval-server/internal/serve/tx_approve_response.go
- services/regulated-assets-approval-server/internal/serve/tx_approve_test.go
<details>
otherwise).
packages.
</details>
Support SEP-8 [success](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#success) response.
According to SEP-8, if a client submits a transaction in a format already compliant with SEP-8 the server should be …
> services/regulated-assets-approval-server: implement SEP-8 "success" response

- .github/workflows/go.yml
Add GitHub Actions workflow that mirrors the CircleCI workflow.
To simplify our CI workflows, make onboarding easier, and address some security improvements.
This does not include build steps relating to publishing artifacts and Horizon specific builds.
> all: add github actions workflow

- services/horizon/internal/actions/helpers.go
- services/horizon/internal/actions/root.go
- services/horizon/internal/actions/submit_transaction.go
- services/horizon/internal/actions_transaction_test.go
- services/horizon/internal/app.go
- services/horizon/internal/corestate/main.go
- services/horizon/internal/httpx/router.go
- services/horizon/internal/init.go
- services/horizon/internal/render/problem/problem.go
<details>
otherwise).
packages.
</details>
This commit changes `POST /transactions` behaviour to return `503 Service Unavailable` (`stale_history`) instead of `504 Gateway Timeout` (`timeout`) response if connected Stellar-Core is not synced.
Close #3550.
`timeout` error is …
> services/horizon: Return 503 error in POST /transactions if Stellar-Core not synced

- services/horizon/internal/app.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Adds metrics exposing supported protocol version of Horizon, Stellar-Core and Captive Stellar-Core.
New metrics will allow tracking if Horizon and Stellar-Core are using compatible versions.
> services/horizon: Add Stellar protocol version metrics

- services/regulated-assets-approval-server/internal/serve/tx_approve.go
- services/regulated-assets-approval-server/internal/serve/tx_approve_test.go
<details>
otherwise).
packages.
</details>
Prevent server from revising or approving a transaction if the destination account is the asset issuer.
When you send a payment to the asset issuer those assets end up being burned and cease from existing. We don't want to allow that to …
> SEP-8: prevent server from revising or approving a transaction if the destination account is the asset issuer

- services/regulated-assets-approval-server/internal/db/db.go
<details>
otherwise).
packages.
</details>
Add missing Postgres driver that was being added automagically in the xdr package.
Builds started failing due to this change: https://github.com/stellar/go/commit/11f0c3f96df0ac113341d8a00fdc295fe30f246f.
Ideally, we should add a test to …
> services/regulated-assets-approval-server: add missing postgres driver

- exp/services/recoverysigner/README.md
<details>
otherwise).
packages.
</details>
Update the usage of recoverysigner in its readme.
It looks like it has become out of date. Notably the allowed source accounts option is not present.
N/A
> exp/services/recoverysigner: update usage in readme

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/internal/db2/history/ledger.go
- services/horizon/internal/db2/history/ledger_test.go
- services/horizon/internal/db2/history/main.go
Fixes #3530
This PR adds a new `horizon db detect-gaps` command
> services/horizon: Add `horizon db detect-gaps` command

- txnbuild/CHANGELOG.md
- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Uses the unmuxed transaction source account when calculating claimable balance IDs.
Fixes #3676.
n/a
> txnbuild: Properly calculate claimable balance IDs with muxed accounts.

- services/horizon/cmd/ingest.go
<details>
otherwise).
packages.
</details>
Add two missing params to `ingestVerifyRangeCmd` (probably missed in https://github.com/stellar/go/commit/4c983802b17b22efe4f968820847470e9e54fbc1).
Crash when used with Captive-Core:
```
panic: runtime error: invalid memory address or …
```
> services/horizon: Fix verify-range command toml crash

- services/horizon/internal/httpx/server.go
- support/db/main.go
- support/db/session.go
<details>
otherwise).
packages.
</details>
This commit returns `ErrConflictWithRecovery` error in case of Postgres `canceling statement due to conflict with recovery` error and handles this error in Horizon.
> support/db: Handle "conflict with recovery" errors gracefully

- .circleci/config.yml
- services/horizon/docker/Dockerfile.dev
- services/horizon/docker/core-start.sh
- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/docker/verify-range/Dockerfile
Update references across the board to use the [latest stable](https://github.com/stellar/stellar-core/releases/tag/v17.1.0) Stellar-Core: `17.1.0-584.fbc0325`.
We need 17.1.0 to take advantage of #3670 (though Horizon will be backwards-compatible) and close #3631.
> all: Update Horizon-related Stellar-Core references to use v17.1.0.

- services/regulated-assets-approval-server/internal/serve/api_tx_approve_test.go
- services/regulated-assets-approval-server/internal/serve/tx_approve_response.go
<details>
otherwise).
packages.
</details>
Make sure the SEP-8 "pending" response contains the "timeout" field.
According to [SEP-8](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#pending), the "timeout" field is mandatory and if no timestamp can be …
> services/regulated-assets-approval-server: make sure the SEP-8 "pending" response contains the "timeout" field

- ingest/ledgerbackend/file_watcher.go
- ingest/ledgerbackend/file_watcher_test.go
- ingest/ledgerbackend/stellar_core_runner.go
- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/3602
* Add a ticker to stellarCoreRunner which will execute every 10 seconds. The stellarCoreRunner context will interrupt the goroutine attached to the ticker so that if captive core shutsdown …
> ingest/ledgerbackend: Restart captive core when a new version of core is detected on disk

- .circleci/config.yml
- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/client.go
- clients/horizonclient/main.go
- services/horizon/internal/actions/helpers.go
<details>
otherwise).
packages.
</details>
This commit adds `-race` flag to Horizon integration tests and fixes two bugs found by race detector:
* `Client.sendRequest` overwriting `c.HorizonURL` when used in multiple go routines.
* `decoder.IgnoreUnknownKeys` overwriting …
> services/horizon: Fix data races found by integration tests

- services/horizon/internal/actions/submit_transaction_test.go
- services/horizon/internal/integration/txsub_test.go
- services/horizon/internal/test/integration/integration.go
<details>
otherwise).
packages.
</details>
Adds sanity integration test for txsub. Add a test (`submit_transaction_test.go`) I forgot to include in https://github.com/stellar/go/pull/3653.
While we have some unit tests for txsub we don't test the transaction submission endpoint …
> services/horizon: Add txsub integration test

- .circleci/config.yml
- .github/workflows/go.yml
- exp/services/recoverysigner/docker/Dockerfile
- exp/services/webauth/docker/Dockerfile
- exp/tools/dump-ledger-state/Dockerfile
- services/friendbot/docker/Dockerfile
- services/horizon/docker/Dockerfile.dev
- services/horizon/docker/verify-range/dependencies
- services/horizon/internal/scripts/check_release_hash/Dockerfile
- services/keystore/docker/Dockerfile
- services/regulated-assets-approval-server/docker/Dockerfile
- services/ticker/docker/Dockerfile
- services/ticker/docker/Dockerfile-dev
Bumps from 1.16.3 -> 1.16.5 and 1.15.11 -> 1.15.13.
This bump includes security issues. Refer to the [release announcement](https://groups.google.com/g/golang-announce/c/RgCMkAEQjSI/m/r_EP-NlKBgAJ) for more.
> all: Bump Golang minor versions in accordance with latest release.

- services/horizon/CHANGELOG.md
- support/config/config_option.go
- support/config/config_option_test.go
Fixes https://github.com/stellar/go/issues/3696
This PR fixes a bug where the configuration variables listed below were ignored if they were configured via environment variables instead of command line arguments:
```
CAPTIVE_CORE_LOG_PATH
CAPTIVE_CORE_PEER_PORT
CAPTIVE_CORE_HTTP_PORT
```
> Fix configuration via environment variables for optional parameters

- services/horizon/CHANGELOG.md
I accidentally listed https://github.com/stellar/go/pull/3702 as a bug fix in  v 2.4.1 instead of the current release
> services/horizon: Fix changelog

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_test.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Adds a new `--captive-core-reuse-storage-dir` flag to enable/disable Captive-Core storage dir reuse.
In Stellar-Core 17.1.0 there is a bug that can potentially corrupt storage dir: https://github.com/stellar/stellar-core/issues/3085. The …
> services/horizon: Add feature flag to reuse Captive-Core storage dir

- protocols/horizon/operations/main.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/db2/history/operation.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/integration/muxed_account_details_test.go
- services/horizon/internal/integration/muxed_operations_test.go
- txnbuild/account_merge.go
- txnbuild/account_merge_test.go
Fixes #3714 . In particular it fixed the problem found at https://github.com/stellar/go/pull/3716#issuecomment-868358655
> Preprocess _muxed_id fields before unmarshalling from the DB

- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- services/horizon/internal/test/integration/integration.go
Introduce `integration.NewTestForRemoteHorizon()`, which allows integration-testing
a remote Horizon instance. This is useful for testing a Horizon deployment
(e.g. when deploying a new cluster or a new Horizon release).
TODO: add a simple way to run all the integration tests without changing
the constructor invocation (i.e. s/NewTest()/NewTestForRemoteHorizon()/) of all the tests.
> services/horizon: Support integration-testing a remote Horizon

- services/horizon/internal/httpx/server.go
- services/horizon/internal/txsub/system.go
- support/db/main.go
- support/db/session.go
- support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
In https://github.com/stellar/go/pull/3674 I silenced `canceling statement due to conflict with recovery` so Horizon does not report expected errors with `level=error`. However, I missed `bad connection` errors that occur from time to …
> services/horizon: Fix remaining HTTP error logging

- services/horizon/CHANGELOG.md
- services/horizon/internal/db2/history/transaction_batch_insert_builder.go
- services/horizon/internal/db2/history/transaction_batch_insert_builder_test.go
Unfortunately this still requires a reingestion in order to fix it for
old ledgers.
Fixes #3733
> Fix ingestion of fee_account_muxed{_id} fields

- CONTRIBUTING.md
Add examples for how to prefix multiple key packages, and make all examples for how to prefix package names clearer.
As an example for consistency based on what the Go project uses, which is the format our title lines are already based on.
N/A
> doc: add examples for how to prefix commit titles

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- services/horizon/CHANGELOG.md
Fixes https://github.com/stellar/go/issues/3726
> ingest/ledgerbackend: Reject bounded ledger ranges that have ledgers after latest checkpoint

- ingest/CHANGELOG.md
- ingest/ledgerbackend/stellar_core_runner.go
<details>
otherwise).
packages.
</details>
Logs better in cases where the line can't be parsed, and properly parses `debug`-level logs, as well.
Logs that are marked with `DEBUG` were treated as un-parseable by the Captive Core runner, which incorrectly truncated the log …
> ingest: Properly parse and emit debug-level tags from Captive Core.

- services/horizon/internal/ingest/fsm.go
Display ledger sequence in the logs instead of `xdr.LedgerCloseMeta` object dump.
> services/horizon: Fix ledger sequence value in runTransactionProcessorsOnLedger

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/verify.go
I noticed that we use `ledger` and `sequence` when sending ledger sequence to the logs. For consistency I changed all `ledger` occurences to `sequence`.
> services/horizon: Rename `ledger` to `sequence` in log fields

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_test.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
Currently, `--captive-core-reuse-storage-dir` has no effect.
> services/horizon: Propagate the `--captive-core-reuse-storage-dir` flag to subsystems.

- services/horizon/internal/reap/main.go
- services/horizon/internal/reap/system.go
<details>
otherwise).
packages.
</details>
Wrap reap processing in a DB transaction.
When checking https://github.com/stellar/go/issues/3711 I realized that since https://github.com/stellar/go/pull/3567 reap process can be stopped in a middle which can result in just a part of …
> services/horizon: Reap data in a DB transaction

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
<details>
otherwise).
packages.
</details>
Fix some bugs introduced in https://github.com/stellar/go/pull/3737
- off-by-one on arg parsing
- not actually using the migration direction
- Without it migrations are totally broken.
- How didn't we (myself mainly) catch this in …
> services/horizon: Fix some bugs in db migrate commands

- services/horizon/cmd/db.go
- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/ingest_history_range_state_test.go
> services/horizon: Check for overlap error before preparing range in reingestion

- services/horizon/docker/README.md
- services/horizon/docker/docker-compose.standalone.yml
- services/horizon/docker/docker-compose.yml
- services/horizon/docker/start.sh
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/3764
Docker for linux recently implemented a fix which allows a container to access the host machine by setting the `extra_hosts` property …
> services/horizon/docker: Remove NETWORK_MODE=host configuration for linux users

- services/horizon/docker/core-start.sh
- services/horizon/docker/docker-compose.standalone.yml
- services/horizon/internal/test/integration/integration.go
This is a recreation of #3769:
Updates the Docker-Compose YAML files to be compatible with the latest version of Stellar-Core.
Running Core+Horizon via the compose workflow will cause issues:
- the core container will fail because `force scp` is deprecated
- the upgrade container will use P15 which is outdated
- [stellar/stellar-core:latest](https://hub.docker.com/layers/stellar/stellar-core/latest/images/sha256-d6b97102fe154afca3fb8e8e5d2f5976bc8c8a878f2d83905cbb577c3a75a96f?context=explore) defines an ENTRYPOINT which is incompatible with the compose `command`
> services/horizon: Fix standalone mode under Docker Compose flow.

- keypair/from_address.go
- keypair/from_address_test.go
- keypair/full.go
- keypair/full_test.go
- keypair/main.go
<details>
otherwise).
packages.
</details>
Add an `Equal` function to `KP`, `Full`, `FromAddress`.
Keypairs are often passed around as pointers because that's how the package creates the types. This makes it inconvenient to do equality checks. Callers knowing the internals are …
> keypair: add Equal func to KP, Full, FromAddress

- services/horizon/internal/app.go
- services/horizon/internal/reap/main.go
- services/horizon/internal/reap/system.go
<details>
otherwise).
packages.
</details>
This commit moves ledger reaping service outside global `Tick()` method.
Close #3711. Close #3728. Part of #613.
After https://github.com/stellar/go/pull/3567 reap process was cancelled after 1s. However in some deployments removing …
> services/horizon: Move reap service outside global tick

- keypair/from_address.go
- keypair/from_address_test.go
- keypair/full.go
- keypair/full_test.go
- keypair/main.go
<details>
otherwise).
packages.
</details>
Limit the keypair types to be comparable to themselves, so that a FromAddress is only comparable to a FromAddress and a Full is only comparable to a Full.
The functions don't actually provide this functionality even though they accept a …
> keypair: remove interface comparisons

- txnbuild/CHANGELOG.md
- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Remove the error from the return values of Transaction.AddSignatureDecorated.
The error value isn't used, the function never returns an error. Using the SDK becomes extra and unnecessarily verbose if callers must handle errors that will …
> txnbuild: remove error from return values of AddSignatureDecorated

- exp/services/market-tracker/go.sum
- exp/services/recoverysigner/internal/serve/auth/sep10_test.go
- exp/services/webauth/internal/serve/token_test.go
- go.list
- go.mod
- go.sum
Use `github.com/golang-jwt/jwt` replace `github.com/dgrijalva/jwt-go`
because https://github.com/advisories/GHSA-w73w-5m7g-f7qc
> all: update jwt-go

- support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
This commit remove some logging changes introduced in https://github.com/stellar/go/pull/3730.
I was hoping to still be able to see `bad connection` errors in the logs but with `warn` level however that are many other known errors which …
> services/horizon: Remove level=warn logs for known errors

- services/horizon/internal/init.go
Horizon logs a "cannot open Horizon DB" message when it fails to establish a database connection.
The problem is that this message is also logged when failing to open a connection to the Stellar Core DB.
This commit fixes the error message by specifying which database incurred the failure.
> services/horizon/internal/: Fix logged message when horizon cannot open a db connection

- services/horizon/CHANGELOG.md
- services/horizon/internal/flags.go
- support/config/config_option.go
@jacekn has advised that we warn about the new default for `--ingest` and give some time for horizon maintainers to update their configurations.
Depends on https://github.com/stellar/go/pull/3794
> services/horizon/internal: Warn about change for ingest flag

- exp/services/captivecore/main.go
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/root.go
- services/horizon/cmd/serve.go
- services/horizon/cmd/version.go
- services/horizon/internal/actions_root_test.go
- services/horizon/internal/app.go
- services/horizon/internal/flags.go
- services/horizon/internal/test/integration/integration.go
- services/horizon/main.go
- services/regulated-assets-approval-server/internal/serve/tx_approve.go
- support/config/config_option.go
<details>
otherwise).
packages.
</details>
Remove `log.Fatal` and `os.Exit` calls from Horizon.
- `log.Fatal` and `os.Exit` should only be called in `func main()`, and `func init()`.
- Everything else which could fail returns an `error`, which propagates up to `func main()`
As …
> services/horizon: Purging log.Fatal, to make horizon CLI easier to test.

- gxdr/xdr_generated.go
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-ledger.x
- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
There were some definitions missing from https://github.com/stellar/go/pull/3811 because I pulled the xdr files from the stellar core repo. The stellar core repo does not have the full changes from https://github.com/stellar/stellar-protocol/blob/master/core/cap-0038.md
For this PR, I have taken the XDR definitions from cap 38 directly.
fixes https://github.com/stellar/go/issues/3807
> Update missing CAP 38 XDR definitions

- services/horizon/CHANGELOG.md
- services/horizon/internal/reap/system.go
- services/horizon/internal/reap/system_test.go
<details>
otherwise).
packages.
</details>
Limit reaper to 100k ledgers/second..
This should keep it running well under an hour (370seconds currently), but stop it from using all available CPU, starving other processes.
Fixes #3819
> services/horizon: Reap in batches of 100k ledgers per second, to play nicely with others

- services/horizon/internal/ingest/processors/trust_lines_processor_test.go
The trustlines can be inserted in any order because they are obtained from a map. In golang entries from a map are returned in random order.
> services/horizon/internal/ingest/processors: Fix flaky test in amm branch

- services/horizon/internal/integration/state_verifier_test.go
- services/horizon/internal/integration/trade_aggregations_test.go
- services/horizon/internal/integration/txsub_test.go
- services/horizon/internal/resourceadapter/operations_test.go
- services/horizon/internal/test/integration/integration.go
- xdr/ledger_key.go
<details>
otherwise).
packages.
</details>
Update `TestProtocol14StateVerifier` with Liquidity Pool entry to ensure state verifier works correctly. Rename `TestProtocol14StateVerifier` to `TestStateVerifier` and use the latest supported protocol version instead of 15.
Close …
> services/horizon: Update TestProtocol14StateVerifier to test LiquidityPoolEntry

- services/horizon/internal/actions/operation.go
- services/horizon/internal/actions/operation_test.go
- services/horizon/internal/actions/transaction.go
- services/horizon/internal/actions/validators.go
- services/horizon/internal/db2/history/history_liquidity_pools.go
- services/horizon/internal/db2/history/operation.go
- services/horizon/internal/db2/history/operation_test.go
- services/horizon/internal/db2/history/transaction.go
- services/horizon/internal/db2/history/transaction_test.go
- services/horizon/internal/httpx/router.go
> services/horizon: Implement /liquidity_pools/{id}/{transactions,operations} endpoints

- services/horizon/internal/codes/main.go
- services/horizon/internal/codes/main_test.go
<details>
otherwise).
packages.
</details>
Added a new Protocol 18 and missing codes from previous protocol upgrade. Added a test to ensure return codes of all specific operation types are implemented.
Close #3858.
> services/horizon: Add missing tx result codes

- services/horizon/internal/db2/history/operation.go
- services/horizon/internal/db2/history/operation_test.go
It seems like the ordering was broken for claimable balances as well
> Fix operation ordering when querying by claimable balance and liq pools

- protocols/horizon/main.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/actions/account.go
- services/horizon/internal/actions/account_test.go
- services/horizon/internal/actions_root_test.go
- services/horizon/internal/assets/main.go
- services/horizon/internal/db2/history/accounts.go
- services/horizon/internal/resourceadapter/account_entry.go
- services/horizon/internal/resourceadapter/account_entry_test.go
- services/horizon/internal/resourceadapter/balance.go
- services/horizon/internal/resourceadapter/balance_test.go
<details>
otherwise).
packages.
</details>
- Amends the API to include liquidity pool details in account balances.
- Allows only querying accounts participating in a particular liquidity pool (`GET /accounts?liquidity_pool=[...some id...]`).
Resolves #3832.
Still needs to be …
> services/horizon: Allow filtering accounts by liquidity pool participation.

- protocols/horizon/operations/main.go
The ingestion code was already generating the detail, but it wasn't incorporated in the Go SDK datastructure.
> Add trustline liquidity pool id to RevokeSponsosrhip operation

- protocols/horizon/base/main.go
- protocols/horizon/operations/main.go
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
When a liquidity pool operation belongs to a failed transaction we
cannot easily retreive the liquidity pool (on failure, the transaction
metadata won't include liquidity pool changes). In fact, we may not be
able to retreive the liquitity pool at all (e.g. if the liquidity pool
id of the operation is incorrect and the transaction failed for that
reason).
Thus, we make the asset optional in the /operation API responses.
When an operation belongs to a failed transaction we omit the asset.
Also, we set the amount in `reserves_received`, `reserves_deposited`
and `shares_received` to 0, which is consistent with a failure (in
that case no shares nor or reserves change).
Closes #3869
> services/horizon: Omit asset details on failed liquidity pools operations

- .circleci/config.yml
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/integration/protocol18_test.go
<details>
otherwise).
packages.
</details>
Adds `TestLiquidityPoolRevoke` test checking the liquidity pool revoke scenario.
Close #3842.
> services/horizon: Add TestLiquidityPoolRevoke integration test

- services/horizon/internal/actions/trade.go
- services/horizon/internal/actions/validators.go
- services/horizon/internal/actions_trade_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/trade.go
- services/horizon/internal/db2/history/trade_scenario.go
- services/horizon/internal/db2/history/trade_test.go
- services/horizon/internal/httpx/router.go
Fixes https://github.com/stellar/go/issues/3835
> services/horizon: Include liquidity pool trades in trades endpoint

- txnbuild/CHANGELOG.md
- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Implement `encoding.TextMarshaler` and `encoding.TextUnmarshaler` in `Transaction`, `FeeBumpTransaction`, `GenericTransaction`.
Transaction, FeeBumpTransaction, and GenericTransaction all have well defined formats for serialization as …
> txnbuild: implement encoding.Text{M,Unm}arshaler in Transaction, FeeBumpTransaction, GenericTransaction

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/client.go
- clients/horizonclient/client_fund_test.go
- clients/horizonclient/main.go
<details>
otherwise).
packages.
</details>
Allow the `Fund` function to submit a fund request to any horizon instance, not just the instance defined by `horizonclient.DefaultTestNetClient`, and rely on the horizon instance responding with a 404 as an indicator that funding is not …
> clients/horizonclient: allow Fund on other networks and rely on server to indicate support

- services/horizon/cmd/db.go
- services/horizon/internal/actions_root_test.go
- services/horizon/internal/app.go
- services/horizon/internal/httpt_test.go
- services/horizon/internal/ledger/ledger_source_test.go
- services/horizon/internal/ledger/main.go
- services/horizon/internal/middleware_test.go
- services/horizon/internal/resourceadapter/root_test.go
<details>
otherwise).
packages.
</details>
This commit splits `UpdateLedgerState` into `UpdateCoreLedgerState` and `UpdateHorizonLedgerState` which update Core and Horizon ledger state separately. It also changes `Tick` frequency to 5 seconds.
Close #3883.
If Stellar-Core is …
> services/horizon: Split App.UpdateLedgerState into Core and Horizon ledger update methods

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/client.go
- clients/horizonclient/client_fund_test.go
- clients/horizonclient/main.go
- services/horizon/cmd/db.go
- services/horizon/internal/actions_root_test.go
- services/horizon/internal/app.go
- services/horizon/internal/httpt_test.go
- services/horizon/internal/ledger/ledger_source_test.go
- services/horizon/internal/ledger/main.go
- services/horizon/internal/middleware_test.go
- services/horizon/internal/resourceadapter/root_test.go
- txnbuild/CHANGELOG.md
- txnbuild/transaction.go
- txnbuild/transaction_test.go
Would be great to test https://github.com/stellar/go/commit/e011c915474e7d742c5840827eaee3c481f44adf in futurenet.
> Merge master into amm

- services/horizon/docker/verify-range/dependencies
- services/horizon/docker/verify-range/start
The commit message of https://github.com/stellar/go/commit/e011c915474e7d742c5840827eaee3c481f44adf was long enough to make `git log -1` command enable scrolling. This was causing `test_verify_range_docker_image` job failures because it got stuck at `git log -1` command waiting for user action.
I also noticed that the Golang version in the image does not match the one we use in other places. I changed it to Go 1.17.
> services/horizon: Fix verify-image issues

- .vscode/tasks.json
Format the VSCode tasks file.
When I open the stellar/go repo locally in the latest version of VSCode it displays a warning saying the file is "dirty". It appears the file is not formatted to how VSCode prefers it to be formatted. I don't really know what this file does or is for, but supposedly it was added because somebody uses it. This change resolves the warning.
N/A
> .vscode: fix tasks file

- exp/orderbook/batch.go
- exp/orderbook/graph.go
- exp/orderbook/graph_test.go
- services/horizon/internal/db2/history/liquidity_pools.go
- services/horizon/internal/db2/history/liquidity_pools_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/mock_q_liquidity_pools.go
- services/horizon/internal/ingest/main_test.go
- services/horizon/internal/ingest/mock_orderbook_graph.go
- services/horizon/internal/ingest/orderbook.go
- services/horizon/internal/ingest/orderbook_test.go
- services/horizon/internal/ingest/verify.go
Extend the OrderBookStream so that it polls for updated liquidity pools from the DB. The liquidity pool rows from the db will be used to update the in-memory orderbook graph.
> services/horizon/internal: Include liquidity pools in OrderBookStream

- services/horizon/internal/integration/protocol18_test.go
Also, add missing test-cases to the happy path test.
> services/horizon: Add integration test for failed liquidity pool operations

- services/horizon/internal/test/integration/integration.go
Using a generic `docker-compose down` command for stopping the Horizon
integration test containers causes every docker-compose container to
be brought down (including other containers, like the Horizon database
container which can be started using docker-compose).
This change makes sure we only destroy the containers brought up
during integration testing.
> services/horizon: Avoid docker-compose side-effects during integration tests cleanup

- exp/services/recoverysigner/Makefile
- exp/services/webauth/Makefile
- services/friendbot/Makefile
- services/horizon/docker/Makefile
- services/keystore/Makefile
- services/regulated-assets-approval-server/Makefile
- services/ticker/Makefile
Golang time parser is not compatible with format rendered by the GNU date,
even though both claim to be RFC3339. This change replaces space separator
between date and time with "T" which will allow golang to parse it.
It also switches from `--utc` to `-u` that's supported by both GNU and BSD
date commands.
> Update docker image build timestamp format

- protocols/horizon/main.go
- services/horizon/internal/actions_trade_test.go
- services/horizon/internal/db2/history/trade_aggregation.go
- services/horizon/internal/integration/protocol18_test.go
- services/horizon/internal/resourceadapter/trade.go
- services/horizon/internal/resourceadapter/trade_aggregation.go
- services/ticker/internal/scraper/trade_scraper_test.go
<details>
otherwise).
packages.
</details>
Represent trade prices as int64 fractions.
Prior to protocol 18 we represented trade prices as a fraction where the numerator and denominator took on 32 bit integer values:
```golang
type Price struct {
N int32 `json:"n"`
D int32 …
```
> protocols/horizon: Represent trade prices as int64 fractions

- txnbuild/CHANGELOG.md
- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Adds a 5 minute grace period to `ReadChallengeTx`'s `Transaction.Timebounds().MinTime` constraint to account for clock drift between the client and server.
The JS SDK recently merged a similar change …
> txnbuild: adds a 5 minute grace period to ReadChallengeTx MinTime constraint

- services/horizon/internal/ingest/parallel_test.go
In an attempt to reproduce the problem presented at https://github.com/stellar/go/issues/3907
> services/horizon: Add additional test cases for parallel reingestion

- services/horizon/internal/scripts/check_release_hash/Dockerfile
- services/horizon/internal/scripts/check_release_hash/check.sh
Several `check_release_hash` script improvements:
* Run `apt-get` commands separately. Commands were previously joined by `&&` operator which returned 0 code in case any of the commands failure (🤔).
* Hide hashes if they match.
* Add unstable repo.
Close #3651.
> `check_release_hash` improvements

- keypair/from_address_test.go
- keypair/full_test.go
<details>
otherwise).
packages.
</details>
Add test coverage for the Hint functions of the keypair.FromAddress and keypair.Full types.
Those functions aren't tested, and I'm iterating on the keypair code in https://github.com/stellar/go/pull/3914 that involves changing the Hint …
> keypair: add test coverage for hint functions

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Add a new metric `ProcessorsRunDurationSummary` (`processor_run_duration_seconds`) to replace existing `ProcessorsRunDuration` (`processor_run_duration_seconds_total`). The old metric is now deprecated.
The `ProcessorsRunDuration` is a …
> services/horizon: Change `ProcessorsRunDuration` metric type from counter to summary

- services/horizon/internal/db2/schema/bindata.go
- services/horizon/internal/db2/schema/migrations/50_fix_fee_account_muxed.sql
It seems like we will need to reingest anyways so there is no use in having this migration
> services/horizon/internal/db2/schema: Remove migration to fix fee account transactions

- services/horizon/internal/db2/history/mock_q_offers.go
- services/horizon/internal/db2/history/offers.go
- services/horizon/internal/db2/history/offers_test.go
- services/horizon/internal/db2/history/orderbook_test.go
- services/horizon/internal/ingest/processors/offers_processor.go
- services/horizon/internal/ingest/processors/offers_processor_test.go
This should remove one DB query per ledger
> services/horizon: Batch deletion of offers with offer upserting

- exp/orderbook/graph_test.go
- exp/orderbook/pools.go
- exp/orderbook/pools_test.go
<details>
otherwise).
packages.
</details>
Testing various edge and error cases of LP functions. 
It includes an edge case bugfix in which the wrong reserve was checked for underflows:
```diff
-	if reserveA-disbursed <= 0 {
+	if disbursed >= reserveB {
```
and adds a check for …
> exp/orderbook: Adds tests for liquidity pool exchange math.

- services/horizon/cmd/db.go
Atoi parses ints which do not match the range of the expected arguments (uint32)
Closes #3968
> services/horizon: Fix uint32 argument parsing type mismatch

- services/horizon/internal/db2/history/effect.go
- services/horizon/internal/db2/history/effect_test.go
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
<details>
otherwise).
packages.
</details>
29c16d3 adds a new `asset_type` field to trust line sponsorship effects in order to distinguish asset trust lines from liquidity pool trust lines. There is an issue with this approach: effects ingested before 2.9.0 release will not have …
> services/horizon: Update `asset_type` for trust line sponsorship effects on fly

- services/horizon/internal/flags.go
This change has been scheduled for the 2.9.0 release
> services/horizon/internal: Set default for ingest flag to be true

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
I tried to be comprehensive in the CHANGELOGs but the [diff is massive](https://github.com/stellar/go/compare/horizonclient-v7.1.1...master), plus you can't filter by path in the GitHub UI:
- for horizonclient: `git diff horizonclient-v7.1.1..master clients/horizonclient/`
- for txnbuild: `git diff horizonclient-v7.1.1..master txnbuild/`
(Note: tagging all committers to these releases.)
> txnbuild, clients/horizonclient: Release v8.0.0-beta.0.

- protocols/horizon/main.go
- services/horizon/internal/integration/negative_seq_txsub_test.go
- services/horizon/internal/txsub/system.go
Also: Create integration test for negative tx sequence submission
Closes https://github.com/stellar/go/issues/3982
> Handle negative transaction sequences gracefully

- benchmarks/xdr_test.go
- go.list
- go.mod
- go.sum
This PR incorporates stellar/go-xdr#16  in Horizon.
The benchmarks (copied from https://github.com/stellar/xdrgen/pull/65 but using a larger transaction) show a big improvement in the allocations made by the encoder/decoder.
Before:
```                                                                                                                                                                                                                                                             
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/benchmarks
BenchmarkXDRUnmarshal
BenchmarkXDRUnmarshal-8              100             18301 ns/op            5968 B/op        232 allocs/op
BenchmarkGXDRUnmarshal
BenchmarkGXDRUnmarshal-8             100 …
```
> Add stellar/go-xdr#16 (reduction on XDR encoding/decoding allocations)

- exp/tools/dump-ledger-state/docker-entrypoint.sh
<details>
otherwise).
packages.
</details>
Currently, the dump ledger state job sends a notification to slack whenever there is a diff between the ingestion library and stellar core. This commit removes the slack notification.
There is no need to be notified by slack because we …
> exp/tools/dump-ledger-state: Remove slack notification from dump ledger state job

- ingest/change_compactor.go
- ingest/checkpoint_change_reader.go
- services/horizon/internal/ingest/verify/main.go
- services/horizon/internal/ingest/verify/main_test.go
<details>
otherwise).
packages.
</details>
This commit changes all key representations of `LedgerKey` from base64 string to raw bytes string. This should lower memory requirements of `ChangeCompactor`, `CheckpointChangeReader` and `StateVerifier` by around 25% (given that base64 …
> ingest: Remove base64 encoding when storing LedgerKey in memory

- services/friendbot/internal/friendbot_handler.go
<details>
otherwise).
packages.
</details>
Remove the error messages for when friendbot is disabled.
Friendbot is never disabled. The field that this code checks is always set with a value, and so the error is never triggered. I think this code is old code that is probably from …
> services/friendbot: remove disabled error messages that is dead code

- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/verify.go
<details>
otherwise).
packages.
</details>
Change the type of `horizon_ingest_state_verify_ledger_entries` metric to gauge.
In https://github.com/stellar/go/pull/4015 I create a new metric tracking the number of ledger entries in buckets. After writing a few PromQL queries I …
> services/horizon: Change horizon_ingest_state_verify_ledger_entries metric to gauge

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/internal/db2/history/ledger.go
- services/horizon/internal/db2/history/ledger_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/ingest/ingest_history_range_state_test.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/main_test.go
- services/horizon/internal/ingest/parallel.go
- services/horizon/internal/ingest/parallel_test.go
- services/horizon/internal/integration/db_test.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/4010
`horizon db fill-gaps` can be called with no parameters in which case it queries for any existing gaps in the horizon db and then proceeds to ingest history to fill the gaps.
The command …
> services/horizon: Implement horizon db fill-gaps command

- benchmarks/xdr_test.go
- ingest/change_compactor.go
- services/horizon/internal/db2/history/transaction_batch_insert_builder.go
- services/horizon/internal/db2/history/transaction_batch_insert_builder_test.go
- services/horizon/internal/ingest/orderbook.go
- services/horizon/internal/ingest/processors/claimable_balances_change_processor.go
- services/horizon/internal/ingest/verify.go
- xdr/main.go
The improvement is considerable. It reduces the allocations (and CPU consumption) by roughly half.
```
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/benchmarks
BenchmarkXDRMarshal
BenchmarkXDRMarshal-8                          	 1000000	      1050 ns/op	    1352 B/op	      14 allocs/op
BenchmarkXDRMarshalWithEncoder
BenchmarkXDRMarshalWithEncoder-8               	 1909111	       619.1 ns/op	     176 B/op	       9 allocs/op
BenchmarkGXDRMarshal
BenchmarkGXDRMarshal-8                         	  151929	      7880 ns/op	    2152 B/op	     157 allocs/op
BenchmarkXDRMarshalHex
BenchmarkXDRMarshalHex-8                       	  473662	      2199 ns/op	    3640 B/op	      19 allocs/op
BenchmarkXDRMarshalHexWithEncoder …
```
> Create xdr.EncodingBuffer, which reduces buffer allocations

- keypair/from_address.go
- keypair/from_address_test.go
<details>
otherwise).
packages.
</details>
Make `FromAddress` compatible with the `BinaryMarshaler` interface.
It makes the type compatible with encoders/decoders that support the `BinaryMarshaler` interface such as the `encoding/gob` package.
N/A
> keypair: add BinaryMarsheler support to FromAddress

- Gemfile.lock
- Makefile
- Rakefile
- benchmarks/xdr_test.go
- xdr/xdr_generated.go
It improves XDR marshaling performance.
See stellar/xdrgen#68 for details
> xdr: update using stellar/xdrgen#68

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
We were not printing parsing errors properly if captive core exits right away.
Without the fix https://app.circleci.com/pipelines/github/stellar/go/9834/workflows/44ff1f80-b9fe-4787-8783-711d6cd0b8e8/jobs/57566
With the fix https://app.circleci.com/pipelines/github/stellar/go/9842/workflows/718f86b9-1495-4851-a51b-21af6a3c16d4/jobs/57633
> services/horizon: Fix stream parsing error printing in captive core

- services/horizon/CHANGELOG.md
- services/horizon/internal/actions/effects.go
- services/horizon/internal/db2/history/effect.go
- services/horizon/internal/db2/history/effect_test.go
<details>
otherwise).
packages.
</details>
Currently, requests to `/liquidity_pools/{liquidity_pool_id}/effects` are timing out. Because the query to fetch effects for a given liquidity pool is running too slowly.
This is the query and its explain analyze output:
```
EXPLAIN …
```
> services/horizon/internal/db2/history: Improve effects for liquidity pool query

- services/horizon/internal/ingest/verify.go
- services/horizon/internal/ingest/verify/main.go
- services/horizon/internal/ingest/verify/main_test.go
- xdr/main.go
Profiling shows there are a lot of allocations due to buffer resizing.
> services/horizon: Use encoding buffer in state verifier

- Gemfile
- Gemfile.lock
- Rakefile
- xdr/xdr_generated.go
See https://github.com/stellar/xdrgen/pull/72 for more details
> xdr: update using xdrgen#72

- Gemfile
- Gemfile.lock
- benchmarks/xdr_test.go
- txnbuild/transaction_test.go
- xdr/xdr_generated.go
This PR regenerates the xdr types using https://github.com/stellar/xdrgen/pull/71
There is a dramatic performance improvement. ~13x speedup and and 11x reduction of allocations.
```
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/benchmarks
BenchmarkXDRUnmarshalWithReflection
BenchmarkXDRUnmarshalWithReflection-8                 	   70221	     17617 ns/op	    5528 B/op	     185 allocs/op
BenchmarkXDRUnmarshal
BenchmarkXDRUnmarshal-8                               	  762405	      1360 ns/op	    1344 B/op	      17 allocs/op
BenchmarkGXDRUnmarshal
BenchmarkGXDRUnmarshal-8                              	   39950	     28912 ns/op	   86736 B/op	     278 allocs/op
```
This performance can be later improved even further by using the same …
> xdr: update using xdrgen#71

- benchmarks/xdr_test.go
- ingest/checkpoint_change_reader.go
- xdr/account_id.go
- xdr/asset.go
- xdr/asset_test.go
- xdr/claimable_balance_id.go
- xdr/ledger_key.go
- xdr/ledger_key_test.go
- xdr/main.go
- xdr/trust_line_asset.go
15x CPU time improvement, all allocations were removed
Before:
```
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/benchmarks
BenchmarkXDRMarshalCompress
BenchmarkXDRMarshalCompress-8   	  608031	      1970 ns/op	    2048 B/op	      59 allocs/op
PASS
```
After:
```
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/benchmarks
BenchmarkXDRMarshalCompress
BenchmarkXDRMarshalCompress-8   	 8785383	       133.8 ns/op	       0 B/op	       0 allocs/op
PASS
```
~One of the remaning allocations is, in fact, caused by a call to PoolID.Encode which I think can be removed.~
> xdr and horizon: Optimize compress-marshaling of ledger keys

- historyarchive/json.go
- historyarchive/verify.go
- historyarchive/xdrstream.go
- xdr/go_string_test.go
- xdr/main.go
Also:
* Move Uint32Ptr into test file (it was only used for testing)
* Tidy up EncoderTo and DecoderFrom interfaces
> xdr and historyarchive: Remove XDR decoder allocations from XdrStream

- CONTRIBUTING.md
Prefix issues by their primarily affected service or area of the monorepo.
It's difficult to sometimes understand what the scope of an issue is because our issue titles assume the reader has some prior knowledge that the scope relates to the Go SDK, or Horizon, or something else. Sometimes we don't provide this context at all in the title, other times the context can be found in labels, and other times we do mention it in the title but inside the text.
We have a really clear pattern for communicating this in pull requests: we prefix titles with their area most affected. This results in pull requests having titles like `services/ticker: ...` or `ingest: ...`. This pattern can be applied to issues as well.
We have several teams working in this repository and so context is not always obvious …
> doc: use pull request title pattern for issues too

- protocols/horizon/main.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/actions_transaction_test.go
- services/horizon/internal/resourceadapter/transaction_result_codes.go
- services/horizon/internal/txsub/errors.go
- services/regulated-assets-approval-server/internal/serve/httperror/http_error_test.go
<details>
otherwise).
packages.
</details>
Return both inner and outer result codes for fee bump transactions.
Currently only the outer code is returned for fee bump transactions
N/A
> services/horizon: Return both inner and outer result codes for fee bump transactions.

- benchmarks/xdr_test.go
- support/db/batch_insert_builder_test.go
It includes a leftover from https://github.com/stellar/go/pull/4086
> xdr and support/db: Minor benchmark code quality improvements

- exp/orderbook/pools.go
- exp/orderbook/pools_test.go
- go.list
- go.mod
- go.sum
Before:
```
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/exp/orderbook
BenchmarkVibrantPath
BenchmarkVibrantPath-8                16          77022055 ns/op        18015408 B/op      70026 allocs/op
PASS
```
After:
```
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/exp/orderbook
BenchmarkVibrantPath
BenchmarkVibrantPath-8                19          65228205 ns/op        17494446 B/op      43836 allocs/op
PASS
```
It improves CPU performance (by ~15%) and considerably reduces allocations (by ~40%)
> exp/orderbook: Use uint128s for pool calculations to improve performance

- exp/orderbook/edges.go
- exp/orderbook/graph.go
- exp/orderbook/graph_benchmark_test.go
- exp/orderbook/graph_test.go
- exp/orderbook/pools.go
- exp/orderbook/pools_test.go
- exp/orderbook/search.go
- exp/orderbook/utils.go
- services/horizon/internal/paths/main.go
- services/horizon/internal/resourceadapter/path.go
- services/horizon/internal/resourceadapter/path_test.go
<details>
otherwise).
packages.
</details>
Previously we were representing the adjacency list for the graph as a mapping from asset string to the list of offers / pools which buy / sell that asset.
Now, every asset is assigned an integer id and the adjacency list is represented …
> exp/orderbook: Represent assets in orderbook graph as int32 instead of strings

- exp/orderbook/pools.go
- exp/orderbook/pools_test.go
- go.list
- go.mod
- go.sum
Reverts stellar/go#4104
After replaying some production requests I found some cases where calculatePoolPayout panics with an overflow.
Here is one case which causes a panic:
calculatePoolPayout(92017260901926686, 9157376027422527, 4000000000000000000, 30)
> Revert "exp/orderbook: Use uint128s for pool calculations to improve performance"

- exp/orderbook/graph_test.go
- exp/orderbook/search.go
<details>
otherwise).
packages.
</details>
One of the changes to the path finding algorithm introduced by https://github.com/stellar/go/pull/4096 is that the new algorithm includes paths which take advantage of arbitrage opportunities. In this commit, I have removed that behavior …
> exp/orderbook: Exclude arbitrage paths from path finding search

- exp/orderbook/graph.go
Leftover from https://github.com/stellar/go/pull/4105
I just found it in a local branch and I realized I forgot to push it.
Very very minor stuff.
> exp/orderbook: Micro-optimization for paths search

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/internal/integration/db_test.go
<details>
otherwise).
packages.
</details>
https://github.com/stellar/go/pull/4060 introduced a bug where command line flags such as `--parallel-workers` are not getting parsed when running the `horizon db reingest range` command. This commit fixes this bug so that all the …
> services/horizon/cmd: Fix parsing of reingest range flags like --parallel-workers

- exp/orderbook/graph.go
- exp/orderbook/graph_test.go
<details>
otherwise).
packages.
</details>
There is a bug where if you query for path finding requests starting from or ending at a non-existent asset the path finding algorithm may return invalid paths. There is a mapping between an asset's string representation and its integer …
> exp/orderbook:

- gogenerate.sh
- gxdr/generate.go
<details>
otherwise).
packages.
</details>
Generate gxdr using go:generate.
I was modifying the gogenerate.sh script for another reason and noticed we have a generation step that is embedded in the gogenerate.sh script that's job is not to do generation, but primarily to make …
> gxdr: generate using go:generate

- services/horizon/CHANGELOG.md
Rebuilds Horizon using Go 1.17.5 (pulled automatically because we don't pin to any specific patch release) to mitigate CVE-2021-44716.
> services/horizon: Horizon 2.12.1 CHANGELOG

- exp/services/recoverysigner/docker/Dockerfile
- exp/services/webauth/docker/Dockerfile
- services/friendbot/docker/Dockerfile
- services/keystore/docker/Dockerfile
- services/regulated-assets-approval-server/docker/Dockerfile
- services/ticker/docker/Dockerfile
- services/ticker/docker/Dockerfile-dev
<details>
otherwise).
packages.
</details>
Make all docker images in this repo consistently build from Go 1.17.
Some are building from Go 1.16 when we usually target building with the latest version we support, and we currently support 1.16 and 1.17.
Also, some are building from …
> all: make docker images consistently build from go 1.17

- exp/orderbook/graph.go
- exp/orderbook/graph_test.go
- exp/orderbook/search.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/4131
If the source asset is included in the list of destination assets we will include the empty path in the path finding response. For example:
If we receive the following `/paths/strict-send` …
> exp/orderbook: Include empty paths in path finding response

- xdr/asset.go
- xdr/asset_test.go
Yet another leftover branch I had hanging around from optimizing path finding.
Not a critical optimization, but it doesn't hurt either.
> xdr: Improve performance of StringCanonical() and add asset string benchmarks

- services/horizon/internal/actions/account.go
- services/horizon/internal/actions/claimable_balance.go
- services/horizon/internal/actions/claimable_balance_test.go
- services/horizon/internal/actions/helpers.go
- services/horizon/internal/actions/liquidity_pool.go
- services/horizon/internal/actions/path.go
and fix the liquidity pools and claimable balances templates as a result.
closes #4103
> Refactor HAL template generation in root endpoint

- services/horizon/CHANGELOG.md
- services/horizon/internal/resourceadapter/claimable_balances_test.go
- xdr/json.go
- xdr/json_test.go
<details>
otherwise).
packages.
</details>
added a new optional field `AbsBeforeEpoch` to the API resource `ClaimableBalance:Predicate`, it is the Unix Epoch value represented by the same custom extended ISO date value in the `AbsBefore` field.
this extra info for Epoch will …
> xdr: Add AbsBeforeEpoch to ClaimableBalance:Predicate API resource 

- services/horizon/internal/integration/claimable_balance_ops_test.go
- services/horizon/internal/integration/claimable_balance_test.go
- services/horizon/internal/integration/clawback_test.go
- services/horizon/internal/integration/db_test.go
- services/horizon/internal/integration/liquidity_pool_test.go
- services/horizon/internal/integration/muxed_account_details_test.go
- services/horizon/internal/integration/muxed_operations_test.go
- services/horizon/internal/integration/negative_seq_txsub_test.go
- services/horizon/internal/integration/sponsorship_test.go
- services/horizon/internal/integration/state_verifier_test.go
- services/horizon/internal/integration/trade_aggregations_test.go
- services/horizon/internal/integration/txsub_test.go
- services/horizon/internal/test/integration/integration.go
* Use the latest protocol version for all tests.
* Set the protocol to the latest version if not specified explicitly.
* Rename tests according to their content, stop using protocol numbers.
* Remove all the sanity tests.
Closes  #3149
> services/horizon/internal/integration: Refactor integration tests

- ingest/change.go
- services/horizon/internal/ingest/processors/asset_stats_set.go
<details>
otherwise).
packages.
</details>
Add method to `ingest.Change` that extracts liquidity pool type
This functionality is likely to be used elsewhere while processing liquidity pools.
> horizon/ingest: Add method to ingest.Change that returns liquidity pool type

- services/horizon/internal/app.go
- services/horizon/internal/flags.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Add more verbose logging to horizon start up. Include lines that signal db migration and captive core set up, which should be logged to stdout since it happens before logging is set up.
It would make debugging easier.
> services/horizon: Add more verbose logging for horizon start up

- services/horizon/internal/httpx/router.go
- services/horizon/internal/middleware_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/2852
This commit removes rate limiting on the http middleware for streaming requests.
Rate limiting is applied on horizon http requests via a middleware. However, for streaming requests, rate …
> services/horizon/internal/httpx: Exempt SSE requests from rate limiting middleware

- historyarchive/xdrstream.go
- historyarchive/xdrstream_test.go
- services/horizon/internal/ingest/history_archive_adapter_test.go
<details>
otherwise).
packages.
</details>
Introduce MockArchive to history_archive_adapter unit test
This removes a network call. Unit tests should not require internet
> Remove network call from history_archive_adapter unit test

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/resume_state_test.go
<details>
otherwise).
packages.
</details>
Update cursor in Stellar-Core to latest ingested ledger when local ingestion is behind the cluster.
If there is a DB ingesting instance more than one ingesting instance: either Captive-Core or DB connected to another Stellar-Core, it's …
> services/horizon: Update cursor when bumping ledger to latest

- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Add `ClearSignatures` functions to `Transaction` and `FeeBumpTransaction`.
`Transaction` and `FeeBumpTransaction` have functions for adding signatures, but not for clearing them to get back the original transaction without signatures …
> txnbuild: add ClearSignatures functions to Transaction and FeeBumpTransaction

- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Add `AddSignatureDecorated` to `FeeBumpTransaction`.
The function exists on `Transaction` but not on `FeeBumpTransaction`. I am writing some code that needs to be able to add decorated signatures to fee bump transactions in the same way …
> txnbuild: add AddSignatureDecorated to FeeBumpTransaction

- services/horizon/internal/render/sse/stream.go
- services/horizon/internal/render/sse/stream_test.go
Leftover from https://github.com/stellar/go/pull/4151
> services/horizon/../sse:  Stop counting the SSE preamble as an event

- integration.sh
- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/docker/docker-compose.pubnet.yml
- services/horizon/docker/docker-compose.standalone.yml
- services/horizon/docker/docker-compose.yml
<details>
otherwise).
packages.
</details>
Set `platform: linux/amd64` for docker commands.
Core isn't currently compiled for arm, so the integration tests etc wouldn't work on new ARM macs. Previously there were bugs in docker/hypervisor which would crash core when running with …
> services/horizon: Set docker platform flag so core works on ARM Macs

- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Remove databaseURL from log
We shouldn't log passwords
> Remove databaseURL from log.

- services/horizon/internal/app.go
<details>
otherwise).
packages.
</details>
Update `UpdateCoreLedgerState` to use local `ctx` variable (`Tick` context) instead of `a.ctx` (application context).
Application context is only cancelled on Horizon shutdown. This means that if `UpdateCoreLedgerState` hangs (ex. due to …
> services/horizon: Update UpdateCoreLedgerState to use local ctx

- txnbuild/transaction.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
Add MarshalBinary to GenericTransaction.
GenericTransaction can be marshaled to text in base64, but not to binary. Transaction and FeeBumpTransaction can be marshaled to binary and there's no reason I can see to disallow same on …
> txnbuild: add MarshalBinary to GenericTransaction

- txnbuild/transaction.go
- txnbuild/transaction_test.go
Add NewGenericTransaction* functions for creating a GenericTransaction with either a Transaction of a FeeBumpTransaction.
GenericTransaction was created as a temporary type that houses a Transaction or FeeBumpTransaction after being parsed, and so the SDK exposes no way to build a GenericTransaction with the other types. 
When an application starts using GenericTransaction it inevitably ends up needing to build them which is what I've run into.
> txnbuild: add NewGenericTransaction* functions

- services/friendbot/internal/friendbot_handler.go
- services/friendbot/main.go
<details>
* [ x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
otherwise).
* [ x] This PR's title starts with name of package that is most changed in the PR, ex.
packages.
</details>
fixes friendbot handler to register the account exists error on …
> friendbot: create new problem on each handler call

- ingest/ledgerbackend/database_backend.go
<details>
otherwise).
packages.
</details>
In `DatabaseBackend.GetLedger(ctx, sequence)` check if there are newer ledgers than `sequence` if ledger not found. If there are newer ledgers return an error.
If Stellar-Core cursors were manually removed or updated, it's possible it …
> ingest/ledgerbackend: Check if there are newer ledger when requested ledger does not exist

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/resume_state_test.go
<details>
otherwise).
packages.
</details>
When more than one ingesting instances is running and the current one is behind, go to `resumeState` immediately instead of after 1s. Waiting 1s can slow down make applying ledgers by Captive-Core slower in catching-up mode.
> services/horizon: Resume ingestion immediately when catching up

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
After refactoring in https://github.com/stellar/go/pull/4088 (and as a result of my wrong comment: https://github.com/stellar/go/pull/4088#discussion_r764394296) the `CaptiveCoreBackend.isPrepared` method returned `true` if …
> ingest/ledgerbackend: Restart Stellar-Core when it's context is cancelled

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- services/horizon/internal/test/integration/integration.go
I noticed two things on captive core ingestion, `stellar-core new-db; stellar-core run` does not output meta replayed from genesis, rather it fast-forwards internally to whatever it has for current LCL, and starts emitting meta at that point, but some tests were defaulting horizon into ledger=2 genesis state, and the captive core runner tended to get stuck on that since it was expecting ledger 2 and getting greater than that from meta stream, then got stuck in a state retry loop with a cancelled ctx due to the first missed ledger retrieval and so subsequent new states that tried to get ledgers just kept failing early with ctx cancelled.
> #4038: trying to fix issue with captive core integration tests hanging

- services/horizon/internal/ingest/orderbook.go
<details>
otherwise).
packages.
</details>
While debugging https://github.com/stellar/go/issues/4197 I realized that logging the two sets of LPs is broken. One set contains a pointer field which is logged as a memory address (ex. 0xc004ceb0e0). Also, the sets are two long to read …
> services/horizon: Improve logging the LP verification mismatch

- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/toml.go
- services/horizon/internal/app.go
- services/horizon/internal/test/integration/integration.go
cleaned up the integration test in terms of captive core, removed seeing with BuildGenesisState, it doesn't represent real life Horizon startup/installation scenarios and caused an issue with captive core meta replay not lining up.
> #4038: fixed integration test to not use GenesisState

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/resume_state_test.go
<details>
otherwise).
packages.
</details>
Try to verify state even when not ingesting current ledger.
In distributed ingestion, it's possible that a single node will keep ingesting for a longer period of time. If state verification is stuck for whatever reason on the ingesting …
> services/horizon: Attempt state verification when bumping ledger sequence

- services/horizon/internal/integration/db_test.go
This change ensures that all existing operations are reingested and that all future operations are covered(by going through `xdr.OperationTypeToStringMap`)
Closes #3660
> horizon: Make sure we test reingestion for all possible operations

- historyarchive/http_archive.go
- ingest/ledgerbackend/stellar_core_runner.go
- services/horizon/internal/txsub/system.go
- tools/archive-reader/archive_reader.go
Make some small stylistic changes to satisfy the next version of static check that will be released with Go 1.18 support.
While seeing if our code runs with Go 1.18rc1 I discovered that newer versions of static check, that are required for checking code when using Go 1.18, are more particularly about duplicate type declarations. This is okay change to make regardless so I'm making it separately.
Related to #4143.
> all: staticcheck fixes

- .github/workflows/horizon.yml
> services/horizon: Migrate integration tests to GitHub Actions

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Merge changelog entries back into master.
Because the release is released.
[TODO or N/A]
> Merge Horizon 2.15.0 back to Master

- services/horizon/internal/ingest/main.go
`LedgerHashStore` was removed from Horizon's `CaptiveCoreConfig` in: https://github.com/stellar/go/commit/b7fde588a61abdcb52b13b1b802b3e827202013b. This change makes it impossible to `PrepareRange` using Captive-Core if there is any other ingestion instance running because `CaptiveCoreBackend` tries to load the hash of the ledger from archives when `LedgerHashStore` is not set. But ledgers are published every 5 minutes so they contain the hash of the latest ledger only for a brief amount of time (the moment when checkpoint is published).
> services/horizon: Add LedgerHashStore to Captive-Core config

- .github/actions/setup-go/action.yml
- .github/workflows/go.yml
- .github/workflows/horizon-master.yml
- .github/workflows/horizon-release.yml
- .github/workflows/horizon.yml
- services/horizon/docker/verify-range/dependencies
- support/scripts/build_release_artifacts/main.go
Addresses most of  https://github.com/stellar/go/issues/4229
> all: migrate the rest of the CircleCI jobs to GitHub Actions

- .github/workflows/go.yml
- .github/workflows/horizon-master.yml
- .github/workflows/horizon.yml
See https://github.com/stellar/go/runs/5395864747?check_suite_focus=true
Followup to #4250
> horizon: Fix GitHub action problem with verify-range push in master

- .github/actions/setup-go/action.yml
Invert the ref_protected checked used to control whether test caching occurs.
Caching of tests should be disabled for protected branches, not enabled.
> all: fix ci ref_protected check for caching

- .github/actions/setup-go/action.yml
Before, we:
1. Didn't use the build cache in the master branch. This caused the cache
to not be updated. This caused PRs to rerun all the tests.
2. Didn't reset the go module cache. This would eventually cause the cache
to accumulate orphan dependencies when we remove them.
> all: [GitHub actions] Reset the module and build cache in master/protected

- .github/actions/setup-go/action.yml
This time I tested that everything works in a fork.
> all: More go-setup github action fixes

- Rakefile
- xdr/README.md
Add a readme for the xdr package describing how to generate xdr.
I frequently forget and have to figure it out each time. This might help someone else too.
The examples use docker so that it is a quick copy/paste for most people. We use docker frequently so most of us have docker. There's a good chance that less of us have ruby setup in a good state locally.
I also added the ref to the Rakefile because I also forget how to specify a different source location for downloading XDR and if the ref was always specified it would be easier to just edit it.
N/A
> xdr: add instructions for generating xdr

- services/ticker/internal/scraper/asset_scraper.go
- services/ticker/internal/scraper/asset_scraper_test.go
<details>
otherwise).
packages.
</details>
Cache TOMLs to during scraping to some degree. Caching is local to each routine that is scraping and not shared across those routines, so it is possible to still get duplicate requests. Cache usage is logged.
The asset scraper may end up …
> services/ticker: cache tomls during scraping

- services/ticker/internal/scraper/asset_scraper.go
- services/ticker/internal/scraper/asset_scraper_test.go
Use log fields in logs in the asset ingestion job of Ticker and include TOML url in logs.
To make filtering and analyzing logs easier.
N/A
> services/ticker: use log fields during asset ingestion

- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/file_watcher_test.go
- ingest/ledgerbackend/stellar_core_runner_test.go
<details>
otherwise).
packages.
</details>
Write captive core test files to `/tmp`. So they don't pollute local workspace.
Fixes #4290
> services/horizon: Fix captive core tests to write to /tmp, instead of polluting the repo

- .github/workflows/go.yml
- .github/workflows/horizon.yml
- exp/services/recoverysigner/docker/Dockerfile
- exp/services/webauth/docker/Dockerfile
- go.mod
- services/friendbot/docker/Dockerfile
- services/keystore/docker/Dockerfile
- services/regulated-assets-approval-server/docker/Dockerfile
- services/ticker/docker/Dockerfile
- services/ticker/docker/Dockerfile-dev
- staticcheck.sh
Remove testing and official support for Go 1.16, and add support for Go 1.18. Update all docker images to use Go 1.18, except Horizon.
Go 1.18 was released today and Go 1.16 is now no longer supported for security fixes.
I have not updated the Horizon docker images as that should be coordinated by @stellar/horizon-committers.
Please note that this commit will cease to run Horizon whole program checks. See this for more details:
https://github.com/stellar/go/blob/3d935af3d9e78bec5a729473cac3434689cd4186/staticcheck.sh#L19-L25
Depends on: https://github.com/docker-library/official-images/pull/12045
> all: remove go1.16 add go1.18

- services/horizon/internal/txsub/sequence/account_tx_submission_queue.go
- services/horizon/internal/txsub/sequence/account_tx_submission_queue_test.go
- services/horizon/internal/txsub/sequence/manager.go
- services/horizon/internal/txsub/sequence/manager_test.go
- services/horizon/internal/txsub/submitter.go
It's the first time I get into this code (as part of https://github.com/stellar/go/issues/4283 ) and the naming has made it hard to understand. So, I decided to make the naming more understandable.
> services/horizon: Rename methods and functions in submission system

- .github/workflows/horizon.yml
They are failing with:
```
The following packages have unmet dependencies:
stellar-core : Depends: libc++1-8 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Most likely due to a problem in the azure deb Ubuntu mirror used by GitHub
Workaround for https://github.com/actions/virtual-environments/issues/5245
> all: Fix Horizon integration tests

- .github/workflows/horizon.yml
- services/horizon/docker/docker-compose.integration-tests.yml
Captive core `18.0.3-746.f3baea6.focal` seems to be incompatible with a Core container running version `18.5.0-873.rc1.d387c6a71.focal`
Upgrading captive core to `18.5.0-873.rc1.d387c6a71.focal` fixes the issue.
> horizon: Fix integration tests

- README.md
Use the GitHub actions Go workflow badge (liking to the master push Go workflow page)
> all: Change outdated CircleCI build badge

- services/horizon/internal/integration/transaction_preconditions_test.go
- services/horizon/internal/test/integration/integration.go
Also, improve the protocol check of tests
Addresses part of https://github.com/stellar/go/issues/4305
> horizon: Add integration test for new protocol 19 account fields

- staticcheck.sh
Update staticcheck to 2022.1.
Version 2022.1 is the first released version supporting Go 1.18. We've been using a non-released version to get Go 1.18 support.
N/A
> all: update staticcheck to 2022.1

- services/horizon/internal/integration/transaction_preconditions_test.go
new integration test case for using the `Precondtions.ExtraSigners` parameter with a standard AccountID as the additional signer.
> Add integration test for extra signers using tx preconditions

- services/horizon/internal/integration/transaction_preconditions_test.go
> horizon: Add transaction submission test for Protocol 19

- .github/workflows/go.yml
- .github/workflows/horizon.yml
- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
port the [horizon 2.16.1 security release](https://github.com/stellar/go/releases/tag/horizon-v2.16.1) changes back into master
update mainline to have latest release changes also
> Port Horizon v2.16.1 release back into master

- .github/workflows/go.yml
- .github/workflows/horizon.yml
Reverts Golang version pinning required to build Horizon v2.16.1.
> Revert "Pin go versions temporarily"

- .github/workflows/horizon.yml
- services/horizon/docker/docker-compose.integration-tests.yml
[v19.0.0rc1](https://github.com/stellar/stellar-core/releases/tag/v19.0.0rc1) of Stellar Core is released, and we should use it in our tests as early as possible.
> services/horizon: Bump Stellar Core to official v19.0.0rc1 for Horizon tests

- protocols/horizon/main.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/resourceadapter/root.go
- services/horizon/internal/resourceadapter/root_test.go
<details>
otherwise).
packages.
</details>
Expose the supported protocol version of Horizon on the root endpoint.
Improved visibility for debugging, etc. Also useful in contexts like the quickstart tests that want to upgrade core to the latest version supported by all components. …
> services/horizon: expose supported protocol version on root endpoint

- .github/workflows/horizon.yml
- gxdr/xdr_generated.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/actions/account_test.go
- services/horizon/internal/codes/main.go
- services/horizon/internal/db2/history/accounts_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/accounts_processor.go
- services/horizon/internal/ingest/processors/accounts_processor_test.go
- services/horizon/internal/ingest/verify.go
- services/horizon/internal/ingest/verify_range_state_test.go
- services/horizon/internal/integration/protocol_19_upgrade_test.go
- services/horizon/internal/integration/transaction_preconditions_test.go
- services/horizon/internal/resourceadapter/account_entry.go
- services/horizon/internal/resourceadapter/account_entry_test.go
- services/horizon/internal/test/integration/integration.go
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-transaction.x
- xdr/Stellar-types.x
- xdr/xdr_generated.go
- Bugfix: Properly handle pre-P19 accounts which have `nil` extensions (SequenceTime/Ledger)
- Sync XDR w/ latest Stellar Core master, add new `txMalformed` and `txBadMinSeqAgeOrGap` error codes
- Bump Stellar Core versions to v19.0.0 stable
- More integration tests
- Changelog bump
Various things added to and/or found throughout release testing.
> xdr, services/horizon: Merge Horizon v2.17.0rc1 back into master.

- services/friendbot/internal/minion.go
<details>
otherwise).
packages.
</details>
Include the transaction hash in friendbot logs when transactions are being submitted to the network.
To help with debugging in cases where transactions fail to submit since we can lookup what happened in Horizon for the transaction.
N/A
> services/friendbot: include txhash in logs

- protocols/horizon/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/transaction_ledger_bounds.go
- services/horizon/internal/resourceadapter/transaction.go
- services/horizon/internal/resourceadapter/transaction_test.go
Two new omissions:
1. omit minimum account sequence age when it's `"0"`
2. omit `max_ledger` when it's `0`
1. Because we use a string for the field (to work around languages that don't natively support uint64 values) in the JSON response, but the field is a non-pointer in the XDR, it will always be set and will be 0 by default. Since it's a duration, 0 is effectively "not set", and so it should be omitted from the resulting precondition.
2. Because `0` is "no upper bound," so it's effectively "not set."
(1) feels a little hacky. Caveat: if someone explicitly sets it to 0 when building their tx, this is equivalent to not setting it, so they may be confused about its omission, but this is working as intended.
> services/horizon: Improve transaction precondition `omitempty` behavior

- services/horizon/CHANGELOG.md
- services/horizon/internal/integration/transaction_preconditions_test.go
- services/horizon/internal/resourceadapter/transaction.go
- services/horizon/internal/resourceadapter/transaction_test.go
<details>
otherwise).
packages.
</details>
The timebounds w/in the new preconditions field are now UNIX timestamps.
We all agreed that time-related fields going forward should be UNIX timestamps in seconds.
This one slipped through the cracks, because it comes from the existing …
> services/horizon: Use UNIX timestamps instead of RFC3339 strings for timebounds.

- tools/horizon-cmp/internal/response.go
This adds the requested URL to a panic message.
If `horizon-cmp` encounters an unexpected HTTP status code (like a 500), it will just spit out `panic: 500`. This isn't useful for debugging or reproducing the error, since you have no idea what the requested URL was.
> tools/horizon-cmp: Improve panic error message

- exp/lighthorizon/index/trie_test.go
Use `testify/assert` library in `TrieIndex` tests. 
This makes the test cases cleaner by having less reliance on custom conditionals & error messages. It's a preliminary step to moving the `TrieIndex` serialization to XDR so that it's clear that existing tests are unchanged (and pass).
Things still work:
```
exp/lighthorizon> go test -failfast ./index/...    
ok  	github.com/stellar/go/exp/lighthorizon/index	13.964s
```
> exp/lighthorizon: Modify trie tests to use `assert` over raw comparisons.

- exp/lighthorizon/index/trie.go
- exp/lighthorizon/index/xdr/LightHorizon-types.x
- exp/lighthorizon/index/xdr/xdr_generated.go
This is a continuation of #4369.
Generate XDR for the trie and extend it to support the `encoding.Binary(Un)marshaler` interface.
XDR is better than custom stuff.
I'm not sure if there's a better way to do this than the current full conversion to/from `TrieNode`, since the in-memory structure needs a key-value mapping for the children but XDR doesn't support maps.
> exp/lighthorizon: Add XDR marshalling for the `TrieNode` structure.

- services/horizon/cmd/db.go
`db migrate down` should specify that it goes, well, down :smile:
> services/horizon: Fixes tiny copy-paste typo in `--help` text

- tools/alb-replay/README.md
- tools/alb-replay/main.go
* Allow opening gzip log files directly
* Allow filtering requests in the log file by path and by status code
* Add quiet mode (which only logs failing requests)
> tools/alb-replay: Add new features to alb-replay

- services/horizon/internal/httpx/server.go
- services/horizon/internal/init.go
- support/db/main.go
- support/db/main_test.go
- support/db/session.go
- support/db/session_test.go
<details>
otherwise).
packages.
</details>
Postgres provides several configuration options for clients:
https://www.postgresql.org/docs/9.6/runtime-config-client.html
In this commit I have configured the statement_timeout and idle_in_transaction_session_timeout for the horizon …
> support/db, services/horizon/internal: Configure postgres client connection timeouts for read only db

- services/horizon/CHANGELOG.md
- services/horizon/internal/db2/history/trade_aggregation.go
<details>
otherwise).
packages.
</details>
Refactor trade aggregation query to be more performant.
Expensive queries are hogging DB connections.
> services/horizon: Refactor trade aggregation query.

- services/horizon/internal/app.go
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/httpx/router.go
- services/horizon/internal/init.go
- services/horizon/internal/integration/parameters_test.go
<details>
otherwise).
packages.
</details>
Add a flag to disable path finding endpoints.
For ingesting horizon nodes that do not serve HTTP traffic it makes sense to disable the path finding endpoints because the path finding endpoints require storing all offers and liquidity …
> services/horizon/internal: Add flag to disable path finding endpoints

- services/horizon/CHANGELOG.md
The ingestion filtering feature was wrongly added to the 2.17.0 entry at https://github.com/stellar/go/pull/4277
> Add Horizon 2.18.0 CHANGELOG entry

- services/horizon/CHANGELOG.md
- services/horizon/internal/app.go
- services/horizon/internal/config.go
- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/claimable_balances_test.go
- services/horizon/internal/db2/history/offers.go
- services/horizon/internal/db2/history/offers_test.go
- services/horizon/internal/db2/history/trade_aggregation.go
- services/horizon/internal/flags.go
- services/horizon/internal/httpx/router.go
- services/horizon/internal/httpx/server.go
- services/horizon/internal/ingest/orderbook.go
- services/horizon/internal/init.go
- services/horizon/internal/integration/parameters_test.go
- support/db/main.go
- support/db/main_test.go
- support/db/session.go
- support/db/session_test.go
<details>
otherwise).
packages.
</details>
porting the db performance optimizations into a 2.17.1 release 
want to get these changes out soon to avoid further repeat of some known performance issues
> Horizon: merge db performance optimizations to 2.17.1

- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/cmd/single/main.go
- toid/main.go
This refactors the single-process index builder: (see 90d8ffa1c5512e467e5368acdf71485b878702c0):
- allow worker count to be a command line parameter
- split work by checkpoints rather than ledgers
- move actual index insertion work to helpers
- move progress bar into helpers
- simplify participants code, payments vs. all
- move index building into its own object (`IndexBuilder`)
This also chunks out work to the workers using ledger ranges that correspond to checkpoints.
Code cleanup and optimization: this minimizes flushes to the filesystem/network by isolating it to checkpoint ranges, which makes flushes more meaningful and is a better discretization.
The refactor into `IndexBuilder` is prep work for #4403, where an important part of that is using a unified codebase for both builders. …
> exp/lighthorizon: Refactor single-process index builder.

- exp/lighthorizon/index/cmd/batch/reduce/main.go
- exp/lighthorizon/index/cmd/batch/reduce/set.go
- exp/lighthorizon/index/connect.go
- exp/lighthorizon/index/store.go
This refactors and repairs the reduce job in the following way (:flying_saucer: = refactor, :hammer_and_wrench: = fix):
* :flying_saucer: use environmental variables for every parameter, including index sources and final target
* :flying_saucer: helper functions: merging indices, partitioning work based on hashes
* :flying_saucer: much more logging!
* :flying_saucer: move thread-safe set into its own abstraction
* :hammer_and_wrench: make reduce back-end agnostic rather than tied to S3
* :hammer_and_wrench: generalize non-existence errors (`os.IsNotExist(err)` over `err == ErrNotExist`)
* :hammer_and_wrench: make transaction flushing thread-safe (for parallel reduces)
* :hammer_and_wrench: flush accounts list as part of `Flush()`
* :hammer_and_wrench: split work across multiple channels …
> exp/lighthorizon: Refactor and repair the reduce job

- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/cmd/batch/map/main.go
- exp/lighthorizon/index/cmd/single/main.go
A handful of refactors:
* The main thing: `./index/cmd/single` and `./index/cmd/batch/map` now leverage the same index building code (`BuildIndices`)
* Extends the map-reduce builder to take the txmeta source / index destination URLs from the environment rather than hard-coding S3 paths (because splitting that out from the giga-PR was difficult).
* Infer checkpoints from `ledger.LedgerSequence()` rather than passing it as a parameter
* Add a new `ProcessAccountsWithoutBackend` module for the Map job
One codebase to rule them all :+1: 
This gets us per-ledger index building "for free" for the map-reduce version.
n/a
> exp/lighthorizon: Unify map-reduce and single-process index builders

- exp/lighthorizon/index/cmd/batch/reduce/main.go
- exp/lighthorizon/index/file.go
- exp/lighthorizon/index/file_test.go
Three key changes:
* actually read the account list when using a filesystem backend
* using `O_APPEND` on the file to support concurrent writes
* ensure that the _read_ list is a unique set of accounts
Concurrent writes make `FileBackend` a viable option for MapReduce-based index building.
The written list of accounts may contain duplicates due to concurrent writes.
> exp/lighthorizon: Add thread-safe support for reading account list from `FileBackend`.

- protocols/horizon/main.go
- protocols/horizon/main_test.go
<details>
otherwise).
packages.
</details>
fix #4428 
see #4428 
N/A
> protocols/horizon: add missing strkey type names.

- protocols/horizon/main.go
- protocols/horizon/main_test.go
- services/friendbot/init_friendbot_test.go
- services/friendbot/internal/account.go
- services/horizon/internal/actions/account_test.go
- services/horizon/internal/integration/db_test.go
- services/horizon/internal/resourceadapter/account_entry.go
- services/horizon/internal/resourceadapter/account_entry_test.go
- services/horizon/internal/test/integration/integration.go
- services/regulated-assets-approval-server/internal/configureissuer/configureissuer_test.go
- services/regulated-assets-approval-server/internal/serve/api_tx_approve_test.go
- services/regulated-assets-approval-server/internal/serve/friendbot_test.go
- services/regulated-assets-approval-server/internal/serve/tx_approve.go
- services/regulated-assets-approval-server/internal/serve/tx_approve_test.go
- txnbuild/examplehorizonclient/examplehorizonclient.go
<details>
otherwise).
packages.
</details>
Change `protocols/horizon/Account.Sequence` to `int64` from `string`.
There shouldn't be any extra parsing required in Go since `Account.Sequence` returned by Horizon will be always a valid int64 value. We can make sure the value is …
> protocols/horizon: Change Account.Sequence to int64

- protocols/horizon/operations/main.go
<details>
otherwise).
packages.
</details>
Adds `Operation.GetBase()` method.
`Base` struct contains some fields that are not exposes by getters (ex. `SourceAccount`). This means it's impossible to get them without type asserting to one of the concrete operation structs.
[TODO or …
> protocols/horizon: Add GetBase() to Operation interface

- exp/lighthorizon/actions/transaction.go
- exp/lighthorizon/archive/ingest_archive.go
- exp/lighthorizon/common/transaction.go
- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/connect.go
- exp/lighthorizon/index/store.go
- exp/lighthorizon/index/types/bitmap.go
- exp/lighthorizon/index/types/trie.go
- exp/lighthorizon/main.go
Two major changes:
- adding a `ConnectWithConfig` helper that enables passing a config to `index.Store`
- adding a preliminary metric to demonstrate scaffolding: the size of the index working set
Metrics are good! Plus #4451.
I'd like to get :heavy_check_mark: on the way I've set up metrics before investing too much time into the metrics themselves.
n/a
> exp/lighthorizon: Add basic scaffolding for metrics.

- exp/lighthorizon/index/cmd/batch/reduce/main.go
- exp/lighthorizon/index/cmd/map.sh
- exp/lighthorizon/index/cmd/mapreduce_test.go
- exp/lighthorizon/index/cmd/reduce.sh
This adds a test, `TestReduce`, that ensures that running parallel reduce jobs on previously-map'd jobs results in a complete and valid set of indices. It also extends the existing `TestMap` test to ensure that TOIDs are indexed properly.
This test uncovered an off-by-one bug that segues into an overflow bug, summarized by this (pseudo)diff:
```diff
-	for i := byte(0x00); i < 0xff; i++ {
+	for ii := int(0x00); ii <= 0xff; ii++ {
+		i := byte(ii) // can't loop over byte range bc overflow
```
Testing is important and bugs are bad.
This introduces another Bash script to compile & run binaries in parallel, which means dependence on *nix-based systems.
> exp/lighthorizon/index: More testing for batch indexing and off-by-one bugfix.

- exp/services/captivecore/main.go
- exp/tools/dump-ledger-state/main.go
- exp/tools/dump-orderbook/main.go
- historyarchive/archive.go
- historyarchive/http_archive.go
- ingest/ledgerbackend/captive_core_backend.go
- services/horizon/internal/ingest/main.go
- tools/archive-reader/archive_reader.go
<details>
otherwise).
packages.
</details>
Add `UserAgent` to `historyarchive.ConnectOptions`. The value will be propagated to `User-Agent` header send along http requests to history achive.
This will allow better tracking of clients using history achives.
[TODO or N/A]
> historyarchive: Add User-Agent header to history archive HTTP requests

- exp/lighthorizon/index/backend/file.go
- exp/lighthorizon/index/cmd/reduce.sh
- exp/lighthorizon/index/connect.go
This sets a default worker count for the index store if it's unspecified.
The default value for an integer in Golang is 0, which means no writer workers get created when flushing to the filesystem if you don't specify a quantity, which means nothing gets written to disk :facepalm: 
It's likely that the CPU-based default value is not the best choice for every case. 
Would just setting it to 1 be better?
> exp/lighthorizon: Set a default number of workers.

- services/horizon/internal/ingest/verify/main.go
- services/horizon/internal/ingest/verify/main_test.go
<details>
otherwise).
packages.
</details>
Improve error message to explicitly say where a given ledger entry come from.
It's easy to confuse what is expected and what is actual ledger entry.
[TODO or N/A]
> services/horizon: Improve state verifier error message

- exp/lighthorizon/index/backend/parallel_flush.go
- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/connect.go
Synchronizes the parallel flush job distributor goroutine.
There's a write/read data race that's breaking tests.
n/a
> exp/lighthorizon: Fix the single-process index builder data race.

- services/ticker/internal/scraper/main.go
- services/ticker/internal/scraper/main_test.go
- services/ticker/internal/scraper/trade_scraper.go
<details>
otherwise).
packages.
</details>
Fix `panic: runtime error: index out of range [-1]` issue happening in:
https://github.com/stellar/go/blob/9d9d81ecd855a20d5e2dd2a205e3745959d91e27/services/ticker/internal/scraper/main.go#L138
We were not checking the size of the …
> services/ticker: fix "panic: runtime error: index out of range [-1]"

- tools/horizon-cmp/internal/response.go
<details>
otherwise).
packages.
</details>
Ignore 502s in horizon-cmp
Cause they happen sometimes, and it currently panics.
[TODO or N/A]
> Ignore 502s in horizon-cmp

- exp/lighthorizon/archive/ingest_archive.go
- exp/lighthorizon/archive/main.go
- exp/lighthorizon/main.go
- go.mod
- historyarchive/fs_cache.go
Two changes:
- Update `historyarchive.FsCacheBackend` to use an off-the-shelf package ([`hashicorp/golang-lru`](https://pkg.go.dev/github.com/hashicorp/golang-lru#Cache)) over a custom solution.
- Use the above to wrap the ledger backend
This nearly eliminates request latency if the ledgers are cached locally.
We should think about a best practice for cache eviction when we upgrade the exported meta, though maybe this just means operators delete their caches.
> exp/lighthorizon: Add an on-disk cache for frequently accessed ledgers.

- exp/lighthorizon/index/cmd/single_test.go
- exp/lighthorizon/index/modules.go
- historyarchive/range.go
For the MVP described in #4317, we don't need indices for successful transactions. We only need them for all transactions and payments, should we decide to expand to that endpoint.
This also slightly unifies the code & its tests to do checkpoint number math consistently.
This will reduce the index sizes for the MVP.
> exp/lighthorizon/index: Drop building indices for successful transactions.

- exp/lighthorizon/http.go
- exp/lighthorizon/main.go
<details>
otherwise).
packages.
</details>
Add metrics middleware to collect request duration metrics.
Implements part of https://github.com/stellar/go/issues/4451
[N/A]
> exp/lighthorizon: Add metrics middleware to collect request duration metrics

- exp/lighthorizon/index/types/bitmap.go
- exp/lighthorizon/services/cursor.go
- exp/lighthorizon/services/cursor_test.go
- exp/lighthorizon/services/main.go
- exp/lighthorizon/services/main_test.go
<details>
otherwise).
packages.
</details>
This introduces the `CursorManager` interface which describes how a cursor advances for a particular set of indices, and adds the `AccountTransactionCursorManager` to handle cursor advancement for the MVP endpoint.
This isolates that …
> exp/lighthorizon: Isolate cursor advancement code to its own interface

- exp/lighthorizon/index/backend/parallel_flush.go
- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/cmd/batch/map/main.go
- exp/lighthorizon/index/cmd/map.sh
- exp/lighthorizon/index/cmd/mapreduce_test.go
Besides some minor logging and memory usage improvements, this adds the `NETWORK_PASSPHRASE` env which can be set to either `pubnet` or `testnet` for the public and test network passphrases, respectively, or a custom passphrase.
This is important for getting the map jobs on AWS Batch.
n/a
> exp/lighthorizon/index: Parse network passphrase from the env.

- exp/lighthorizon/archive/ingest_archive.go
- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/cmd/single_test.go
- exp/services/ledgerexporter/main.go
- exp/tools/dump-ledger-state/main.go
- exp/tools/dump-orderbook/main.go
- historyarchive/archive.go
- historyarchive/archive_pool.go
- historyarchive/archive_test.go
- historyarchive/mock_archive.go
- historyarchive/util.go
- ingest/doc_test.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/history_archive_backend.go
- ingest/tutorial/example_claimables.go
- metaarchive/main.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/integration/db_test.go
- support/storage/filesystem.go
- support/storage/gsc.go
- support/storage/http.go
- support/storage/main.go
- support/storage/ondisk_cache.go
- support/storage/s3.go
- tools/archive-reader/archive_reader.go
- tools/stellar-archivist/main.go
- tools/stellar-archivist/main_test.go
<details>
otherwise).
packages.
</details>
Refactor `historyarchive` and `ledgerbackend` to allow better access to the new meta archives:
* Created `metaarchive` package that connects to the new meta archives (and allows accessing `xdr.SerializedLedgerCloseMeta`).
* Extracted …
> Refactor access to meta archive

- exp/lighthorizon/http.go
- exp/lighthorizon/main.go
- exp/lighthorizon/services/main.go
- exp/lighthorizon/services/main_test.go
- services/horizon/internal/httpx/middleware.go
- support/http/logging_middleware.go
- support/http/sanitize_route_test.go
<details>
otherwise).
packages.
</details>
As part of https://github.com/stellar/go/issues/4451 , this PR adds a metric to keep track of the age of the data contained in the service response. The response age is defined as the difference between the current time and the ledger …
> exp/lighthorizon: Add response age prometheus metrics

- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/cmd/batch/map/main.go
- exp/lighthorizon/index/cmd/map.sh
- exp/lighthorizon/index/modules.go
This adds `Module`s to build indices by ledger in addition to by checkpoint for account indices.
It also extends the map job to have a `MODULES` environmental variable to control which modules are built. To build without indices, you would pass `MODULES="accounts_by_ledger_unbacked"`.
It also removes building transaction indices by default.
We need to evaluate the difference in size / latency / etc. in using by-checkpoint or by-ledger indices for accounts.
n/a
> exp/lighthorizon/index: Allow accounts to be indexed by ledger.

- exp/services/ledgerexporter/main.go
- historyarchive/s3_archive.go
- services/horizon/docker/ledgerexporter/Dockerfile
- services/horizon/docker/ledgerexporter/captive-core-testnet.cfg
- services/horizon/docker/ledgerexporter/ledgerexporter.yml
- services/horizon/docker/ledgerexporter/start
- support/storage/main.go
- support/storage/s3.go
- support/storage/s3_test.go
<details>
otherwise).
packages.
</details>
Enable the ledgerexporter image to be deployed/run as service in container orchestration, enable more env settings for configurability between testnet/pubnet. Create deployment on kubernetes that emits to S3 bucket.
Will enable latest …
> services/horizon/docker/ledgerexporter: deploy ledgerexporter image as service

- exp/lighthorizon/index/backend/s3.go
- exp/lighthorizon/index/builder.go
- exp/lighthorizon/index/connect.go
- exp/lighthorizon/index/store.go
- exp/lighthorizon/main.go
- exp/lighthorizon/services/cursor_test.go
Closes #4504 
Also, 
* Renames Url to URL
* stops the abuse of `StoreConfig.URL` which I don't think should be overwritten
> exp/lighhorizon: Make indexing s3 bucket configurable

- exp/lighthorizon/main.go
- exp/lighthorizon/services/main.go
Add basic aggregate metrics for request fulfillment:
- how long did ledger _downloads_ take, on average?
- how long did ledger _processing_ take, on average?
- how long did index lookups take, on average?
- how many ledgers were needed?
- how long did the entire request take, in total?
#4451, these will be crucial for doing performance analysis, identifying optimization opportunities, and making comparisons to classic Horizon.
There are some alternatives:
- logging each of these metrics on its own line
- should these be part of Prometheus, instead?
> exp/lighthorizon: Add duration metrics for on-the-fly ingestion elements.

- exp/lighthorizon/actions/main.go
Adds JSON `Content-Type` header to responses to render correctly.
self-explanatory
> exp/lighthorizon: Add JSON content type to responses.

- exp/lighthorizon/actions/main.go
This sets the content-type at the right time and also makes error messages proper JSON.
The headers can't be set after `Write()` is called on `w`.
> exp/lighthorizon: *Correctly* set `Content-Type`, plus JSONify errors

- exp/lighthorizon/services/main.go
- exp/lighthorizon/services/operations.go
- exp/lighthorizon/services/transactions.go
<details>
otherwise).
packages.
</details>
This moves transaction-related stuff to `./services/transactions.go` and operation-related stuff to `./services/operations.go`.
Better readability via code grouping.
> exp/lighthorizon/services: Move service-specific stuff to its own file.

- exp/lighthorizon/index/backend/gzip.go
- exp/lighthorizon/index/backend/gzip_test.go
- exp/lighthorizon/index/backend/s3.go
- exp/lighthorizon/index/cmd/batch/reduce/main.go
- exp/lighthorizon/index/store.go
- exp/lighthorizon/index/types/bitmap.go
- exp/lighthorizon/index/types/bitmap_test.go
- gxdr/xdr_generated.go
- xdr/Stellar-lighthorizon.x
- xdr/xdr_generated.go
Rename `{types,xdr}.CheckpointIndex` -> `{types,xdr}.BitmapIndex`.  
Rename `NextActive` -> `NextActiveBit`.
This is a better reflection of the capability of the index: it can operate on any value, not necessarily just checkpoints (this is further evidenced by using it to index by ledger).
n/a
> exp/lighthorizon, xdr: Rename `CheckpointIndex` to better reflect its capabilty.

- services/horizon/docker/verify-range/dependencies
<details>
otherwise).
packages.
</details>
Temporarily remove unstable apt repo from verify-range.
The latest build of `stellar-core` in unstable throws:
```
default: Got an exception: bad value of v in _ext_t
```
when running catchup command on specific ledger ranges [1].
[1] …
> services/horizon: Remove unstable apt repo from verify-range

- exp/lighthorizon/tools/cache.go
- support/storage/ondisk_cache.go
Adds a set of tools to manage the on-disk cache:
- `cache build`: caches a ledger range on-disk w/o running Horizon Lite
- `cache purge`: purges ledger ranges from the disk
- `cache show`: shows which ledger ranges are cached on-disk
Output of `cache --help`, for more details:
```
Manages the on-disk cache of ledgers.
Usage:
cache [flags]
cache [command]
Examples:
cache build --start 1234 --count 1000 s3://txmeta /tmp/example
cache purge /tmp/example 1234 1300
cache show /tmp/example
Available Commands:
build       
purge       
show        
Use "cache [command] --help" for more information about a command.
```
Caching is important for performance, but by default, Horizon Lite only caches ledgers that get _used_. It's very useful to be able to cache ledgers _before_ they are needed, for …
> exp/lighthorizon: Add a suite of tools to manage the on-disk ledger cache.

- .github/workflows/go.yml
This adds a `go-complete` (prefixed in case we want to add e.g. a `horizon-complete` in the future) job that encompasses all of the Go-related checks into one job.
It makes it easier to control which jobs are "required" for a PR to be merged. Additional context from @leighmcculloch is [here](https://github.com/stellar/terraform/pull/892#discussion_r942737090).
n/a
> all: Add a generic 'complete' job for PR pass criteria flexibility.

- exp/tools/dump-ledger-state/Dockerfile
Similar to https://github.com/stellar/go/pull/4521: remove unstable repo that contains a broken stellar-core build.
> exp/tools/dump-ledger-state: Use only stable core builds

- exp/lighthorizon/archive/ingest_archive.go
- exp/lighthorizon/archive/main.go
- exp/lighthorizon/archive/mock_archive.go
- exp/lighthorizon/index/backend/file.go
- exp/lighthorizon/index/cmd/mapreduce_test.go
- exp/lighthorizon/services/main_test.go
- support/collections/maps/map.go
- support/collections/maps/map_test.go
- support/collections/set/set.go
Incorporate `set.Set[T]` into the codebase and introduce a new `Keys` for `map`s.
Forcing users to use `map[string]struct{}` as a set structure in 2022 is absurd.
None, generics are amazing.
> Incorporate generics into Light Horizon code

- exp/tools/dump-ledger-state/Dockerfile
<details>
otherwise).
packages.
</details>
Bump golang used by `exp/tools/dump-ledger-state` to 1.19.
There's a go mod error for the current `go.sum` file when using `go1.16.5`.
[TODO or N/A]
> exp/tools/dump-ledger-state: Bump golang version

- exp/lighthorizon/build/index-batch/Dockerfile
- exp/lighthorizon/build/index-single/Dockerfile
- exp/lighthorizon/build/web/Dockerfile
<details>
otherwise).
packages.
</details>
bump go version on the lighthorizon dockers to 18
some of app code is now using go 18 aspects.
> exp/lighthorizon/build: bump go version to 18 on lighthorizon docker images, they need it now

- services/horizon/internal/scripts/check_release_hash/Dockerfile
- services/horizon/internal/scripts/check_release_hash/check.sh
<details>
otherwise).
packages.
</details>
Ensure the git working dir in `check_release_hash` image is clean.
Starting from the Go 1.18 [release notes](https://tip.golang.org/doc/go1.18):
> The go command now embeds version control information in binaries. It includes the …
> services/horizon: Fix check_release_hash in Golang 1.18+

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Skip integration test if they have already passed for the `[hash of horizon binary, hash of horizon integration tests files, p19 core docker image name, p18 core docker image name]` set. The solution leverages `actions/cache@v3` action …
> services/horizon: Skip integration tests when no changes

- exp/lighthorizon/tools/cache.go
- exp/lighthorizon/tools/explorer.go
- exp/lighthorizon/tools/main.go
- support/collections/set/set.go
- support/ordered/math.go
This extends the `tools` toolkit (which previously only let you inspect the web server ledger cache) to add helpful tools to inspect indexes. It includes the following tools: when given an index location, you can
* view what accounts are indexed there
* view what checkpoints particular accounts are active at
* view statistics about the index such as:
- the # of accounts indexed, 
- the range (smallest, largest) of indexed checkpoints
- the total # of active checkpoints (thus giving you a ledger range covered by the index)
- the index names
This is particularly useful until we extend the index format to store some of this stuff internally, so that we can learn about long-running processes (like the map-reduce index builder) and how much progress they've made.
For example, I used this …
> exp/lighthorizon: Add a set of tools to aide in index inspection.

- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/reap_test.go
- services/horizon/internal/db2/schema/60_add_asset_id_indexes.sql
- services/horizon/internal/db2/schema/bindata.go
<details>
otherwise).
packages.
</details>
Adds the last remaining table: `history_assets` to lookup table reaper.
Close #4396.
In https://github.com/stellar/go/pull/4518 the code responsible for reaping lookup tables was added but was missing one table: `history_assets` due to …
> services/horizon: Add history_assets to lookup tables reap

- support/storage/ondisk_cache.go
When caching files, add a `<name>.lock` file that exists until the file is fully written. When retrieving files, check that they don't have a corresponding .lock file before reading them from the cache.
This adds thread safety to the on-disk cache and is necessary for both #4468 and #4526.
n/a
> support/storage: Make the on-disk cache thread-safe.

- exp/lighthorizon/index/builder.go
- support/storage/http.go
- support/storage/s3.go
- support/storage/s3_test.go
<details>
otherwise).
packages.
</details>
Noticed the index single cmd with `watch` was err'ing on getting latest ledger from txmeta source, and then exiting execution, the s3 'not found' was not being converted to the expected os `ErrNotFound` to allow it to re-attempt after …
> exp/lighthorizon/index/cmd: Fix index single watch, slow down the retry on not-found ledgers 

- exp/lighthorizon/actions/accounts.go
- exp/lighthorizon/build/k8s/lighthorizon_web.yml
- exp/lighthorizon/build/web/Dockerfile
- exp/lighthorizon/services/main.go
<details>
otherwise).
packages.
</details>
Three small things:
* actually set the `PARALLEL_DOWNLOADS` parameter to use #4468 
* return a 404 rather than a 500 if a ledger is missing as its more descriptive
* handle `count = 0` in average calculations
In order:
* use the feature …
> exp/lighthorizon: Minor error-handling and deployment improvements.

- clients/horizonclient/internal.go
- clients/horizonclient/internal_test.go
- clients/horizonclient/main_test.go
The code in currentServerTime was not testing the existence of the entry in `ServerTimeMap` correctly. As a result, it would have missed the case where an entry could be missing from the map.
That being said, this is a benign bug. It would never triggered unless the clock is set around epoch time ( which is not really realistic ). This fix is just to make sure that our code is correct. There should be no expectation of any behavioral change.
otherwise).
packages.
needed with deprecations, added features, breaking changes, and DB …
> clients/horizonclient: fix theoretical bug in currentServerTime

- .github/workflows/golangci-lint.yml
- .github/workflows/reviewdog.yml
- .golangci.yml
otherwise).
packages.
</details>
This PR adds the golangci linter as a GitHub action.
The command line version would be more capable than this version, as the integration with GitHub isn't that great.
( adding comments require elevated privileges, which might be a security issue ).
It would allow us to get …
> all: add golangci linter as a GitHub action

- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_test.go
<details>
otherwise).
packages.
</details>
This commit improves `stellarCoreRunner` code to not remove storage dir if LCL of Captive-Core is greater than or equal requested `from` ledger.
In e3d3abc01de7bfb3e1e7e675d17fb2e45a250257 we added a code that skips removing storage dir …
> ingest/ledgerbackend: Skip removing storage dir when Captive-Core in front of requested ledger

- exp/services/soroban-rpc/internal/jsonrpc.go
- exp/services/soroban-rpc/internal/methods/transaction.go
- exp/services/soroban-rpc/internal/methods/transaction_test.go
- exp/services/soroban-rpc/internal/test/integration.go
- exp/services/soroban-rpc/internal/test/transaction_test.go
- exp/services/soroban-rpc/main.go
- network/main.go
<details>
otherwise).
packages.
</details>
Add json rpc methods for sending a transaction and querying a transaction status. This is implemented by proxying to the horizon txsub endpoint and the horizon transaction detail endpoint.
https://github.com/stellar/go/issues/4595 …
>   exp/services/soroban-rpc: Add getTransactionStatus and sendTransaction json rpc methods

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
update the horizon p20 integration tests to use latest soroban build of core
need to confirm ingestion works with newest xdr and core versions
Closes: #4604
> horizon: update core version in p20 integration tests, to latest 1085 build

- ingest/checkpoint_change_reader.go
- xdr/ledger_entry.go
- xdr/ledger_key.go
<details>
otherwise).
packages.
</details>
```
time="2022-10-07T22:32:45.491Z" level=info msg="Processing entries from History Archive Snapshot" pid=23460 sequence=149503 service=ingest
time="2022-10-07T22:32:46.491Z" level=info msg="Finished request" app_name=undefined …
```
> horizon\ingest: fix LedgerEntryTypeContractData

- .github/workflows/horizon-master.yml
When migrating the repository from CircleCI to GitHub we were planning on enabling pushing docker image `stellar/horizon:<commit-sha>` from the master branch on every merged commit.
However, we never enabled it (note the commented `# push: true` line)
If we haven't used this in 8 months and we haven't missed it, it's clear we don't need it. Also, `stellar/horizon` is confusing due to the name similarity with `stellar/stellar-horizon`, see #4669).
> services/horizon: Remove (unused) stellar/horizon docker image push

- services/horizon/cmd/ingest.go
- services/horizon/internal/ingest/build_state_test.go
- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/main_test.go
- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/verify_range_state_test.go
<details>
otherwise).
packages.
</details>
Add `ingest build-state` command which builds state at any given sequence number and exists. It's also possible to skip bucket list hash checks which significantly speeds up the process (useful for debugging purposes).
It's ofter useful …
> services/horizon: Add `ingest build-state` command

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/internal/ingest/db_integration_test.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/main_test.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Use the entire list of provided history archives when ingesting.
Though #3402 allows Captive Core to rotate through a list of history archives, the ingestion interface continued to use the first one in the list. This creates undue strain …
> services/horizon: Propogate *all* history archives through the ingestion interface.

- services/horizon/docker/verify-range/captive-core-pubnet.cfg
- services/horizon/docker/verify-range/start
Revert on-disk mode in Captive-Core config and use S3 URLs for history archives. The first change ensures that verify-range container runs fast (currently it takes 2 hours in AWS to ingest state alone for a single range), the second makes the download of bucket files faster in AWS Batch.
> verify-range: revert on-disk mode, use S3 URLs for history archives

- .github/workflows/go.yml
- .github/workflows/horizon-release.yml
- .github/workflows/horizon.yml
Update Github Actions to use latest `golang:1.19` image for Horizon testing and releases. This is done to match internal pipeline that builds Debian packages.
> Use latest golang 1.19 tag

- .github/workflows/horizon.yml
new build of core came out for upcoming soroban release, include it here for integration test verification, the xdr updates are already in from https://github.com/stellar/go/pull/4704
> soroban release prep, update soroban core version for p20 integration tests

- ingest/ledgerbackend/toml.go
- ingest/ledgerbackend/toml_test.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/integration/parameters_test.go
<details>
otherwise).
packages.
</details>
Changing the error message returned when BUCKET_DIR_PATH is set when using captive core, just so that it's clear what corrective action needs to be taken.
Partner engineering raised this when working through an issue with Kraken, the …
> services/horizon: Add clarity to error when setting BUCKET_DIR_PATH with captive core

- xdr/ledger_key.go
Without this change all the contract data entries of a contract resulted in the same serialization regardless of their keys.
> horizon: Include the contract data key when compress-encoding ledger keys

- exp/services/captivecore/main.go
- ingest/ledgerbackend/toml.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/flags.go
Addresses #4710.
This PR exposes BucketListDB related configuration parameters in the captive-core toml file and enables BucketListDB by default in captive-core when using `--captive-core-use-db`. When enabled, BucketListDB reduces captive-core disk usage by around 50% and significantly reduces startup and catchup time.
This update exposes the captive core flags `EXPERIMENTAL_BUCKETLIST_DB`, `EXPERIMENTAL_BUCKETLIST_DB_INDEX_PAGE_SIZE_EXPONENT`, and `EXPERIMENTAL_BUCKETLIST_DB_INDEX_CUTOFF`. These flags control the memory usage of BucketListDB. See the [stellar-core docs](https://github.com/stellar/stellar-core/blob/master/src/bucket/readme.md) for more information on configuring these flags.
By default, captive-core will enable BucketListDB with a page size of 4 KB. This is different …
> services/horizon: Enable BucketListDB by default in captive core

- services/horizon/docker/Dockerfile
- services/horizon/docker/Makefile
allow optional stellar_core_version to be passed to horizon docker build
need it for the SRE hackathon project and could be useful for other things
will test with branch
https://github.com/stellar/ops/issues/2076
> allow optional stellar_core_version to be passed to horizon docker build

- exp/services/webauth/internal/serve/challenge.go
- exp/services/webauth/internal/serve/challenge_test.go
- exp/services/webauth/internal/serve/token.go
- exp/services/webauth/internal/serve/token_test.go
- txnbuild/CHANGELOG.md
- txnbuild/example_test.go
- txnbuild/transaction.go
- txnbuild/transaction_challenge_example_test.go
- txnbuild/transaction_test.go
<details>
otherwise).
packages.
</details>
resolves #3937
Adds support for muxed accounts to be specified as client account IDs and memos to be added to challenge transactions. This is a breaking change.
SEP-10 was modified to support users of shared Stellar accounts. The two …
> txnbuild: add muxed account & memo support to SEP-10 utility functions

- services/horizon/docker/Dockerfile
- services/horizon/docker/Makefile
Update the Makefile and Dockerfile to allow for an optional core_version.
If no version is specified, behavior is same as before.
To allow versions of Core from the Unstable repo to be used in builds of horizon for testing.
https://github.com/stellar/ops/issues/2076
> Allow Core version to be specified in stellar-horizon docker build DEV

- services/horizon/configs/captive-core-pubnet.cfg
- services/horizon/docker/captive-core-pubnet.cfg
- services/horizon/docker/stellar-core-pubnet.cfg
<details>
otherwise).
packages.
</details>
Wirex shut down their public nodes back in early January, so removing references to those from our config. 
Since Wirex shut down their nodes back in January, we've had at least 3 separate partners send us over  logs that indicate …
> services/horizon: remove references to wirex validators

- xdr/ledger_key.go
- xdr/ledger_key_test.go
`GetLedgerKeyFromData()` is migrated from `soroban-tools` (soroban-rpc). They will be used to implement https://github.com/stellar/soroban-tools/issues/378
> xdr: Add SetConfigSetting() and GetLedgerKeyFromData()

- ingest/event.go
- ingest/event_test.go
- xdr/asset.go
- xdr/ledger_key.go
Adds an abstraction layer for standardized contract events that come from the Stellar Asset Contract.
Event parsing is necessary to generate effects and record payments as part of #4722 (and #4725).
This only covers the `transfer` events generated by calling `xfer` and `xfer_from`. It could also use more test cases.
Ideally, @sreuland and I would build the parsing/testing on top of this PR for the events we need as they pertain to our issues.
> ingest: Adds basic event parsing for standard Stellar Asset Contract events

- services/horizon/configs/captive-core-pubnet.cfg
- services/horizon/docker/captive-core-pubnet.cfg
- services/horizon/docker/stellar-core-pubnet.cfg
<details>
otherwise).
packages.
</details>
Add Franklin Templeton to quorum set for captive core nodes. Actual config is managed in puppet and updated [here](https://github.com/stellar/puppet-v4/pull/3157), but we should keep this example in-line as partners often look to it as …
> Add franklin templeton to captive core QS

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
This is exactly like #4803, but targeting the `soroban-xdr-next` branch where the matrix is even larger.
These are no longer necessary as the upgrade occurred a while ago and they waste a ton of time.
n/a
> all: Drop Protocol 18 integration tests from GHAs, Soroban edition

- support/contractevents/event.go
- support/contractevents/event_test.go
- support/contractevents/generate.go
- support/contractevents/utils.go
This PR has three components:
1. It fixes a misunderstanding in event parsing in which assets were assumed to be encoded in SEP-11 `<code>:<issuer>` format, whereas they're actually encoded as raw XDR separated by a `:` byte
2. It adds more tests for various parts of the library
3. It adds an exported `GenerateEvent` function which lets external packages generate arbitrary event fixtures for testing without worrying about packing the XDR correctly 
Respectively,
1. This is a bug when using this on real events and the new `TestRealXdr()` proves this
2. For stability, of course
3. Related issues like #4806 can benefit from creating events w/o needing to understand their structure
See stellar/rs-soroban-env#727 for recommendations on improving (1).
n/a
> support/contractevents: Properly parse asset topic, add event generator.

- xdr/scval.go
- xdr/scval_test.go
- xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
Fix the ScVal.Equals method for the soroban xdr value overhaul.
Part of https://github.com/stellar/soroban-tools/issues/477
Needed for https://github.com/stellar/go/issues/4789, because this change gets the `xdr` package compiling and …
> Soroban xdr value overhaul ScVal.Equals fixes

- Makefile
- xdr/xdr_generated.go
This is the result of https://github.com/stellar/xdrgen/pull/155
We will probably need to adjust the xdrgen commit once https://github.com/stellar/xdrgen/pull/155 gets merged
> soroban-xdr-next-next: Fix XDR bool encoding/decoding

- .github/workflows/go.yml
- .github/workflows/horizon-release.yml
- .github/workflows/horizon.yml
- staticcheck.sh
It's time :eyes:
Also, stop using specific versions so that we always used the latest patch version of a major release. Didn't this used to be the case?
> all: Bump supported Go versions to 1.19 and 1.20.

- tools/stellar-sign/README.md
Fix quick typo in stellar-sign README
> Fix typo stellar-sign README

- services/horizon/docker/Dockerfile.dev
<details>
otherwise).
packages.
</details>
remove reference to now [deprecated captive core package](https://github.com/stellar/go/pull/4826) 'exp/services/captivecore' from the horizon dockerfile build.
causing a docker build error on the missing package now in downstream client …
> removed reference to remote captivecore package as it's been deprecated

- services/horizon/docker/Dockerfile.dev
porting latest from master back to soroban next branch, pull in a recent [small fix for dockerfile build related to deprecated captivecore package](https://github.com/stellar/go/pull/4846) that happened today.
> merge latest from master to soroban-xdr-next

- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/operations_processor_test.go
- services/horizon/internal/integration/contracts/sac_test/src/lib.rs
- services/horizon/internal/integration/sac_test.go
- support/contractevents/event.go
- support/contractevents/event_test.go
services/horizon: update sac integration tests for new token interface changes
- Event hasn't actually changed.
> services/horizon: update sac integration tests for new token interface changes

- xdr/asset_test.go
Based on https://github.com/stellar/js-stellar-base/issues/593, I added a small unit test for the go xdr asset sorting with mixed upper/lower case assets.
> Add a simple test for asset case sorting in ascii

- ingest/ledgerbackend/toml.go
<details>
otherwise).
packages.
</details>
add support for parsing LIMIT_TX_QUEUE_SOURCE_ACCOUNT config
Without that change, parsing a valid core toml file would fail.
n/a
> horizon: add support for parsing LIMIT_TX_QUEUE_SOURCE_ACCOUNT config

- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/main_test.go
<details>
otherwise).
packages.
</details>
Protect the currentState variable using a Mutex to avoid a race condition caused by reading the currentState variable from UpdateCoreLedgerState() in one goroutine while updating it in the ingestion loop from another goroutine. 
Since …
> services/horizon: Protect 'currentState' variable using Mutex to prevent race condition.

- services/horizon/CHANGELOG.md
- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
Modify the default value of the `--captive-core-use-db` command line flag to true. This modification ensures that CaptiveCore utilizes an external database instead of relying on memory (RAM). The configuration of the external database …
> services/horizon: Update default for  --captive-core-use-db to true

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
Improve the error handling order and display more helpful error messages when stellar-core crashes.
When stellar-core crashes, the meta pipe will close and attempting to read from the closed pipe will result in an EOF error during the …
> services/horizon: Improve error handling for when stellar-core crashes

- ingest/ledgerbackend/toml.go
<details>
otherwise).
packages.
</details>
Porting this change https://github.com/stellar/go/pull/4882 from `soroban-xdr-next` into `master`.
Core wants to be able to release the 1 transaction/account/ledger restriction ahead of when it is forced by protocol 20, to observe any …
> Parse LIMIT_TX_QUEUE_SOURCE_ACCOUNT in core config

- .github/workflows/codeql-analysis.yml
- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/horizon-master.yml
- .github/workflows/horizon-release.yml
- .github/workflows/horizon.yml
- exp/services/recoverysigner/docker/Dockerfile
- exp/services/webauth/docker/Dockerfile
- services/friendbot/docker/Dockerfile
- services/horizon/docker/Dockerfile.dev
- services/horizon/docker/verify-range/Dockerfile
- services/horizon/docker/verify-range/start
- services/horizon/internal/scripts/check_release_hash/Dockerfile
<details>
otherwise).
packages.
</details>
- Upgrade ubuntu versions from 20.04 to 22.04
- Pin golang images to specify the debian OS version we want to use (`bullseye`)
- Sync golang versioning across repos to latest (`1.20-bullseye`)
- Run horizon integration tests on the full …
> Pinning and updating golang and ubuntu images

- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/internal/integration/db_test.go
<details>
otherwise).
packages.
</details>
Might be complementary to https://github.com/stellar/go/pull/4938
> integration tests: Add horizon test support for new bump/restore footprint ops

- services/horizon/CHANGELOG.md
- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
The local captive core config steps have been consolidated into a single 'if' condition. Removed `--remote-captive-core-url` from flags.
This is a minor code refactoring aimed at simplifying code before adding the new NETWORK flag #4913. …
> services/horizon: Consolidate local captive core config steps

- .github/workflows/horizon.yml
- protocols/horizon/operations/main.go
- services/horizon/internal/actions/operation_test.go
- services/horizon/internal/ingest/processors/contract_data.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/operations_processor_test.go
- services/horizon/internal/ingest/verify_test.go
- services/horizon/internal/integration/invokehostfunction_test.go
- services/horizon/internal/integration/sac_test.go
- support/contractevents/event.go
- support/contractevents/event_test.go
- support/contractevents/generate.go
This is part #2 of updates for preview 10 data model on horizon:
part #1 focused on non-sac test fixing and has merged - https://github.com/stellar/go/pull/4938
this is focused on fixing the sac tests:
* asset stats 
* effects(contract events parsing) 
* contract events
all these areas were affected by changes in different vec/map layout and instance vs. persistent contract data paths in ContractDataEntry and ScString usage in sac event topics and contract ledger entry asset issuer value.
Closes #4896
> fix sac tests for preview 10 data model

- services/horizon/docker/docker-compose.standalone.yml
<details>
otherwise).
packages.
</details>
Set `STELLAR_CORE_URL` to `http://host.docker.internal:11626`.
The default value of STELLAR_CORE_URL (localhost:11626) in standalone network mode doesn't work. We need to explicitly set STELLAR_CORE_URL to …
> services/horizon: Fix Horizon connectivity to core in standalone docker

- services/horizon/internal/integration/contracts/README.md
<details>
otherwise).
packages.
</details>
added documentation explaining configuration of soroban rpc for preflight usage in horizon/internal/integration/contracts tests.
the contract integration tests require soroban rpc to perform preflight before submitting transactions, …
> horizon/integration/contracts: readme docs on rpc usage for contract integration tests

- protocols/horizon/effects/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/resourceadapter/effects.go
- services/horizon/internal/resourceadapter/effects_test.go
<details>
otherwise).
packages.
</details>
The EffectRestoreFootprint had the same value as EffectBumpFootprintExpiration, which would generate uncertainties when processing effects.
Trivial
n/a
> horizon: fix EffectRestoreFootprint enum

- protocols/horizon/operations/main.go
Modifies `LedgersToExpire` to be an `int64` that encodes to a `string` (for languages that don't have clean 64-bit number abstractions).
The other ledger sequence numbers are always natively used as numbers, see e.g. [horizon/main.go#L47](https://github.com/stellar/go/blob/master/protocols/horizon/main.go#L47).
n/a
> Make ledger sequence numbers be `int64`s natively

- services/horizon/internal/app.go
<details>
otherwise).
packages.
</details>
When Horizon is in the `build` state, skip querying stellar-core on 127.0.0.1.
In PR #4860, we addressed the issue of excessive log output when Horizon is in the "build" state by skipping querying stellar-core when the STELLAR_CORE_URL …
> Services/horizon: Reduce log output

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Update this [fix](https://github.com/stellar/go/pull/4292) to handle all versions of libc++ 
Horizon CI is failing with errors while running integration test. The error occurs because the apt package manager is unable to install the …
> Resolve Horizon CI failures caused by the failure to install the right version of libc++ 

- Makefile
- services/horizon/Makefile
This PR adds Makefile entries to allow us to build horizon in an isolated, docker based, environment.
This will make build process more transparent and it will simplify build systems where horizon is built.
> services/horizon add horizon binary building Makefile

- services/horizon/internal/flags.go
- services/horizon/internal/flags_test.go
- services/horizon/internal/integration/parameters_test.go
- services/horizon/internal/test/integration/integration.go
<details>
otherwise).
packages.
</details>
Introduce integration tests to verify that Horizon starts successfully with the default configuration when the NETWORK parameter is set to either "pubnet" or "testnet". The tests cover `Network` parameter using both command-line argument …
> Services/horizon: Integration tests for NETWORK parameter

- services/horizon/internal/test/integration/integration.go
They add unnecessary noise to the integration tests output
> services/horizon/internal/test/integration: Stop printing env variables in docker-compose commands

- xdr/main.go
- xdr/main_test.go
> xdr: Add function to obtain the type of a binary-compressed key 

- .github/workflows/horizon.yml
- services/horizon/internal/integration/contracts/Cargo.toml
update core dependencies following fon's fix to env.
fee calculation fixed.
n/a
> horizon: update core dependencies

- .github/workflows/horizon.yml
self-explanatory: this is the "final" (_knocks on wood_) Soroban RPC Docker image for Preview 11.
> Re-point Soroban RPC to the final Docker image

- services/horizon/internal/db2/history/operation.go
- services/horizon/internal/db2/history/operation_batch_insert_builder.go
- services/horizon/internal/db2/history/operation_test.go
<details>
otherwise).
packages.
</details>
The query to select payments from the operations table does not handle the case where is_payments is NULL. The following error occurs in that case:
```
select failed: sql: Scan error on column index 7, name \"is_payment\": sql/driver: …
```
> services/horizon/internal/db2/history: fix payments query

- ingest/ledgerbackend/toml.go
<details>
otherwise).
packages.
</details>
Remove this config that enables/disables the 1 tx/account/ledger limit. 
This flag is defunct now that we're on protocol 20 (see https://github.com/stellar/stellar-core/issues/3933) since it's always enabled. We aren't specifying this …
> Remove LIMIT_TX_QUEUE_SOURCE_ACCOUNT core config

- services/horizon/CHANGELOG.md
- services/horizon/internal/flags.go
- services/horizon/internal/flags_test.go
<details>
otherwise).
packages.
</details>
When running `horizon --db-url postgres://postgres@localhost:5432?sslmode=disable --apply-migrations db reingest range 48263265 48263265` with the following environment variables:
``` …
```
> services/horizon/internal: Fix configuration of captive core in reingest command

- ingest/change.go
- ingest/change_test.go
- ingest/ledger_change_reader.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/integration/liquidity_pool_test.go
- xdr/ledger_close_meta.go
<details>
otherwise).
packages.
</details>
In https://github.com/stellar/stellar-core/issues/3952 we discovered that the tx meta emitted by captive core can appear in a random order. This is problematic for Horizon because we would like ingestion to always be deterministic and …
> ingest: Extract ledger entry changes from Tx Meta in a deterministic order

- .github/workflows/go.yml
- .github/workflows/horizon.yml
- go.mod
- go.sum
https://github.com/stellar/go/pull/5084 broke the Go dependencies, because:
1. `go mod tidy` wasn't invoked before merging leading to a misaligned Go version in go.mod (we should probably enforce this in CI and make sure there are no diffs)
2. It ugraded github.com/creachadair/jrpc2 to 1.1.1 which requires Go 1.21 (breaking the two-Go-release compatibility guarantee we make)
> Fix Go dependencies

- services/horizon/internal/ingest/processors/contract_data.go
<details>
otherwise).
packages.
</details>
fix comment following updated XDR
comment became irrelevant and would only create additional confusion.
n/a
> horizon: fix comment following updated XDR

- ingest/ledgerbackend/metrics.go
- services/horizon/internal/httpx/server.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/txsub/system.go
- support/db/metrics.go
<details>
otherwise).
packages.
</details>
This PR explicitly supplies objectives in `Prometheus.SummaryOpts` because the new version of the Prometheus go client no longer provides the default value.
In previous versions of the Prometheus go client, default objectives were …
> services/horizon: Explicitly supply objectives in Prometheus SummaryOpts to fix metrics dashboards

- .github/workflows/go.yml
- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Upgrade the Postgres versions that we use for integration tests.
Since Horizon requires Postgres version 12 or higher ([as per new docs](https://github.com/stellar/stellar-docs/pull/249/files#diff-55398e93ceb3417fe250daeca353620a9ced43dc9 …
> Update Postgres version used in integration tests

- ingest/checkpoint_change_reader.go
<details>
otherwise).
packages.
</details>
avoid redundant reallocation during streamBucketContents
Existing code was optimized for preloading keys from temp set. However, while this optimization was made, the resizing of the temporary staging buffers was ignored. These could add …
> ingestion: avoid redundant reallocation during streamBucketContents

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Remove legacy ingestion tests from Horizon CI.
We have deprecated legacy ingestion in both prod and staging environments (https://stellarfoundation.slack.com/archives/C02B04RMK/p1697802518821039). We also recommend that partners use …
> services/horizon: Remove legacy ingestion tests from Horizon CI

- services/horizon/internal/actions/claimable_balance_test.go
- services/horizon/internal/db2/history/claimable_balance_batch_insert_builder.go
- services/horizon/internal/db2/history/claimable_balance_claimant_batch_insert_builder.go
- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/claimable_balances_test.go
- services/horizon/internal/db2/history/mock_claimable_balance_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_claimable_balance_claimant_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_q_claimable_balances.go
- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/claimable_balances_change_processor.go
- services/horizon/internal/ingest/processors/claimable_balances_change_processor_test.go
- services/horizon/internal/ingest/verify_test.go
<details>
otherwise).
packages.
</details>
Use [FastBatchInsertBuilder](https://github.com/stellar/go/blob/9ce82de12cbade47de862ad5e9d0684029558564/support/db/fast_batch_insert_builder.go) for writing to claimable_balances and claimable_balance_claimants tables. …
> services/horizon: Use COPY to speed up ClaimableBalanceChangeProcessor

- services/horizon/internal/db2/history/account_signers.go
- services/horizon/internal/db2/history/account_signers_batch_insert_builder.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/mock_account_signers_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_q_signers.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/signer_processor_test.go
- services/horizon/internal/ingest/processors/signers_processor.go
<details>
otherwise).
packages.
</details>
Optimize the `SignersProcessor` to use `FastBatchInsertBuilder` which uses `COPY` to bulk insert into the database table `account_signers`.
* Using the `FastBatchInsertBuilder` when inserting into the `account_signers` table during …
> Update SignersProcessor to use FastBatchInsertBuilder

- services/horizon/internal/app.go
<details>
otherwise).
packages.
</details>
Added checks for to avoid logging "could not load stellar-core info" errors when Horizon is in the build state
When we fixed issue #4446, we missed another place where we are attempting to get core info and the same condition is applied …
> services/horizon: Suppress stellar-core unreachable error when horizon is building state

- services/horizon/internal/db2/history/liquidity_pool_batch_insert_builder.go
- services/horizon/internal/db2/history/liquidity_pools.go
- services/horizon/internal/db2/history/mock_liquidity_pool_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_q_liquidity_pools.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/liquidity_pools_change_processor.go
- services/horizon/internal/ingest/processors/liquidity_pools_change_processor_test.go
<details>
otherwise).
packages.
</details>
Optimize the `LiquidityPoolsChangeProcessor` to use `FastBatchInsertBuilder` which uses COPY to bulk insert into the database table `liquidity_pools`. Database update and removal operations remain unchanged.
#5098 
N/A
> services/horizon: Use COPY for inserting into liquidity_pools table

- services/horizon/internal/db2/history/mock_offers_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_q_offers.go
- services/horizon/internal/db2/history/offers.go
- services/horizon/internal/db2/history/offers_batch_insert_builder.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/offers_processor.go
- services/horizon/internal/ingest/processors/offers_processor_test.go
<details>
otherwise).
packages.
</details>
Optimize the `OffersChangeProcessor` to use `FastBatchInsertBuilder` which uses COPY to bulk insert into the database table `offers`. Database update and removal operations remain unchanged.
https://github.com/stellar/go/issues/5098 …
> services/horizon: Use COPY for inserting into offers table

- services/horizon/internal/ingest/processor_runner_test.go
<details>
otherwise).
packages.
</details>
Remove unnecessary code from process_runner_tests.go and other formatting changes.
cleanup
N/A
> services/horizon: cleanup process runner tests

- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/mock_q_trust_lines.go
- services/horizon/internal/db2/history/mock_trust_lines_batch_insert_builder.go
- services/horizon/internal/db2/history/trust_lines_batch_insert_builder.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/trust_lines_processor.go
- services/horizon/internal/ingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
Optimize the `TrustLinesProcessor` to use `FastBatchInsertBuilder` which uses COPY to bulk insert into the database table `trust_lines`. Database update and removal operations remain unchanged.
#5098 
N/A
> services/horizon: Use COPY for inserting into trust_lines table

- services/horizon/internal/db2/history/accounts_batch_insert_builder.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/mock_accounts_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_q_accounts.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/accounts_processor.go
- services/horizon/internal/ingest/processors/accounts_processor_test.go
<details>
otherwise).
packages.
</details>
Optimize the `AccountsProcessor` to use `FastBatchInsertBuilder` which uses COPY to bulk insert into the database table `accounts`. Database update and removal operations remain unchanged.
#5098 
N/A
> services/horizon: Use COPY for inserting into accounts table

- services/horizon/internal/db2/history/account_data_batch_insert_builder.go
- services/horizon/internal/db2/history/account_data_value.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/mock_account_data_batch_insert_builder.go
- services/horizon/internal/db2/history/mock_q_data.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/account_data_processor.go
- services/horizon/internal/ingest/processors/accounts_data_processor_test.go
<details>
otherwise).
packages.
</details>
Optimize the `AccountsDataProcessor` to use FastBatchInsertBuilder which uses COPY to bulk insert into the database table `accounts_data`. Database update and removal operations remain unchanged.
#5098
N/A
> services/horizon: use COPY for inserting into accounts_data table

- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/docker/docker-compose.yml
<details>
otherwise).
packages.
</details>
Updated docker-compose.yml and docker-compose.integration.yml
The `docker-compose.yml` file is used by the start.sh script to start Horizon in `testnet`.
The core image in docker-compose.integration.yml is updated to match the one used …
> services/horizon: Fix docker compose Files for Horizon "testnet" and Integration Tests

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/resume_state_test.go
<details>
otherwise).
packages.
</details>
If there is an error rebuilding trade aggregation buckets we should retry ingesting the ledger. The previous code terminated ingestion entirely when encountering a rebuild trade aggregations error.
Rebuilding trade aggregation buckets …
> services/horizon/internal/ingest: Fix error transition in resume state

- .github/workflows/horizon.yml
Configure integration tests to run the protocol 20 version of core and soroban-rpc.
> services/horizon: Bump Core and soroban-rpc versions

- services/horizon/internal/db2/history/asset_stats.go
- services/horizon/internal/db2/history/asset_stats_test.go
- services/horizon/internal/db2/history/main.go
<details>
otherwise).
packages.
</details>
Use FastBatchInsertBuilder for asset stats to speed up db operations where we need to insert a lot of asset stat rows.
> services/horizon/internal/db2/history: Use FastBatchInsertBuilder for asset stats

- ingest/ledgerbackend/captive_core_backend.go
<details>
otherwise).
packages.
</details>
Captive core configures two prometheus metrics which periodically probe the info http endpoint on captive core. If the info request fails, we currently log the error. 
This commit removes the logs because we are already probing the info …
> ingest/ledgerbackend: Remove captive core info request error logs

- services/horizon/internal/ingest/processors/liquidity_pools_transaction_processor.go
- services/horizon/internal/ingest/processors/operations_processor.go
<details>
otherwise).
packages.
</details>
There are a few places in horizon's ingestion code where we extract unique elements (for example, account participants for an operation) using a map data structure. The problem with that approach is that traversing elements in a map in …
> services/horizon/internal/ingest/processors: Dedupe participants deterministically

- ingest/ledgerbackend/toml.go
- ingest/ledgerbackend/toml_test.go
<details>
otherwise).
packages.
</details>
Remove trailing slash from history archive urls when generating the captive core toml file.
If you ran the `horizon db reingest range` command with a `NETWORK` configured to pubnet, the command would fail because the history archive urls …
> ingest/ledgerbackend: Fix captive core toml history entries

- services/horizon/internal/ingest/processor_runner.go
<details>
otherwise).
packages.
</details>
changed the 'Processed ledger' log output from streamLedger method to be a different and more precise phrase about transaction processors context to avoid conflict with an existing 'Processed ledger' log message that was already emitted …
> fix 'Processed ledger' log message conflict

- ingest/ledgerbackend/toml.go
This is a followup of https://github.com/stellar/stellar-core/pull/4104 and https://github.com/stellar/go/pull/5148
> ingest/ledgerbacked/toml: Add support for ENABLE_DIAGNOSTICS_FOR_TX_SUBMISSION in captive core

- exp/lighthorizon/build/ledgerexporter/captive-core-pubnet.cfg
- exp/services/ledgerexporter/main.go
Just noticed a quirk in the `ledgerexporter` tool (which I believe @sydneynotthecity was investigating for Hubble purposes) in that it still uses `historyarchive` when it really just needs `storage`. Previously, `historyarchive` was a convenient "crutch" package that provided backend-agnostic, "file-like" access, but the `storage` package abstracted this concept.
> exp/ledgerexporter: Drop unneeded dependency on `historyarchive`.

- services/horizon/internal/ingest/fsm_reingest_history_range_state.go
<details>
otherwise).
packages.
</details>
removed inclusion of range prep time in the duration logged by `Reingestion done` , it was inadvertently moved as part of ingestion performance overhaul.
keeps the meaning of `Reingestion done` consistent to prior versions of horizon …
> Fix ingestion logging duration time

- historyarchive/archive.go
- historyarchive/archive_pool.go
- historyarchive/archive_test.go
- historyarchive/mocks.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/history_archive_adapter.go
- services/horizon/internal/ingest/history_archive_adapter_test.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/resume_state_test.go
<details>
otherwise).
packages.
</details>
fixed the history archive config for http backend to include custom user-agent value.
added `history_archive_stats_total`  metrics for counters on requests and downloads of files from `Archive`, most of changes in the pr are related to …
> http archive requests include user agent and metrics

- historyarchive/archive_pool_test.go
- ingest/ledgerbackend/captive_core_backend.go
<details>
otherwise).
packages.
</details>
* Passing user agent in the captive core backend
* Add user agent configuration test for ArchivePool
Help in identifying history archive usage patterns
> ingest/ledgerbackend - Pass user agent in ledger backend

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/fsm_reingest_history_range_state.go
- services/horizon/internal/ingest/ingest_history_range_state_test.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/main_test.go
- services/horizon/internal/ingest/parallel.go
- services/horizon/internal/ingest/parallel_test.go
<details>
otherwise).
packages.
</details>
for reingest command, consolidate the invocations of rebuilding of trade agg buckets to once at end of all parallel workers
this avoids getting:
```
Error rebuilding trade aggregations: could not rebuild trade aggregation bucket: exec …
```
> Fix tradeagg rebuild from reingest command with parallel workers

- services/horizon/internal/ingest/main.go
Triple the amount of files that are allowed to be cached.
We are experimenting with the optimal count in order to balance the size of the on-disk cache with the hit rate in avoiding repeated queries to the history archives.
n/a
> services/horizon: Bump the history archive cache size to increase hit rates

- historyarchive/archive_cache.go
- ingest/verify/main.go
- services/horizon/internal/ingest/verify.go
This optimizes existence checks in the case of concurrent history archive sessions sharing a cache.
It also makes a slight performance improvement to state verification memory allocation and improves logging in the state verifier.
This will reduce churn on `Exists()` requests to the archives.
n/a
> historyarchive: Improve existence checks and performance

- services/horizon/CHANGELOG.md
added release notes on how to manage potential legacy captive core cursors.
> update 2.28.0 changelog, captive core cursor removal notes

- historyarchive/archive.go
- services/horizon/internal/ingest/main.go
<details>
otherwise).
packages.
</details>
added more content to the history archive request metrics
there are sub-labels for the history archive metrics key, and the additional docs help describe what each label is counting.
> services/horizon/ingest: added more description to the history archive metrics labels

- services/horizon/internal/init.go
- services/horizon/internal/integration/bad_seq_txsub_test.go
- services/horizon/internal/ledger/main.go
- services/horizon/internal/txsub/helpers_test.go
- services/horizon/internal/txsub/system.go
- services/horizon/internal/txsub/system_test.go
<details>
otherwise).
packages.
</details>
Adds a check in the transaction submission workflow, where it returns the bad sequence error immediately if Horizon and Core sync up with each other.
During a particular edge-case, if core reports bad-seq error, and Horizon and Core are …
> Fix for transaction submission timeout

- ingest/ledger_transaction.go
- xdr/transaction_meta.go
<details>
otherwise).
packages.
</details>
Moving core logic of GetDiagnosticEvents from LedgerTransaction to TransactionMeta
In order to use GetDiagnosticEvents directly from TransactionMeta in soroban-rpc. This is mainly required for this feature --> …
> Refactor GetDiagnosticEvents so that it can be used directly from TransactionMeta

- services/horizon/docker/Makefile
do not append UNSTABLE to tag for horizon docker builds even if unstable core is used
they've decided they want to be able to bundle unstable captivecore with production horizon, so no point in appending UNSTABLE to the tag
https://buildmeister-v3.stellar-ops.com/job/Platform/job/stellar-horizon-docker-builder/149/
https://github.com/stellar/ops/issues/2812
> do not append UNSTABLE to tag for horizon docker builds

- .github/workflows/horizon.yml
- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/claimable_balances_test.go
<details>
otherwise).
packages.
</details>
Explicitly qualify columns with table name/alias in claimable balance db query.
Query before the fix:
SELECT cb.id, cb.claimants, cb.asset, cb.amount, cb.sponsor, cb.last_modified_ledger, cb.flags FROM claimable_balances cb JOIN …
> services/horizon: Fix claimable balance query

- services/horizon/internal/db2/history/claimable_balances.go
- services/horizon/internal/db2/history/claimable_balances_test.go
<details>
otherwise).
packages.
</details>
The request to `/claimable_balances?claimant=GDFZV7N7WXJCHL27IX4CI6TQY7ZDHLXMLVX5XHOV6CPCQVUCGDKKFPGQ` times out on staging (running horizon 2.28.2) but not on production (running horizon 2.28.0). The degradation in this endpoint is …
> services/horizon/internal/db2/history: Fix claimable_balance_claimants subquery in GetClaimableBalances()

- .github/workflows/horizon.yml
- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/claimable_balances_transaction_processor_test.go
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/ledgers_processor_test.go
- services/horizon/internal/ingest/processors/liquidity_pools_transaction_processor_test.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/operations_processor_test.go
- services/horizon/internal/ingest/processors/participants_processor_test.go
- services/horizon/internal/ingest/processors/trades_processor_test.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/ingest/processors/transactions_processor.go
- services/horizon/internal/ingest/processors/transactions_processor_test.go
- services/horizon/internal/ingest/verify_test.go
- services/horizon/internal/init.go
- services/horizon/internal/integration/invokehostfunction_test.go
- services/horizon/internal/integration/sac_test.go
- services/horizon/internal/integration/transaction_test.go
<details>
otherwise).
packages.
</details>
Added new `SKIP_TXMETA`. Defaults to `FALSE`. When `TRUE` the transaction model for classic or soroban tx's won't have tx meta populated anymore, on database, history_transactions.tx_meta column will have serialized xdr that equates to …
> /services/horizon/ingest: add SKIP_TXMETA

- clients/horizonclient/client.go
- clients/horizonclient/client_test.go
- clients/horizonclient/main.go
Add Headers field to the Client struct in order to allow passing custom HTTP headers with requests made by the SDK.
This change enables users of SDK to include custom headers, such as authorization headers, when making HTTP requests to Stellar API. Previously, there was no built-in mechanism to add custom headers, which limited the flexibility of the SDK in certain scenarios. By introducing the Headers field, users can now easily include any additional headers required for their specific use cases.
N/A
> clients/horizonclient: allow sending user-defined headers on requests

- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/transaction.go
- services/horizon/internal/db2/history/transaction_test.go
<details>
otherwise).
packages.
</details>
The transactions for account query is one the most common queries which appears in the slow query logs and in the Top SQL dashboard in the RDS performance insights page. 
```sql
SELECT
ht.id, ht.transaction_hash, ht.ledger_sequence, …
```
> services/horizon/internal/db2/history: Fix account transactions query

- services/horizon/internal/ingest/fsm.go
<details>
otherwise).
packages.
</details>
Fixes a typo from https://github.com/stellar/go/pull/5216 
We're incorrectly populating the loader ingestion metrics with the transaction ingestion processors. 
[N/A]
> services/horizon/internal/ingest: Fix ingestion loader duration metric

- services/horizon/internal/actions/effects.go
- services/horizon/internal/db2/history/effect.go
- services/horizon/internal/db2/history/effect_batch_insert_builder_test.go
- services/horizon/internal/db2/history/effect_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/transaction_test.go
<details>
otherwise).
packages.
</details>
The effects query below is one of the top 5 queries in the RDS performance insights dashboard:
```sql
SELECT heff.*, hacc.address FROM history_effects heff LEFT JOIN history_accounts hacc ON hacc.id = heff.history_account_id WHERE ( …
```
> services/horizon/internal/db2/history: Improve performance of effects query

- services/horizon/internal/db2/history/asset_loader.go
<details>
otherwise).
packages.
</details>
We spend up to 250ms querying rows from the `history_assets` table during ingestion despite the fact we look up only ~10 rows on average during every ingestion round. The reason for that is because the query we're doing uses a table …
> services/horizon/internal/db2/history: Improve asset loader query

- services/horizon/internal/app.go
- services/horizon/internal/config.go
- services/horizon/internal/db2/history/liquidity_pools.go
- services/horizon/internal/db2/history/liquidity_pools_test.go
- services/horizon/internal/db2/history/offers.go
- services/horizon/internal/flags.go
- services/horizon/internal/flags_test.go
- services/horizon/internal/httpx/middleware.go
- services/horizon/internal/httpx/router.go
- services/horizon/internal/init.go
- services/horizon/internal/middleware_test.go
- staticcheck.sh
- support/config/config_option.go
- support/config/config_option_test.go
- support/db/main.go
- support/db/mock_session.go
- support/db/session.go
- support/db/session_test.go
<details>
otherwise).
packages.
</details>
Add a `--cancel-db-query-timeout` flag which configures a timeout on all db queries invoked by a horizon HTTP request. This timeout is a postgres client side timeout which means that it is triggered by horizon establishing a new …
> support/db: Delay canceling queries from client side when there's a statement / transaction timeout configured in postgres

- services/horizon/internal/app.go
- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/httpx/router.go
<details>
otherwise).
packages.
</details>
Add limit on number of horizon requests in flight.
We observed a case where a staging horizon node received too many requests which caused it to OOM. See https://stellarfoundation.slack.com/archives/C02B04RMK/p1710326856362359?thread_ts=1 …
> services/horizon/internal: Add limit on number of horizon requests in flight

- services/horizon/internal/flags.go
<details>
otherwise).
packages.
</details>
We are using go-chi version 4.1 in horizon:
https://github.com/stellar/go/blob/release-horizon-v2.29.0/go.mod#L22
And, in that version, the request throttler middleware uses a response code of 503 when the number of in flight requests …
> services/horizon/internal: fix flag usage for max-concurrent-requests

- .github/workflows/go.yml
- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
- Run unit tests and integration tests with postgres versions 12 and 16
- Only run integration tests with protocol 20 (we no longer need to support protocol 19)
- Only run integration tests with captive core using buckets db since …
> .github/workflows: upgrade postgres version to 16

- .github/workflows/horizon.yml
- Makefile
- exp/services/ledgerexporter/Makefile
- exp/services/ledgerexporter/docker/Dockerfile
- exp/services/ledgerexporter/docker/start
<details>
otherwise).
packages.
</details>
- Created a Dockerfile to build the Ledger Exporter image. 
- Currently, there is no versioning scheme for the Ledge Exporter, so the Docker image is created with the `latest` tag. 
- Command line parameters such as `start`, `end`, and …
> exp/services/ledgerexporter: Implement Docker based deployment

- exp/tools/dump-ledger-state/Dockerfile
<details>
otherwise).
packages.
</details>
Bump Go version to 1.22 in dump-ledger-state Dockerfile.
The "dump-ledger-state" Docker build is [failing](https://github.com/stellar/go/actions/runs/8473259017/job/23217168499) due to an outdated version of Go (1.19). We've recently …
> exp/tools/dump-ledger-state: Bump go version to 1.22

- xdr/ledger_close_meta.go
This introduces a method `xdr.LedgerCloseMeta.LedgerCloseTime()` which extracts the close time from the structure.
It's annoying and error-prone to dig into the raw structure.
n/a
There are no tests but you can see that this is exactly how it's done, e.g. 
https://github.com/stellar/soroban-rpc/blob/638c62d8f58707ec5e079f68b4e6dbf96b94401b/cmd/soroban-rpc/internal/transactions/transactions.go#L119
> xdr: Add wrapper to fetch a ledger's close time

- .github/workflows/horizon.yml
- services/horizon/internal/integration/parameters_test.go
- services/horizon/internal/test/integration/integration.go
All tests use captive-core so there is no need to specify it explicitly.
Soroban-rpc is enabled on a test by test basis so there is no need to guard it through its own env variable.
> horizon: Clean up integration test variables

- services/regulated-assets-approval-server/docker/Dockerfile
<details>
otherwise).
packages.
</details>
Bump the Go version in Dockerfile that it was missed in #5249
The toolchain command in go.mod was requiring a Go version newer than the one in the Dockerfile, which was causing docker-build [to …
> services/regulated-assets-approval-server: bump the Go version in Dockerfile that it was missed in #5249

- support/datastore/gcs_datastore.go
<details>
otherwise).
packages.
</details>
Add CRC32C validation validation when uploading and downloading tx meta files.
<del>https://stellarorg.atlassian.net/browse/HUBBLE-271</del>
https://stellarorg.atlassian.net/browse/HUBBLE-278
From …
> support/datastore: Add CRC32C validation when exporting and consuming tx meta files

- exp/services/ledgerexporter/internal/app.go
- exp/services/ledgerexporter/internal/exportmanager.go
- exp/services/ledgerexporter/internal/exportmanager_test.go
<details>
otherwise).
packages.
</details>
Call PrepareRange() in exporter manager goroutine instead of during app initialization.
PrepareRange() can block up to 15 minutes because it will wait until the first ledger has been emitted over the captive core pipe. So if we call it …
> exp/services/ledgerexporter/internal: Call PrepareRange() in exporter manager goroutine

- exp/services/ledgerexporter/internal/config.go
- exp/services/ledgerexporter/internal/config_test.go
<details>
otherwise).
packages.
</details>
`adjustLedgerRange()` attempts to clamp the start and end ledger for a given ledger range so that they align on the ledgers per file boundary. However, there is a bug in the implementation because the end ledger should be aligned to the …
> exp/services/ledgerexporter/internal: Fix adjustLedgerRange()

- support/datastore/resumablemanager_test.go
- support/datastore/resumeablemanager.go
<details>
otherwise).
packages.
</details>
Adjacent ranges may end up overlapping due to the clamping behavior in [`adjustLedgerRange()`](https://github.com/stellar/go/blob/fff01229a5af77dee170a37bf0c71b2ce8bb8474/exp/services/ledgerexporter/internal/config.go#L173-L192)
For …
> support/datastore: Make resumability robust to unexpected overlaps in adjacent ranges

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update Changelog for the release.
N/A
N/A
> Update CHANGELOG for Horizon release 2.31.0

- exp/services/ledgerexporter/internal/app.go
- exp/services/ledgerexporter/internal/config.go
- exp/services/ledgerexporter/internal/config_test.go
- historyarchive/archive.go
- historyarchive/archive_pool.go
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/main.go
- ingest/ledgerbackend/mock_cmd_test.go
- ingest/ledgerbackend/stellar_core_runner.go
- services/horizon/internal/ingest/main.go
- support/datastore/history_archive.go
- support/db/session.go
Closes #5351 
Closes #5350 (including the removal of a nasty cast)
Addresses part of #5349 
Remove redundant code of `(*Session) Begin()`
> Misc fixes

- services/horizon/internal/ingest/fsm.go
<details>
otherwise).
packages.
</details>
Fix ingestion duration metric so it includes time spent reaping lookup tables.
`s.maybeVerifyState(ingestLedger, ledgerCloseMeta.BucketListHash())` and `s.maybeReapHistory(ingestLedger)` occur asynchronously in other goroutines so they …
> services/horizon/internal/ingest: Fix ingestion duration metric so it includes time spent reaping lookup tables

- services/horizon/internal/config.go
- services/horizon/internal/flags.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/resume_state_test.go
- services/horizon/internal/init.go
<details>
otherwise).
packages.
</details>
Add flag to enable / disable reaping of lookup tables.
Reaping of lookup tables is an operation which blocks the ingestion thread and it can be a lengthy operation. We need to have a mechanism to disable reaping of lookup tables while …
> services/horizon/internal: Add flag to enable / disable reaping of lookup tables

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
porting the 2.31.0 changelog notes back to master
include latest release notes in the ongoing changelog history
> Port 2.31.0 release notes to mainline

- .github/workflows/horizon.yml
- .github/workflows/ledgerexporter-release.yml
- .github/workflows/ledgerexporter.yml
- exp/services/ledgerexporter/Makefile
<details>
otherwise).
packages.
</details>
Two new git CI workflows for the ledger exporter:
1. PR Workflow: Runs whenever a pull request is merged to the master branch and does the following:
- Builds the ledger exporter docker image.
- Tests the image using a fake-gcs-storage …
> Create CI workflow for ledger exporter release

- ingest/ledgerbackend/buffered_storage_backend.go
- ingest/ledgerbackend/buffered_storage_backend_test.go
- ingest/ledgerbackend/ledger_buffer.go
- services/horizon/cmd/db.go
- services/horizon/config.storagebackend.toml
- services/horizon/internal/ingest/main.go
- support/datastore/datastore.go
- support/datastore/gcs_datastore.go
- support/datastore/gcs_test.go
- support/datastore/mocks.go
<details>
otherwise).
packages.
</details>
Reingest from precomputed TxMeta 
#4911
> services/horizon: Reingest from precomputed TxMeta

- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/internal/flags.go
- services/horizon/internal/flags_test.go
- services/horizon/internal/integration/parameters_test.go
<details>
otherwise).
packages.
</details>
- Skip captive-core configuration when reingesting from the datastore.
- Remove the AlwaysIngest option, as Ingest is always true by default.
- Refactor code to separate captive-core config from stellar network config, since network …
> services/horizon: Skip captive-core configuration when reingesting from datastore

- services/horizon/cmd/db.go
- services/horizon/cmd/db_test.go
<details>
otherwise).
packages.
</details>
Add unit test for new --ledgerbackend flag 
#4911 
N/A
> services/horizon: Add unit test for new --ledgerbackend flag

- .github/workflows/ledgerexporter-release.yml
<details>
otherwise).
packages.
</details>
Fix Ledgerexporter release workflow
Fixes Ledgerexporter release workflow
N/A
> exp/servies/ledgerexporter: Fix github release workflow

- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/reap_test.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/main_test.go
<details>
otherwise).
packages.
</details>
Add duration metrics for reaping of lookup tables where we can see how much time is spent reaping each table. See link below which displays the new metrics on staging:
https://grafana.stellar-ops.com/d/x8xDSQQIk/stellar-horizon?orgId=1&vi …
> services/horizon/internal/ingest: Add more fine-grained reap metrics

- support/db/dbtest/db.go
<details>
otherwise).
packages.
</details>
Recently, we've been seeing the following error in the test workflow `Received unexpected error: pq: duplicate key value violates unique constraint 'pg_authid_rolname_index'` in the RecoverySigner unit test. The first occurrence of this …
> Fix CI test workflow errors in RecoverySigner unit tests 

- services/friendbot/init_friendbot.go
- services/friendbot/internal/friendbot_test.go
- services/friendbot/internal/minion.go
- services/friendbot/internal/minion_test.go
- services/friendbot/main.go
Support funding existing accounts in Friendbot.
If an account does not exist, do as done today, create the account with the starting balance.
If an account exists, and balance is equal to or above the starting balance, error as the account is funded sufficiently.
If an account exists, and balance is below the starting balance, send a payment to the account of the starting balance.
The stellar-cli supports funding accounts and there's a request to support funding to top up existing accounts that have spent funds (https://github.com/stellar/stellar-cli/issues/1389).
There are reasons why this shouldn't be done. It's possible for someone to more easily exhaust the testnet native balance available. However, it is really already very easy to do that by simply passing random addresses. And …
> services/friendbot: support funding existing accounts

- services/horizon/internal/db2/history/key_value.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/main_test.go
- services/horizon/internal/db2/history/reap_test.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/main_test.go
<details>
otherwise).
packages.
</details>
Previously the sql queries to fined orphaned history lookup table rows looked like:
```sql
SELECT id
FROM   (SELECT id,
(SELECT 1
FROM   history_effects
WHERE  history_account_id = hcb.id
LIMIT  1) AS c0,
(SELECT 1
FROM …
```
> services/horizon/internal/db2/history: Optimize query for reaping lookup tables

- .github/workflows/galexie-release.yml
- services/galexie/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Merge galexie v1.0.0 release branch back to master
N/A
> services/galexie: merge galexie v1.0.0 release branch to master

- services/horizon/internal/test/integration/integration.go
<details>
otherwise).
packages.
</details>
Migrate to [Docker Compose v2](https://docs.docker.com/compose/migrate/), which requires changing the docker compose invocation from `docker-compose` to `docker compose`. 
The `exec.Command` in Go doesn’t support commands with spaces in …
> services/horizon: migrate to docker compose v2

- services/horizon/internal/actions/effects.go
- services/horizon/internal/actions/helpers.go
- services/horizon/internal/actions/helpers_test.go
- services/horizon/internal/actions/ledger.go
- services/horizon/internal/actions/operation.go
- services/horizon/internal/actions/operation_test.go
- services/horizon/internal/actions/trade.go
- services/horizon/internal/actions/transaction.go
- services/horizon/internal/actions/transaction_test.go
<details>
otherwise).
packages.
</details>
The following endpoints use a [TOID](https://github.com/stellar/go/blob/master/toid/main.go#L8) cursor value derived from the ledger sequence number:
/effects
/operations
/transactions
/ledgers
/trades
/payments
When a cursor is omitted …
> services/horizon/internal/actions: populate default cursor value for history endpoints

- .github/pull_request_template.md
<details>
otherwise).
packages.
</details>
per sprint retro feedback, we want to highlight keeping CHANGELOG's up to date in between releases by focusing on PR's updating it incrementally.
* Release process may not retro-actively capture all the PRs and accurate descriptions for …
> Update GH repo PR template checklist for CHANGELOG expectations

- services/galexie/docker/Dockerfile
- services/horizon/docker/Dockerfile.dev
<details>
otherwise).
packages.
</details>
Update Galexie's Docker to use `golang:1.22-bookworm` for building to match the `ubuntu:22.04` runtime. The same inconsistency was found in the Horizon dev Docker image, so updated that as well.
Addresses #5430
N/A
> Fix inconsistent debian version used in Dockerfile

- services/horizon/CONTRIBUTING.md
Remove CLA reference from contributing document.
The CLA was deprecated at some point and this reference remained.
> Remove CLA reference from contributing document

- protocols/horizon/main.go
- services/horizon/internal/httpx/static/txsub_async_oapi.yaml
<details>
otherwise).
packages.
</details>
Closes #5441 
This change makes it uniform with the snake-case naming in other endpoints.
NA
> Change `ErrorResultXDR` to `error_result_xdr` in `AsyncTransactionSubmissionResponse`

- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/file_watcher_test.go
- ingest/ledgerbackend/run_from.go
- ingest/ledgerbackend/stellar_core_runner.go
- ingest/ledgerbackend/stellar_core_runner_test.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/5417
This PR adds two prometheus metrics to captive core:
1. A counter which increments whenever we need to run captive core on a clean db instead of resuming from the LCL of the previous run
2. A summary which measures the amount of seconds it takes for captive core to emit …
> ingest/ledgerbackend: Add prometheus metrics to track captive core startup time

- .github/workflows/horizon.yml
> .github: Bump RPC reference to latest patch

- clients/horizonclient/internal.go
- services/horizon/internal/integration/txsub_async_test.go
<details>
otherwise).
packages.
</details>
Change the decoding method for non-2xx codes in `async-txsub` endpoint. Current code decodes all error responses to `horizon.Problem` object. This change adds a separate decoding method specific for the async-txsub endpoint responses.
For non-2xx codes, the `async-txsub` endpoint not only sends a `horizon.Problem` …
> Send an error response for Horizon.Problem

- support/db/dbtest/db.go
<details>
otherwise).
packages.
</details>
Fix a race condition in unit tests that causes  `pq: role 'user_ro' already exists` error.  The error happens when another transaction creates the role at the same time. Handle this by ignoring the error if the role already exists. This is similar to what was done in https://github.com/stellar/go/pull/5398 for fixing …
> fix CI failures due to race condition in recoverysigner unit tests

- services/horizon/docker/Dockerfile
- services/horizon/docker/Dockerfile.core-testing
- services/horizon/docker/Dockerfile.stable
- services/horizon/docker/Makefile
- a new Dockerfile to install Core from the "testing" pool an update to the Makefile specifically for this case
- a new Dockerfile to install Core and Horizon from their "stable" pools
- additional comments to clarify what the different files do
this is needed to support Horizon's new workflow
this has been tested successfully
https://github.com/stellar/ops/issues/3124
> updates to horizon docker builds

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Merging the 2.32.0 release branch back into the master branch
> Update changelog for 2.32.0 release (#5403)

- ingest/cdp/producer_test.go
<details>
otherwise).
packages.
</details>
fixed inconsistent test on producer caller context cancelled.
the test had inconsistent pass/fail results due to race conditions
> ingest/cdp: fixed producer test for caller ctx cancel to be consistent

- ingest/ledgerbackend/buffered_storage_backend_test.go
- ingest/ledgerbackend/ledger_buffer.go
- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/cmd/db_test.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/parallel.go
- services/horizon/internal/ingest/parallel_test.go
<details>
otherwise).
packages.
</details>
- Removed the `--parallel-job-size` config parameter. 
- buffer_size parameter is capped to the job/range size.
Fixes #5468 
This could potentially disrupt any automation scripts using `--parallel-job-size` parameter, although it's unlikely since reingestion is generally run as a batch job on as needed basis.
> services/horizon: Remove --parallel-job-size config parameter used for reingestion.

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update changelog for Horizon v22 release. See diff https://github.com/stellar/go/compare/horizon-v2.32.0...protocol-22?expand=1
> services/horizon: Update changelog for Horizon v22 release 

- protocols/horizon/main.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/actions/submit_transaction_async.go
- services/horizon/internal/actions/submit_transaction_async_test.go
- services/horizon/internal/httpx/static/txsub_async_oapi.yaml
- services/horizon/internal/integration/txsub_async_test.go
<details>
otherwise).
packages.
</details>
In https://github.com/stellar/go/pull/5445 , `errorResultXdr` was renamed to `error_result_xdr`. Although the v22 is a major release, we should provide a pathway for horizon clients to upgrade without incurring any downtime. So, will still include the field in the async txsub response and in the v23 release we can …
> protocols/horizon: Reinstate errorResultXdr with deprecation warning

- .github/workflows/galexie-release.yml
- .github/workflows/galexie.yml
- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Update core version to 22.0.0 stable release.
> Update core version to 22.0.0-2138.721fd0a65

- services/horizon/internal/httpx/router.go
<details>
otherwise).
packages.
</details>
Add missing `skip-txmeta` flag in the `/transactions/{tx-id}` endpoint.
`skip-txmeta` flag was implemented in https://github.com/stellar/go/pull/5228. However, the `/transactions/` endpoint was missed. As a result, the 22.0.0-rc2 horizon deployed on the testnet still includes `result_meta_xdr` in its response.
N/A
> services/horizon: Add missing skip-txmeta flag in the /transactions/ endpoint.

- support/http/httptest/client_expectation.go
- support/http/httptest/main.go
- utils/apiclient/client.go
- utils/apiclient/client_test.go
- utils/apiclient/main.go
- utils/apiclient/request.go
- utils/apiclient/request_test.go
<details>
otherwise).
packages.
</details>
This PR adds a general purpose API wrapper which could be used to call any API endpoint with given query params and headers.
There are two modules added:
- Client: Contains function to call an API. This supports retries in case there are throttling or service unavailable.
- Request: Contains function to build …
> Add General purpose API wrapper util

- exp/orderbook/pools.go
- exp/orderbook/pools_test.go
- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/5143
This commit fixes three inconsistencies with how liquidity pool payouts / expectations are calculated in core vs horizon:
1. When calculating how much we need to deposit into a pool in order to receive a desired payout we need to consider that the calculated deposit may …
> exp/orderbook: Fix bug in CalculatePoolExpectation()

- clients/stellarcore/client.go
- clients/stellarcore/client_test.go
See https://github.com/stellar/stellar-core/blob/0241e79f74dc017f20e190abd3825873222c5ca5/src/main/CommandHandler.cpp#L568 for alll the supported parameters.
> clients/stellarcore: Support more parameters from the upgrades endpoint

- .github/workflows/galexie-release.yml
- .github/workflows/galexie.yml
<details>
otherwise).
packages.
</details>
The github action which tests galexie functionality started failing:
https://github.com/stellar/go/actions/runs/12483719925/job/35064750830
Configuring the OS version to `ubuntu-22.04`, which is what we use in the Horizon github actions, instead of `latest` has fixed the test failures.
[N/A]
> .github: fix OS version for galexie CI

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Drop protocol 21 from the horizon integration test matrix. Pubnet is now on protocol 22 so it is no longer necessary to exercise protocol 21 in our integration tests.
[N/A]
> .github: Remove protocol 21 from horizon testing matrix

- ingest/ledgerbackend/configs/captive-core-pubnet.cfg
- services/galexie/internal/config_test.go
- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Replace Whalestack with Creit Technologies in default pubnet captive core config.
This will make the quorum set in the default captive core config match the tier 1 validator list:
https://stellarfoundation.slack.com/archives/C02U19A2A/p1735930631316469
[N/A]
> ingest/ledgerbackend/configs: Update default captive core config

- ingest/CHANGELOG.md
- ingest/ledgerbackend/buffered_storage_backend_test.go
- ingest/ledgerbackend/ledger_buffer.go
<details>
otherwise).
packages.
</details>
The fix updates the boundary check in bounded mode to ensure the `BufferedStorageBackend`/`LedgerBuffer` queues ledgers up to the end *boundary* ledger of the specified range. This fixes an issue where the final batch of ledgers is skipped in scenarios where multiple ledgers are stored per file and the `from` ledger …
> ingest/ledgerbackend: fix to ensure that the ledger buffer properly queues the last batch of ledgers (LCM) within the specified range

- services/horizon/CHANGELOG.md
- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/participants_processor.go
- services/horizon/internal/ingest/processors/participants_processor_test.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/integration/sac_test.go
<details>
otherwise).
packages.
</details>
Updates participant detection logic for the InvokeHostFunction operation type. When a smart contract is invoked, the accounts affected will be identified by iterating through the events. Additionally, the logic examines the list of changes resulting from the operation to ensure all affected accounts are detected.
All …
> services/horizon: Fix operations participants logic to include InvokeHostFunction operation

- historyarchive/history_archive_state.go
- historyarchive/history_archive_state_test.go
- historyarchive/testdata/historyV1.json
- historyarchive/testdata/historyV2.json
- ingest/checkpoint_change_reader.go
- ingest/checkpoint_change_reader_test.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/5425
In protocol 23 there will be two bucketlists: one for the live ledger entries and one for evicted archived ledger entries. Consequently the bucketlist hash in the ledger header will change to (see [CAP-62](https://github.com/stellar/stellar-protocol/blob/master/core/cap-00 …
> historyarchive: Update bucket list hash validation for protocol 23

- ingest/change_compactor.go
- ingest/change_compactor_test.go
- ingest/ledger_change_reader_test.go
- ingest/processors/ledger_processor/ledger.go
- xdr/ledger_close_meta.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/5614
This PR implements support for CAP-63 see https://github.com/stellar/go/issues/5614 for more details.
The failing tests are fixed in https://github.com/stellar/go/pull/5611 . Once https://github.com/stellar/go/pull/5611 is merged , I will rebase this PR and the tests …
> ingest: Add support for CAP-63

- clients/stellarcore/client_test.go
- ingest/processors/asset_processor/asset_test.go
- ingest/processors/operation_processor/operation_test.go
- ingest/processors/trade_processor/trade_test.go
- ingest/processors/transaction_processor/transaction_test.go
- protocols/stellarcore/getledgerentry_response.go
<details>
otherwise).
packages.
</details>
Update the API to reflect its latest schema and enhance testing by building real ledger keys and entries.
The API has been updated, see [Slack thread](https://stellarfoundation.slack.com/archives/C07ET021CA2/p1739921403806869?thread_ts=1739921155.418029&cid=C07ET021CA2) and [the …
> clients: Update Stellar Core client to latest state archival API

- services/horizon/internal/ingest/processors/asset_stats_processor.go
- services/horizon/internal/ingest/processors/asset_stats_processor_test.go
- services/horizon/internal/ingest/processors/contract_asset_stats.go
- services/horizon/internal/ingest/processors/contract_asset_stats_test.go
<details>
otherwise).
packages.
</details>
This PR is a follow up to https://github.com/stellar/go/pull/5611
In https://github.com/stellar/go/pull/5611 , I assumed that the structure of the restoration meta differed depending on whether the restoration was for an evicted ledger entry or a ledger entry which was archived but not yet evicted. But in the latest …
> services/horizon/internal/ingest/processors: Fix ingestContractAssetBalance() restore case

- ingest/change.go
- ingest/ledger_change_reader.go
- ingest/ledger_change_reader_test.go
- ingest/ledger_transaction.go
- ingest/stats_change_processor.go
- ingest/stats_change_processor_test.go
- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/ingest/processors/asset_stats_processor.go
- services/horizon/internal/ingest/processors/asset_stats_processor_test.go
- services/horizon/internal/ingest/processors/contract_asset_stats.go
- services/horizon/internal/ingest/processors/contract_asset_stats_test.go
- services/horizon/internal/ingest/processors/contract_data.go
- services/horizon/internal/ingest/verify.go
- services/horizon/internal/ingest/verify_test.go
- services/horizon/internal/integration/change_test.go
- xdr/ledger_close_meta.go
<details>
otherwise).
packages.
</details>
[CAP-62](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0062.md#meta) and [CAP-66](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0066.md#xdr-changes) updates the LedgerCloseMeta xdr to no longer populate  the  `evictedPersistentLedgerEntries` field. Instead, both persistent and …
> ingest: Update ingestion library and horizon to adapt to protocol 23 representation of evictions

- ingest/processors/token_transfer/verify_events.go
<details>
otherwise).
packages.
</details>
[TODO: Short statement about what is changing.]
[TODO or N/A]
> Add ledgerSeq to error

- ingest/ledgerbackend/configs/captive-core-pubnet.cfg
- services/galexie/internal/config_test.go
- services/horizon/docker/stellar-core-pubnet.cfg
<details>
otherwise).
packages.
</details>
removed deprecated validator addresses from some hardcoded captive config quorum sets
better performance for captive core, avoid broken connection attempts to invalid qset addresses.
> remove deprecated lobstr validator addresses from captive quorum sets

- ingest/ledger_transaction.go
- ingest/ledger_transaction_test.go
- ingest/processors/token_transfer/token_transfer_processor.go
- ingest/processors/token_transfer/token_transfer_processor_test.go
- ingest/processors/token_transfer/verify_events.go
Add support for fee refund events.
The comments in the `NewEventsFromLedger` function highlight the chronological order before P22 (i.e. the status quo)
I had to modify the signature of `NewEventsFromTransaction` to return FeeEvents and OperationEvents separately.
The coalescing is done in chronological order in `NewEventsFromLedger`
> Fee Event breakdown in token transfer processor

- .github/workflows/galexie-release.yml
- .github/workflows/galexie.yml
<details>
otherwise).
packages.
</details>
Bump stellar-core to 23.0.0-rc1 in preparation for Galexie release.
We want to do an P23 RC release for Galexie so the data team can start backfilling
N/A
> Bump stellar-core to 23.0.0.rc1 for galexie

- services/galexie/Makefile
<details>
otherwise).
packages.
</details>
Skip publishing docker image with latest tag for RC builds
https://github.com/stellar/go/issues/5703
depends on the presence of "-rc" in the github tag/version.
> Galexie: Skip publishing docker image with latest tag for RC builds

- clients/stellarcore/client_test.go
- protocols/stellarcore/getledgerentry_response.go
Update field names:
* `state` is always present
* `new` -> `not-found`
* `ttl` -> `liveUntilLedgerSeq`
* `e` -> `entry`, only present if `state == live|archived`
This matches the changes in https://github.com/stellar/stellar-core/pull/4721, cc @SirTyson.
> protocols: Update Stellar Core's `getledgerentry` endpoint schema

- .github/workflows/horizon.yml
- clients/stellarcore/client.go
- clients/stellarcore/client_test.go
- ingest/ledgerbackend/testdata/expected-disable-backfill-restore-meta.cfg
- ingest/ledgerbackend/testdata/expected-enable-backfill-restore-meta.cfg
- ingest/ledgerbackend/toml.go
- ingest/ledgerbackend/toml_test.go
- services/horizon/internal/test/integration/integration.go
<details>
otherwise).
packages.
</details>
Update CI to use the new core v23 release candidate binary when running protocol 22 integration tests. I discovered some a difference in behavior in the `get-settings-upgrade-txs` stellar-core command which resulted in integration tests failing. To work around that, I'm using the v22 core binary to invoke …
> Update core binary to v23 rc

- .github/workflows/golangci-lint.yml
- .golangci.yml
- go.mod
- ingest/ledgerbackend/rpc_backend.go
- ingest/ledgerbackend/rpc_backend_test.go
<details>
otherwise).
packages.
</details>
Added new error code checking on GetLedgers response from RPC.
RPC may emit a jrpc2 Error from GetLedgers when a request exceeds internal duration limits configured in rpc, if this type of error does occur, the rpc ledger backend as client should retry, it's not a fatal error.
> ingest/ledgerbackend: fix rpc ledger backend retries

- services/horizon/internal/integration/sac_test.go
<details>
otherwise).
packages.
</details>
Follow up to https://github.com/stellar/go/pull/5722 which adds more eviction integration tests that exercise the case where the SAC itself is evicted.
https://github.com/stellar/go/issues/5613
N/A
> services/horizon/internal/integration: Add more eviction integration tests

- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/ingest_test.go
- services/horizon/cmd/root.go
<details>
otherwise).
packages.
</details>
added `--ledgerbackend` and `--datastore-config` options to `ingest verify-range` command
working example invocation:
```
./horizon ingest verify-range --from 57609343 --to 57609353 \
--ledgerbackend datastore \
--datastore-config <my gcs datastore config file for pubnet> \
--db-url <my empty horizon db url> \ …
```
> services/horizon/cmd:  add datastore config option to ingest verify-range cmd

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update horizon changelog for the next protocol 23 release to reflect that the  `destination_muxed_id_type` field was removed (see https://github.com/stellar/go/pull/5739)
[N/A]
> services/horizon: Update changelog for protocol 23 release

- .github/workflows/horizon.yml
- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/cmd/ingest_test.go
- services/horizon/docker/verify-range/README.md
- services/horizon/docker/verify-range/start
<details>
otherwise).
packages.
</details>
* Updated the verify-range image to use optional GCS Datastore settings if present from environment to use instead of captive core for accessing ledgers. Refer to [README.md](https://github.com/stellar/go/pull/5736/files#diff-689188d34f82a03e4e61112951c05f1870b2373356c1ea4e9da5e1a608423f03R29)
* Refactored the …
> services/horizon/docker: cdp enabled verify range image

- services/horizon/internal/integration/sac_test.go
Tests for the presence of effects in a robust manner.
Their order isn't guaranteed.
Why hasn't this come up before?
> services/horizon: Add robustness to checks for the existence of an effect

- services/horizon/docker/verify-range/start
<details>
otherwise).
packages.
</details>
Delete files from the data directory in verify-range container at exit time after processing has finished.
the data files can be significant GB's in size and when the container is running in a cloud batch environment
the data path is mounted to external cloud storage and do not want these files left around after the …
> services/horizon/docker: purge files after verify-range container finishes

- services/horizon/docker/verify-range/start
<details>
otherwise).
packages.
</details>
remove file attribute reset during verify-range image's data file purge routine
the pre-emptive fle attribute reset with `chattr` is not necessary, once pg is stopped the working data files path is ready for deletion. additionally, the file attrib reset wasn't compatible if the images /data path is mounted to an efs …
> services/horizon/docker: adjust verify range data file purge

- services/galexie/internal/config.go
<details>
otherwise).
packages.
</details>
Set the stellar-core binary path in the params when generating the captive-core config for Galexie.
This [PR](https://github.com/stellar/go/pull/5759) added recently, [sets several flags](https://github.com/stellar/go/pull/5759/files#diff-c7702ef819e52917ed3868588dff5273774c61a6aa8d36c1644d7ba251fb7756R608-R639) based …
> services/galexie: Fix missing stellar-core binary path

- support/datastore/datastore.go
- support/datastore/gcs_datastore.go
- support/datastore/gcs_test.go
- support/datastore/mocks.go
- support/datastore/s3_datastore.go
- support/datastore/s3_datastore_test.go
<details>
otherwise).
packages.
</details>
Implement functionality in datastore for listing objects in the datastore.
This functionality is required for https://github.com/stellar/go/issues/5762 and https://github.com/stellar/go/issues/5774
[N/A]
> support/datastore: Add list files functionality to datastore

- ingest/cdp/producer_test.go
- services/galexie/internal/app_test.go
- support/datastore/configure.go
- support/datastore/configure_test.go
<details>
otherwise).
packages.
</details>
Use default limit when listing files for determining extension to use in the ledger data lake.
2 is chosen because it assumes the data lake will contain only 1 file  (`.config.json`) apart from the ledgers. If that assumption breaks (for example if the data lake contains another file besides `.config.json` which is not …
> support/datastore: Use default limit when listing files for determining extension

- support/datastore/gcs.go
- support/datastore/s3.go
<details>
otherwise).
packages.
</details>
Change log level to debug in DataStore implementations.
It's unexpected for a library to be producing info and error level logs. For example, when using a BufferedStorageBackend to fetch ledgers on an unbounded range, there will be a point where we have caught up to the latest ledger and the request to get the next …
> support/datastore: Use debug logging in DataStore implementations

- services/horizon/cmd/db.go
- services/horizon/cmd/ingest.go
- services/horizon/internal/httpx/router.go
<details>
otherwise).
packages.
</details>
Run a metrics server which can provide prometheus metrics while running long running ingest commands.
This is particularly useful for the recently introduced load-test command because we want to observe ingestion performance in grafana and compare it to our regular baseline. Without running a metrics server, we would …
> services/horizon/cmd: Run metrics server when invoking horizon ingest commands
