- clients/federation/client.go
- clients/federation/client_test.go
- clients/federation/main.go
- clients/horizon/main.go
- clients/stellartoml/client.go
- Fixes a leaked connection in stellartoml client
- Adds HomeDomainForAccount to horizon client
This code is a port from the bridge server.
> Add federation client package, with supporting changes:

- clients/stellartoml/client.go
- clients/stellartoml/client_test.go
The location of `stellar.toml` files [changed](https://github.com/stellar/docs/commit/ce9ffd37811c9205de9488727939c9dcb1f0d76c) to root domain.
> New stellar.toml location

- clients/horizon/main_test.go
- clients/horizon/responses.go
Close https://github.com/stellar/go/issues/35
> Update horizon account response

- clients/horizon/error.go
- clients/horizon/internal.go
- clients/horizon/main_test.go
Close https://github.com/stellar/go/issues/54
> Add more information to horizon.Error message

- xdr/price.go
- xdr/price_test.go
Close https://github.com/stellar/go/issues/57
> Price.Invert

- services/horizon/ingest/session.go
pulled this commit into the `stellar/go` repo after porting the `stellar/horizon` repo into `stellar/go/services/horizon`
> Horizon merge commits: ingestion fix

- clients/horizon/client.go
- clients/horizon/main.go
- clients/horizon/main_test.go
- clients/horizon/mocks.go
- services/horizon/actions_order_book.go
- services/horizon/actions_order_book_test.go
- services/horizon/db2/core/order_book_summary.go
- services/horizon/db2/core/order_book_summary_test.go
- services/horizon/docs/reference/endpoints/orderbook-details.md
- services/horizon/resource/root.go
closes https://github.com/stellar/horizon/issues/399
> added limit param for order_book with json default of 20

- services/horizon/internal/simplepath/search.go
closes https://github.com/stellar/horizon/issues/409
> updated pathfinding limit to 20

- .travis.yml
Note: this may not work because I cannot easily test changes to our travis config.  It may require some further tweaking.
> Add github release for nighly builds

- protocols/compliance/main.go
As explained in [SEP-0003](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0003.md).
> Add errors to compliance.AuthResponse

- address/main_test.go
- clients/federation/client_test.go
- tools/stellar-archivist/internal/dirprefix_test.go
> 32 assert.equal change

- services/horizon/internal/actions_trade.go
- services/horizon/internal/actions_trade_test.go
- services/horizon/internal/test/http.go
> Fix paging links format in trade aggregation.

- services/horizon/internal/actions_trade_test.go
- services/horizon/internal/db2/history/trade_aggregation.go
- services/horizon/internal/test/trades/main.go
> fix trade aggregation ordering

- services/horizon/internal/docs/reference/resources/trade.md
- services/horizon/internal/docs/reference/resources/trade_aggregation.md
> trade doc fixup

- services/horizon/internal/docs/reference/tutorials/follow-received-payments.md
Close https://github.com/stellar/horizon/issues/418
> Fix "Follow received payments" examples

- services/friendbot/README.md
allows build artifacts to complete
> friendbot readme file

- services/friendbot/CHANGELOG.md
forgot this file, should be good now.
> friendbot changelog to unblock build artifacts

- services/horizon/internal/docs/reference/resources/path.md
Just fixing this little typo.
Thanks!
> fixing minor typo in paths reference.

- services/bifrost/README.md
- services/bifrost/bifrost.cfg
- services/bifrost/config/main.go
- services/bifrost/main.go
- services/bifrost/stellar/account_configurator.go
- services/bifrost/stellar/main.go
- services/bifrost/stellar/transactions.go
In our project, we need to customise initial stellar balance on the account. Here's an implementation.
> Adds Stellar.StartingBalance config field

- services/horizon/internal/db2/history/effect.go
Query in `EffectsQ.Page` method was performing a full-table scan to get results. Analyzing `EXPLAIN ANALYZE` output it seems that planner wasn't able to figure out which index to use to speed up the query. I rewrote the query to the equivalent query but that makes use of the index.
Close #314.
---
Old query:
```
horizon=> EXPLAIN ANALYZE SELECT heff.*, hacc.address FROM history_effects heff LEFT JOIN history_accounts hacc ON hacc.id = heff.history_account_id WHERE (
horizon(>            heff.history_operation_id > '69950027815981057'                                                           
horizon(>   OR (                                                                                              
horizon(>                           heff.history_operation_id = '69950027815981057' …
```
> Fix slow effects page query

- services/horizon/internal/actions/helpers.go
- services/horizon/internal/actions/helpers_test.go
> Fix panic triggered in `GetAsset`

- services/horizon/internal/actions_trade.go
- services/horizon/internal/actions_trade_test.go
- services/horizon/internal/db2/history/trade_aggregation.go
to: 1 minute, 15 minutes, 1 hour, 1 day, 1 week
> restrict trade aggregations resolution

- services/horizon/internal/ingest/ledger_bundle.go
> Improve error message when a ledger gap is encountered by ingestion

- services/friendbot/internal/friendbot.go
I've tested this locally and it refreshes the friendbot sequence number correctly now. One of the issues we had was that it was not correctly checking for the tx_bad_seq, which is fixed.
On another note, I’m seeing a lot of 504 gateway timeouts (error decoding horizon.Problem: EOF) and "400 Bad Request" as responses from horizon when I’m testing locally. I don't think this can be fixed since we naturally want to push multiple txns per ledger with friendbot and cannot preempt these responses (at least not in a way that I'm currently aware). We are seeing this now as opposed to earlier because this is the first time friendbot is hitting the horizon server directly as opposed to going through the txSub sub-system.
@nullstyle
> fix friendbot sequence number issues

- services/horizon/internal/actions_ledger_test.go
- services/horizon/internal/db2/history/ledger.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/session.go
- services/horizon/internal/ingest/session_test.go
- services/horizon/internal/resource/effects/main.go
- support/scripts/build_release_artifacts/main.go
This PR contains a couple of fixes blocking release of v0.12.0.  See the commit messages for details
> Pre V0.12.0 fixes

- amount/main.go
- amount/main_test.go
Hi folks,
I'm working on a new stellar project and have need to convert human friendly amount strings into a `int64`. I found the `amount` package, but the existing `Parse` function returns a xdr int64. I thought that it would be a useful addition to this package's interface that there should be a function that parses to Go's native int64 type. This would also complement the existing `StringFromInt64(int64)`.
I decided to contribute this change, if you think this sounds reasonable. This PR introduces a new function `ParseInt64` to the amount package. The purpose of this function is to parse a human friendly amount string to its `int64` representation.
In addition, a few minor performance and idiomatic tweaks:
* Extracts out the static big.Rat(One) into a package constant
* Uses the …
> Add ParseInt64 function to amount pkg

- services/horizon/internal/actions_effects.go
- services/horizon/internal/actions_effects_test.go
- services/horizon/internal/resource/effects/base.go
- services/horizon/internal/resource/effects/main.go
- services/horizon/internal/resource/main.go
> Add `created_at` property to effect resources

- Gemfile.lock
- Rakefile
- meta/bundle.go
- services/horizon/internal/codes/main.go
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-ledger.x
- xdr/Stellar-overlay.x
- xdr/Stellar-transaction.x
- xdr/Stellar-types.x
- xdr/signer_key.go
- xdr/xdr_generated.go
First step towards #370: 
update xdr definitions to protocol version 10.0.0
fix signer key to match xdr naming changes
modify bundle to work with new xdr `TransactionMetaV1`
> update xdr definitions

- clients/horizon/client.go
- clients/horizon/main.go
- clients/horizon/mocks.go
- clients/horizon/responses.go
Support /trades_aggregations endpoint in go SDK
1. Added func LoadTradeAggregations() in client.go
2. Added func interface in main.go
3. Added 2 types: TradeAggregations and TradeAggregation
4. TODO add mock testing code
5. TODO support time range (start/end time) which is not yet a proper type in the client SDK
Go SDK doc
https://www.stellar.org/developers/go/reference/index.html
Js SDK doc
https://www.stellar.org/developers/js-stellar-sdk/reference/index.html
Rest API doc
https://www.stellar.org/developers/horizon/reference/endpoints/trade_aggregations.html
Example endpoint:
https://horizon-testnet.stellar.org/trade_aggregations?base_asset_type=credit_alphanum4&base_asset_code=CMA&base_asset_issuer=GD6OHWXPO7T46SEL2SNAFKGHLQZQ467U6MMDFKZ6BR3UXCINQ4BP3IZA&counter_asset_type=native&resolut …
> Add trade_aggregations endpoint in Go client

- services/horizon/internal/docs/reference/admin.md
Sorry, this one was caught after the LGTM :(
> Missed a typo

- services/bifrost/README.md
Bifrost v0.0.2 does this automatically.
> Remove manual migrations instructions

- services/horizon/internal/ingest/session.go
> Fix error wrapping in ingest.Session

- services/horizon/internal/docs/reference/endpoints/transactions-for-account.md
Removed duplicate `### JavaScript Example Request`
Trivial change, but someone had to do it :smile:
> Duplicate in transactions for account

- services/horizon/internal/docs/reference/endpoints/trades-for-account.md
- services/horizon/internal/docs/reference/resources/trade.md
> Add documentation for trades for account endpoint

- services/horizon/internal/actions_offer_test.go
- services/horizon/internal/docs/reference/endpoints/offers-for-account.md
- services/horizon/internal/docs/reference/resources/offer.md
- services/horizon/internal/resource/main.go
- services/horizon/internal/resource/offer.go
- support/time/main.go
> add last_modified timestamp to offer resource

- services/horizon/internal/actions_payment_test.go
- services/horizon/internal/resource/operations/main.go
> add source_amount to path_payment operation details resource

- README.md
- glide.lock
- glide.yaml
- protocols/compliance/auth_request_test.go
custom validations were merged in https://github.com/asaskevich/govalidator/pull/165
> update go validator to upstream

- services/horizon/internal/actions_trade_test.go
- services/horizon/internal/db2/history/trade.go
add trades for account paging tests
closes #486
> fix trades account filter

- protocols/horizon/operations/main.go
- services/horizon/internal/resourceadapter/operations.go
extract operation type name mapping from services/horizon to protocols/horizon
> extract operation type name mapping to protocols/horizon

- clients/horizon/main_test.go
**Motivation:** As part of the initiative to update tests to our current testing standard and in preparation for the push to update our Go SDK, I have directly translated these tests from `ginko/gomega` --> `testify`.
> Update client - main_test to current test standard

- support/scripts/build_release_artifacts/main.go
Fix for https://travis-ci.org/stellar/go/jobs/393728917#L1243
> Ignore internal package in build_release_artifacts

- clients/horizon/main_test.go
- clients/horizon/responses.go
- protocols/horizon/main.go
use resources from protocols/horizon in clients/horizon using type aliases
> use resources from protocols/horizon in clients/horizon

- clients/horizon/client.go
- clients/horizon/main_test.go
- protocols/horizon/README.md
Closely resembles the load operation method (although this one actually includes a test).
> Add LoadTransactions (/transactions/) to Horizon Client

- services/horizon/internal/docs/reference/endpoints/transactions-create.md
- services/horizon/internal/docs/reference/errors/timeout.md
Currently there is no documentation about `Timeout` errors.
Close #305.
> Add information about timeouts in POST /transactions

- services/horizon/CHANGELOG.md
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/session.go
- services/horizon/internal/ingest/session_test.go
Also adds a couple simple smoke tests for payment effects
> Adds credit/debit effects for path payments

- support/db/update_builder.go
Stumbled upon these likely copypasted identical comments today :)
> Fix copy-pasted comments

- services/horizon/internal/docs/reference/resources/account.md
- services/horizon/internal/docs/reference/resources/asset.md
- services/horizon/internal/docs/reference/resources/offer.md
- services/horizon/internal/docs/reference/resources/orderbook.md
- services/horizon/internal/docs/reference/resources/path.md
- services/horizon/internal/docs/reference/resources/trade.md
- services/horizon/internal/docs/reference/resources/trade_aggregation.md
Closes #537 
I looked at all resources in the horizon docs and documented the object fields, detailing the different properties of each.
> Document sub resources

- clients/horizon/client.go
- clients/horizon/main_test.go
> Fix LoadAccountMerge so that it returns horizon errors #529

- services/horizon/internal/docs/reference/endpoints/trades-for-offer.md
> Trades for Offer

- services/horizon/internal/docs/reference/resources/operation.md
> Add bump sequence op to operation doc

- protocols/horizon/main.go
- services/horizon/internal/actions_account.go
- services/horizon/internal/actions_path.go
- services/horizon/internal/db2/core/account.go
- services/horizon/internal/db2/core/main.go
- services/horizon/internal/db2/core/trustline.go
- services/horizon/internal/ingest/asset_stat.go
- services/horizon/internal/resourceadapter/account.go
- services/horizon/internal/resourceadapter/balance.go
- xdr/Stellar-ledger-entries.x
- xdr/xdr_generated.go
Adds offer liabilities to Account and Trustline objects. More info: https://github.com/stellar/stellar-core/pull/1718
~This is a **breaking change**, release with other Protocol V10 updates.~ No longer a breaking change after https://github.com/stellar/go/pull/531/commits/c60f8886739d3a79ff0afb227b035177b5aaae14.
TODO:
> Add offer liabilities

- glide.lock
- services/horizon/internal/codes/main.go
- xdr/Stellar-transaction.x
- xdr/Stellar-types.x
- xdr/xdr_generated.go
XDR as of https://github.com/stellar/stellar-core/commit/4dab9625d42b252d3f11500151ffcc66a1cd5ad2.
This PR also updates `gopkg.in/fatih/set.v0` to use GitHub repo directly as it was apparently [archived](https://github.com/fatih/set#archived-project-no-maintenance).
> Update XDR and result codes

- protocols/horizon/README.md
Human readable: https://github.com/stellar/go/blob/c35a827b74f975f09a973b139cdc250069a5dc9c/protocols/horizon/README.md I wanted tables to be aligned, from this version we will add a new tables in the top so the diffs will be much cleaner.
> Update Horizon v0.14.0 protocol changes doc

- services/horizon/internal/docs/reference/endpoints/offers-for-account.md
> Note about 200 response for offers for account

- Dockerfile
> godep instead of glide for docker build

- CHANGELOG.md
- services/horizon/internal/actions_trade.go
- services/horizon/internal/docs/reference/endpoints/trades-for-account.md
- services/horizon/internal/docs/reference/endpoints/trades-for-offer.md
- services/horizon/internal/docs/reference/endpoints/trades.md
- services/horizon/internal/docs/reference/endpoints/transactions-for-account.md
- services/horizon/internal/docs/reference/streaming.md
- closes #546 
- Add a streaming endpoint to trades
> Add SSE to TradeIndexAction

- support/render/hal/link_builder_test.go
> Remove goconvey from hal/link_builder_test.go

- services/horizon/internal/render/main_test.go
> Remove GoConvey dependency in render/main_test.go

- services/horizon/internal/httpx/client_test.go
> Refactor goconvey tests

- services/horizon/internal/render/problem/main_test.go
> Refactor to remove goconvey from internal/render/problem

- services/horizon/internal/txsub/sequence/queue_test.go
- services/horizon/internal/txsub/submitter_test.go
- Addresses #638 
- Convert tests from sequence package.
> Remove goconvey txsub queue

- services/horizon/internal/txsub/sequence/manager_test.go
- services/horizon/internal/txsub/submitter_test.go
- Addresses #638 to remove goconvey from manager_test.go
> Remove go convey txsub manager

- services/horizon/internal/txsub/open_submission_list_test.go
- services/horizon/internal/txsub/submitter_test.go
> Remove goconvey from txsub/open_submission_list

- services/horizon/internal/render/sse/stream.go
- Add a mutex to Stream struct in order to make its methods safe to call concurrently.
- This is needed in order to implement a go routine that sends SSE heartbeats which will be implemented in a later PR.
> Add mutex to stream

- services/horizon/internal/codes/main_test.go
- Addresses #638 to remove GoConvey from internal/codes/main_test
> Remove goconvey from internal/codes/main_test

- xdr/asset.go
- xdr/asset_test.go
> Fix Asset.SetCredit

- services/horizon/internal/middleware_rate_limit_test.go
- Addresses #638 to remove go convey dependency
>  Remove goconvey from middleware rate limit

- CHANGELOG.md
- services/horizon/internal/docs/reference/endpoints/trade_aggregations.md
- resolves #702 
- Add offset to the change log
- Provide documentation of this new parameter to trade_aggregations.md
> Add documentation for trade aggregation offset

- services/horizon/internal/config.go
- services/horizon/main.go
> Allow sending logs to file

- protocols/horizon/main.go
- services/horizon/internal/db2/core/account.go
- services/horizon/internal/resourceadapter/account_flags.go
- services/horizon/internal/resourceadapter/asset_stat.go
> add AUTH_IMMUTABLE flag to account resource

- services/horizon/internal/docs/reference/responses.md
- `indent`
- `give` > `given`
++ :heart_decoration: ;
> minute update to responses.md

- services/horizon/internal/db2/schema/bindata.go
- services/horizon/internal/db2/schema/migrations/14_fix_asset_toml_field.sql
- services/horizon/internal/ingest/asset_stat.go
- services/horizon/internal/test/scenarios/bindata.go
> Fix init-asset-stats command

- services/horizon/internal/docs/reference/admin.md
Added instructions on how to ingest historical data from stellar-core into horizon.
> Horizon Documentation

- support/scripts/run_tests
Fixed run_tests script to run tests only once.
> Fix run_tests

- .travis.yml
- build/transaction_envelope_test.go
- clients/horizon/responses.go
- govet.sh
- handlers/compliance/callback_strategy.go
- services/bifrost/stellar/account_configurator.go
- services/bifrost/stellar/transactions.go
- services/bifrost/stress/users.go
- services/bridge/internal/config/main.go
- services/bridge/internal/handlers/request_handler_authorize.go
- services/bridge/internal/handlers/request_handler_builder.go
- services/bridge/internal/handlers/request_handler_payment.go
- services/bridge/internal/listener/payment_listener.go
- services/bridge/internal/submitter/transaction_submitter.go
- services/compliance/internal/handlers/request_handler_auth.go
- services/compliance/internal/handlers/request_handler_send.go
- services/horizon/db.go
- services/horizon/internal/actions_effects.go
- services/horizon/internal/actions_offer.go
- services/horizon/internal/actions_operation.go
- services/horizon/internal/actions_payment.go
- services/horizon/internal/db2/page_query_test.go
- services/horizon/internal/init_redis.go
- support/db/insert_builder_test.go
- support/render/problem/main.go
- tools/stellar-archivist/internal/mirror.go
- tools/stellar-sign/main.go
Use [`go vet`](https://golang.org/cmd/vet/) in Travis to find potential issues with the code.
> Use go vet in CI

- Gopkg.lock
- services/horizon/internal/docs/developing.md
- services/horizon/internal/docs/reference/admin.md
When setting up Horizon on my local dev box, I ran into some issues which were missing from the docs. I eventually got to a working set of Horizon unit tests, but it's certainly possible that I did some extra steps that weren't necessary. I've noted places where this may be the case. Any review comments appreciated, especially by someone else new using these instructions to reproduce the same workflow.
> Doc: flesh out docs for developers

- .travis.yml
- support/db/dbtest/postgres.go
I will be updating the sql files after merging this one, and my local postgres version is 10.4. I wanted to make sure I don't break things.
> Bump postgres version for Travis

- README.md
This makes it easier to understand and navigate the monorepo.
> Add package index to README

- services/horizon/internal/actions/base.go
- services/horizon/internal/actions/responders.go
- services/horizon/internal/actions_account.go
- services/horizon/internal/actions_order_book.go
> horizon/actions: check hash before sending an event to the stream of orderbook

- services/horizon/CHANGELOG.md
> Update Horizon 0.16.0 CHANGELOG with db migration notes

- services/horizon/CHANGELOG.md
This PR adds a section for horizon `v0.16.1`
Close #887
> horizon: update changelog

- services/horizon/internal/docs/reference/streaming.md
> horizon/doc: add account streaming to the api doc

- services/horizon/CHANGELOG.md
- services/horizon/internal/docs/reference/endpoints/operation-fee-stats.md
- services/horizon/internal/docs/reference/endpoints/operations-all.md
- services/horizon/internal/docs/reference/endpoints/operations-for-account.md
- services/horizon/internal/docs/reference/endpoints/operations-for-ledger.md
- services/horizon/internal/docs/reference/endpoints/operations-for-transaction.md
- services/horizon/internal/docs/reference/endpoints/operations-single.md
- services/horizon/internal/docs/reference/endpoints/transactions-all.md
- services/horizon/internal/docs/reference/endpoints/transactions-for-account.md
- services/horizon/internal/docs/reference/endpoints/transactions-for-ledger.md
- services/horizon/internal/docs/reference/endpoints/transactions-single.md
- services/horizon/internal/docs/reference/rate-limiting.md
- services/horizon/internal/docs/reference/resources/account.md
- services/horizon/internal/docs/reference/resources/ledger.md
- services/horizon/internal/docs/reference/resources/operation.md
- services/horizon/internal/docs/reference/resources/transaction.md
Close #536.
Close #890.
Close stellar/docs#434.
> horizon: Update docs with Horizon 0.17.0 changes

- protocols/horizon/main.go
- services/bifrost/stellar/account_configurator.go
- services/horizon/internal/actions_ledger_test.go
- services/horizon/internal/actions_root_test.go
- services/horizon/internal/resourceadapter/ledger.go
- services/horizon/internal/resourceadapter/root.go
- services/horizon/internal/resourceadapter/signer.go
Do not merge before Horizon 0.17.0 tests are finished and it's ready for a release.
Close #905.
> Remove fields scheduled for removal in Horizon 0.17.0

- exp/clients/horizon/client.go
- exp/clients/horizon/main.go
- exp/clients/horizon/main_test.go
- exp/clients/horizon/metrics_request.go
- exp/clients/horizon/mocks.go
- exp/clients/horizon/responses.go
This adds support to SDK for getting metrics from the horizon server
> exp/clients/horizon: metrics endpoint

- services/horizon/cmd/db.go
> horizon/cmd: make `db migration` print messages on success

- services/horizon/internal/docs/reference/endpoints/accounts-single.md
- services/horizon/internal/docs/reference/endpoints/offers-for-account.md
> Add last_modified_ledger to Accounts and Account Offers.

- services/horizon/internal/docs/admin.md
> Add notes on reingesting ledgers to Horizon Admin Guide.

- exp/clients/horizon/client.go
- exp/clients/horizon/internal.go
- exp/clients/horizon/main.go
- exp/clients/horizon/mocks.go
- exp/clients/horizon/paths_request.go
- exp/clients/horizon/paths_request_test.go
- protocols/horizon/main.go
This PR adds support for path finding. 
Closes #1021 
Closes #168
> exp/clients/horizon: path finding

- exp/clients/horizon/client.go
- exp/clients/horizon/main.go
- exp/clients/horizon/mocks.go
- exp/clients/horizon/trade_aggregation_request.go
- exp/clients/horizon/trade_aggregation_request_test.go
This PR add support for querying trade aggregations.
Closes #1060
> exp/clients/horizon: support trade aggregations

- clients/horizon/client.go
- clients/horizon/main.go
- services/bifrost/main.go
- services/bridge/main.go
- services/friendbot/init_friendbot.go
Add support for headers in current Go SDK (see related PR for new Go SDK https://github.com/stellar/go/pull/1072)
```
X-Client-Name
X-Client-Version
X-App-Name
X-App-Version
```
> App name version current sdk

- services/horizon/internal/codes/main.go
> support changeTrustSelfNotAllowed

- exp/clients/horizon/client.go
- exp/clients/horizon/main.go
- exp/clients/horizon/mocks.go
- exp/clients/horizon/order_book_request.go
- exp/clients/horizon/order_book_request_test.go
This PR adds support for streaming orderbooks in the new horizon client
> exp/clients/horizon: StreamOrderBooks

- services/horizon/internal/docs/reference/endpoints/accounts-single.md
- services/horizon/internal/docs/reference/resources/account.md
First request pulling in the changes in #549.
> Update examples for account resource and endpoint.

- services/horizon/internal/docs/reference/endpoints/assets-all.md
- services/horizon/internal/docs/reference/endpoints/data-for-account.md
- services/horizon/internal/docs/reference/endpoints/ledgers-all.md
Included examples from #549 for the following endpoints.
* Assets All
* Data for Account
* All Ledgers
> Add a few examples for unrelated endpoints.

- services/horizon/internal/docs/reference/endpoints/operations-all.md
- services/horizon/internal/docs/reference/endpoints/operations-for-account.md
- services/horizon/internal/docs/reference/endpoints/operations-for-ledger.md
- services/horizon/internal/docs/reference/endpoints/operations-for-transaction.md
- services/horizon/internal/docs/reference/endpoints/operations-single.md
Another bit of merging and reworking the work in #549.
> Update examples for all of the operation endpoints.

- services/horizon/internal/docs/reference/endpoints/path-finding.md
- services/horizon/internal/docs/reference/endpoints/payments-all.md
- services/horizon/internal/docs/reference/endpoints/payments-for-account.md
- services/horizon/internal/docs/reference/endpoints/payments-for-ledger.md
- services/horizon/internal/docs/reference/endpoints/payments-for-transaction.md
Updated all of the payment endpoints using the work in #549.
> Update payment endpoint examples.

- services/horizon/internal/docs/reference/endpoints/transactions-all.md
- services/horizon/internal/docs/reference/endpoints/transactions-for-account.md
- services/horizon/internal/docs/reference/endpoints/transactions-for-ledger.md
- services/horizon/internal/docs/reference/endpoints/transactions-single.md
Final PR for the work in #549 — added and updated everything for transaction endpoints.
> Add examples for transaction endpoints.

- services/horizon/internal/docs/reference/endpoints/effects-all.md
- services/horizon/internal/docs/reference/endpoints/effects-for-account.md
- services/horizon/internal/docs/reference/endpoints/effects-for-ledger.md
- services/horizon/internal/docs/reference/endpoints/effects-for-operation.md
- services/horizon/internal/docs/reference/endpoints/effects-for-transaction.md
Second PR pulling in the changes from #549. Updates all of the effects endpoints examples (verified on testnet).
> Add updated examples for effects docs.

- support/historyarchive/archive.go
- support/historyarchive/dirprefix.go
- support/historyarchive/fs_archive.go
- support/historyarchive/http_archive.go
- support/historyarchive/mirror.go
- support/historyarchive/mock_archive.go
- support/historyarchive/range.go
- support/historyarchive/repair.go
- support/historyarchive/s3_archive.go
- support/historyarchive/scan.go
- support/historyarchive/util.go
- support/historyarchive/verify.go
closes #1120 
only some variable renames
> Unexport variables in support/historyarchive, closes #1120

- exp/clients/horizon/error.go
The diff looks kind of weird, but all that was done was to extract the first part of method `Envelope()` into a new method `EnvelopeXDR()`. This allows the client to access the raw base 64 XDR string, which is useful for debugging in Stellar Laboratory. The behaviour of the original method `Envelope()` should be unchanged.
There are further more sophisticated improvements that could be made (see #1109 for discussion), but in the interest of time, this is the simplest, least invasive approach.
Closes #1109.
> Extract base 64 XDR envelope for Horizon errors

- exp/ticker/docs/API.md
- exp/ticker/internal/actions_market.go
- exp/ticker/internal/main.go
This PR aims to:
- Provide a preliminary documentation on the Ticker's API endpoints
- Ensure the provided market data is backwards compatible with the current Ticker running on https://ticker.stellar.org
> exp/ticker: API Documentation and Backwards Compatibility

- exp/ticker/README.md
Fixed the spelling of ephemeral and cleaned up some long lines while I was at it.
> Fix a spelling mistake and formatting.

- .github/pull_request_template.md
Here's a proposed PR template @debnil @accordeiro @bartekn . Please tweak! See the file [here](https://github.com/stellar/go/tree/tomquisel-patch-2/.github/pull_request_template.md)
> Add a rough PR template. Please improve me :)

- services/horizon/CHANGELOG.md
Updates CHANGELOG for a new Horizon release.
Updates CHANGELOG for a new Horizon release.
Updates CHANGELOG for a new Horizon release.
None.
None.
> Horizon 0.17.6 CHANGELOG

- clients/horizonclient/CHANGELOG.md
This PR updates the changelog for v1.1 release
> horizonclient: update changelog

- exp/services/keystore/cmd/keystored/main.go
This is to ensure dead connections can go away gracefully.
> keystore: add tcpKeepAlive listener

- services/horizon/internal/docs/admin.md
In the Horizon admin guide describe situations like #1245, where no stellar-core has been set up.
> Horizon troubleshooting (no stellar-core)

- tools/stellar-archivist/README.md
Document how to connect to [Cloud Storage](https://cloud.google.com/storage/) via S3 backend.
> tools/stellar-archivist: docs on working with Cloud Storage

- txnbuild/CHANGELOG.md
This PR updates the changelog for txnbuild in preparation for v1.2.0 release.
> txnbuild: update changelog

- services/friendbot/friendbot.cfg
- services/friendbot/init_friendbot.go
- services/friendbot/internal/account.go
- services/friendbot/internal/friendbot.go
- services/friendbot/internal/friendbot_handler.go
- services/friendbot/internal/friendbot_test.go
- services/friendbot/internal/minion.go
- services/friendbot/loadtest/loadtest.go
- services/friendbot/main.go
This PR re-attempts to add Stellar channels to friendbot (#1187 ), after realizing that the issue was not one of the code but rather not updating the config (d'oh!).
> services/friendbot: adds Stellar channels to friendbot

- services/friendbot/init_friendbot.go
This PR fixes a possible bug - in the case that the transaction to initially create minions fails, previously, we would not account for possible failures. Now, we will.
> services/friendbot: fix minion creation bug

- services/friendbot/internal/minion.go
If you're making a doc PR or something tiny where the below is irrelevant, just delete this
template and use a short description.
otherwise).
[TODO]
[TODO]
[TODO]
[TODO]
> friendbot fix error nil pointer

- services/ticker/docs/API.md
Change `ticker-v2.stellar.org` to `ticker.stellar.org`.
> services/ticker: update API root on ticker docs

- services/ticker/README.md
#1334
Hi, @accordeiro, please merge this.
> fix: installation guides in ticker

- README.md
This PR updates the monorepo's `README.md` to add the ticker to the package index.
> services/ticker: add ticker to the package index

- protocols/horizon/operations/main.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/docs/reference/resources/effect.md
- services/horizon/internal/docs/reference/resources/operation.md
Changes pushed to Horizon 0.19.0.
> Revert v11 operation type changes

- protocols/horizon/operations/main.go
- services/horizon/CHANGELOG.md
This finally changes the operation types in Horizon 0.19.0.
> Update v11 operation types

- exp/services/keystore/keys.go
- exp/services/keystore/problems.go
This PR adds the check for the required fields. Otherwise we will
receive an error from the DB, which will become an internal error.
> exp/keystore: check for required fields

- support/scripts/run_tests
This commit turns on race detector in `go test`.
> Run go test with -race flag

- services/bridge/CHANGELOG.md
- services/bridge/internal/submitter/transaction_submitter_test.go
This PR updates the changelog for the release of `bridgev0.0.32`
> services/bridge: update changelog

- services/compliance/CHANGELOG.md
This PR updates the changelog for the release of `compliancev0.0.32`
> services/compliance 0.0.32 changelogs

- protocols/compliance/auth_data.go
- services/compliance/internal/handlers/request_handler_auth_test.go
- services/compliance/internal/handlers/request_handler_receive_test.go
- services/compliance/internal/handlers/request_handler_send_test.go
- services/compliance/internal/handlers/request_handler_tx_status_test.go
- services/compliance/internal/mocks/main.go
- services/compliance/internal/mocks/mock_database.go
- services/compliance/internal/mocks/mock_federation_resolve.go
- services/compliance/internal/mocks/mock_http_client.go
- services/compliance/internal/mocks/mock_signer_verifier.go
- services/compliance/internal/mocks/mock_stellar_toml_resolver.go
- services/compliance/internal/test/helpers.go
- services/internal/bridge-compliance-shared/main.go
This PR adds unit tests to the compliance server in preparation for 0.032 release. Most of the tests are from the old repo.
> Compliance server unit tests

- support/render/problem/problem.go
This PR fixes some of our commonly used error messages.
> support/render/problem: fix our common error messages

- services/keystore/api.go
We would like to get extra information about the internal error in the log.
> keystore: wrap error messages

- clients/stellartoml/main.go
> clients/stellartoml: increase response max size to 100kb

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/account_request_test.go
- clients/horizonclient/client.go
- clients/horizonclient/effect_request_test.go
- clients/horizonclient/main_test.go
- clients/horizonclient/operation_request_test.go
- clients/horizonclient/submit_request_test.go
- clients/horizonclient/trade_request_test.go
- clients/horizonclient/transaction_request_test.go
- clients/horizonclient/version.go
This PR fixes some issues revealed by `staticcheck` and updates the change log.
> horizonclient: staticcheck fix

- support/render/httpjson/encoding.go
We need a type to check whether the incoming request is a valid json object.
> support/render/httpjson: add json object checker

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
<details>
otherwise).
</details>
This PR updates the changelog for `txnbuild` and `horizonclient` in preparation for `v1.3.0` release.
> horizonclient: update changelogs

- exp/support/pipeline/pipeline.go
This commit fixes a race condition in `Pipeline`. The value was sent to
error channel before updating the running state of the pipeline back to
`false`. This means that the next call to `Process` could panic with
"Pipeline is running..." error.
> Fix pipeline error channel and running state race

- services/horizon/CHANGELOG.md
Merge release branch into master (all new features were on master already because they were patch release changes).
> Horizon v0.18.1 CHANGELOG (#1427)

- exp/ingest/adapters/history_archive_adapter.go
- exp/ingest/adapters/ledger_backend_adapter.go
- exp/ingest/io/ledger_read_closer.go
- exp/ingest/io/main.go
- exp/ingest/io/memory_state_reader.go
- exp/ingest/io/mock_ledger_read_closer.go
- exp/ingest/pipeline/ledger_pipeline.go
- exp/ingest/pipeline/main.go
- exp/ingest/pipeline/pipeline_test.go
- exp/ingest/pipeline/state_pipeline.go
- exp/ingest/pipeline/wrappers.go
- exp/ingest/processors/csv_printer.go
- exp/ingest/processors/entry_type_filter.go
- exp/ingest/processors/root_processor.go
- exp/ingest/processors/status_logger.go
- exp/support/pipeline/buffered_read_write_closer.go
- exp/support/pipeline/buffered_read_write_closer_test.go
- exp/support/pipeline/main.go
- exp/support/pipeline/multi_write_closer.go
- exp/support/pipeline/pipeline.go
- exp/support/pipeline/pipeline_test.go
- exp/tools/accounts-for-signer/processors.go
- exp/tools/horizon-demo/database_processor.go
- exp/tools/horizon-demo/orderbook_processor.go
fixes https://github.com/stellar/go/issues/1432
<details>
otherwise).
</details>
See https://github.com/stellar/go/issues/1432 for motiviation
> exp/ingest: Remove closer suffix from ingest interfaces

- txnbuild/README.md
It should be txe not txeBase64.
> Fix var name in txnbuild inline example.

- .circleci/config.yml
Cherry-pick @accordeiro's commit to fix tests on release branch.
> ci: Ensure tests / builds run on Debian "stretch" (#1532)

- exp/ingest/io/mock_ledger_writer.go
- services/horizon/internal/expingest/processors/database_processor_test.go
Extra tests for `DatabaseProcessor`.
> DatabaseProcessor.ProcessLedger tests

- staticcheck.sh
- txnbuild/account_merge.go
- txnbuild/allow_trust.go
- txnbuild/asset.go
- txnbuild/bump_sequence.go
- txnbuild/change_trust.go
- txnbuild/create_account.go
- txnbuild/create_passive_offer.go
- txnbuild/inflation.go
- txnbuild/manage_buy_offer.go
- txnbuild/manage_data.go
- txnbuild/manage_offer.go
- txnbuild/memo.go
- txnbuild/operation.go
- txnbuild/path_payment.go
- txnbuild/payment.go
- txnbuild/set_options.go
- txnbuild/transaction.go
- txnbuild/transaction_test.go
This is the first attempt at adding a method(`FromXDR`) that parses an xdr string into a Transaction struct. 
The goal of this PR is to gather input on the approach being used before we make further progress.
Please pay close attention to the changes in
- `transaction.go`
- `operation.go`
- `payment.go` and `create_account.go`
> txnbuild: parse base64 XDR strings into Transaction structs

- txnbuild/README.md
<details>
otherwise).
</details>
There's a small, but potentially time-consuming error in the example code provided in the [txnbuild/README.md](https://github.com/stellar/go/tree/master/txnbuild#txnbuild) file.
The `Timebounds` field in the constructed `txnbuild.Transaction` is set to `txnbuild.NewTimebounds(0, 300)` but this puts a max …
> txnbuild/doc: fix TimeBounds error in README (#1561)

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/version.go
- txnbuild/CHANGELOG.md
This PR updates the changelog and version number in preparation for horizonclient-v1.4.0 release
> horizonclient: update changelog for v1.4.0

- services/horizon/docker/README.md
- services/horizon/docker/docker-compose.yml
- services/horizon/docker/stellar-core-pubnet.env
<details>
otherwise).
</details>
Add instructions for running Docker Compose against pubnet.
Previously `docker-compose.yml` was only configured to connect to the testnet environment. I was trying to reproduce an issue on pubnet earlier today and I realized it would be nice to have some configuration to run the docker containers against …
> services/horizon/docker: Add instructions for running Docker Compose against pubnet

- services/horizon/internal/expingest/pipeline_hooks_test.go
- services/horizon/internal/expingest/pipelines.go
<details>
otherwise).
</details>
Add tests for the horizon ingestion pipeline hooks.
The pipeline hooks are a critical component of the horizon ingestion pipelines. Distributed ingestion will only work if the pipeline hooks are functioning properly. The goal of this PR is to add test coverage for the pipeline hooks
Extract the pre and …
> services/horizon/internal/expingest: Add pipeline hooks tests

- exp/orderbook/edges.go
- price/main.go
- price/main_test.go
- price/mul_bits.go
- price/mul_legacy.go
<details>
* [ x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
* [ x] This PR's title starts with name of package that is most changed in the PR, ex.
* [x ] This PR adds tests for the most critical parts of the new functionality or fixes.
* [ x] I've decided if this PR requires a new major/minor version according to …
> exp/orderbook: Optimize in memory path finding

- services/horizon/CHANGELOG.md
- services/horizon/internal/expingest/BETA_TESTING.md
> Beta testing expingest guide

- services/horizon/CHANGELOG.md
- services/horizon/internal/expingest/BETA_TESTING.md
Additionally fix markdown issues in Horizon CHANGELOG.
> Update expingest blog post URL

- .circleci/config.yml
- exp/tools/dump-ledger-state/diff_test.sh
* Fix memory usage of `sort` to 1GB max.
* Fix getting `postgresql-client-9.6` on Debian Buster.
> Fix ingest state diff

- services/horizon/docker/README.md
- services/horizon/docker/docker-compose.yml
* Include info on how to use a specific version of stellar core
* Include forgotten feedback from https://github.com/stellar/go/pull/1626
> services/horizon/docker: Update docker compose instructions

- services/horizon/internal/docs/reference/resources/account.md
- services/horizon/internal/docs/reference/resources/asset.md
<details>
otherwise).
packages.
</details>
I noticed the documentation on the accounts and assets resources does not reflect what's returned by Horizon. I updated them accordingly.
> doc: Fix assets and accounts documentation

- exp/orderbook/dfs.go
- exp/orderbook/graph.go
- exp/orderbook/graph_test.go
- price/main.go
- price/main_test.go
<details>
otherwise).
packages.
* [] I've updated any docs ([developer docs](https://www.stellar.org/developers/reference/), `.md`
</details>
Ignore offers which result in overflow errors in path finding search. Fixes https://github.com/stellar/go/issues/1692
> exp/orderbook: Ignore offers which result in overflow errors in path finding search

- services/horizon/internal/expingest/main.go
We don't want to crash entire app in case of `expingest` unexpected errors. Close #1651.
> services/horizon/expingest: Expingest recover

- DEVELOPING.md
<details>
otherwise).
packages.
</details>
Add reference in the `DEVELOPING.md` to the Horizon docs that including more specific developing instructions.
To guide contributors to the right place. #1752 added general developing documentation and @abuiles pointed out in …
> docs: add link to horizon docs for developing

- services/horizon/internal/docs/admin.md
Adds the most popular log entries, metrics and alerts to Horizon Admin Guide. @ire-and-curses @brahman81 please add comments if something is not clear or you feel we should expand the doc.
Close #1740.
> Add Horizon metrics to Admin Guide

- services/horizon/internal/docs/admin.md
Thanks @leighmcculloch for reminding about it.
> Add `req` value to Horizon Admin Guide

- services/horizon/internal/middleware.go
- services/horizon/internal/middleware_test.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/1864
> In #1830 we started sending Latest-Ledger header that includes info about the latest ingested ledger. The problem is that we start REPEATABLE READ transaction in a middleware and …
>  services/horizon/internal: Do not start repeatable read sessions for streaming endpoints

- .circleci/config.yml
- services/horizon/docker/Dockerfile
<details>
otherwise).
</details>
Add CircleCI step to publish horizon docker image for every release
The goal of this PR is to publish a horizon docker image for every release of horizon.
* Add `publish_horizon_docker_image` , a circle CI job which builds and pushes a horizon docker image
* invoke  `publish_horizon_docker_image` on all …
> Add CircleCI step to publish horizon docker image for every release

- protocols/horizon/main.go
- services/horizon/internal/actions/account.go
- services/horizon/internal/actions/asset.go
- services/horizon/internal/actions/helpers.go
- services/horizon/internal/actions/helpers_test.go
- services/horizon/internal/actions/offer.go
- services/horizon/internal/actions/query_params.go
- services/horizon/internal/actions/validators.go
- services/horizon/internal/actions/validators_test.go
- services/horizon/internal/actions_path.go
- services/horizon/internal/actions_path_test.go
- services/horizon/internal/actions_root.go
- services/horizon/internal/actions_root_test.go
- services/horizon/internal/resourceadapter/root.go
- services/horizon/internal/resourceadapter/root_test.go
- xdr/asset.go
- xdr/asset_test.go
<details>
otherwise).
packages.
</details>
Update strict send path action to use query structs.
We are in the process of documenting all the experimental endpoints and `paths/strict-send` does not get listed on the root resource in Horizon. To facilite documentation, this PR adds …
> services/horizon/internal/actions: Update strict send path action to use query structs.

- services/horizon/CHANGELOG.md
- services/horizon/internal/expingest/main.go
- services/horizon/internal/expingest/processors/accounts_signer_processor_test.go
- services/horizon/internal/expingest/processors/database_processor.go
- services/horizon/internal/expingest/processors/offers_processor_test.go
- services/horizon/internal/expingest/verify.go
> services/horizon: Fix `AccountsForSigner` to remove preauth tx signer

- services/horizon/internal/actions/account.go
<details>
otherwise).
packages.
</details>
Fix the message to include the right format for asset.  Fixes #1926 1926
After #1835, asset is passed using asset param instead of asset_type, asset_issuer and asset_code.
N/A
> Fix invalid account params message.

- services/federation/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update Federation's CHANGELOG to move features that were released in [Federation v0.2.1] into their own section, separate from unreleased features.
It looks like when we released [Federation v0.2.1] we forgot to update the CHANGELOG. …
> services/federation: fix changelog for v0.2.1

- services/friendbot/CHANGELOG.md
<details>
otherwise).~
packages.
</details>
Set version in CHANGELOG for Friendbot v0.0.2.
Also added version for the initial release of [Friendbot v0.0.1] that was missing.
To release Friendbot v0.0.2.
N/A
[Friendbot v0.0.1]: …
> services/friendbot: set version for release v0.0.2

- services/bridge/CHANGELOG.md
- services/compliance/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update CHANGELOG of Bridge and Compliance with change introduced in 12f6d43.
To release Bridge and Compliance with the fix in the shared library.
N/A
> services/{bridge,compliance}: update changelogs for release 0.0.33

- README.md
<details>
otherwise).
packages.
</details>
Link the Stellar logo in the README to stellar.org.
I intended to do this when I added the logo in #1948 and forgot.
N/A
> doc: link Stellar logo in header

- services/horizon/internal/expingest/pipelines.go
<details>
otherwise).
packages.
</details>
Rollback DB transaction in case of errors in the pipeline pre-hook.
In case of DB queries errors in the pipeline pre-hook all the following queries will fail with:
```
current transaction is aborted, commands ignored until end of …
```
> services/horizon: Rollback DB transaction in case of errors in the pipeline pre-hook

- tools/horizon-cmp/README.md
<details>
otherwise).
packages.
</details>
Documents both modes for `horizon-cmp` and available options.
There were no docs.
N/A
> Update horizon-cmp README.

- services/horizon/internal/render/problem/problem.go
- services/horizon/internal/web.go
Discussion here: https://github.com/stellar/go/pull/1995#pullrequestreview-326390169
> services/horizon/render/problem: Change Cancelled to Service Unavailable

- services/horizon/internal/actions/account.go
<details>
otherwise).
packages.
</details>
Annotate the errors to help us on the debug process.
> Use errors.Wrap to help debugging. 

- services/horizon/CHANGELOG.md
Add changelog for v0.24.1 release
> services/horizon/CHANGELOG.md: Add changelog for v0.24.1 release

- Gemfile.lock
<details>
otherwise).
packages.
</details>
Update the version of excon in the repositories Gemfile.lock to 0.71.0.
Excon is a dependency of the ruby stellar-sdk which we pin in this repository for using xdrgen. It's pretty old and there's a new version released.
N/A
> all: update excon to 0.71.0

- clients/horizonclient/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update horizon client changelog for 2.0.0 release
> clients/horizonclient: Update horizon client changelog for 2.0.0 release

- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/expingest/processors/effects_processor_test.go
<details>
otherwise).
packages.
</details>
Don't create an effect when an account is sending a trust to itself. Fixes #2121.
When an account trusts itself, the transaction is successful but no ledger entries are actually modified. This was producing an effect where none should …
> services/horizon/internal/expingest: Fix regression on change trust effects

- protocols/horizon/operations/main.go
<details>
otherwise).
packages.
</details>
Update type name for operations: `pathPaymentStrictReceive`, `manageSellOffer`, and `createPassiveSellOffer`. Fixes #2132 
The used type doesn't match the operation type, we delayed this change up to `0.25.0` and we are doing it now. …
> protocols/horizon: Apply deprecation on some operation types, updating them to the correct value

- services/horizon/internal/expingest/TESTING.md
This commit updates testing guide. See: #2127.
> services/horizon: Testing guide

- exp/ingest/io/ledger_entry_change_cache.go
- services/horizon/internal/expingest/processors/accounts_data_processor_test.go
- services/horizon/internal/expingest/processors/accounts_processor.go
- services/horizon/internal/expingest/processors/accounts_processor_test.go
- services/horizon/internal/expingest/processors/new_transactions_processor.go
- services/horizon/internal/expingest/processors/offers_processor.go
- services/horizon/internal/expingest/processors/offers_processor_test.go
- services/horizon/internal/expingest/processors/transactions_processor_test.go
- services/horizon/internal/expingest/processors/trust_lines_processor.go
- services/horizon/internal/expingest/processors/trust_lines_processor_test.go
<details>
otherwise).
packages.
</details>
[TODO: Short statement about what is changing.]
[TODO or N/A]
> services/horizon/expingest/processors: Refactor state processors

- exp/services/webauth/README.md
<details>
otherwise).
packages.
</details>
Update the webauth README with details for how it works as of the changes that were just made to it for v1.3.0.
I missed updating the README file.
N/A
> exp/services/webauth: update readme for v1.3.0

- services/horizon/internal/expingest/main.go
<details>
otherwise).
packages.
</details>
* Inline `validateStartLedger()` into `ingestHistoryRange()`
* Omit return error if `lastHistoryLedger != s.state.rangeFromLedger-1`
In the `init` state it’s possible that during transition to  `ingestHistoryRangeState` another horizon …
> services/horizon/internal/expingest: Inline validateStartLedger() into ingestHistoryRange()

- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/expingest/processors/ledgers_processor.go
- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/expingest/processors/participants_processor.go
- services/horizon/internal/expingest/processors/trades_processor.go
- services/horizon/internal/expingest/processors/transactions_processor.go
<details>
otherwise).
packages.
</details>
Fix interface check for ledger processors.
Processors should implement io.LedgerTransactionProcessor
[TODO or N/A]
> services/horizon/internal/expingest/processors: Fix interface check.

- services/horizon/internal/docs/reference/resources/account.md
- services/horizon/internal/docs/reference/resources/ledger.md
- services/horizon/internal/docs/reference/resources/operation.md
- services/horizon/internal/docs/reference/resources/transaction.md
<details>
otherwise).
packages.
</details>
Remove mentions to deprecated fields which are not longer on Horizon and notes mentioning since when a specific field is available in Horizon.
This is part of the documentation cleanup before 1.0.
[TODO or N/A]
> services/horizon/internal/docs: Improve more documentation.

- protocols/horizon/main.go
<details>
otherwise).
packages.
</details>
Update  `Offer` to remove dependency on `offerBase`  and allow creation of offers without relying on another struct. 
We find out Kelp needs to build Offers manually, @nikhilsaraf put a temporary hack in his fork here …
> protocols/horizon: Make offerBase an inline struct and move back original fields to Offer.

- clients/horizonclient/CHANGELOG.md
Update horizonclient CHANGELO.
> clients/horizon: 2.1.0 CHANGELOG

- clients/horizonclient/CHANGELOG.md
- clients/horizonclient/main_test.go
- clients/horizonclient/version.go
<details>
otherwise).
packages.
</details>
Update `client.Version` to match current release.
It was outdated.
[TODO or N/A]
> Update Client and date.

- tools/horizon-cmp/README.md
<details>
otherwise).
packages.
</details>
Document `horizon-cmp history`.
The README doesn't mention this sub-command.
[TODO or N/A]
> tools/horizon-cmp: Document horizon-cmp history.

- exp/services/recoverysigner/README.md
<details>
otherwise).
packages.
</details>
Update README with link to SEP-30.
When the service was being developed the SEP wasn't yet assigned a
number or published to the stellar-protocol repository. That has
happened now.
N/A
> exp/services/recoverysigner: update readme with link to sep30

- services/horizon/internal/ingest/session.go
- services/horizon/internal/ingest/session_test.go
Port signer updated fix to old ingestion  -  fix #2384
> Fix signer update effects.

- exp/ingest/io/single_ledger_state_reader.go
- exp/ingest/io/single_ledger_state_reader_test.go
<details>
otherwise).
packages.
</details>
The `SingleLedgerStateReader` fetches all the bucket hashes belonging to a history archive snapshot for a specific ledger. Afterwards, the reader iterates through all the entries in the history archive snapshot using the following …
> exp/ingest/io: Retry bucket exists requests upon failure

- go.list
- go.mod
- go.sum
<details>
otherwise).
packages.
</details>
Update `github.com/stretchr/testify` from `v1.4.0` to `v1.5.1`.
I'd like to use the [`PanicsWithError`] function that I added in stretchr/testify#839. It allows us to write assertions on error objects that are passed up the stack with …
> all: update github.com/stretchr/testify v1.4.0=>v1.5.1

- exp/services/recoverysigner/README-Firebase.md
- exp/services/recoverysigner/README.md
<details>
otherwise).
packages.
</details>
Add Firebase setup instructions for setting up a Firebase project for use with recoverysigner.
Recoverysigner currently uses Firebase as an authentication method for email address and phone number but it may not be clear to someone using …
> exp/services/recoverysigner: add Firebase setup instructions

- services/horizon/CHANGELOG.md
Includes https://github.com/stellar/go/commit/2f93e52e1aec9ed242ada518da239f93038a3db3 in 1.2.0 branch.
> Update migration time

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
Update changelog for horizon client and txnbuild
> horizonclient,txnbuild: Update changelog

- services/horizon/internal/web.go
> Add heap and CPU profilers to ADMIN_PORT

- txnbuild/CHANGELOG.md
This PR amends https://github.com/stellar/go/pull/2586 to include the update to the changelog.
Keep changelog updated.
> txnbuild: update changelog to include AddSignatureBase64

- services/ticker/internal/actions_orderbook.go
- services/ticker/internal/actions_trade.go
- services/ticker/internal/gql/resolvers_market.go
- services/ticker/internal/gql/resolvers_market_test.go
- services/ticker/internal/tickerdb/helpers.go
- services/ticker/internal/tickerdb/main.go
- services/ticker/internal/tickerdb/queries_market.go
- services/ticker/internal/tickerdb/queries_market_test.go
<details>
otherwise).
packages.
</details>
This PR swaps the base and counter logic in the ticker. Prices will now be computed denominated against the base. Along the way, this also enables two-sided queries for `ticker` and `markets`, to confirm this functionality.
This makes …
> services/ticker: swap base/counter, allow two-sided queries

- services/horizon/internal/expingest/verify.go
<details>
otherwise).
packages.
</details>
This commit updates error messages in `System.verifyState` with more information about the state.
> services/horizon/ingest: Update error messages in System.verifyState

- services/ticker/internal/gql/main.go
- services/ticker/internal/graphql_test.go
- services/ticker/internal/tickerdb/tickerdb_test/queries_asset_test.go
- services/ticker/internal/tickerdb/tickerdb_test/queries_issuer_test.go
- services/ticker/internal/tickerdb/tickerdb_test/queries_market_test.go
- services/ticker/internal/tickerdb/tickerdb_test/queries_orderbook_test.go
- services/ticker/internal/tickerdb/tickerdb_test/queries_trade_test.go
- services/ticker/internal/tickerdb/tickerdbtest/tickerdbtest.go
<details>
otherwise).
packages.
</details>
This PR adds tests for the GraphQL API. It also refactors existing `tickerdb` tests into their own package, so the same database setup can be used for the API testing.
As we change the API in ticker v2, testing the API directly helps …
> services/ticker: test the GraphQL API

- support/render/problem/problem.go
otherwise).
packages.
</details>
Fixes the error message of ServerError by adding a space.
`systemadministrator` is hard to read.
N/A
> support/render/problem: fix 500 detail message

- services/ticker/internal/graphql_test.go
<details>
otherwise).
packages.
</details>
Reduce the ticker query test to raw request response comparisons and
split the three tests within the one test into their own tests.
Reducing code re-usability in tests improves the maintainability of the
tests as it becomes easier to …
> services/ticker: reduce the ticker query test to raw request response comparisons

- exp/ingest/ledgerbackend/captive_core_backend.go
<details>
otherwise).
packages.
</details>
Add a simple caching of the latest fetched ledger in `captiveStellarCore`.
It's possible that the ledger will be fetched multiple times, ex. to create change and transaction readers. Because of the fact that it's not possible to rewind …
> exp/ingest/io: Cache the latest fetched ledger in captiveStellarCore

- exp/services/recoverysigner/README.md
This PR adds the missing db usage to the readme.
To make the README updated.
N/A
> exp/services/recoverysigner: add db usage to readme

- .circleci/config.yml
- services/keystore/README.md
- tools/archive-reader/CHANGELOG.md
- tools/archive-reader/README.md
<details>
otherwise).
packages.
</details>
Build packages as an extra testing step, this will help us make sure that the windows build work.
The windows build was broken and we find out just while cutting a new release. This will help us identify this issues earlier.
A more …
> Run build_packages in tests step.

- exp/ingest/ledgerbackend/stellar_core_runner_windows.go
<details>
otherwise).
packages.
</details>
Fix err variable in windows runner.
I think this was a side-effect of merging 1.6.0  - master is okay.
> exp/ingest: Fix stellar core runner in  windows.

- exp/ingest/ledgerbackend/captive_core_backend_test.go
<details>
otherwise).
packages.
</details>
Improve test coverage for `GetLedger`.
We need to test captive core.
> exp/ingest: Add more test for captive_core_backend GetLedger.

- services/horizon/internal/expingest/fsm.go
<details>
otherwise).
packages.
</details>
I'm not sure if my comment https://github.com/stellar/go/pull/2802#discussion_r454547057 about removing the transition return value in `maybePrepareRange()` was clear. So I created this PR to show what I had in mind.
I believe that the …
> services/horizon/internal/expingest: Simplify maybePrepareRange()

- exp/ingest/ledgerbackend/captive_core_backend.go
- services/horizon/CHANGELOG.md
- services/horizon/cmd/db.go
- services/horizon/internal/expingest/fsm.go
- services/horizon/internal/expingest/main.go
* Updated CHANGELOG.
* Fixed typos.
* Small _nit_ code improvements.
> services/horizon: Minor fixes and updates before 1.6.0 release

- services/horizon/CHANGELOG.md
> services/horizon: Update CHANGELOG

- services/horizon/internal/actions/helpers.go
- services/horizon/internal/actions/helpers_test.go
- services/horizon/internal/actions/ledger.go
- services/horizon/internal/actions/offer.go
- services/horizon/internal/actions/offer_test.go
- services/horizon/internal/actions/validators.go
- services/horizon/internal/web.go
Follow up to #2829 . Part of #2582
> services/horizon: Get /ledger/{ledger_id} fixes and refactorings

- Rakefile
- exp/ingest/io/change.go
- exp/ingest/io/ledger_transaction_test.go
- services/horizon/internal/actions/account_test.go
- services/horizon/internal/actions_path_test.go
- services/horizon/internal/db2/history/accounts_test.go
- services/horizon/internal/expingest/verify.go
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-ledger.x
- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
Update `.x` files and auto-generated XDR code.
We need to support Protocol 14.
This is using the following branch https://github.com/jonjove/stellar-core/tree/cap-0033
> xdr: Regenerate XDR files using Protocol 14.

- exp/ingest/doc.go
- exp/ingest/doc_test.go
- exp/ingest/io/main.go
- exp/ingest/ledgerbackend/captive_core_backend.go
- exp/ingest/ledgerbackend/ledger_backend.go
- exp/ingest/main.go
- services/horizon/cmd/db.go
- services/horizon/internal/docs/captive_core.md
> Merge master into 1.7.0 release branch

- xdr/Stellar-ledger-entries.x
- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
Rebuild XDR definitions to match RC version.
Because it's still changing.
> Rebuild XDRs to match RC.

- exp/ingest/io/stats_ledger_transaction_processor.go
- exp/ingest/io/stats_ledger_transaction_processor_test.go
<details>
otherwise).
packages.
</details>
Update StatsLedgerTransactionProcessor with Protocol 14 operations.
There are new operations in protocol 14.
[TODO or N/A]
> exp/ingest: Extend stats ledger transaction processor with Protocol 14 operations. 

- xdr/json.go
- xdr/json_test.go
Fixes https://github.com/stellar/go/issues/2977
> xdr: Fix bug in json serliazation of claim predicates

- services/horizon/internal/resourceadapter/operations.go
<details>
otherwise).
packages.
</details>
Transaction details are currently not rendered. This commit fixes this bug.
> services/horizon: Fix Protocol 14 operations resource adapter

- protocols/horizon/operations/main.go
> services/horizon: Omit begin_sponsor detail of EndSponsoringFutureReserves if missing

- exp/services/market-tracker/README.md
- exp/services/market-tracker/calc.go
- exp/services/market-tracker/calc_test.go
- exp/services/market-tracker/config.go
- exp/services/market-tracker/config_sample.json
- exp/services/market-tracker/main.go
- exp/services/market-tracker/orders.go
- exp/services/market-tracker/orders_test.go
- exp/services/market-tracker/price.go
- exp/services/market-tracker/spread.go
- exp/services/market-tracker/volume.go
- exp/services/market-tracker/volume_test.go
- exp/services/market-tracker/watchers.go
<details>
otherwise).
packages.
</details>
This PR updates the `market-tracker` codebase with changes made since initially porting it to the monorepo. The public version will be in line with the private repo. Although this change is large, all changes have already been reviewed.
We want to fully expose the market tracker to the public. Closes https://github.com/stellar/market-tracker/issues/58.
N/A
> exp/services/market-tracker: update codebase

- services/horizon/internal/expingest/processors/operations_processor.go
- services/horizon/internal/expingest/processors/transaction_operation_wrapper_test.go
> services/horizon: Account for overlapping sandwiches in EndSponsoringFutureReserves

- services/ticker/cmd/root.go
<details>
otherwise).
packages.
</details>
This PR adds a small comment to an exported function.
To test the Jenkins pipelines logic, as per [this discussion with ops](https://github.com/stellar/ops/issues/376#issuecomment-692030572).
N/A
> Add exported function comment.

- services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
<details>
otherwise).
packages.
</details>
Test claimable balance creation inside a sandwich.
>  services/horizon: Add integration test for sponsored claimable balance. 

- protocols/horizon/effects/main.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/expingest/processors/effects_processor.go
- services/horizon/internal/expingest/processors/effects_processor_test.go
- services/horizon/internal/expingest/processors/signers_processor.go
- services/horizon/internal/resourceadapter/effects.go
- services/horizon/internal/resourceadapter/transaction_result_codes.go
- xdr/account_entry.go
- xdr/account_entry_test.go
<details>
otherwise).
packages.
</details>
Close https://github.com/stellar/go/issues/2943 
Close https://github.com/stellar/go/issues/2942
Add Horizon responses for Claimable Balance and Sponsorship effects.  
[N/A]
> services/horizon: Add sponsorship and claimable balance effects

- .circleci/config.yml
This pull request reverts stellar/go/pull/3009
Original PR breaks CircleCI runs in some situations
> Revert PR #3009 as it breaks CircleCI runs in some cases

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update changelog for upcoming 1.9.0-rc release with information about new Protocol 14 features.
> services/horizon: Add changelog entry for protocol 14 additions

- services/horizon/internal/resourceadapter/effects.go
> services/horizon: Fix data effect details not being ingested

- services/horizon/internal/integration/protocol14_state_verifier_test.go
<details>
otherwise).
packages.
</details>
Update state verifier integration test to check if it works correct if the middle signer is sponsored.
To ensure that we check the 1:1 mapping correctly. The code was [invalid](https://github.com/stellar/go/pull/2945#discussion_r476510659 …
> services/horizon: Update state verifier tests to check the middle signer's sponsor

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
- txnbuild/begin_sponsoring_future_reserves_test.go
- txnbuild/claim_claimable_balance_test.go
- txnbuild/create_claimable_balance.go
- txnbuild/create_claimable_balance_test.go
- txnbuild/end_sponsoring_future_reserves_test.go
- txnbuild/operation.go
- txnbuild/revoke_sponsorship_test.go
<details>
otherwise).
packages.
</details>
There was a bug which occurred when parsing transaction XDR strings which contained protocol 14 operation. This PR fixes the bug and adds test to ensure that all Protocol 14 operations can be parsed correctly.
> txnbuild: Fix bug in parsing transactions with Protocol 14 operations

- services/horizon/internal/expingest/processors/signer_processor_test.go
- services/horizon/internal/expingest/processors/signers_processor.go
<details>
otherwise).
packages.
</details>
Fixes `SignersProcessor` to insert sponsorship information during state ingestion from history archives.
`SignersProcessor` operates in two modes: `useLedgerEntryCache` set to `true` or `false`. When ingesting history archives we use …
> services/horizon: Insert signers's sponsorship information during state ingestion

- services/horizon/CHANGELOG.md
http://github.com/stellar/go/compare/horizon-v1.9.0...release-horizon-v1.9.1
> Horizon 1.9.1 CHANGELOG

- services/horizon/internal/test/integration.go
To do so, you need to set the `HORIZON_INTEGRATION_ENABLE_CAPTIVE_CORE` env variable to any value (e.g. `true`).
> services/horizon: Allow using captive core in integration tests

- services/horizon/CHANGELOG.md
- services/horizon/internal/expingest/main.go
- services/horizon/internal/expingest/processor_runner_test.go
- services/horizon/internal/integration/protocol14_claimable_balance_ops_test.go
- services/horizon/internal/integration/protocol14_sponsorship_ops_test.go
- services/horizon/internal/integration/protocol14_state_verifier_test.go
- services/horizon/internal/integration/protocol14_test.go
> services/horizon: Bump max supported protocol version to 15

- services/horizon/docker/verify-range/Dockerfile
<details>
otherwise).
packages.
</details>
Bump Stellar Core to latest version.
We'll need this once there is a protocol upgrade.
> services/horizon/docker/verify-range: Bump stellar-core  version.

- services/horizon/internal/integration/protocol14_test.go
- txnbuild/CHANGELOG.md
- txnbuild/helpers.go
- xdr/transaction_result.go
<details>
otherwise).
packages.
</details>
See title.
Closes #3126.
> xdr: Adds a helper to extract balance IDs from transaction results.

- exp/tools/dump-ledger-state/Dockerfile
- exp/tools/dump-ledger-state/README.md
- exp/tools/dump-ledger-state/diff_test.sh
- exp/tools/dump-ledger-state/dump_core_db.sh
- exp/tools/dump-ledger-state/main.go
<details>
otherwise).
packages.
</details>
Fixes https://github.com/stellar/go/issues/3022
Stellar Core recently modified its database schema which consequently broke the SQL queries used in dump_core_db.sh.
This commit fixes the SQL queries so that it works with the latest …
> exp/tools/dump-ledger-state: Fix dump ledger state script

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Add v1.11.0 to Horizon's Changelog.
> services/horizon: Update changelog with v1.11.0.

- ingest/ledgerbackend/stellar_core_runner.go
<details>
otherwise).
packages.
</details>
Fixed two minor issued connected to Stellar-Core logging:
* Regexp missed pubkeys with digits.
* After each ledger close Stellar-Core prints an empty line. Removed empty lines from log.
> ingest/ledgerbackend: Minor Core logging fixes

- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/verify_range_state_test.go
<details>
otherwise).
packages.
</details>
Calls `PrepareRange` on ledger backend in `verifyRange` ingestion state.
This is correct usage of `LedgerBackend` interface and is required by captive core to be initialized.
> services/horizon/ingest: Call PrepareRange in verifyRange state

- services/horizon/internal/docs/captive_core.md
Fixed formatting issues (see image below):
> Fix small formatting issues in captive_core.md

- services/keystore/api.go
<details>
otherwise).
packages.
</details>
In the `/health` endpoint, use the `PassHandler` in the `support/render/health` package to replace the handler implemented in the `keystore` itself.
Already described above.
[N/A]
> services/keystore: improve health endpoint.

- services/horizon/internal/docs/reference/endpoints/metrics.md
It no longer outputs JSON
Closes https://github.com/stellar/go/issues/591
> Update GET /metrics docs

- protocols/horizon/operations/main.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/resourceadapter/operations.go
Depends on #3349 
Part of #3348
> [CAP 35] Implement ingestion for Clawback operations

- protocols/horizon/main.go
- services/horizon/internal/actions/asset_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/trust_lines.go
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/resourceadapter/asset_stat.go
- services/horizon/internal/resourceadapter/asset_stat_test.go
- services/horizon/internal/resourceadapter/balance.go
- txnbuild/allow_trust.go
- txnbuild/operation_test.go
- txnbuild/set_options.go
- xdr/account_flags.go
- xdr/account_flags_test.go
- xdr/trust_line_flags.go
- xdr/trust_line_flags_test.go
Add support for the new flags in CAP 35
Part of #3348 
Depends on #3350
> [CAP 35] Add support for clawback account and trustline flags

- services/horizon/internal/codes/main.go
- services/horizon/internal/codes/main_test.go
> [CAP 35] Add support for SetOptions AuthRevocablRequired code

- services/horizon/CHANGELOG.md
Add change log entry for the horizon 1.14.0 release
> services/horizon: Add Horizon 1.14.0 changelog

- services/horizon/internal/db2/history/accounts.go
- services/horizon/internal/resourceadapter/account_entry.go
- services/horizon/internal/resourceadapter/account_entry_test.go
> [CAP 35] Populate account clawback flag

- services/horizon/internal/flags.go
> services/horizon: Allow --stellar-core-binary-path to be prefilled from the PATH

- services/horizon/internal/ingest/processors/stats_ledger_transaction_processor.go
- services/horizon/internal/ingest/processors/stats_ledger_transaction_processor_test.go
> [CAP 35] Add operations stats for new clawback operations

- txnbuild/CHANGELOG.md
- txnbuild/allow_trust.go
- txnbuild/clawback.go
- txnbuild/clawback_test.go
> [CAP 35] txnbuild: Add txnbuild support for the Clawback operation

- .circleci/config.yml
- services/horizon/docker/Dockerfile
- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/internal/ingest/main.go
- services/horizon/internal/ingest/processor_runner_test.go
- services/horizon/internal/integration/protocol14_test.go
- services/horizon/internal/integration/protocol_16_test.go
- services/horizon/internal/test/integration/integration.go
> [CAP 35] Add Clawback happy path integration test

- xdr/Stellar-ledger-entries.x
- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
> [CAP 35] Update XDR definitions with the latest CAP updates

- services/horizon/internal/codes/main.go
- services/horizon/internal/codes/main_test.go
> [CAP 35] Add support for new result codes in CAP35

- historyarchive/archive.go
- historyarchive/archive_test.go
<details>
otherwise).
packages.
</details>
This commit fixes a few bugs found in the `GetLedgers()` function of the history archive client. It also includes a test case which should prevent future regressions.
[N/A]
> historyarchive: Fix bugs in GetLedgers()

- .circleci/config.yml
- services/horizon/internal/integration/protocol16_test.go
> [CAP 35] Add happy-path integrationt test for ClawbackClaimableBalance

- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/integration/protocol16_test.go
Part of #3348 
Leftover from https://github.com/stellar/go/pull/3358#discussion_r561784015 (CC @tamirms )
> [CAP 35] Add AccountCredited effect to ClawbackCB operation

- services/horizon/internal/codes/main.go
- services/horizon/internal/ingest/processors/stats_ledger_transaction_processor.go
- services/horizon/internal/integration/protocol16_test.go
> [CAP 35] Add happy-path test for SetTrustLineFlags operation

- protocols/horizon/effects/main.go
- protocols/horizon/operations/main.go
- services/horizon/internal/integration/protocol16_test.go
Part of https://github.com/stellar/go/issues/3447
> [CAP 35] Improve SetTrustLineFlags integration testing

- services/regulated-assets-approval-server-demo/CHANGELOG.md
- services/regulated-assets-approval-server-demo/README.md
- services/regulated-assets-approval-server-demo/cmd/serve.go
- services/regulated-assets-approval-server-demo/main.go
- services/regulated-assets-approval-server-demo/serve/handlers.go
- services/regulated-assets-approval-server-demo/serve/middleware.go
- services/regulated-assets-approval-server-demo/serve/serve.go
<details>
otherwise).
packages.
</details>
Bootstrap a go service that will be used to serve a demo implementation of a [SEP-8] approval server.
After this PR is merged we can start implementing the Approval Server features.
N/A
[SEP-8]: …
> services/regulated-assets-approval-server-demo: bootstrap service for the regulated assets' approval server demo

- Makefile
- services/regulated-assets-approval-server-demo/Makefile
- services/regulated-assets-approval-server-demo/docker/Dockerfile
<details>
otherwise).
packages.
</details>
Add build files for deploying regulated-assets-approval-server-demo.
So we can have CD/CI.
> services/regulated-assets-approval-server-demo: add Dockerfile and Makefile

- services/horizon/internal/db2/schema/bindata.go
- services/horizon/internal/db2/schema/migrations/43_add_claimable_balances_flags.sql
Fixes #3465
The migration of the `claimable_balances` DB table was failing
> [CAP 35] Add default value to claimable balance flags table migration

- .circleci/config.yml
- services/horizon/internal/ingest/processors/effects_processor.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- txnbuild/set_trust_line_flags.go
- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
See https://github.com/stellar/stellar-protocol/pull/878 for more details.
Fixes https://github.com/stellar/go/issues/3448
> [CAP 35] Update XDR definitions according to the latest CAP35 changes

- services/horizon/internal/flags.go
> Only consistency-check the Captive Core flags when captive-core ingestion is enabled

- services/horizon/internal/httpx/server.go
- support/render/problem/default.go
- support/render/problem/problem.go
<details>
otherwise).
packages.
</details>
Set log filter to `LogUnkownErrors` in Horizon to log only unknown errors in `Problem.Render`.
Known errors are expected and don't need to be logged.
> services/horizon: Log only unknown errors in Problem.Render

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
> txnbuild: Add txnbuild/horizonclient CHANGELOG entries for 7.0 release

- clients/horizonclient/CHANGELOG.md
- txnbuild/CHANGELOG.md
> Merge release-horizonclient-v7.0.0 branch into master

- services/regulated-assets-approval-server/README.md
- services/regulated-assets-approval-server/internal/serve/toml.go
- services/regulated-assets-approval-server/internal/serve/toml_test.go
<details>
otherwise).
packages.
</details>
Adds new tests to the TOML handler and adds a validate function to ensure correct data is given.
Closes: https://github.com/stellar/nebula/issues/184
Improve test coverage.
N/A
> `services/regulated-assets-approval-server/internal/serve/`:  Add validator and tests to toml handler

- .circleci/config.yml
- services/horizon/docker/Dockerfile.dev
- services/horizon/docker/core-start.sh
- services/horizon/docker/docker-compose.integration-tests.yml
- services/horizon/internal/integration/protocol16_test.go
> Horizon: re-enable core 17 for CI (reverts #3600)

- services/horizon/CHANGELOG.md
- services/horizon/internal/actions/orderbook_test.go
- services/horizon/internal/actions_path_test.go
- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/orderbook_test.go
- services/horizon/internal/db2/history/trust_lines_test.go
- services/horizon/internal/httpx/handler.go
- services/horizon/internal/httpx/middleware.go
- services/horizon/internal/httpx/stream_handler_test.go
- services/horizon/internal/ingest/build_state_test.go
- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/ingest_history_range_state_test.go
- services/horizon/internal/ingest/init_state_test.go
- services/horizon/internal/ingest/main_test.go
- services/horizon/internal/ingest/orderbook.go
- services/horizon/internal/ingest/resume_state_test.go
- services/horizon/internal/ingest/stress_test.go
- services/horizon/internal/ingest/verify.go
- services/horizon/internal/ingest/verify_range_state_test.go
- services/horizon/internal/txsub/helpers_test.go
- services/horizon/internal/txsub/results.go
- services/horizon/internal/txsub/system.go
- services/horizon/internal/txsub/system_test.go
- support/db/batch_insert_builder_test.go
- support/db/main.go
- support/db/mock_session.go
- support/db/session.go
- support/db/session_test.go
<details>
otherwise).
packages.
</details>
[TODO: Short statement about what is changing.]
[TODO or N/A]
> Horizon Release v2.4.0

- services/regulated-assets-approval-server/internal/serve/toml.go
- services/regulated-assets-approval-server/internal/serve/toml_test.go
<details>
otherwise).
packages.
</details>
Update toml file `approval_criteria`.
To make the criteria more precise with the server behaviour.
> services/regulated-assets-approval-server: update toml file approval_criteria

- .circleci/config.yml
> horizon: Publish verify-range image in master branch

- go.list
- go.mod
- go.sum
- gxdr/xdr_generated.go
- protocols/horizon/operations/main_test.go
- services/horizon/internal/codes/main_test.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/ingest/processors/stats_ledger_transaction_processor_test.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/resourceadapter/operations_test.go
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-transaction.x
- xdr/xdr_generated.go
Most of the XDR definitions were already merged in https://github.com/stellar/go/pull/3789 but there were a few recent changes https://github.com/stellar/stellar-core/commit/8beff7604c26d6358f96174414f084b00fbe4929 which need to be included
> Update CAP 38 XDR definitions

- services/horizon/internal/actions/effects.go
- services/horizon/internal/actions/liquidity_pool.go
- services/horizon/internal/actions/liquidity_pool_test.go
- services/horizon/internal/actions/operation.go
- services/horizon/internal/actions/transaction.go
- services/horizon/internal/actions/validators.go
- services/horizon/internal/httpx/router.go
Also, incorporate several fixes to  /liquidity_pools/{id}/{transactions,operations}
Fixes #3834
> services/horizon: Implement /liquidity_pools/{id}/effects endpoint

- protocols/horizon/main.go
- services/horizon/internal/actions/liquidity_pool.go
- services/horizon/internal/actions/root.go
- services/horizon/internal/resourceadapter/root.go
> services/horizon: Add /liquidity_pools to root resource _links

- services/horizon/internal/ingest/processors/effects_processor.go
> services/horizon: Sort liquidity pool revocation claimable balance effects

- services/horizon/CHANGELOG.md
Set of changes: https://github.com/stellar/go/compare/horizon-v2.8.2...release-horizon-v2.8.3
> Horizon 2.8.3 CHANGELOG

- services/horizon/internal/db2/history/main.go
- services/horizon/internal/db2/history/mock_q_trust_lines.go
- services/horizon/internal/db2/history/trust_lines.go
- services/horizon/internal/db2/history/trust_lines_test.go
- services/horizon/internal/ingest/processors/trust_lines_processor.go
- services/horizon/internal/ingest/processors/trust_lines_processor_test.go
Closes #3929 
Depends on https://github.com/stellar/go/pull/3962
> services/horizon: Batch trustline removals

- Gemfile
- Gemfile.lock
- xdr/xdr_generated.go
> xdr: update using xdrgen#73

- ingest/ledgerbackend/buffered_meta_pipe_reader.go
- xdr/main.go
Also, remove `UnmarshalFramed` which wasn't used
> xdr and horizon: Optimize captive-core pipe decoding

- services/horizon/internal/db2/schema/bindata.go
- services/horizon/internal/db2/schema/migrations/51_remove_ht_unused_indexes.sql
Leftover from https://github.com/stellar/go/pull/4035
> services/horizon: Remove unused indexes from history_transactions

- exp/orderbook/graph.go
- services/horizon/internal/ingest/mock_orderbook_graph.go
- services/horizon/internal/ingest/orderbook.go
- services/horizon/internal/ingest/orderbook_test.go
<details>
otherwise).
packages.
</details>
[TODO: Short statement about what is changing.]
[N/A]
> exp/orderbook: Periodically verify internal consistency of in memory orderbook

- go.list
- go.mod
- go.sum
<details>
otherwise).
packages.
</details>
Update the golang.org/x/crypto and golang.org/x/net dependencies.
Update the golang.org/x dependencies that are a few months old and are essentially stdlib.
There was a security fix in golang.org/x/crypto/ssh package's server code. The …
> all: update golang.org/x/crypto and golang.org/x/net

- go.list
- go.mod
- go.sum
> services/ticker: update dep

- go.list
- go.mod
- go.sum
- ingest/ledgerbackend/captive_core_backend.go
- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/database_backend.go
- services/horizon/internal/ingest/fsm.go
- services/horizon/internal/ingest/resume_state_test.go
fixed merge conflicts with master
> 4038/captive core sqlite, clean merge conflicts

- exp/tools/dump-ledger-state/stellar-core.cfg
- services/horizon/configs/captive-core-pubnet.cfg
- services/horizon/docker/captive-core-pubnet.cfg
- services/horizon/docker/stellar-core-pubnet.cfg
<details>
otherwise).
packages.
</details>
Replace keybase validator config with publicnode validator config.
We want to update core config with publicnode validator config. 
NA
Signed-off-by: Satyam Zode <satyamz@users.noreply.github.com>
> services/horizon, exp/tools/dump-ledger-state: replace keybase with publicnode in the stellar core config

- ingest/ledgerbackend/captive_core_backend_test.go
- ingest/ledgerbackend/file_watcher_test.go
- ingest/ledgerbackend/stellar_core_runner_test.go
- services/horizon/internal/integration/parameters_test.go
<details>
otherwise).
packages.
</details>
Fixes PR feedback from https://github.com/stellar/go/pull/4296
Because it got automerged, with comments.
[TODO or N/A]
> services/horizon: PR feedback from 4296

- services/horizon/internal/ingest/verify_test.go
<details>
otherwise).
packages.
</details>
Uncomment StateVerifier test that generates account v3 extensions now that they are implemented.
The relevant tests are now passing.
> Uncomment StateVerifier test that generates account v3 extensions

- gxdr/xdr_generated.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- services/horizon/internal/resourceadapter/claimable_balances_test.go
- txnbuild/create_claimable_balance.go
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-transaction.x
- xdr/json.go
- xdr/json_test.go
- xdr/xdr_generated.go
The XDR comes from stellar/stellar-core#3377 (aka sisuresh/stellar-core#cap21-40-2).
> all: Update Protocol 19 XDR to the latest

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
updated release notes for 2.16.0 release
keep the CHANGELOG up to date with latest release comments.
> Port Release 2.16.0 notes back to master

- Gemfile.lock
<details>
otherwise).
packages.
* [ x] I've updated the relevant CHANGELOG ([here](services/horizon/CHANGELOG.md) for Horizon) if
* [ x] I've decided if this PR requires a new major/minor version according to
</details>
Update the xdrgen dependency.
To include: …
> xdr: Update xdrgen

- .github/workflows/horizon.yml
- services/horizon/docker/ledgerexporter/start
* Push the stellar/horizon-ledgerexporter docker image when pushing to the lighthorizon branch
* Fix the ledger exporter aws batch jobs when running on the first batch
> exp/lighthorizon: Minor ledgerexporter infrastructure improvements

- .github/workflows/horizon-release.yml
- ingest/ledgerbackend/stellar_core_runner_windows.go
- services/horizon/CHANGELOG.md
- services/horizon/internal/scripts/check_release_hash/Dockerfile
Contains two commits without reviews fixing the build so PTAL.
> Merge release-horizon-v2.20.0 into master

- .github/workflows/go.yml
<details>
otherwise).
packages.
</details>
Add `build_release_artifacts` script to `check` workflow.
We don't check if binaries are successfully built before release action. But it's possible that something can be broken, i.e. the windows build was broken during the last Horizon …
> .github: Add building binaries to check workflow

- exp/orderbook/edges.go
Replaces slice tricks with the generic `slices` package.
generics r gr8
> exp/orderbook: Use built-in generics over custom slice tricks

- .github/workflows/go.yml
- .github/workflows/horizon-release.yml
- .github/workflows/horizon.yml
- exp/services/recoverysigner/docker/Dockerfile
- exp/services/webauth/docker/Dockerfile
- services/friendbot/docker/Dockerfile
- services/horizon/docker/Dockerfile.dev
- services/horizon/internal/scripts/check_release_hash/Dockerfile
- services/keystore/docker/Dockerfile
- services/regulated-assets-approval-server/docker/Dockerfile
- services/ticker/docker/Dockerfile
- services/ticker/docker/Dockerfile-dev
Ref: https://groups.google.com/g/golang-announce/c/x49AQzIVX-s/m/0tgO0pjiBQAJ
> all: Bump Go to 1.18.6 and 1.19.1

- exp/support/pipeline/pipeline.go
- handlers/federation/main.go
- services/horizon/internal/actions/query_params_test.go
- services/horizon/internal/ingest/processors/effects_processor_test.go
- strkey/decode_test.go
- strkey/encode_test.go
- strkey/main_test.go
- toid/main_test.go
- txnbuild/helpers.go
- txnbuild/revoke_sponsorship.go
- txnbuild/timebounds.go
- txnbuild/transaction.go
- xdr/price.go
This PR addresses several typos within the source code.
It should not have any visible affect.
> all: fix several typos

- ingest/checkpoint_change_reader_test.go
- ingest/ledger_transaction_test.go
- ingest/ledgerbackend/hash_order_test.go
- ingest/ledgerbackend/remote_captive_core_test.go
- ingest/ledgerbackend/toml_test.go
<details>
otherwise).
packages.
</details>
This PR add some validation for functions returned error codes that were ignored in the unit test.
This PR provide some trivial fixes for issues identified by using the linters.
Changes are intuitive & trivial.
> ingest: add error code checks on few unit tests

- .github/workflows/horizon.yml
Updates Stellar-Core version to the newest, bug-free.
> Bump Stellar-Core to updated Soroban build

- .github/workflows/horizon.yml
- gxdr/xdr_generated.go
- services/horizon/internal/ingest/processors/operations_processor_test.go
- services/horizon/internal/integration/db_test.go
- services/horizon/internal/integration/invokehostfunction_test.go
- txnbuild/invoke_host_function_test.go
- xdr/Stellar-contract-spec.x
- xdr/Stellar-contract.x
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-transaction.x
- xdr/Stellar-types.x
- xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
re-generated xdr bindings from latest soroban version of xdr in [stellar-xdr-next](https://github.com/stellar/stellar-xdr-next)
soroban contract and some tx/ledger models have changed in the latest version of xdr, horizon needs to be in …
> horizon: update to latest soroban xdr from stellar-xdr-next

- exp/services/soroban-rpc/internal/methods/simulate_transaction.go
<details>
otherwise).
packages.
</details>
Replace `result` json field with `results`
Was a typo when the field got renamed. The clients all expect `results`.
[TODO or N/A]
> Fix typo in simulateTransaction

- xdr/ledger_key.go
Needed for #4698 (in order to migrate it to https://github.com/stellar/soroban-tools )
> horizon: Add SetContractData method

- xdr/ledger_key.go
> xdr: Add SetContractCode

- services/horizon/CHANGELOG.md
> Mark Horizon v2.24.0 as ready for release.

- Makefile
- gxdr/xdr_generated.go
- xdr/Stellar-contract-spec.x
- xdr/Stellar-contract.x
- xdr/Stellar-transaction.x
- xdr/scval.go
- xdr/xdr_generated.go
<details>
otherwise).
packages.
</details>
Update the XDR
XDR was changed.
N/A
> [xdr] update

- .github/workflows/horizon.yml
updating integration test references to latest core package version for soroban.
> updated to latest core pkg/docker ref

- .github/workflows/horizon.yml
- ingest/ledger_transaction.go
otherwise).
packages.
</details>
updated the core git ref for workflow integration tests
this is the source version of soroban/p20 enabled core marked for next release
Closes #4789
> tests/integration: bumped core git ref for p20 integration tests

- txnbuild/CHANGELOG.md
Updates txnbuild CHANGELOG after the [v11.0.0 release](https://github.com/stellar/go/releases/tag/horizonclient-v11.0.0)
> txnbuild: Update CHANGELOG.md

- .github/workflows/horizon.yml
- exp/tools/dump-ledger-state/Dockerfile
latest stable core release v19.9.0
> Bump core image to v19.9.0

- support/log/entry.go
- support/log/main.go
Needed for https://github.com/stellar/soroban-tools/issues/497 (since soroban-tools uses the `support/log`)
> support/log: Add support for JSON log formatting

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
update core version used for testing.
This is the official preview 9 core release.
If we do conduct testing, these should be relevant
-- requires @sreuland to produce the said image first.. --
N/A
> tests: update core version used for testing

- .github/workflows/horizon.yml
- .github/workflows/update-completed-sprint-on-issue-closed.yml
- exp/tools/dump-ledger-state/Dockerfile
<details>
otherwise).
packages.
</details>
Update the soroban-xdr-next with the changes that have been merged into main.
We want the releases to be identical, with the exception of the soroban support.
N/A
> syncup with master

- .github/workflows/horizon.yml
- exp/tools/dump-ledger-state/Dockerfile
latest core release v19.11.0
horizon.yaml
Dockerfile
> Bump core image to latest release v19.11.0

- services/horizon/internal/integration/sac_test.go
> services/horizon: Reenable SAC integration tests

- services/horizon/internal/resourceadapter/root.go
<details>
otherwise).
packages.
</details>
Fixed ledgers endpoint link in HAL.
Changed:
`"href": "https://horizon-testnet.stellar.org/ledger/{sequence}"`
To:
`"href": "https://horizon-testnet.stellar.org/ledgers/{sequence}"`
> services/horizon: Fix ledgers endpoint url in HAL

- xdr/ledger_close_meta.go
- xdr/ledger_close_meta_test.go
<details>
otherwise).
packages.
</details>
Implement basic `ingest` package support for LedgerCloseMetaV2. Note this doesn't do anything for horizon.
So the soroban-rpc transaction unit tests stop failing.
[TODO or N/A]
> LedgerCloseMetaV2

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
updated changelog from 2.26.0 release
include 2.26.0 changelog notes now that it's released.
> Merge 2.26 rel notes

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Update core image to use 19.11.1-1349.fae91b092.focal~soroban
[TODO or N/A]
> Update to use 19.11.1-1349.fae91b092.focal~soroban

- go.mod
- go.sum
- support/log/main.go
- tools/goreplay-middleware/README.md
- tools/goreplay-middleware/main.go
- tools/goreplay-middleware/main_test.go
- tools/goreplay-middleware/request.go
- tools/goreplay-middleware/request_test.go
<details>
otherwise).
packages.
</details>
Merge `goreplay-middleware` branch into `master`. Refer to this PR for the original proposal https://github.com/stellar/go/pull/4496 
Closes https://github.com/stellar/go/issues/2840
In the Horizon release checklist, there is an item for …
> Goreplay middleware

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Update to final core preview 10 image
19.11.1-1357.e38ee728d.focal~sorobanP10
[TODO or N/A]
> Update to final core preview 10 image

- .github/workflows/horizon.yml
- exp/tools/dump-ledger-state/Dockerfile
latest core release v19.12.0
horizon.yaml
Dockerfile
> Bump core image to latest release v19.12.0

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
update core image to 19.12.1-1393
previous core build was crashing
n/a
> build: update core image to 19.12.1-1393

- services/horizon/internal/test/integration/integration.go
<details>
otherwise).
packages.
</details>
Refactor `StartHorizon` function.
The code has been broken down into smaller, modular functions for improved readability and maintainability.
[N/A]
> services/horizon: Refactor StartHorizon() function

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update changelog for 2.27.0 release.
> horizon: Update changelog for 2.27.0 release

- .github/workflows/horizon.yml
update integration testing to use the latest soroban-rpc
The latest version of the soroban RPC contains several important fixes, including PRNG support and corrected simulation execution. These are important fixes that our testing infrastructure should be having.
n/a
> testing: update integration testing to use the latest soroban-rpc

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Merge the changes in the rc2 release branch into release-horizon-v2.27.0. release-horizon-v2.27.0 is the release branch for the stable 2.27.0 release which we aim to deploy to production.
> horizon: Merge rc2 release branch into 2.27.0 release branch

- .github/workflows/go.yml
- .github/workflows/horizon.yml
- ingest/ledgerbackend/metrics.go
- services/horizon/internal/httpx/server.go
- services/horizon/internal/ingest/main.go
- services/horizon/internal/txsub/system.go
- support/db/metrics.go
resolved recent conflicts on master related to ingeestion-next
> Ingestion next

- xdr/event.go
- xdr/scval.go
- xdr/scval_test.go
Useful for printing out Diagnostic events
> xdr: Add String() method to ScVal

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Update core and soroban-rpc builds in horizon integration tests.
> services/horizon: Update core and soroban-rpc builds in horizon integration tests

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update change log.
N/A
N/A
> services/horizon: Update CHANGELOG.md

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Merge Horizon v2.30.0 release branch back to master
> Merge Horizon v2.30.0 release branch back to master

- services/horizon/internal/integration/sponsorship_test.go
<details>
otherwise).
packages.
</details>
Add integration test to cover sponsorship change on claimable balance.
Addresses https://github.com/stellar/go/issues/5255
N/A
> services/horizon: Add integration test for claimable balance sponsor change

- exp/services/ledgerexporter/README.md
<details>
otherwise).
packages.
</details>
Update default compression algorithm in LedgerExporter readme.
> exp/services/ledgerexporter: Update docs with default compression zstd

- exp/services/ledgerexporter/internal/app.go
- exp/services/ledgerexporter/internal/uploader.go
- exp/services/ledgerexporter/internal/uploader_test.go
<details>
otherwise).
packages.
</details>
Add latest ledger uploaded metric. @urvisavla suggested including this metric in https://github.com/stellar/go/pull/5265 but but I decided to defer until we tried implementing concurrent uploads. After …
> exp/services/ledgerexporter: Add latest uploaded ledger metric

- ingest/README.md
- ingest/doc.go
- ingest/tutorial/example_common.go
<details>
otherwise).
packages.
</details>
- Fixed dead links
- Removed outdated information.
- Updated the sample code to use the default config values for the network
Docs clean up
It doesn't include details about the new `buffered_storage_backend` and should be addressed …
> ingest:  fixed dead links and remove outdated information.

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update change log for 2.32.0 release
Here are all the changes since the 2.31.0 release:
https://github.com/stellar/go/compare/horizon-v2.31.0...master
> services/horizon: Update change log for 2.32.0 release

- ingest/README.md
<details>
otherwise).
packages.
</details>
Added BufferedStorage ledger backend in README.md. 
The current README only shows Captive Core as the ledger backend.
Even though BufferedStorageBackend implements the LedgerBackend interface, making the doc technically accurate, the requirement and configuration for BufferedStorageBackend are different from that of …
> ingest: Add BufferedStorate ledger backend in README.md

- .github/workflows/horizon.yml
- services/horizon/internal/ingest/main.go
<details>
otherwise).
packages.
</details>
Bump the max supported protocol version in horizon ingestion so that horizon can support protocol 22.
[N/A]
> services/horizon: Enable protocol 22 in Horizon

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Update CI to use the latest protocol 22 stellar-core build.
[N/A]
> services/horizon: Update core version for protocol 22

- .github/workflows/galexie-release.yml
- .github/workflows/galexie.yml
- .github/workflows/horizon.yml
- ingest/cdp/producer_test.go
<details>
otherwise).
packages.
</details>
Update stellar-core version to the rc3 build in the horizon and galexie integration tests
> services/horizon: Update core protocol 22 version

- services/galexie/DEVELOPER_GUIDE.md
- services/galexie/README.md
<details>
otherwise).
packages.
</details>
Remove the content from the README and instead point to the [public docs](https://developers.stellar.org/docs/data/galexie) to avoid duplication.
Addressed [1012](https://github.com/stellar/stellar-docs/issues/1012)
N/A
> services/galexie: Remove the content from the README

- services/horizon/CHANGELOG.md
- services/horizon/internal/ingest/reap.go
<details>
otherwise).
packages.
</details>
Merge horizon v22.0.1 branch back into master
> services/horizon: merge horizon v22.0.1 branch back into master

- go.mod
- go.sum
<details>
otherwise).
packages.
</details>
Update github.com/docker/docker dependency which is used solely in [galexie integration tests](https://github.com/stellar/go/pull/5370/files).
[N/A]
> Update github.com/docker/docker dependency

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Update horizon changelog for v22.0.2 release
> services/horizon: Update horizon changelog for v22.0.2 release

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
https://github.com/stellar/go/pull/5555 was merged into the 22.0.2 release branch but I forgot to also merge it to master.
> services/horizon: fix changelog

- .github/workflows/horizon.yml
> .github: Update Horizon integration tests to latest RPC Docker image

- support/log/entry.go
Needed for https://github.com/stellar/stellar-rpc/issues/241
> support/log: allow setting exit function

- services/galexie/config.example.toml
<details>
otherwise).
packages.
</details>
Fix config parameter name for captive core config file path in the sample config.
N/A
> Fix config parameter name in the sample config

- .github/actions/setup-go/action.yml
- .github/workflows/galexie-release.yml
- .github/workflows/galexie.yml
- .github/workflows/go.yml
- .github/workflows/horizon-release.yml
- .github/workflows/horizon.yml
- exp/services/recoverysigner/docker/Dockerfile
- exp/services/webauth/docker/Dockerfile
- go.mod
- ingest/ledgerbackend/toml.go
- services/friendbot/docker/Dockerfile
- services/galexie/docker/Dockerfile
- services/horizon/CHANGELOG.md
- services/horizon/Makefile
- services/horizon/docker/Dockerfile.dev
- services/horizon/docker/verify-range/dependencies
- services/horizon/internal/ingest/processor_runner.go
- services/horizon/internal/ingest/processors/operations_processor.go
- services/horizon/internal/ingest/processors/participants_processor.go
- services/horizon/internal/ingest/processors/participants_processor_test.go
- services/horizon/internal/ingest/processors/transaction_operation_wrapper_test.go
- services/horizon/internal/integration/sac_test.go
- services/horizon/internal/scripts/check_release_hash/Dockerfile
- services/regulated-assets-approval-server/docker/Dockerfile
- staticcheck.sh
<details>
otherwise).
packages.
</details>
Cherry-pick [PR #5574](https://github.com/stellar/go/pull/5574) for the Horizon patch release v22.0.3.
see https://github.com/stellar/go/pull/5574
N/A
> services/horizon: Fix operations participants logic to include SAC (#5574)

- services/horizon/CHANGELOG.md
<details>
otherwise).
packages.
</details>
Merge release v22.0.3
> Merge release v22.0.3

- ingest/processors/token_transfer/token_transfer_processor.go
Needed for https://github.com/stellar/stellar-rpc/issues/387 since RPC already extracts contract events directly.
> ingest: Allow disabling contract events for events processor

- services/galexie/config.example.toml
<details>
otherwise).
packages.
</details>
Update the default Galexie schema to reflect the recommended settings.
> Update the default Galexie schema to reflect the recommended settings

- support/datastore/s3_datastore.go
- support/datastore/s3_datastore_test.go
<details>
otherwise).
packages.
</details>
Merge master into protocol-23
> Merge master into protocol-23

- services/galexie/CHANGELOG.md
- services/galexie/UPGRADE.md
<details>
otherwise).
packages.
</details>
Update changelog for v23 release with upgrade instructions.
Release prep
> services/galexie: Update changelog for v23 release

- .github/workflows/horizon.yml
<details>
otherwise).
packages.
</details>
Bump rpc v23.0.1
> services/horizon: Bump rpc v23.0.1
